-- +goose Up
-- Seeded admin for the demo school. Dev login: admin@demo.mindimprint.local,
-- password "admin-dev-pass". Hash generated by `go run ./tools/genhash admin-dev-pass`;
-- regenerate with that command if argon2id params change. seed_admin_test.go asserts it.
-- Admins belong to a school but no class (no enrollments row).
INSERT INTO users (id, email, email_verified_at, password_hash, role, school_id, display_name, avatar_color)
VALUES ('00000000-0000-0000-0000-000000000005',
        'admin@demo.mindimprint.local',
        now(),
        '$argon2id$v=19$m=65536,t=1,p=4$BxhAlLNEbGCYxuW3HFBkuQ$X7MPbZbZVo/VwQ28G2eTTrwCsnKwFOVojUAozK7npIs',
        'admin',
        '00000000-0000-0000-0000-000000000001',
        'Demo Admin',
        '#E0A458');

-- +goose Down
DELETE FROM users WHERE id = '00000000-0000-0000-0000-000000000005';
