package prompts

// Assembly is review metadata, not executable routing configuration. Paths are
// relative to apps/api. Builders name the runtime code, not copied templates.
type Assembly struct {
	ID        string   `json:"id"`
	Purpose   string   `json:"purpose"`
	Builders  []string `json:"builders"`
	Context   []string `json:"context,omitempty"`
	Contracts []string `json:"contracts"`
	Tests     []string `json:"tests"`
}

// Assemblies includes dynamic-only prompts, retries, tool descriptions and data
// registries; Catalog alone is intentionally not described as the whole request.
func Assemblies() []Assembly {
	return []Assembly{
		{ID: "shared.voice", Purpose: "共用教学语气；供阅读、写作、探询与批改按原调用关系使用", Builders: []string{"internal/teachingvoice/voice.go"}, Contracts: []string{"internal/prompts/teachingvoice_voice.go"}, Tests: []string{"internal/api/clarity_teaching_live_test.go"}},
		{ID: "reading.coach", Purpose: "带读、推进判断、卡片操作帮助、工具完成反馈；包含动态覆盖指令", Builders: []string{"internal/api/reading_coach_prompt.go", "internal/api/reading_coach_repeat_prompt.go", "internal/api/reading_coach_help.go"}, Context: []string{"internal/api/reading_coach_context.go", "internal/api/reading_disclosure.go", "internal/api/reading_genre.go"}, Contracts: []string{"internal/api/reading_coach.go", "internal/api/reading_coach_card.go"}, Tests: []string{"internal/api/prompt_context_test.go", "internal/api/clarity_live_test.go", "internal/api/reading_coach_readstep_internal_test.go"}},
		{ID: "reading.plan", Purpose: "文章分析与阅读任务生成", Builders: []string{"internal/api/reading_plan_prompt.go"}, Context: []string{"internal/api/reading_routines.go"}, Contracts: []string{"internal/api/reading_plan.go", "internal/api/reading_outline.go"}, Tests: []string{"internal/api/reading_plan_test.go", "internal/api/reading_plan_genre_live_test.go"}},
		{ID: "reading.block", Purpose: "段落工具：解释、词义、语法、仿写等；工具自有指令在 registry 中", Builders: []string{"internal/api/reading_block_prompt.go"}, Context: []string{"internal/api/reading_blocks.go", "internal/api/reading_routines.go"}, Contracts: []string{"internal/api/reading_block.go", "internal/api/reading_block_grammar.go"}, Tests: []string{"internal/api/reading_block_test.go", "internal/api/reading_block_grammar_live_test.go"}},
		{ID: "reading.router", Purpose: "共用阅读接口的工具卡选择", Builders: []string{"internal/agent/reading_router_prompt.go"}, Context: []string{"internal/agent/reading_brief.go", "internal/agent/reading_deck.go"}, Contracts: []string{"internal/agent/reading_router.go"}, Tests: []string{"internal/agent/reading_router_test.go"}},
		{ID: "reading.lens", Purpose: "透镜示范与学生选句评价；卡片 spec 为动态输入", Builders: []string{"internal/agent/reading_card_example_prompt.go", "internal/agent/reading_eval_prompt.go"}, Context: []string{"internal/cards/specs"}, Contracts: []string{"internal/agent/reading_eval.go", "internal/agent/reading_card_example.go"}, Tests: []string{"internal/agent/reading_eval_test.go", "internal/api/clarity_live_test.go"}},
		{ID: "reading.followup", Purpose: "阅读收获整理与延伸问题", Builders: []string{"internal/agent/reading_takeaway_prompt.go", "internal/api/reading_questions_prompt.go"}, Contracts: []string{"internal/agent/reading_takeaway.go", "internal/api/reading_questions.go"}, Tests: []string{"internal/agent/reading_takeaway_test.go", "internal/api/reading_questions_test.go"}},
		{ID: "writing.opening", Purpose: "新写作、教师布置题目及带成稿进入时的开场", Builders: []string{"internal/api/writing_setup_prompt.go"}, Context: []string{"internal/api/writing_lang.go"}, Contracts: []string{"internal/api/writing_setup.go"}, Tests: []string{"internal/api/writing_setup_test.go", "internal/api/clarity_merge_live_test.go"}},
		{ID: "writing.plan", Purpose: "中英文议论/记叙文规划；包含计划检查和条件重试", Builders: []string{"internal/api/writing_plan_prompt.go", "internal/api/writing_plan_lang_prompt.go", "internal/api/writing_plan_state_prompt.go", "internal/api/writing_points_check_prompt.go", "internal/api/writing_plan_place_prompt.go", "internal/api/writing_plan_invite_prompt.go", "internal/api/writing_refusal_prompt.go"}, Context: []string{"internal/api/writing_plan_context.go", "internal/api/writing_plan_state.go", "internal/api/writing_points_check.go"}, Contracts: []string{"internal/api/writing_plan.go", "internal/api/writing_kind.go"}, Tests: []string{"internal/api/prompt_context_test.go", "internal/api/clarity_merge_live_test.go", "internal/api/clarity_prose_live_test.go"}},
		{ID: "writing.guide", Purpose: "单段/批量写作引导与深入讨论", Builders: []string{"internal/api/writing_piece_prompt.go", "internal/api/writing_guide_prompt.go", "internal/api/writing_deepen_prompt.go", "internal/api/writing_stall_prompt.go"}, Context: []string{"internal/api/writing_piece_context.go", "internal/api/writing_guide.go", "internal/vocab/methods.json"}, Contracts: []string{"internal/api/writing_guide.go", "internal/api/writing_deepen.go"}, Tests: []string{"internal/api/writing_guide_test.go", "internal/api/writing_piece_context_test.go", "internal/api/clarity_live_test.go"}},
		{ID: "writing.feedback", Purpose: "段落/整篇审阅，段落职责、帮助模式、格式及语气重试", Builders: []string{"internal/api/writing_comment_prompt.go", "internal/api/writing_comment_summary_prompt.go", "internal/api/writing_tone_prompt.go", "internal/api/writing_stall_prompt.go"}, Context: []string{"internal/api/writing_piece_context.go", "internal/api/writing_repeats.go", "internal/api/writing_length_gap.go", "internal/api/writing_symptoms.go"}, Contracts: []string{"internal/api/writing_comment.go", "internal/api/writing_comment_summary.go"}, Tests: []string{"internal/api/writing_comment_test.go", "internal/api/writing_comment_live_test.go", "internal/api/clarity_comment_delivery_test.go"}},
		{ID: "writing.chat", Purpose: "写作房间常规对话，复用项目陪练；状态投影包含操作说明", Builders: []string{"internal/agent/project_coach_prompt.go", "internal/api/writing_turn_prompt.go", "internal/api/writing_board_prompt.go"}, Context: []string{"internal/api/writing_turn_context.go"}, Contracts: []string{"internal/agent/project_coach.go", "internal/api/writing_turn.go"}, Tests: []string{"internal/api/writing_turn_test.go", "internal/api/writing_projection_internal_test.go"}},
		{ID: "writing.title", Purpose: "从学生已有正文中提取标题构思关键词", Builders: []string{"internal/api/writing_title_prompt.go"}, Contracts: []string{"internal/api/writing_title.go"}, Tests: []string{"internal/api/writing_title_internal_test.go"}},
		{ID: "awakening", Purpose: "兴趣探询对话、收尾、兴趣选择与报告；节点问题和助手风格也是输入", Builders: []string{"internal/awakening/dialogue.go", "internal/awakening/selection.go", "internal/awakening/report.go", "internal/awakening/title.go"}, Context: []string{"internal/awakening/brief.go", "internal/awakening/nodes.go", "internal/awakening/awakening.go"}, Contracts: []string{"internal/awakening/selection.go", "internal/awakening/report.go"}, Tests: []string{"internal/awakening/awakening_test.go", "internal/awakening/clarity_live_test.go"}},
		{ID: "interest", Purpose: "学习活动兴趣提取与兴趣词延伸", Builders: []string{"internal/interest/harvest.go", "internal/interest/dig.go"}, Context: []string{"internal/interests/interests.json"}, Contracts: []string{"internal/interest/harvest.go", "internal/interest/dig.go"}, Tests: []string{"internal/interest/interest_test.go", "internal/interest/dig_test.go"}},
		{ID: "reports", Purpose: "学习报告、学生/班级周报、家长报告和班级摘要", Builders: []string{"internal/api/atom_report_prompt.go", "internal/agent/compose_lite_weekly_prompt.go", "internal/agent/compose_lite_parent_prompt.go", "internal/api/lite_class_summary_prompt.go"}, Context: []string{"internal/api/report_facts.go", "internal/liteparent/facts.go", "internal/liteweekly/class.go"}, Contracts: []string{"internal/api/atom_report.go", "internal/agent/compose_lite_parent.go", "internal/agent/compose_lite_weekly.go"}, Tests: []string{"internal/api/atom_report_live_test.go", "internal/agent/compose_lite_weekly_test.go", "internal/agent/compose_lite_parent_test.go"}},
		{ID: "teacher.workspace", Purpose: "教师作业助手、班级问答、报告编辑；包含工具描述与参数 schema", Builders: []string{"internal/liteworkspace/tools.go", "internal/api/lite_assignment_extract_prompt.go"}, Context: []string{"internal/liteworkspace/calendar.go", "internal/liteworkspace/workspace.go"}, Contracts: []string{"internal/liteworkspace/tools.go", "internal/api/lite_assignment_extract.go"}, Tests: []string{"internal/liteworkspace/tools_test.go", "internal/api/lite_teacher_workspace_live_test.go"}},
		{ID: "teacher.grading", Purpose: "按教师 rubric 批改，含校验失败的重试指令", Builders: []string{"internal/litegrade/prompt.go"}, Context: []string{"internal/litegrade/content.go", "internal/liteassign/rubric.go"}, Contracts: []string{"internal/litegrade/check.go", "internal/api/lite_grading_run.go"}, Tests: []string{"internal/litegrade/prompt_test.go", "internal/api/clarity_grading_live_test.go"}},
		{ID: "news", Purpose: "新闻筛选与面向学生的新闻说明", Builders: []string{"internal/news/select.go", "internal/news/write.go"}, Contracts: []string{"internal/news/select.go", "internal/news/write.go"}, Tests: []string{"internal/news/live_test.go"}},
		{ID: "course", Purpose: "共用课程问答和开场/结束旁白；课程正文作为上下文", Builders: []string{"internal/agent/course_coach_prompt.go", "internal/agent/course_scene_prompt.go"}, Contracts: []string{"internal/agent/course_coach.go", "internal/agent/course_scene.go"}, Tests: []string{"internal/agent/course_coach_test.go", "internal/agent/course_scene_test.go"}},
	}
}
