import { ProcessComparison } from "../../../site/ProcessComparison";
import { SiteContentEditor } from "./SiteContentEditor";
import { Says, errorMarkdown } from "../../Says";
import type { HeroTrial, HeroResponseDraft } from "../../../api/creativeDirection";
import { useEffect, useState } from "react";
import { codePreviewURL, listCodeVersions, type CodeVersion } from "../../../api/codeVersions";
import { GrowingTextarea } from "../../../shared/GrowingTextarea";
import { apiErrorText } from "../../../api/errorText";
type VersionResponse = HeroResponseDraft;
const emptyVersionResponse:VersionResponse={redrawImage:false,feedback:"",observation:"",response:""};
export function CodePreview({includeComparison,onIncludeComparison,responses, onResponseChange, mode,projectId, newest, busy, onRevise, trial, onAccept, onCompose, includeProcess, onIncludeProcess}: {includeComparison:boolean;onIncludeComparison:(include:boolean)=>void;responses:Record<string,VersionResponse>;onResponseChange:(version:string,draft:VersionResponse)=>void;mode:string;projectId:string;newest:CodeVersion|null;busy:boolean;includeProcess:boolean;onIncludeProcess:(include:boolean)=>void;onCompose:(version:string)=>void;trial?:HeroTrial;onAccept:(version:string,observation:string)=>void;onRevise:(version:string,feedback:string,redrawImage:boolean)=>void}) {
 const [versions,setVersions]=useState<CodeVersion[]>([]);
 const [selected,setSelected]=useState("");
 const [running,setRunning]=useState(true);
 const [compare,setCompare]=useState(false);
 const [narrow,setNarrow]=useState(false);
 const [contentPending,setContentPending]=useState(true);
 const responseKey=selected;
 const {redrawImage,feedback,observation,response}=responses[responseKey]??emptyVersionResponse;
 const updateResponse=(patch:Partial<VersionResponse>)=>onResponseChange(responseKey,{...(responses[responseKey]??emptyVersionResponse),...patch});
 const [error,setError]=useState("");
 useEffect(()=>{let active=true;setError("");listCodeVersions(projectId).then(rows=>{if(active){setVersions(rows??[]);setSelected(newest?.id??rows?.[0]?.id??"");setRunning(true);}}).catch(e=>{if(active)setError(apiErrorText(e));});return()=>{active=false;};},[projectId,newest]);
 const current=versions.find(version=>version.id===selected);
 const modeChanged=Boolean(current?.mode && current.mode!==mode);
 if(error)return <div role="alert"><Says content={errorMarkdown(`读取作品版本失败：${error}`)} /></div>;
 if(!selected)return null;
 return <section className="space-y-3 border-t border-mk-border pt-5">
  <div className="flex flex-wrap items-center justify-between gap-2"><h3 className="text-mk-body font-semibold">作品试用</h3><button type="button" className="rounded-full border border-mk-border px-3 py-2 text-mk-small" onClick={()=>setRunning(!running)}>{running?"停止预览":"重新运行"}</button></div>
  <div className="flex flex-wrap items-center justify-between gap-3"><label className="block text-mk-small">作品版本<select aria-label="作品版本" value={selected} onChange={e=>{setSelected(e.target.value);setRunning(true);}} className="ml-3 rounded border border-mk-border p-2">{versions.map((version,i)=><option key={version.id} value={version.id}>{i===0?"最新版本":"历史版本"} · {new Date(version.created_at).toLocaleString()}</option>)}</select></label><a href={codePreviewURL(projectId,selected)} target="_blank" rel="noopener noreferrer" className="text-mk-small underline">独立窗口试用</a></div>
  {modeChanged&&<p role="status" className="rounded-mk-lg border border-mk-border p-3 text-mk-small">当前构思的呈现方式与这一版不同。请在上方生成新的第一幕，或将呈现方式改回后继续修改。历史版本仍可预览。</p>}
  {current?.parent_version_id&&<div className="rounded-mk-lg bg-mk-accent-50 p-3"><p className="text-mk-small font-semibold">本版修改意见</p><p className="mt-1 whitespace-pre-wrap text-mk-small">{current.feedback}</p><button type="button" className="mt-2 text-mk-small underline" onClick={()=>{setSelected(current.parent_version_id!);setRunning(true);}}>查看修改前版本</button></div>}
  <p className="text-mk-small text-mk-secondary">请移动鼠标、点击或使用键盘，检查实际效果是否符合构思。独立窗口试用后，请返回这里填写修改意见或保留理由。作品内容尚未添加的入口需要继续完善。</p>
  {current?.parent_version_id&&<button type="button" aria-pressed={compare} className="rounded-full border border-mk-border px-4 py-2 text-mk-small" onClick={()=>setCompare(!compare)}>{compare?"只看当前版本":"对比修改前后"}</button>}
  <div className="flex flex-wrap items-center gap-2" role="group" aria-label="预览宽度"><button type="button" aria-pressed={!narrow} onClick={()=>setNarrow(false)} className="rounded-full border border-mk-border px-3 py-2 text-mk-small aria-pressed:bg-mk-accent-50">适应面板</button><button type="button" aria-pressed={narrow} onClick={()=>setNarrow(true)} className="rounded-full border border-mk-border px-3 py-2 text-mk-small aria-pressed:bg-mk-accent-50">窄屏布局</button></div>
  {narrow&&<p className="text-mk-small text-mk-muted">预览宽度上限为390像素；这里只检查布局，触摸操作需要在实际设备上试用。</p>}
  {running?<div className={compare&&current?.parent_version_id?"grid gap-4 md:grid-cols-2":""}>
   {compare&&current?.parent_version_id&&<section className="rounded-mk-lg border border-mk-border p-2"><h4 className="mb-2 text-mk-small font-semibold">修改前</h4><iframe key={current.parent_version_id} title="修改前版本预览" src={codePreviewURL(projectId,current.parent_version_id)} sandbox="allow-scripts" referrerPolicy="no-referrer" allow="camera 'none'; microphone 'none'; geolocation 'none'; payment 'none'" style={{maxWidth:narrow?390:undefined}} className="mx-auto block h-[600px] w-full rounded-mk-lg border-0 bg-white"/></section>}
   <section className={compare&&current?.parent_version_id?"rounded-mk-lg border-2 border-mk-accent-200 p-2":""}>{compare&&current?.parent_version_id&&<h4 className="mb-2 text-mk-small font-semibold">修改后</h4>}<iframe key={selected} title="第一幕交互预览" src={codePreviewURL(projectId,selected)} sandbox="allow-scripts" referrerPolicy="no-referrer" allow="camera 'none'; microphone 'none'; geolocation 'none'; payment 'none'" style={{maxWidth:narrow?390:undefined}} className="mx-auto block h-[600px] w-full rounded-mk-lg border-0 bg-white"/></section>
  </div>:<div className="rounded-mk-lg border border-mk-border p-8 text-mk-small">预览已停止</div>}
  {trial?.versionId===selected&&<div role="status" className="rounded-mk-lg bg-mk-accent-50 p-4"><p className="font-semibold">已保留这一版</p><p className="whitespace-pre-wrap text-mk-small">{trial.observation}</p><p className="text-mk-small text-mk-muted">这是你对该版本的试用判断，后续版本需要重新检查。</p></div>}
  <div className="flex flex-wrap gap-3"><button type="button" aria-pressed={response==="revise"} onClick={()=>updateResponse({response:"revise"})} className="rounded-full border border-mk-border px-4 py-2 aria-pressed:bg-mk-accent-50">还想修改</button><button type="button" aria-pressed={response==="retain"} onClick={()=>updateResponse({response:"retain"})} className="rounded-full border border-mk-border px-4 py-2 aria-pressed:bg-mk-accent-50">可以继续，用这一版</button></div>
  {response==="revise"&&<div className="space-y-3 rounded-mk-lg border border-mk-border p-4"><h4 className="text-mk-body font-semibold">试用后，想修改什么？</h4><p className="text-mk-small text-mk-secondary">请指出看到的问题和希望的变化。修改将基于当前预览的版本，原版本会保留。</p><GrowingTextarea aria-label="第一幕修改意见" value={feedback} maxLength={2000} onChange={e=>updateResponse({feedback:e.target.value})} placeholder="例如：温室不够明显，请放大玻璃外框；保留花朵点击效果。" className="w-full rounded-mk-lg border border-mk-border p-3 text-mk-body"/>{mode==="mixed"&&<label className="flex items-start gap-2 text-mk-small"><input type="checkbox" checked={redrawImage} disabled={busy} onChange={e=>updateResponse({redrawImage:e.target.checked})}/>同时重新生成图片（未勾选时保留图片，只修改页面与互动）</label>}{mode==="image"&&<p className="text-mk-small text-mk-secondary">将根据构思和修改意见重新生成图片，原图保留在历史版本。新图的细节可能改变。</p>}<button type="button" disabled={busy||modeChanged||!feedback.trim()} className="rounded-full bg-mk-accent-500 px-4 py-2 text-mk-body text-white disabled:opacity-40" onClick={()=>onRevise(selected,feedback,redrawImage)}>{busy?"正在修改…":"根据意见修改"}</button></div>}
  {response==="retain"&&<div className="space-y-3 rounded-mk-lg border border-mk-border p-4"><h4 className="font-semibold">这一版符合你的构思吗？</h4><p className="text-mk-small text-mk-secondary">请记录实际看到或试过的效果，以及保留这一版的理由。作品仍可继续修改。</p><GrowingTextarea aria-label="保留版本的理由" value={observation} maxLength={2000} onChange={e=>updateResponse({observation:e.target.value})} placeholder="例如：温室轮廓看清了，点击花朵能打开作品入口。" className="w-full rounded-mk-lg border border-mk-border p-3 text-mk-body"/><button type="button" disabled={busy||!observation.trim()} className="rounded-full border border-mk-border px-4 py-2 disabled:opacity-40" onClick={()=>onAccept(selected,observation)}>保留这一版</button></div>}
  {trial&&<section className="space-y-3 rounded-mk-lg border border-mk-border p-4"><h4 className="font-semibold">展示我的制作过程</h4><p className="text-mk-small text-mk-secondary">使用已保留版本的修改意见和试用判断，不需要重新填写。</p><label className="flex items-start gap-2 text-mk-small"><input type="checkbox" checked={includeProcess} disabled={busy} onChange={e=>onIncludeProcess(e.target.checked)}/>加入主页草稿</label>{includeProcess&&<div className="space-y-3 text-mk-small"><p className="whitespace-pre-wrap">{versions.find(v=>v.id===trial.versionId)?.feedback||"该版本没有修改意见"}</p><p className="whitespace-pre-wrap">{trial.observation}</p></div>}</section>}
  {trial&&includeProcess&&<label className="flex items-start gap-2 text-mk-small"><input type="checkbox" checked={includeComparison} disabled={busy||(!includeComparison&&!versions.find(v=>v.id===trial.versionId)?.parent_version_id)} onChange={e=>onIncludeComparison(e.target.checked)}/>展示这次修改的前后效果。发布后，访客可以试用这两版页面；之后的新修改不会替换这组对比。</label>}
  {current?.comparison&&<ProcessComparison comparison={current.comparison} source={codePreviewURL(projectId,selected)}/>}
  <SiteContentEditor projectId={projectId} onPendingChange={setContentPending}/>
  <div className="border-t border-mk-border pt-4"><p className="mb-3 text-mk-small text-mk-secondary">已保存的自我介绍、作品文字或已选择的制作过程，可以加入当前版本。生成后请试用完整主页，再决定是否发布。</p><button type="button" disabled={busy||modeChanged||contentPending} onClick={()=>onCompose(selected)} className="rounded-full border border-mk-border px-4 py-2 disabled:opacity-40">将已保存的内容加入这一版</button></div>
 </section>;
}
