// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: cards.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createCardInstance = `-- name: CreateCardInstance :one
INSERT INTO card_instances (card_id, task_id, status)
VALUES ($1, $2, 'proposed')
RETURNING id, card_id, task_id, parent_node_id, status, field_values, event_trace, rubric_tags, created_at, completed_at
`

type CreateCardInstanceParams struct {
	CardID string    `json:"card_id"`
	TaskID uuid.UUID `json:"task_id"`
}

func (q *Queries) CreateCardInstance(ctx context.Context, arg CreateCardInstanceParams) (CardInstance, error) {
	row := q.db.QueryRow(ctx, createCardInstance, arg.CardID, arg.TaskID)
	var i CardInstance
	err := row.Scan(
		&i.ID,
		&i.CardID,
		&i.TaskID,
		&i.ParentNodeID,
		&i.Status,
		&i.FieldValues,
		&i.EventTrace,
		&i.RubricTags,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getCard = `-- name: GetCard :one
SELECT id, card_id, task_id, parent_node_id, status, field_values, event_trace, rubric_tags, created_at, completed_at FROM card_instances WHERE id = $1
`

func (q *Queries) GetCard(ctx context.Context, id uuid.UUID) (CardInstance, error) {
	row := q.db.QueryRow(ctx, getCard, id)
	var i CardInstance
	err := row.Scan(
		&i.ID,
		&i.CardID,
		&i.TaskID,
		&i.ParentNodeID,
		&i.Status,
		&i.FieldValues,
		&i.EventTrace,
		&i.RubricTags,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listCardsByTask = `-- name: ListCardsByTask :many
SELECT id, card_id, task_id, parent_node_id, status, field_values, event_trace, rubric_tags, created_at, completed_at FROM card_instances
WHERE task_id = $1
ORDER BY created_at, id
`

func (q *Queries) ListCardsByTask(ctx context.Context, taskID uuid.UUID) ([]CardInstance, error) {
	rows, err := q.db.Query(ctx, listCardsByTask, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CardInstance
	for rows.Next() {
		var i CardInstance
		if err := rows.Scan(
			&i.ID,
			&i.CardID,
			&i.TaskID,
			&i.ParentNodeID,
			&i.Status,
			&i.FieldValues,
			&i.EventTrace,
			&i.RubricTags,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
