// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: card_instance.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countCompletedCardUsesByUser = `-- name: CountCompletedCardUsesByUser :one
SELECT count(*)::int FROM (
  SELECT ci.id FROM card_instances ci JOIN project p ON p.id = ci.project_id
  WHERE ci.project_id IS NOT NULL AND ci.status = 'completed'
    AND p.user_id = $1 AND ci.card_id = $2
) rows
`

type CountCompletedCardUsesByUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	CardID string    `json:"card_id"`
}

// How many times this student has COMPLETED this specific card, PROJECT
// SCOPE ONLY — user-scoped across ALL her projects (a second project must
// not reset her to novice), but deliberately NOT unioned with the chat scope
// ListCollectedCardsByUser above unions.
//
// Whole-branch review IMPORTANT 2 (N3c): this feeds the guidance fade
// (agent/guidance.go), which removes AI scaffolding (the question, then the
// located span) the more completions it counts. Only the project scope's
// "completed" is gated on the card's own completion predicate
// (projectcards.go's CompleteCard runs it before flipping status) — it
// genuinely reflects work the card was for. chat.go writes status='completed'
// UNCONDITIONALLY on submit, with no predicate and no anchors at all (chat
// cards are thin by design): a student can submit an anchor-less chat CRAAP
// sheet twice and have her FIRST-EVER Studio CRAAP card surface at max
// scaffold removed, having never once done the card properly. Counting that
// ungated surface here would make the ladder's premise false, so this query
// counts project-scope completions only — see the spec's own §3 for the full
// reasoning. A skip is a decline and does not count either way.
func (q *Queries) CountCompletedCardUsesByUser(ctx context.Context, arg CountCompletedCardUsesByUserParams) (int32, error) {
	row := q.db.QueryRow(ctx, countCompletedCardUsesByUser, arg.UserID, arg.CardID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createProjectCardInstance = `-- name: CreateProjectCardInstance :one

INSERT INTO card_instances (task_id, project_id, card_id, contract_ref, status)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, card_id, task_id, parent_node_id, status, field_values, event_trace, rubric_tags, created_at, completed_at, anchors, project_id, contract_ref, framework_fill, thread_id, session_id
`

type CreateProjectCardInstanceParams struct {
	TaskID      pgtype.UUID `json:"task_id"`
	ProjectID   pgtype.UUID `json:"project_id"`
	CardID      string      `json:"card_id"`
	ContractRef *string     `json:"contract_ref"`
	Status      string      `json:"status"`
}

// Project-scoped card_instance lifecycle (Slice 3, agent-spec §3). The
// table is `card_instances` (Slice-0's task-scoped table, extended by
// migration 0016 with project_id/contract_ref/framework_fill); task_id went
// nullable in migration 0020 alongside material.task_id (Slice 6b's
// project-scoped source-log ingestion creates materials with no task) —
// the runtime resolves it from the target material's own (possibly NULL)
// task_id (agentstore.go), never asking the pure agent code to know about
// tasks.
// The old task-scoped queries in cards.sql (CreateCardInstance, SetCardActive,
// SubmitCard, SkipCard, SetCardAnchors) are otherwise unused — there is no
// legacy path any more (Slice 5d retired the task-based surface) — they stay
// alive only because their own tests (store/sqlc_lifecycle_test.go,
// api/anchors_store_test.go) still exercise them directly against the table.
func (q *Queries) CreateProjectCardInstance(ctx context.Context, arg CreateProjectCardInstanceParams) (CardInstance, error) {
	row := q.db.QueryRow(ctx, createProjectCardInstance,
		arg.TaskID,
		arg.ProjectID,
		arg.CardID,
		arg.ContractRef,
		arg.Status,
	)
	var i CardInstance
	err := row.Scan(
		&i.ID,
		&i.CardID,
		&i.TaskID,
		&i.ParentNodeID,
		&i.Status,
		&i.FieldValues,
		&i.EventTrace,
		&i.RubricTags,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.Anchors,
		&i.ProjectID,
		&i.ContractRef,
		&i.FrameworkFill,
		&i.ThreadID,
		&i.SessionID,
	)
	return i, err
}

const createSessionCardInstance = `-- name: CreateSessionCardInstance :one

INSERT INTO card_instances (session_id, card_id, status)
VALUES ($1, $2, $3)
RETURNING id, card_id, task_id, parent_node_id, status, field_values, event_trace, rubric_tags, created_at, completed_at, anchors, project_id, contract_ref, framework_fill, thread_id, session_id
`

type CreateSessionCardInstanceParams struct {
	SessionID pgtype.UUID `json:"session_id"`
	CardID    string      `json:"card_id"`
	Status    string      `json:"status"`
}

// Course session scope (Slice 12): mirrors the thread-scoped queries above
// exactly (card_instances has no material_id/tool_id column — the offer's
// material link is carried in Go's CardOffer struct, not the row).
func (q *Queries) CreateSessionCardInstance(ctx context.Context, arg CreateSessionCardInstanceParams) (CardInstance, error) {
	row := q.db.QueryRow(ctx, createSessionCardInstance, arg.SessionID, arg.CardID, arg.Status)
	var i CardInstance
	err := row.Scan(
		&i.ID,
		&i.CardID,
		&i.TaskID,
		&i.ParentNodeID,
		&i.Status,
		&i.FieldValues,
		&i.EventTrace,
		&i.RubricTags,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.Anchors,
		&i.ProjectID,
		&i.ContractRef,
		&i.FrameworkFill,
		&i.ThreadID,
		&i.SessionID,
	)
	return i, err
}

const createThreadCardInstance = `-- name: CreateThreadCardInstance :one

INSERT INTO card_instances (thread_id, card_id, status)
VALUES ($1, $2, $3)
RETURNING id, card_id, task_id, parent_node_id, status, field_values, event_trace, rubric_tags, created_at, completed_at, anchors, project_id, contract_ref, framework_fill, thread_id, session_id
`

type CreateThreadCardInstanceParams struct {
	ThreadID pgtype.UUID `json:"thread_id"`
	CardID   string      `json:"card_id"`
	Status   string      `json:"status"`
}

// Thread-scoped card_instances (Slice 11): thread_id set, task_id/project_id NULL.
func (q *Queries) CreateThreadCardInstance(ctx context.Context, arg CreateThreadCardInstanceParams) (CardInstance, error) {
	row := q.db.QueryRow(ctx, createThreadCardInstance, arg.ThreadID, arg.CardID, arg.Status)
	var i CardInstance
	err := row.Scan(
		&i.ID,
		&i.CardID,
		&i.TaskID,
		&i.ParentNodeID,
		&i.Status,
		&i.FieldValues,
		&i.EventTrace,
		&i.RubricTags,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.Anchors,
		&i.ProjectID,
		&i.ContractRef,
		&i.FrameworkFill,
		&i.ThreadID,
		&i.SessionID,
	)
	return i, err
}

const getCardInstance = `-- name: GetCardInstance :one
SELECT id, card_id, task_id, parent_node_id, status, field_values, event_trace, rubric_tags, created_at, completed_at, anchors, project_id, contract_ref, framework_fill, thread_id, session_id FROM card_instances WHERE id = $1
`

func (q *Queries) GetCardInstance(ctx context.Context, id uuid.UUID) (CardInstance, error) {
	row := q.db.QueryRow(ctx, getCardInstance, id)
	var i CardInstance
	err := row.Scan(
		&i.ID,
		&i.CardID,
		&i.TaskID,
		&i.ParentNodeID,
		&i.Status,
		&i.FieldValues,
		&i.EventTrace,
		&i.RubricTags,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.Anchors,
		&i.ProjectID,
		&i.ContractRef,
		&i.FrameworkFill,
		&i.ThreadID,
		&i.SessionID,
	)
	return i, err
}

const listCardInstancesByProject = `-- name: ListCardInstancesByProject :many
SELECT id, card_id, task_id, parent_node_id, status, field_values, event_trace, rubric_tags, created_at, completed_at, anchors, project_id, contract_ref, framework_fill, thread_id, session_id FROM card_instances
WHERE project_id = $1
ORDER BY created_at, id
`

func (q *Queries) ListCardInstancesByProject(ctx context.Context, projectID pgtype.UUID) ([]CardInstance, error) {
	rows, err := q.db.Query(ctx, listCardInstancesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CardInstance
	for rows.Next() {
		var i CardInstance
		if err := rows.Scan(
			&i.ID,
			&i.CardID,
			&i.TaskID,
			&i.ParentNodeID,
			&i.Status,
			&i.FieldValues,
			&i.EventTrace,
			&i.RubricTags,
			&i.CreatedAt,
			&i.CompletedAt,
			&i.Anchors,
			&i.ProjectID,
			&i.ContractRef,
			&i.FrameworkFill,
			&i.ThreadID,
			&i.SessionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCardInstancesBySession = `-- name: ListCardInstancesBySession :many
SELECT id, card_id, task_id, parent_node_id, status, field_values, event_trace, rubric_tags, created_at, completed_at, anchors, project_id, contract_ref, framework_fill, thread_id, session_id FROM card_instances WHERE session_id = $1 ORDER BY created_at, id
`

func (q *Queries) ListCardInstancesBySession(ctx context.Context, sessionID pgtype.UUID) ([]CardInstance, error) {
	rows, err := q.db.Query(ctx, listCardInstancesBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CardInstance
	for rows.Next() {
		var i CardInstance
		if err := rows.Scan(
			&i.ID,
			&i.CardID,
			&i.TaskID,
			&i.ParentNodeID,
			&i.Status,
			&i.FieldValues,
			&i.EventTrace,
			&i.RubricTags,
			&i.CreatedAt,
			&i.CompletedAt,
			&i.Anchors,
			&i.ProjectID,
			&i.ContractRef,
			&i.FrameworkFill,
			&i.ThreadID,
			&i.SessionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCardInstancesByThread = `-- name: ListCardInstancesByThread :many
SELECT id, card_id, task_id, parent_node_id, status, field_values, event_trace, rubric_tags, created_at, completed_at, anchors, project_id, contract_ref, framework_fill, thread_id, session_id FROM card_instances WHERE thread_id = $1 ORDER BY created_at, id
`

func (q *Queries) ListCardInstancesByThread(ctx context.Context, threadID pgtype.UUID) ([]CardInstance, error) {
	rows, err := q.db.Query(ctx, listCardInstancesByThread, threadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CardInstance
	for rows.Next() {
		var i CardInstance
		if err := rows.Scan(
			&i.ID,
			&i.CardID,
			&i.TaskID,
			&i.ParentNodeID,
			&i.Status,
			&i.FieldValues,
			&i.EventTrace,
			&i.RubricTags,
			&i.CreatedAt,
			&i.CompletedAt,
			&i.Anchors,
			&i.ProjectID,
			&i.ContractRef,
			&i.FrameworkFill,
			&i.ThreadID,
			&i.SessionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCollectedCardsByUser = `-- name: ListCollectedCardsByUser :many
SELECT card_id,
       count(*)::int AS uses,
       array_agg(DISTINCT surface ORDER BY surface)::text[] AS surfaces,
       max(created_at) AS last_used
FROM (
  (SELECT ci.card_id AS card_id, 'project'::text AS surface, ci.created_at AS created_at
   FROM card_instances ci JOIN project p ON p.id = ci.project_id
   WHERE ci.project_id IS NOT NULL AND ci.status = 'completed' AND p.user_id = $1)
  UNION ALL
  (SELECT ci.card_id, 'chat'::text, ci.created_at
   FROM card_instances ci JOIN chat_thread t ON t.id = ci.thread_id
   WHERE ci.thread_id IS NOT NULL AND ci.status = 'completed' AND t.user_id = $1)
) rows
GROUP BY card_id
ORDER BY uses DESC, last_used DESC
`

type ListCollectedCardsByUserRow struct {
	CardID   string      `json:"card_id"`
	Uses     int32       `json:"uses"`
	Surfaces []string    `json:"surfaces"`
	LastUsed interface{} `json:"last_used"`
}

// Every tool card the caller has COMPLETED at least once, across both
// remaining scopes, deduped to one row per card_id with a usage summary.
// status='completed' only (a skip is a decline). Owner-filtered through each
// scope's own parent join (card_instances has no user_id). No cost, no model
// — a pure read for the 工具卡 tab. created_at (always non-null) is the usage
// timestamp. The course-session scope is retired along with course_session
// itself (migration 0050, course v2, no back-compat).
func (q *Queries) ListCollectedCardsByUser(ctx context.Context, userID uuid.UUID) ([]ListCollectedCardsByUserRow, error) {
	rows, err := q.db.Query(ctx, listCollectedCardsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCollectedCardsByUserRow
	for rows.Next() {
		var i ListCollectedCardsByUserRow
		if err := rows.Scan(
			&i.CardID,
			&i.Uses,
			&i.Surfaces,
			&i.LastUsed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectCardCompletionsByUser = `-- name: ListProjectCardCompletionsByUser :many
SELECT ci.card_id AS card_id, count(*)::int AS completions
FROM card_instances ci JOIN project p ON p.id = ci.project_id
WHERE ci.project_id IS NOT NULL AND ci.status = 'completed' AND p.user_id = $1
GROUP BY ci.card_id
`

type ListProjectCardCompletionsByUserRow struct {
	CardID      string `json:"card_id"`
	Completions int32  `json:"completions"`
}

// Per-card PROJECT-SCOPE completion counts for a user, across ALL her projects.
// This is the "genuine practice" signal for card proficiency: project-scope
// 'completed' is gated on the card's own completion predicate (projectcards.go's
// CompleteCard), unlike the chat scope which writes completed
// unconditionally. Mirrors CountCompletedCardUsesByUser's scoping but grouped
// over every card at once, for the 工具卡图鉴 proficiency computation.
func (q *Queries) ListProjectCardCompletionsByUser(ctx context.Context, userID uuid.UUID) ([]ListProjectCardCompletionsByUserRow, error) {
	rows, err := q.db.Query(ctx, listProjectCardCompletionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectCardCompletionsByUserRow
	for rows.Next() {
		var i ListProjectCardCompletionsByUserRow
		if err := rows.Scan(&i.CardID, &i.Completions); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCardInstanceAnchors = `-- name: SetCardInstanceAnchors :one
UPDATE card_instances SET anchors = $3
WHERE id = $1 AND project_id = $2
RETURNING id, card_id, task_id, parent_node_id, status, field_values, event_trace, rubric_tags, created_at, completed_at, anchors, project_id, contract_ref, framework_fill, thread_id, session_id
`

type SetCardInstanceAnchorsParams struct {
	ID        uuid.UUID   `json:"id"`
	ProjectID pgtype.UUID `json:"project_id"`
	Anchors   []byte      `json:"anchors"`
}

func (q *Queries) SetCardInstanceAnchors(ctx context.Context, arg SetCardInstanceAnchorsParams) (CardInstance, error) {
	row := q.db.QueryRow(ctx, setCardInstanceAnchors, arg.ID, arg.ProjectID, arg.Anchors)
	var i CardInstance
	err := row.Scan(
		&i.ID,
		&i.CardID,
		&i.TaskID,
		&i.ParentNodeID,
		&i.Status,
		&i.FieldValues,
		&i.EventTrace,
		&i.RubricTags,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.Anchors,
		&i.ProjectID,
		&i.ContractRef,
		&i.FrameworkFill,
		&i.ThreadID,
		&i.SessionID,
	)
	return i, err
}

const setCardInstanceFramework = `-- name: SetCardInstanceFramework :one
UPDATE card_instances SET framework_fill = $3
WHERE id = $1 AND project_id = $2
RETURNING id, card_id, task_id, parent_node_id, status, field_values, event_trace, rubric_tags, created_at, completed_at, anchors, project_id, contract_ref, framework_fill, thread_id, session_id
`

type SetCardInstanceFrameworkParams struct {
	ID            uuid.UUID   `json:"id"`
	ProjectID     pgtype.UUID `json:"project_id"`
	FrameworkFill []byte      `json:"framework_fill"`
}

func (q *Queries) SetCardInstanceFramework(ctx context.Context, arg SetCardInstanceFrameworkParams) (CardInstance, error) {
	row := q.db.QueryRow(ctx, setCardInstanceFramework, arg.ID, arg.ProjectID, arg.FrameworkFill)
	var i CardInstance
	err := row.Scan(
		&i.ID,
		&i.CardID,
		&i.TaskID,
		&i.ParentNodeID,
		&i.Status,
		&i.FieldValues,
		&i.EventTrace,
		&i.RubricTags,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.Anchors,
		&i.ProjectID,
		&i.ContractRef,
		&i.FrameworkFill,
		&i.ThreadID,
		&i.SessionID,
	)
	return i, err
}

const setCardInstanceStatus = `-- name: SetCardInstanceStatus :one
UPDATE card_instances SET status = $3
WHERE id = $1 AND project_id = $2
RETURNING id, card_id, task_id, parent_node_id, status, field_values, event_trace, rubric_tags, created_at, completed_at, anchors, project_id, contract_ref, framework_fill, thread_id, session_id
`

type SetCardInstanceStatusParams struct {
	ID        uuid.UUID   `json:"id"`
	ProjectID pgtype.UUID `json:"project_id"`
	Status    string      `json:"status"`
}

func (q *Queries) SetCardInstanceStatus(ctx context.Context, arg SetCardInstanceStatusParams) (CardInstance, error) {
	row := q.db.QueryRow(ctx, setCardInstanceStatus, arg.ID, arg.ProjectID, arg.Status)
	var i CardInstance
	err := row.Scan(
		&i.ID,
		&i.CardID,
		&i.TaskID,
		&i.ParentNodeID,
		&i.Status,
		&i.FieldValues,
		&i.EventTrace,
		&i.RubricTags,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.Anchors,
		&i.ProjectID,
		&i.ContractRef,
		&i.FrameworkFill,
		&i.ThreadID,
		&i.SessionID,
	)
	return i, err
}

const setSessionCardInstanceStatus = `-- name: SetSessionCardInstanceStatus :one
UPDATE card_instances SET status = $3
WHERE id = $1 AND session_id = $2
RETURNING id, card_id, task_id, parent_node_id, status, field_values, event_trace, rubric_tags, created_at, completed_at, anchors, project_id, contract_ref, framework_fill, thread_id, session_id
`

type SetSessionCardInstanceStatusParams struct {
	ID        uuid.UUID   `json:"id"`
	SessionID pgtype.UUID `json:"session_id"`
	Status    string      `json:"status"`
}

func (q *Queries) SetSessionCardInstanceStatus(ctx context.Context, arg SetSessionCardInstanceStatusParams) (CardInstance, error) {
	row := q.db.QueryRow(ctx, setSessionCardInstanceStatus, arg.ID, arg.SessionID, arg.Status)
	var i CardInstance
	err := row.Scan(
		&i.ID,
		&i.CardID,
		&i.TaskID,
		&i.ParentNodeID,
		&i.Status,
		&i.FieldValues,
		&i.EventTrace,
		&i.RubricTags,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.Anchors,
		&i.ProjectID,
		&i.ContractRef,
		&i.FrameworkFill,
		&i.ThreadID,
		&i.SessionID,
	)
	return i, err
}

const setThreadCardInstanceStatus = `-- name: SetThreadCardInstanceStatus :one
UPDATE card_instances SET status = $3
WHERE id = $1 AND thread_id = $2
RETURNING id, card_id, task_id, parent_node_id, status, field_values, event_trace, rubric_tags, created_at, completed_at, anchors, project_id, contract_ref, framework_fill, thread_id, session_id
`

type SetThreadCardInstanceStatusParams struct {
	ID       uuid.UUID   `json:"id"`
	ThreadID pgtype.UUID `json:"thread_id"`
	Status   string      `json:"status"`
}

func (q *Queries) SetThreadCardInstanceStatus(ctx context.Context, arg SetThreadCardInstanceStatusParams) (CardInstance, error) {
	row := q.db.QueryRow(ctx, setThreadCardInstanceStatus, arg.ID, arg.ThreadID, arg.Status)
	var i CardInstance
	err := row.Scan(
		&i.ID,
		&i.CardID,
		&i.TaskID,
		&i.ParentNodeID,
		&i.Status,
		&i.FieldValues,
		&i.EventTrace,
		&i.RubricTags,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.Anchors,
		&i.ProjectID,
		&i.ContractRef,
		&i.FrameworkFill,
		&i.ThreadID,
		&i.SessionID,
	)
	return i, err
}

const submitProjectCardInstance = `-- name: SubmitProjectCardInstance :one
UPDATE card_instances SET field_values = $3, event_trace = $4
WHERE id = $1 AND project_id = $2
RETURNING id, card_id, task_id, parent_node_id, status, field_values, event_trace, rubric_tags, created_at, completed_at, anchors, project_id, contract_ref, framework_fill, thread_id, session_id
`

type SubmitProjectCardInstanceParams struct {
	ID          uuid.UUID   `json:"id"`
	ProjectID   pgtype.UUID `json:"project_id"`
	FieldValues []byte      `json:"field_values"`
	EventTrace  []byte      `json:"event_trace"`
}

func (q *Queries) SubmitProjectCardInstance(ctx context.Context, arg SubmitProjectCardInstanceParams) (CardInstance, error) {
	row := q.db.QueryRow(ctx, submitProjectCardInstance,
		arg.ID,
		arg.ProjectID,
		arg.FieldValues,
		arg.EventTrace,
	)
	var i CardInstance
	err := row.Scan(
		&i.ID,
		&i.CardID,
		&i.TaskID,
		&i.ParentNodeID,
		&i.Status,
		&i.FieldValues,
		&i.EventTrace,
		&i.RubricTags,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.Anchors,
		&i.ProjectID,
		&i.ContractRef,
		&i.FrameworkFill,
		&i.ThreadID,
		&i.SessionID,
	)
	return i, err
}

const submitSessionCardInstance = `-- name: SubmitSessionCardInstance :one
UPDATE card_instances
SET field_values = $3, event_trace = $4, status = $5, completed_at = now()
WHERE id = $1 AND session_id = $2
RETURNING id, card_id, task_id, parent_node_id, status, field_values, event_trace, rubric_tags, created_at, completed_at, anchors, project_id, contract_ref, framework_fill, thread_id, session_id
`

type SubmitSessionCardInstanceParams struct {
	ID          uuid.UUID   `json:"id"`
	SessionID   pgtype.UUID `json:"session_id"`
	FieldValues []byte      `json:"field_values"`
	EventTrace  []byte      `json:"event_trace"`
	Status      string      `json:"status"`
}

func (q *Queries) SubmitSessionCardInstance(ctx context.Context, arg SubmitSessionCardInstanceParams) (CardInstance, error) {
	row := q.db.QueryRow(ctx, submitSessionCardInstance,
		arg.ID,
		arg.SessionID,
		arg.FieldValues,
		arg.EventTrace,
		arg.Status,
	)
	var i CardInstance
	err := row.Scan(
		&i.ID,
		&i.CardID,
		&i.TaskID,
		&i.ParentNodeID,
		&i.Status,
		&i.FieldValues,
		&i.EventTrace,
		&i.RubricTags,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.Anchors,
		&i.ProjectID,
		&i.ContractRef,
		&i.FrameworkFill,
		&i.ThreadID,
		&i.SessionID,
	)
	return i, err
}

const submitThreadCardInstance = `-- name: SubmitThreadCardInstance :one
UPDATE card_instances SET field_values = $3, event_trace = $4, status = $5
WHERE id = $1 AND thread_id = $2
RETURNING id, card_id, task_id, parent_node_id, status, field_values, event_trace, rubric_tags, created_at, completed_at, anchors, project_id, contract_ref, framework_fill, thread_id, session_id
`

type SubmitThreadCardInstanceParams struct {
	ID          uuid.UUID   `json:"id"`
	ThreadID    pgtype.UUID `json:"thread_id"`
	FieldValues []byte      `json:"field_values"`
	EventTrace  []byte      `json:"event_trace"`
	Status      string      `json:"status"`
}

func (q *Queries) SubmitThreadCardInstance(ctx context.Context, arg SubmitThreadCardInstanceParams) (CardInstance, error) {
	row := q.db.QueryRow(ctx, submitThreadCardInstance,
		arg.ID,
		arg.ThreadID,
		arg.FieldValues,
		arg.EventTrace,
		arg.Status,
	)
	var i CardInstance
	err := row.Scan(
		&i.ID,
		&i.CardID,
		&i.TaskID,
		&i.ParentNodeID,
		&i.Status,
		&i.FieldValues,
		&i.EventTrace,
		&i.RubricTags,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.Anchors,
		&i.ProjectID,
		&i.ContractRef,
		&i.FrameworkFill,
		&i.ThreadID,
		&i.SessionID,
	)
	return i, err
}
