// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: chat.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createChatMessage = `-- name: CreateChatMessage :one
INSERT INTO chat_message (thread_id, role, content, modality)
VALUES ($1, $2, $3, $4)
RETURNING id, thread_id, role, content, modality, attachments, quoted_fragment, created_at
`

type CreateChatMessageParams struct {
	ThreadID uuid.UUID `json:"thread_id"`
	Role     string    `json:"role"`
	Content  string    `json:"content"`
	Modality string    `json:"modality"`
}

func (q *Queries) CreateChatMessage(ctx context.Context, arg CreateChatMessageParams) (ChatMessage, error) {
	row := q.db.QueryRow(ctx, createChatMessage,
		arg.ThreadID,
		arg.Role,
		arg.Content,
		arg.Modality,
	)
	var i ChatMessage
	err := row.Scan(
		&i.ID,
		&i.ThreadID,
		&i.Role,
		&i.Content,
		&i.Modality,
		&i.Attachments,
		&i.QuotedFragment,
		&i.CreatedAt,
	)
	return i, err
}

const createThread = `-- name: CreateThread :one
INSERT INTO chat_thread (user_id, seeded_project_id) VALUES ($1, $2)
RETURNING id, user_id, title, seeded_project_id, created_at
`

type CreateThreadParams struct {
	UserID          uuid.UUID   `json:"user_id"`
	SeededProjectID pgtype.UUID `json:"seeded_project_id"`
}

func (q *Queries) CreateThread(ctx context.Context, arg CreateThreadParams) (ChatThread, error) {
	row := q.db.QueryRow(ctx, createThread, arg.UserID, arg.SeededProjectID)
	var i ChatThread
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.SeededProjectID,
		&i.CreatedAt,
	)
	return i, err
}

const getThreadByProject = `-- name: GetThreadByProject :one

SELECT id, user_id, title, seeded_project_id, created_at FROM chat_thread WHERE seeded_project_id = $1 LIMIT 1
`

// chat_thread/chat_message queries (Slice 5c, agent conversational loop).
// chat_message has no project_id of its own — it joins through
// chat_thread.seeded_project_id, which is nullable (pgtype.UUID param).
func (q *Queries) GetThreadByProject(ctx context.Context, seededProjectID pgtype.UUID) (ChatThread, error) {
	row := q.db.QueryRow(ctx, getThreadByProject, seededProjectID)
	var i ChatThread
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.SeededProjectID,
		&i.CreatedAt,
	)
	return i, err
}

const listChatMessagesByProject = `-- name: ListChatMessagesByProject :many
SELECT cm.id, cm.thread_id, cm.role, cm.content, cm.modality, cm.attachments, cm.quoted_fragment, cm.created_at FROM chat_message cm
JOIN chat_thread ct ON cm.thread_id = ct.id
WHERE ct.seeded_project_id = $1
ORDER BY cm.created_at, cm.id
`

func (q *Queries) ListChatMessagesByProject(ctx context.Context, seededProjectID pgtype.UUID) ([]ChatMessage, error) {
	rows, err := q.db.Query(ctx, listChatMessagesByProject, seededProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatMessage
	for rows.Next() {
		var i ChatMessage
		if err := rows.Scan(
			&i.ID,
			&i.ThreadID,
			&i.Role,
			&i.Content,
			&i.Modality,
			&i.Attachments,
			&i.QuotedFragment,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
