// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: citation.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createCitation = `-- name: CreateCitation :one

INSERT INTO citation (project_id, reference_id, section)
VALUES ($1, $2, $3)
RETURNING id, project_id, reference_id, section, created_at
`

type CreateCitationParams struct {
	ProjectID   uuid.UUID `json:"project_id"`
	ReferenceID uuid.UUID `json:"reference_id"`
	Section     string    `json:"section"`
}

// G3 · source→section citation links (see migration 0068).
func (q *Queries) CreateCitation(ctx context.Context, arg CreateCitationParams) (Citation, error) {
	row := q.db.QueryRow(ctx, createCitation, arg.ProjectID, arg.ReferenceID, arg.Section)
	var i Citation
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ReferenceID,
		&i.Section,
		&i.CreatedAt,
	)
	return i, err
}

const listCitationsByProject = `-- name: ListCitationsByProject :many
SELECT id, project_id, reference_id, section, created_at FROM citation
WHERE project_id = $1
ORDER BY created_at, id
`

func (q *Queries) ListCitationsByProject(ctx context.Context, projectID uuid.UUID) ([]Citation, error) {
	rows, err := q.db.Query(ctx, listCitationsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Citation
	for rows.Next() {
		var i Citation
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ReferenceID,
			&i.Section,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
