// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: course.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const finishedCourseIDsByUser = `-- name: FinishedCourseIDsByUser :many
SELECT DISTINCT course_id FROM course_progress
WHERE user_id = $1 AND completed_at IS NOT NULL
`

// Task 5 addition: cards_catalog.go's proficiency computation ("which
// courses has this student finished") needs this and it was dropped by
// Task 3 with no v2 replacement ("no v2 replacement asked for" — it used to
// read course_session.status='finished', a table migration 0050 removed).
// Ported to the v2 schema: a course is finished when course_progress.
// completed_at is set (SaveProgress sets it exactly when the student's
// current_ordinal reaches the last authored step — see coursestore.go).
func (q *Queries) FinishedCourseIDsByUser(ctx context.Context, userID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, finishedCourseIDsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var course_id uuid.UUID
		if err := rows.Scan(&course_id); err != nil {
			return nil, err
		}
		items = append(items, course_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCourseBySlug = `-- name: GetCourseBySlug :one
SELECT id, slug, branch, title, blurb, time_label, card_ids, step_count, structure, render_cache
FROM course WHERE slug = $1
`

type GetCourseBySlugRow struct {
	ID          uuid.UUID `json:"id"`
	Slug        string    `json:"slug"`
	Branch      string    `json:"branch"`
	Title       string    `json:"title"`
	Blurb       string    `json:"blurb"`
	TimeLabel   string    `json:"time_label"`
	CardIds     []string  `json:"card_ids"`
	StepCount   int32     `json:"step_count"`
	Structure   []byte    `json:"structure"`
	RenderCache []byte    `json:"render_cache"`
}

func (q *Queries) GetCourseBySlug(ctx context.Context, slug string) (GetCourseBySlugRow, error) {
	row := q.db.QueryRow(ctx, getCourseBySlug, slug)
	var i GetCourseBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Branch,
		&i.Title,
		&i.Blurb,
		&i.TimeLabel,
		&i.CardIds,
		&i.StepCount,
		&i.Structure,
		&i.RenderCache,
	)
	return i, err
}

const getCourseProgressByCourseID = `-- name: GetCourseProgressByCourseID :one
SELECT course_id, current_ordinal, completed_ordinals, started_at, completed_at, updated_at
FROM course_progress
WHERE user_id = $1 AND course_id = $2
`

type GetCourseProgressByCourseIDParams struct {
	UserID   uuid.UUID `json:"user_id"`
	CourseID uuid.UUID `json:"course_id"`
}

type GetCourseProgressByCourseIDRow struct {
	CourseID          uuid.UUID          `json:"course_id"`
	CurrentOrdinal    int32              `json:"current_ordinal"`
	CompletedOrdinals []int32            `json:"completed_ordinals"`
	StartedAt         pgtype.Timestamptz `json:"started_at"`
	CompletedAt       pgtype.Timestamptz `json:"completed_at"`
	UpdatedAt         time.Time          `json:"updated_at"`
}

// Task 4 addition: SaveProgress's union-completed-ordinals step is keyed by
// courseUUID (not slug) — it already holds the course row's id from
// GetCoursePayload, and a slug round-trip would be a wasted join. Mirrors
// GetCourseProgressBySlug's column list/order exactly.
func (q *Queries) GetCourseProgressByCourseID(ctx context.Context, arg GetCourseProgressByCourseIDParams) (GetCourseProgressByCourseIDRow, error) {
	row := q.db.QueryRow(ctx, getCourseProgressByCourseID, arg.UserID, arg.CourseID)
	var i GetCourseProgressByCourseIDRow
	err := row.Scan(
		&i.CourseID,
		&i.CurrentOrdinal,
		&i.CompletedOrdinals,
		&i.StartedAt,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCourseProgressBySlug = `-- name: GetCourseProgressBySlug :one
SELECT p.course_id, p.current_ordinal, p.completed_ordinals, p.started_at, p.completed_at, p.updated_at
FROM course_progress p JOIN course c ON c.id = p.course_id
WHERE p.user_id = $1 AND c.slug = $2
`

type GetCourseProgressBySlugParams struct {
	UserID uuid.UUID `json:"user_id"`
	Slug   string    `json:"slug"`
}

type GetCourseProgressBySlugRow struct {
	CourseID          uuid.UUID          `json:"course_id"`
	CurrentOrdinal    int32              `json:"current_ordinal"`
	CompletedOrdinals []int32            `json:"completed_ordinals"`
	StartedAt         pgtype.Timestamptz `json:"started_at"`
	CompletedAt       pgtype.Timestamptz `json:"completed_at"`
	UpdatedAt         time.Time          `json:"updated_at"`
}

func (q *Queries) GetCourseProgressBySlug(ctx context.Context, arg GetCourseProgressBySlugParams) (GetCourseProgressBySlugRow, error) {
	row := q.db.QueryRow(ctx, getCourseProgressBySlug, arg.UserID, arg.Slug)
	var i GetCourseProgressBySlugRow
	err := row.Scan(
		&i.CourseID,
		&i.CurrentOrdinal,
		&i.CompletedOrdinals,
		&i.StartedAt,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCourseRows = `-- name: ListCourseRows :many

SELECT slug, branch, title, blurb, time_label, card_ids, step_count
FROM course ORDER BY branch, title
`

type ListCourseRowsRow struct {
	Slug      string   `json:"slug"`
	Branch    string   `json:"branch"`
	Title     string   `json:"title"`
	Blurb     string   `json:"blurb"`
	TimeLabel string   `json:"time_label"`
	CardIds   []string `json:"card_ids"`
	StepCount int32    `json:"step_count"`
}

// Course v2 (migration 0050): the phase-gated runtime (course_session/
// course_message/course_step/course_step_render) is retired. `course` now
// holds the externally-authored structure + published render cache verbatim
// (+ attached tool card ids), addressed by a stable slug; course.id stays a
// uuid so the pre-existing event.course_id FK (0031) survives. course_progress
// stays the page-position unit, now with started_at/completed_at bookkeeping.
func (q *Queries) ListCourseRows(ctx context.Context) ([]ListCourseRowsRow, error) {
	rows, err := q.db.Query(ctx, listCourseRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCourseRowsRow
	for rows.Next() {
		var i ListCourseRowsRow
		if err := rows.Scan(
			&i.Slug,
			&i.Branch,
			&i.Title,
			&i.Blurb,
			&i.TimeLabel,
			&i.CardIds,
			&i.StepCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCourse = `-- name: UpsertCourse :one
INSERT INTO course (slug, branch, title, blurb, time_label, card_ids, step_count, structure, render_cache, updated_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9, now())
ON CONFLICT (slug) DO UPDATE SET
  branch = EXCLUDED.branch, title = EXCLUDED.title, blurb = EXCLUDED.blurb,
  time_label = EXCLUDED.time_label, card_ids = EXCLUDED.card_ids,
  step_count = EXCLUDED.step_count, structure = EXCLUDED.structure,
  render_cache = EXCLUDED.render_cache, updated_at = now()
RETURNING id, slug
`

type UpsertCourseParams struct {
	Slug        string   `json:"slug"`
	Branch      string   `json:"branch"`
	Title       string   `json:"title"`
	Blurb       string   `json:"blurb"`
	TimeLabel   string   `json:"time_label"`
	CardIds     []string `json:"card_ids"`
	StepCount   int32    `json:"step_count"`
	Structure   []byte   `json:"structure"`
	RenderCache []byte   `json:"render_cache"`
}

type UpsertCourseRow struct {
	ID   uuid.UUID `json:"id"`
	Slug string    `json:"slug"`
}

func (q *Queries) UpsertCourse(ctx context.Context, arg UpsertCourseParams) (UpsertCourseRow, error) {
	row := q.db.QueryRow(ctx, upsertCourse,
		arg.Slug,
		arg.Branch,
		arg.Title,
		arg.Blurb,
		arg.TimeLabel,
		arg.CardIds,
		arg.StepCount,
		arg.Structure,
		arg.RenderCache,
	)
	var i UpsertCourseRow
	err := row.Scan(&i.ID, &i.Slug)
	return i, err
}

const upsertCourseProgress = `-- name: UpsertCourseProgress :one
INSERT INTO course_progress (user_id, course_id, current_ordinal, completed_ordinals, started_at, completed_at, updated_at)
VALUES (
  $1, $2, $3, $4,
  COALESCE($5::timestamptz, now()), $6, now()
)
ON CONFLICT (user_id, course_id) DO UPDATE SET
  current_ordinal = EXCLUDED.current_ordinal,
  completed_ordinals = EXCLUDED.completed_ordinals,
  started_at = COALESCE(course_progress.started_at, EXCLUDED.started_at),
  completed_at = COALESCE(EXCLUDED.completed_at, course_progress.completed_at),
  updated_at = now()
RETURNING course_id, current_ordinal, completed_ordinals, started_at, completed_at, updated_at
`

type UpsertCourseProgressParams struct {
	UserID            uuid.UUID          `json:"user_id"`
	CourseID          uuid.UUID          `json:"course_id"`
	CurrentOrdinal    int32              `json:"current_ordinal"`
	CompletedOrdinals []int32            `json:"completed_ordinals"`
	StartedAt         pgtype.Timestamptz `json:"started_at"`
	CompletedAt       pgtype.Timestamptz `json:"completed_at"`
}

type UpsertCourseProgressRow struct {
	CourseID          uuid.UUID          `json:"course_id"`
	CurrentOrdinal    int32              `json:"current_ordinal"`
	CompletedOrdinals []int32            `json:"completed_ordinals"`
	StartedAt         pgtype.Timestamptz `json:"started_at"`
	CompletedAt       pgtype.Timestamptz `json:"completed_at"`
	UpdatedAt         time.Time          `json:"updated_at"`
}

func (q *Queries) UpsertCourseProgress(ctx context.Context, arg UpsertCourseProgressParams) (UpsertCourseProgressRow, error) {
	row := q.db.QueryRow(ctx, upsertCourseProgress,
		arg.UserID,
		arg.CourseID,
		arg.CurrentOrdinal,
		arg.CompletedOrdinals,
		arg.StartedAt,
		arg.CompletedAt,
	)
	var i UpsertCourseProgressRow
	err := row.Scan(
		&i.CourseID,
		&i.CurrentOrdinal,
		&i.CompletedOrdinals,
		&i.StartedAt,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}
