// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: course.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countCourseSteps = `-- name: CountCourseSteps :one
SELECT count(*) FROM course_step WHERE course_id = $1
`

func (q *Queries) CountCourseSteps(ctx context.Context, courseID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCourseSteps, courseID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getCourse = `-- name: GetCourse :one
SELECT id, branch, title, blurb, tasks_count, tools_count, time_label, created_at FROM course WHERE id = $1
`

func (q *Queries) GetCourse(ctx context.Context, id uuid.UUID) (Course, error) {
	row := q.db.QueryRow(ctx, getCourse, id)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.Branch,
		&i.Title,
		&i.Blurb,
		&i.TasksCount,
		&i.ToolsCount,
		&i.TimeLabel,
		&i.CreatedAt,
	)
	return i, err
}

const getCourseProgress = `-- name: GetCourseProgress :one
SELECT id, user_id, course_id, current_ordinal, completed_ordinals, updated_at FROM course_progress WHERE user_id = $1 AND course_id = $2
`

type GetCourseProgressParams struct {
	UserID   uuid.UUID `json:"user_id"`
	CourseID uuid.UUID `json:"course_id"`
}

func (q *Queries) GetCourseProgress(ctx context.Context, arg GetCourseProgressParams) (CourseProgress, error) {
	row := q.db.QueryRow(ctx, getCourseProgress, arg.UserID, arg.CourseID)
	var i CourseProgress
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CourseID,
		&i.CurrentOrdinal,
		&i.CompletedOrdinals,
		&i.UpdatedAt,
	)
	return i, err
}

const getCourseStepByOrdinal = `-- name: GetCourseStepByOrdinal :one
SELECT id, course_id, ordinal, kind, purpose, assets, challenge_type, authored_content FROM course_step WHERE course_id = $1 AND ordinal = $2
`

type GetCourseStepByOrdinalParams struct {
	CourseID uuid.UUID `json:"course_id"`
	Ordinal  int32     `json:"ordinal"`
}

func (q *Queries) GetCourseStepByOrdinal(ctx context.Context, arg GetCourseStepByOrdinalParams) (CourseStep, error) {
	row := q.db.QueryRow(ctx, getCourseStepByOrdinal, arg.CourseID, arg.Ordinal)
	var i CourseStep
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Ordinal,
		&i.Kind,
		&i.Purpose,
		&i.Assets,
		&i.ChallengeType,
		&i.AuthoredContent,
	)
	return i, err
}

const getCourseStepRender = `-- name: GetCourseStepRender :one
SELECT course_step_id, content, source, created_at FROM course_step_render WHERE course_step_id = $1
`

func (q *Queries) GetCourseStepRender(ctx context.Context, courseStepID uuid.UUID) (CourseStepRender, error) {
	row := q.db.QueryRow(ctx, getCourseStepRender, courseStepID)
	var i CourseStepRender
	err := row.Scan(
		&i.CourseStepID,
		&i.Content,
		&i.Source,
		&i.CreatedAt,
	)
	return i, err
}

const listCourseSteps = `-- name: ListCourseSteps :many
SELECT id, course_id, ordinal, kind, purpose, assets, challenge_type, authored_content FROM course_step WHERE course_id = $1 ORDER BY ordinal
`

func (q *Queries) ListCourseSteps(ctx context.Context, courseID uuid.UUID) ([]CourseStep, error) {
	rows, err := q.db.Query(ctx, listCourseSteps, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CourseStep
	for rows.Next() {
		var i CourseStep
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.Ordinal,
			&i.Kind,
			&i.Purpose,
			&i.Assets,
			&i.ChallengeType,
			&i.AuthoredContent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCourses = `-- name: ListCourses :many
SELECT c.id, c.branch, c.title, c.blurb, c.tasks_count, c.tools_count, c.time_label, c.created_at, count(s.id) AS step_count
FROM course c
LEFT JOIN course_step s ON s.course_id = c.id
GROUP BY c.id
ORDER BY c.created_at
`

type ListCoursesRow struct {
	ID         uuid.UUID `json:"id"`
	Branch     string    `json:"branch"`
	Title      string    `json:"title"`
	Blurb      string    `json:"blurb"`
	TasksCount int32     `json:"tasks_count"`
	ToolsCount int32     `json:"tools_count"`
	TimeLabel  string    `json:"time_label"`
	CreatedAt  time.Time `json:"created_at"`
	StepCount  int64     `json:"step_count"`
}

func (q *Queries) ListCourses(ctx context.Context) ([]ListCoursesRow, error) {
	rows, err := q.db.Query(ctx, listCourses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCoursesRow
	for rows.Next() {
		var i ListCoursesRow
		if err := rows.Scan(
			&i.ID,
			&i.Branch,
			&i.Title,
			&i.Blurb,
			&i.TasksCount,
			&i.ToolsCount,
			&i.TimeLabel,
			&i.CreatedAt,
			&i.StepCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordCourseStepViewed = `-- name: RecordCourseStepViewed :one
INSERT INTO course_progress (user_id, course_id, current_ordinal, completed_ordinals)
VALUES ($1, $2, $3, ARRAY[$3]::int[])
ON CONFLICT (user_id, course_id) DO UPDATE
SET completed_ordinals = (
        SELECT array_agg(DISTINCT v ORDER BY v)
        FROM unnest(array_append(course_progress.completed_ordinals, $3::int)) AS v
    ),
    updated_at = now()
RETURNING id, user_id, course_id, current_ordinal, completed_ordinals, updated_at
`

type RecordCourseStepViewedParams struct {
	UserID   uuid.UUID `json:"user_id"`
	CourseID uuid.UUID `json:"course_id"`
	Ordinal  int32     `json:"ordinal"`
}

// The `steps_viewed` floor's ONLY input writer (DEC-12.2 / whole-branch
// C1+C3): called once per real POST .../steps/{ordinal}/render — the moment
// the student's browser actually opens that page — appending the ordinal to
// completed_ordinals idempotently (array_agg DISTINCT dedupes a re-render of
// an already-viewed page). A client can never assert this column: PUT
// /progress (SetCourseCurrentOrdinal above) does not accept it.
func (q *Queries) RecordCourseStepViewed(ctx context.Context, arg RecordCourseStepViewedParams) (CourseProgress, error) {
	row := q.db.QueryRow(ctx, recordCourseStepViewed, arg.UserID, arg.CourseID, arg.Ordinal)
	var i CourseProgress
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CourseID,
		&i.CurrentOrdinal,
		&i.CompletedOrdinals,
		&i.UpdatedAt,
	)
	return i, err
}

const setCourseCurrentOrdinal = `-- name: SetCourseCurrentOrdinal :one
INSERT INTO course_progress (user_id, course_id, current_ordinal, completed_ordinals)
VALUES ($1, $2, $3, '{}')
ON CONFLICT (user_id, course_id) DO UPDATE
SET current_ordinal = EXCLUDED.current_ordinal, updated_at = now()
RETURNING id, user_id, course_id, current_ordinal, completed_ordinals, updated_at
`

type SetCourseCurrentOrdinalParams struct {
	UserID         uuid.UUID `json:"user_id"`
	CourseID       uuid.UUID `json:"course_id"`
	CurrentOrdinal int32     `json:"current_ordinal"`
}

// The resume-position write (PUT /courses/{id}/progress): current_ordinal is
// UX, never a floor input (Slice-12 whole-branch C1+C3 fix), so this is the
// ONLY column it touches. completed_ordinals is left untouched on conflict —
// RecordCourseStepViewed below is its only writer — and defaults to empty on
// a fresh row (no step has been server-recorded as viewed yet).
func (q *Queries) SetCourseCurrentOrdinal(ctx context.Context, arg SetCourseCurrentOrdinalParams) (CourseProgress, error) {
	row := q.db.QueryRow(ctx, setCourseCurrentOrdinal, arg.UserID, arg.CourseID, arg.CurrentOrdinal)
	var i CourseProgress
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CourseID,
		&i.CurrentOrdinal,
		&i.CompletedOrdinals,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertCourseProgress = `-- name: UpsertCourseProgress :one
INSERT INTO course_progress (user_id, course_id, current_ordinal, completed_ordinals)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, course_id) DO UPDATE
SET current_ordinal = EXCLUDED.current_ordinal,
    completed_ordinals = EXCLUDED.completed_ordinals,
    updated_at = now()
RETURNING id, user_id, course_id, current_ordinal, completed_ordinals, updated_at
`

type UpsertCourseProgressParams struct {
	UserID            uuid.UUID `json:"user_id"`
	CourseID          uuid.UUID `json:"course_id"`
	CurrentOrdinal    int32     `json:"current_ordinal"`
	CompletedOrdinals []int32   `json:"completed_ordinals"`
}

func (q *Queries) UpsertCourseProgress(ctx context.Context, arg UpsertCourseProgressParams) (CourseProgress, error) {
	row := q.db.QueryRow(ctx, upsertCourseProgress,
		arg.UserID,
		arg.CourseID,
		arg.CurrentOrdinal,
		arg.CompletedOrdinals,
	)
	var i CourseProgress
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CourseID,
		&i.CurrentOrdinal,
		&i.CompletedOrdinals,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertCourseStepRender = `-- name: UpsertCourseStepRender :one
INSERT INTO course_step_render (course_step_id, content, source)
VALUES ($1, $2, $3)
ON CONFLICT (course_step_id) DO UPDATE
SET content = EXCLUDED.content, source = EXCLUDED.source, created_at = now()
RETURNING course_step_id, content, source, created_at
`

type UpsertCourseStepRenderParams struct {
	CourseStepID uuid.UUID `json:"course_step_id"`
	Content      []byte    `json:"content"`
	Source       string    `json:"source"`
}

func (q *Queries) UpsertCourseStepRender(ctx context.Context, arg UpsertCourseStepRenderParams) (CourseStepRender, error) {
	row := q.db.QueryRow(ctx, upsertCourseStepRender, arg.CourseStepID, arg.Content, arg.Source)
	var i CourseStepRender
	err := row.Scan(
		&i.CourseStepID,
		&i.Content,
		&i.Source,
		&i.CreatedAt,
	)
	return i, err
}
