// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: event.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const appendEvent = `-- name: AppendEvent :one

INSERT INTO event (project_id, user_id, surface, type, payload)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, project_id, user_id, surface, type, payload, created_at
`

type AppendEventParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	UserID    uuid.UUID   `json:"user_id"`
	Surface   string      `json:"surface"`
	Type      string      `json:"type"`
	Payload   []byte      `json:"payload"`
}

// Append-only event stream (C4). Deliberately no update/delete query.
func (q *Queries) AppendEvent(ctx context.Context, arg AppendEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, appendEvent,
		arg.ProjectID,
		arg.UserID,
		arg.Surface,
		arg.Type,
		arg.Payload,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.Surface,
		&i.Type,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const listEventsByProject = `-- name: ListEventsByProject :many
SELECT id, project_id, user_id, surface, type, payload, created_at FROM event
WHERE project_id = $1
ORDER BY created_at, id
`

func (q *Queries) ListEventsByProject(ctx context.Context, projectID pgtype.UUID) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEventsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.UserID,
			&i.Surface,
			&i.Type,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
