// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: lite_weekly.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getLiteClassWeeklyProse = `-- name: GetLiteClassWeeklyProse :one
SELECT class_id, week_start, body, created_at FROM lite_class_weekly_prose
WHERE class_id = $1 AND week_start = $2
`

type GetLiteClassWeeklyProseParams struct {
	ClassID   uuid.UUID   `json:"class_id"`
	WeekStart pgtype.Date `json:"week_start"`
}

func (q *Queries) GetLiteClassWeeklyProse(ctx context.Context, arg GetLiteClassWeeklyProseParams) (LiteClassWeeklyProse, error) {
	row := q.db.QueryRow(ctx, getLiteClassWeeklyProse, arg.ClassID, arg.WeekStart)
	var i LiteClassWeeklyProse
	err := row.Scan(
		&i.ClassID,
		&i.WeekStart,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const getLiteStudentWeeklyProse = `-- name: GetLiteStudentWeeklyProse :one
SELECT user_id, week_start, body, created_at FROM lite_student_weekly_prose
WHERE user_id = $1 AND week_start = $2
`

type GetLiteStudentWeeklyProseParams struct {
	UserID    uuid.UUID   `json:"user_id"`
	WeekStart pgtype.Date `json:"week_start"`
}

func (q *Queries) GetLiteStudentWeeklyProse(ctx context.Context, arg GetLiteStudentWeeklyProseParams) (LiteStudentWeeklyProse, error) {
	row := q.db.QueryRow(ctx, getLiteStudentWeeklyProse, arg.UserID, arg.WeekStart)
	var i LiteStudentWeeklyProse
	err := row.Scan(
		&i.UserID,
		&i.WeekStart,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const insertLiteClassWeeklyProse = `-- name: InsertLiteClassWeeklyProse :exec
INSERT INTO lite_class_weekly_prose (class_id, week_start, body)
VALUES ($1, $2, $3)
ON CONFLICT (class_id, week_start) DO NOTHING
`

type InsertLiteClassWeeklyProseParams struct {
	ClassID   uuid.UUID   `json:"class_id"`
	WeekStart pgtype.Date `json:"week_start"`
	Body      []byte      `json:"body"`
}

func (q *Queries) InsertLiteClassWeeklyProse(ctx context.Context, arg InsertLiteClassWeeklyProseParams) error {
	_, err := q.db.Exec(ctx, insertLiteClassWeeklyProse, arg.ClassID, arg.WeekStart, arg.Body)
	return err
}

const insertLiteStudentWeeklyProse = `-- name: InsertLiteStudentWeeklyProse :exec
INSERT INTO lite_student_weekly_prose (user_id, week_start, body)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, week_start) DO NOTHING
`

type InsertLiteStudentWeeklyProseParams struct {
	UserID    uuid.UUID   `json:"user_id"`
	WeekStart pgtype.Date `json:"week_start"`
	Body      []byte      `json:"body"`
}

func (q *Queries) InsertLiteStudentWeeklyProse(ctx context.Context, arg InsertLiteStudentWeeklyProseParams) error {
	_, err := q.db.Exec(ctx, insertLiteStudentWeeklyProse, arg.UserID, arg.WeekStart, arg.Body)
	return err
}

const listLiteWeekActivity = `-- name: ListLiteWeekActivity :many
SELECT u.id AS user_id,
       (SELECT count(DISTINCT x.day) FROM (
          SELECT d.day FROM atom_active_day d JOIN atom a ON a.id = d.atom_id
           WHERE a.user_id = u.id AND d.seconds > 0 AND d.day >= $1::date AND d.day < $2::date
          UNION
          SELECT (m.created_at AT TIME ZONE 'Asia/Shanghai')::date FROM atom_message m JOIN atom a ON a.id = m.atom_id
           WHERE a.user_id = u.id AND m.role = 'student' AND m.created_at >= $3::timestamptz AND m.created_at < $4::timestamptz
        ) x)::int AS active_days,
       (SELECT count(DISTINCT x.day) FROM (
          SELECT d.day FROM atom_active_day d JOIN atom a ON a.id = d.atom_id
           WHERE a.user_id = u.id AND d.seconds > 0 AND d.day >= $5::date AND d.day < $1::date
          UNION
          SELECT (m.created_at AT TIME ZONE 'Asia/Shanghai')::date FROM atom_message m JOIN atom a ON a.id = m.atom_id
           WHERE a.user_id = u.id AND m.role = 'student' AND m.created_at >= $6::timestamptz AND m.created_at < $3::timestamptz
        ) x)::int AS prev_active_days,
       COALESCE((SELECT sum(d.seconds) FROM atom_active_day d JOIN atom a ON a.id = d.atom_id
         WHERE a.user_id = u.id AND d.day >= $1::date AND d.day < $2::date), 0)::int AS seconds,
       EXISTS (SELECT 1 FROM atom_active_day d JOIN atom a ON a.id = d.atom_id
         WHERE a.user_id = u.id AND d.day < $2::date) AS has_any_bucket_by_week_end,
       (SELECT count(*) FROM atom_message m JOIN atom a ON a.id = m.atom_id
         WHERE a.user_id = u.id AND m.role = 'student' AND m.created_at >= $3::timestamptz AND m.created_at < $4::timestamptz)::int AS turns
FROM users u
WHERE u.id = ANY($7::uuid[])
`

type ListLiteWeekActivityParams struct {
	WeekStartDay pgtype.Date `json:"week_start_day"`
	WeekEndDay   pgtype.Date `json:"week_end_day"`
	WeekStart    time.Time   `json:"week_start"`
	WeekEnd      time.Time   `json:"week_end"`
	PrevStartDay pgtype.Date `json:"prev_start_day"`
	PrevStart    time.Time   `json:"prev_start"`
	UserIds      []uuid.UUID `json:"user_ids"`
}

type ListLiteWeekActivityRow struct {
	UserID                uuid.UUID `json:"user_id"`
	ActiveDays            int32     `json:"active_days"`
	PrevActiveDays        int32     `json:"prev_active_days"`
	Seconds               int32     `json:"seconds"`
	HasAnyBucketByWeekEnd bool      `json:"has_any_bucket_by_week_end"`
	Turns                 int32     `json:"turns"`
}

// 活跃天数与名单查询（ListLiteClassRoster）同一个形状：秒数 > 0 的日格 ∪ 她发消息的北京日期。
// has_any_bucket_by_week_end 区分「从没记过时长」（界面显示无记录）与「记过，这周是 0」。
func (q *Queries) ListLiteWeekActivity(ctx context.Context, arg ListLiteWeekActivityParams) ([]ListLiteWeekActivityRow, error) {
	rows, err := q.db.Query(ctx, listLiteWeekActivity,
		arg.WeekStartDay,
		arg.WeekEndDay,
		arg.WeekStart,
		arg.WeekEnd,
		arg.PrevStartDay,
		arg.PrevStart,
		arg.UserIds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLiteWeekActivityRow
	for rows.Next() {
		var i ListLiteWeekActivityRow
		if err := rows.Scan(
			&i.UserID,
			&i.ActiveDays,
			&i.PrevActiveDays,
			&i.Seconds,
			&i.HasAnyBucketByWeekEnd,
			&i.Turns,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiteWeekAssignmentStates = `-- name: ListLiteWeekAssignmentStates :many
SELECT r.user_id, r.started_at, a.due_at,
       COALESCE(rd.finished_at, w.finished_at, p.finished_at) AS finished_at
FROM lite_assignment_recipient r
JOIN lite_assignment a ON a.id = r.assignment_id
LEFT JOIN reading rd ON rd.atom_id = r.atom_id
LEFT JOIN writing w ON w.atom_id = r.atom_id
LEFT JOIN pbl_project p ON p.atom_id = r.atom_id
WHERE a.class_id = $1
  AND (a.archived_at IS NULL OR a.archived_at >= $2::timestamptz)
  AND r.user_id = ANY($3::uuid[])
  AND a.due_at >= $4::timestamptz AND a.due_at < $2::timestamptz
`

type ListLiteWeekAssignmentStatesParams struct {
	ClassID   uuid.UUID   `json:"class_id"`
	WeekEnd   time.Time   `json:"week_end"`
	UserIds   []uuid.UUID `json:"user_ids"`
	WeekStart time.Time   `json:"week_start"`
}

type ListLiteWeekAssignmentStatesRow struct {
	UserID     uuid.UUID          `json:"user_id"`
	StartedAt  pgtype.Timestamptz `json:"started_at"`
	DueAt      time.Time          `json:"due_at"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
}

// 截止时间落在这一周的作业（本班、到周末仍未归档）。finished_at 的取法与 ListLiteClassRecipientStates 一致；
// 状态在 Go 里用 liteassign.Status(…, now = week_end) 推出，周末之后才完成的记为已逾期。
// 周末之后才归档的作业仍算在那一周：归档不改写已经结束的一周（那一周的总结文字只生成一次）。
// 接受的偏差：老师事后改了 due_at，或把某名学生从收件人里移除，那一周的事实会跟着变，这里不追溯。
func (q *Queries) ListLiteWeekAssignmentStates(ctx context.Context, arg ListLiteWeekAssignmentStatesParams) ([]ListLiteWeekAssignmentStatesRow, error) {
	rows, err := q.db.Query(ctx, listLiteWeekAssignmentStates,
		arg.ClassID,
		arg.WeekEnd,
		arg.UserIds,
		arg.WeekStart,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLiteWeekAssignmentStatesRow
	for rows.Next() {
		var i ListLiteWeekAssignmentStatesRow
		if err := rows.Scan(
			&i.UserID,
			&i.StartedAt,
			&i.DueAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiteWeekClassStudents = `-- name: ListLiteWeekClassStudents :many

SELECT u.id, u.display_name
FROM enrollments e
JOIN users u ON u.id = e.user_id
WHERE e.class_id = $1 AND e.role_in_class = 'student' AND u.role = 'student'
ORDER BY u.display_name, u.id
`

type ListLiteWeekClassStudentsRow struct {
	ID          uuid.UUID `json:"id"`
	DisplayName string    `json:"display_name"`
}

// 教师端（lite）周总结的事实数据。只读；只数、只取产出，不取对话正文。
// 一周 = [week_start, week_end)，北京时间周一 00:00 起。*_day 参数是同一时刻的北京日期。
// 所有查询按 user_ids 批量取，Go 侧按 user_id 分组。
//
// 「完成」的判定按种类（与 lite_teacher.sql 的名单一致）：
//
//	reading / writing：status = 'finished'，完成时间取 finished_at；
//	project：pbl_project.finished_at（第一次进入回顾或保留时写入）。
//
// 标题：她的标题 → 项目名 → 她自己开的项目的 idea → 布置这一项的作业标题 → 种类名
// （阅读 / 写作 / 项目），永远不是空串。老师布置的项目（assigned = true）的 idea 是老师的
// 驱动问题，不作标题兜底。布置的写作题目在 writing.assigned_prompt，从不当作标题或金句。
// 当前在班的学生（班内角色与账号角色都是 student），教师与管理员不在内。
func (q *Queries) ListLiteWeekClassStudents(ctx context.Context, classID uuid.UUID) ([]ListLiteWeekClassStudentsRow, error) {
	rows, err := q.db.Query(ctx, listLiteWeekClassStudents, classID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLiteWeekClassStudentsRow
	for rows.Next() {
		var i ListLiteWeekClassStudentsRow
		if err := rows.Scan(&i.ID, &i.DisplayName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiteWeekFinished = `-- name: ListLiteWeekFinished :many
SELECT a.user_id, a.kind,
       COALESCE(
         NULLIF(btrim(COALESCE(r.title, w.title, NULLIF(p.name, ''), CASE WHEN p.assigned THEN NULL ELSE p.idea END, '')), ''),
         NULLIF(btrim(la.title), ''),
         CASE a.kind WHEN 'reading' THEN '阅读' WHEN 'writing' THEN '写作' ELSE '项目' END
       )::text AS title
FROM atom a
LEFT JOIN reading r ON r.atom_id = a.id
LEFT JOIN writing w ON w.atom_id = a.id
LEFT JOIN pbl_project p ON p.atom_id = a.id
LEFT JOIN lite_assignment_recipient lr ON lr.atom_id = a.id
LEFT JOIN lite_assignment la ON la.id = lr.assignment_id
WHERE a.user_id = ANY($1::uuid[])
  AND (
    (a.kind = 'reading' AND r.status = 'finished' AND r.finished_at >= $2::timestamptz AND r.finished_at < $3::timestamptz)
    OR (a.kind = 'writing' AND w.status = 'finished' AND w.finished_at >= $2::timestamptz AND w.finished_at < $3::timestamptz)
    OR (a.kind = 'project' AND p.finished_at >= $2::timestamptz AND p.finished_at < $3::timestamptz)
  )
ORDER BY COALESCE(r.finished_at, w.finished_at, p.finished_at), a.id
`

type ListLiteWeekFinishedParams struct {
	UserIds   []uuid.UUID `json:"user_ids"`
	WeekStart time.Time   `json:"week_start"`
	WeekEnd   time.Time   `json:"week_end"`
}

type ListLiteWeekFinishedRow struct {
	UserID uuid.UUID `json:"user_id"`
	Kind   string    `json:"kind"`
	Title  string    `json:"title"`
}

// 这一周内完成的阅读、写作、项目，按完成时间排序。
func (q *Queries) ListLiteWeekFinished(ctx context.Context, arg ListLiteWeekFinishedParams) ([]ListLiteWeekFinishedRow, error) {
	rows, err := q.db.Query(ctx, listLiteWeekFinished, arg.UserIds, arg.WeekStart, arg.WeekEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLiteWeekFinishedRow
	for rows.Next() {
		var i ListLiteWeekFinishedRow
		if err := rows.Scan(&i.UserID, &i.Kind, &i.Title); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiteWeekMoments = `-- name: ListLiteWeekMoments :many
SELECT a.id AS atom_id, a.user_id,
       COALESCE(
         NULLIF(btrim(COALESCE(r.title, w.title, '')), ''),
         NULLIF(btrim(la.title), ''),
         CASE a.kind WHEN 'reading' THEN '阅读' ELSE '写作' END
       )::text AS title,
       COALESCE(ar.report -> 'moments', 'null'::jsonb)::jsonb AS moments,
       COALESCE((ar.report ->> 'prosePending')::boolean, false)::boolean AS prose_pending,
       w.assigned_prompt
FROM atom_report ar
JOIN atom a ON a.id = ar.atom_id
LEFT JOIN reading r ON r.atom_id = a.id
LEFT JOIN writing w ON w.atom_id = a.id
LEFT JOIN lite_assignment_recipient lr ON lr.atom_id = a.id
LEFT JOIN lite_assignment la ON la.id = lr.assignment_id
WHERE a.user_id = ANY($1::uuid[])
  AND (
    (a.kind = 'reading' AND r.status = 'finished' AND r.finished_at >= $2::timestamptz AND r.finished_at < $3::timestamptz)
    OR (a.kind = 'writing' AND w.status = 'finished' AND w.finished_at >= $2::timestamptz AND w.finished_at < $3::timestamptz)
  )
ORDER BY COALESCE(r.finished_at, w.finished_at), a.id
`

type ListLiteWeekMomentsParams struct {
	UserIds   []uuid.UUID `json:"user_ids"`
	WeekStart time.Time   `json:"week_start"`
	WeekEnd   time.Time   `json:"week_end"`
}

type ListLiteWeekMomentsRow struct {
	AtomID         uuid.UUID `json:"atom_id"`
	UserID         uuid.UUID `json:"user_id"`
	Title          string    `json:"title"`
	Moments        []byte    `json:"moments"`
	ProsePending   bool      `json:"prose_pending"`
	AssignedPrompt *string   `json:"assigned_prompt"`
}

// 这一周完成的阅读 / 写作的报告里的金句（atom_report 只有这两种）。金句在生成报告时
// 已逐字核对过是她的原话，这里原样取出；prose_pending = true 的报告文字还没生成，Go 侧跳过。
// assigned_prompt 只用来在 Go 侧剔除与老师题目重合的句子，从不作为金句。
func (q *Queries) ListLiteWeekMoments(ctx context.Context, arg ListLiteWeekMomentsParams) ([]ListLiteWeekMomentsRow, error) {
	rows, err := q.db.Query(ctx, listLiteWeekMoments, arg.UserIds, arg.WeekStart, arg.WeekEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLiteWeekMomentsRow
	for rows.Next() {
		var i ListLiteWeekMomentsRow
		if err := rows.Scan(
			&i.AtomID,
			&i.UserID,
			&i.Title,
			&i.Moments,
			&i.ProsePending,
			&i.AssignedPrompt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiteWeekNewKeywords = `-- name: ListLiteWeekNewKeywords :many
SELECT k.user_id, k.text_zh
FROM interest_keyword k
WHERE k.user_id = ANY($1::uuid[])
  AND k.first_seen_at >= $2::timestamptz AND k.first_seen_at < $3::timestamptz
ORDER BY k.first_seen_at, k.id
`

type ListLiteWeekNewKeywordsParams struct {
	UserIds   []uuid.UUID `json:"user_ids"`
	WeekStart time.Time   `json:"week_start"`
	WeekEnd   time.Time   `json:"week_end"`
}

type ListLiteWeekNewKeywordsRow struct {
	UserID uuid.UUID `json:"user_id"`
	TextZh string    `json:"text_zh"`
}

// 这一周第一次出现在她树上的词（interest_keyword 里的词都是她认过的）。
func (q *Queries) ListLiteWeekNewKeywords(ctx context.Context, arg ListLiteWeekNewKeywordsParams) ([]ListLiteWeekNewKeywordsRow, error) {
	rows, err := q.db.Query(ctx, listLiteWeekNewKeywords, arg.UserIds, arg.WeekStart, arg.WeekEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLiteWeekNewKeywordsRow
	for rows.Next() {
		var i ListLiteWeekNewKeywordsRow
		if err := rows.Scan(&i.UserID, &i.TextZh); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiteWeekStalled = `-- name: ListLiteWeekStalled :many
SELECT a.user_id, a.kind,
       COALESCE(
         NULLIF(btrim(COALESCE(r.title, w.title, NULLIF(p.name, ''), CASE WHEN p.assigned THEN NULL ELSE p.idea END, '')), ''),
         NULLIF(btrim(la.title), ''),
         CASE a.kind WHEN 'reading' THEN '阅读' WHEN 'writing' THEN '写作' ELSE '项目' END
       )::text AS title
FROM atom a
LEFT JOIN reading r ON r.atom_id = a.id
LEFT JOIN writing w ON w.atom_id = a.id
LEFT JOIN pbl_project p ON p.atom_id = a.id
LEFT JOIN lite_assignment_recipient lr ON lr.atom_id = a.id
LEFT JOIN lite_assignment la ON la.id = lr.assignment_id
WHERE a.user_id = ANY($1::uuid[])
  AND a.kind IN ('reading','writing','project')
  AND a.created_at < $2::timestamptz - interval '7 days'
  AND NOT COALESCE(CASE a.kind
        WHEN 'reading' THEN r.status = 'finished' AND (r.finished_at IS NULL OR r.finished_at < $2::timestamptz)
        WHEN 'writing' THEN w.status = 'finished' AND (w.finished_at IS NULL OR w.finished_at < $2::timestamptz)
        WHEN 'project' THEN p.status = 'archived'
                            OR COALESCE(p.finished_at < $2::timestamptz, false)
                            OR (p.finished_at IS NULL AND p.status IN ('review','keeping'))
      END, false)
  AND NOT EXISTS (
    SELECT 1 FROM atom_active_day d
    WHERE d.atom_id = a.id AND d.seconds > 0
      AND d.day >= $3::date - 7 AND d.day < $3::date)
  AND NOT EXISTS (
    SELECT 1 FROM atom_message m
    WHERE m.atom_id = a.id AND m.role = 'student'
      AND m.created_at >= $2::timestamptz - interval '7 days' AND m.created_at < $2::timestamptz)
ORDER BY a.created_at, a.id
`

type ListLiteWeekStalledParams struct {
	UserIds    []uuid.UUID `json:"user_ids"`
	WeekEnd    time.Time   `json:"week_end"`
	WeekEndDay pgtype.Date `json:"week_end_day"`
}

type ListLiteWeekStalledRow struct {
	UserID uuid.UUID `json:"user_id"`
	Kind   string    `json:"kind"`
	Title  string    `json:"title"`
}

// 停滞：到周末仍未完成、在周末前 7 天之前就已创建、且周末前 7 天里没有任何活动
// （没有秒数 > 0 的日格，也没有她发的消息）。只看周末之前的数据，不看 atom.last_activity_at，
// 所以周末之后她再动这一项，也不会改写那一周的事实。
// 「到周末已完成」：阅读 / 写作 status = 'finished' 且完成时间早于周末（没有 finished_at 的旧数据
// 按早已完成）；项目 finished_at 早于周末，或没有 finished_at 但处于 review/keeping（旧项目）。
// 已归档的项目不算停滞；归档没有时间戳，所以任何已归档的项目都排除。
// 整个判定包在 COALESCE(…, false) 里：进行中的项目 finished_at 为 NULL，比较结果是 NULL，
// 不包的话 NOT(NULL) 会把这一行丢掉。
func (q *Queries) ListLiteWeekStalled(ctx context.Context, arg ListLiteWeekStalledParams) ([]ListLiteWeekStalledRow, error) {
	rows, err := q.db.Query(ctx, listLiteWeekStalled, arg.UserIds, arg.WeekEnd, arg.WeekEndDay)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLiteWeekStalledRow
	for rows.Next() {
		var i ListLiteWeekStalledRow
		if err := rows.Scan(&i.UserID, &i.Kind, &i.Title); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
