// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: lite_teacher.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getLiteStudentItem = `-- name: GetLiteStudentItem :one
SELECT a.id AS atom_id, a.kind, a.created_at, a.last_activity_at, a.active_seconds,
       COALESCE(r.title, w.title, NULLIF(p.name, ''), p.idea, '')::text AS title,
       COALESCE(r.status, w.status, p.status, '')::text AS status,
       r.library_tier AS level,
       COALESCE(r.finished_at, w.finished_at) AS finished_at,
       (SELECT count(*) FROM atom_message m WHERE m.atom_id = a.id AND m.role = 'student')::int AS turns
FROM atom a
LEFT JOIN reading r ON r.atom_id = a.id
LEFT JOIN writing w ON w.atom_id = a.id
LEFT JOIN pbl_project p ON p.atom_id = a.id
WHERE a.user_id = $1 AND a.id = $2 AND a.kind IN ('reading','writing','project')
`

type GetLiteStudentItemParams struct {
	UserID uuid.UUID `json:"user_id"`
	AtomID uuid.UUID `json:"atom_id"`
}

type GetLiteStudentItemRow struct {
	AtomID         uuid.UUID          `json:"atom_id"`
	Kind           string             `json:"kind"`
	CreatedAt      time.Time          `json:"created_at"`
	LastActivityAt time.Time          `json:"last_activity_at"`
	ActiveSeconds  int32              `json:"active_seconds"`
	Title          string             `json:"title"`
	Status         string             `json:"status"`
	Level          *int16             `json:"level"`
	FinishedAt     pgtype.Timestamptz `json:"finished_at"`
	Turns          int32              `json:"turns"`
}

// Same select as ListLiteStudentItems (same COALESCE/nullability notes —
// see its header comment), scoped to one atom by id for the item-detail
// endpoint. Still filtered to kind IN (...) and to user_id: a caller
// probing a chat-kind atom, or an atom belonging to someone else, gets the
// same "no rows" a teacher probing a cross-student atom gets.
func (q *Queries) GetLiteStudentItem(ctx context.Context, arg GetLiteStudentItemParams) (GetLiteStudentItemRow, error) {
	row := q.db.QueryRow(ctx, getLiteStudentItem, arg.UserID, arg.AtomID)
	var i GetLiteStudentItemRow
	err := row.Scan(
		&i.AtomID,
		&i.Kind,
		&i.CreatedAt,
		&i.LastActivityAt,
		&i.ActiveSeconds,
		&i.Title,
		&i.Status,
		&i.Level,
		&i.FinishedAt,
		&i.Turns,
	)
	return i, err
}

const getLiteStudentRosterRow = `-- name: GetLiteStudentRosterRow :one
SELECT u.id, u.display_name, u.avatar_color,
       COALESCE((SELECT max(a.last_activity_at) FROM atom a WHERE a.user_id = u.id), 'epoch'::timestamptz)::timestamptz AS last_active_at,
       COALESCE((SELECT sum(a.active_seconds) FROM atom a WHERE a.user_id = u.id), 0)::int AS seconds_total,
       COALESCE((SELECT sum(d.seconds) FROM atom_active_day d JOIN atom a ON a.id = d.atom_id
         WHERE a.user_id = u.id AND d.day >= $1::date AND d.day < $2::date), 0)::int AS seconds_this_week,
       (SELECT count(*) FROM atom_active_day d JOIN atom a ON a.id = d.atom_id WHERE a.user_id = u.id)::int AS bucket_count,
       (SELECT count(DISTINCT x.day) FROM (
          SELECT d.day FROM atom_active_day d JOIN atom a ON a.id = d.atom_id
           WHERE a.user_id = u.id AND d.seconds > 0 AND d.day >= $1::date AND d.day < $2::date
          UNION
          SELECT (m.created_at AT TIME ZONE 'Asia/Shanghai')::date FROM atom_message m JOIN atom a ON a.id = m.atom_id
           WHERE a.user_id = u.id AND m.role = 'student' AND m.created_at >= $3::timestamptz AND m.created_at < $4::timestamptz
        ) x)::int AS active_days_this_week,
       (SELECT count(*) FROM atom_message m JOIN atom a ON a.id = m.atom_id WHERE a.user_id = u.id AND m.role = 'student')::int AS turns,
       (SELECT count(*) FROM reading r JOIN atom a ON a.id = r.atom_id WHERE a.user_id = u.id AND r.status = 'finished')::int AS readings_done,
       (SELECT count(*) FROM atom a WHERE a.user_id = u.id AND a.kind = 'reading')::int AS readings_total,
       (SELECT count(*) FROM writing w JOIN atom a ON a.id = w.atom_id WHERE a.user_id = u.id AND w.status = 'finished')::int AS writings_done,
       (SELECT count(*) FROM atom a WHERE a.user_id = u.id AND a.kind = 'writing')::int AS writings_total,
       (SELECT count(*) FROM pbl_project p JOIN atom a ON a.id = p.atom_id WHERE a.user_id = u.id AND p.status IN ('review','keeping','archived'))::int AS projects_done,
       (SELECT count(*) FROM atom a WHERE a.user_id = u.id AND a.kind = 'project')::int AS projects_total
FROM users u
WHERE u.id = $5
`

type GetLiteStudentRosterRowParams struct {
	WeekStartDay pgtype.Date `json:"week_start_day"`
	WeekEndDay   pgtype.Date `json:"week_end_day"`
	WeekStart    time.Time   `json:"week_start"`
	WeekEnd      time.Time   `json:"week_end"`
	UserID       uuid.UUID   `json:"user_id"`
}

type GetLiteStudentRosterRowRow struct {
	ID                 uuid.UUID `json:"id"`
	DisplayName        string    `json:"display_name"`
	AvatarColor        string    `json:"avatar_color"`
	LastActiveAt       time.Time `json:"last_active_at"`
	SecondsTotal       int32     `json:"seconds_total"`
	SecondsThisWeek    int32     `json:"seconds_this_week"`
	BucketCount        int32     `json:"bucket_count"`
	ActiveDaysThisWeek int32     `json:"active_days_this_week"`
	Turns              int32     `json:"turns"`
	ReadingsDone       int32     `json:"readings_done"`
	ReadingsTotal      int32     `json:"readings_total"`
	WritingsDone       int32     `json:"writings_done"`
	WritingsTotal      int32     `json:"writings_total"`
	ProjectsDone       int32     `json:"projects_done"`
	ProjectsTotal      int32     `json:"projects_total"`
}

// Same select list as ListLiteClassRoster (same COALESCE sentinel pattern —
// see its header comment), scoped to one student by id instead of by class:
// the caller (authTeacherStudent) already checked class ownership + that
// user_id is a student member, so no enrollments join is needed here.
func (q *Queries) GetLiteStudentRosterRow(ctx context.Context, arg GetLiteStudentRosterRowParams) (GetLiteStudentRosterRowRow, error) {
	row := q.db.QueryRow(ctx, getLiteStudentRosterRow,
		arg.WeekStartDay,
		arg.WeekEndDay,
		arg.WeekStart,
		arg.WeekEnd,
		arg.UserID,
	)
	var i GetLiteStudentRosterRowRow
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.AvatarColor,
		&i.LastActiveAt,
		&i.SecondsTotal,
		&i.SecondsThisWeek,
		&i.BucketCount,
		&i.ActiveDaysThisWeek,
		&i.Turns,
		&i.ReadingsDone,
		&i.ReadingsTotal,
		&i.WritingsDone,
		&i.WritingsTotal,
		&i.ProjectsDone,
		&i.ProjectsTotal,
	)
	return i, err
}

const listLiteClassRecipientStates = `-- name: ListLiteClassRecipientStates :many
SELECT r.user_id, r.started_at, a.due_at,
       COALESCE(rd.finished_at, w.finished_at, p.finished_at) AS finished_at
FROM lite_assignment_recipient r
JOIN lite_assignment a ON a.id = r.assignment_id
LEFT JOIN reading rd ON rd.atom_id = r.atom_id
LEFT JOIN writing w ON w.atom_id = r.atom_id
LEFT JOIN pbl_project p ON p.atom_id = r.atom_id
WHERE a.class_id = $1 AND a.archived_at IS NULL
`

type ListLiteClassRecipientStatesRow struct {
	UserID     uuid.UUID          `json:"user_id"`
	StartedAt  pgtype.Timestamptz `json:"started_at"`
	DueAt      time.Time          `json:"due_at"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
}

// Every recipient row of the class's non-archived assignments — the raw
// ingredients for liteassign.Status, joined the same way as
// ListLiteAssignmentRecipients (lite_assignment.sql) but scoped by class_id
// instead of a list of assignment ids. Status itself is derived in Go
// (getLiteClassRoster), never stored, so overdueAssignments is a per-user
// count over these rows rather than a column here.
func (q *Queries) ListLiteClassRecipientStates(ctx context.Context, classID uuid.UUID) ([]ListLiteClassRecipientStatesRow, error) {
	rows, err := q.db.Query(ctx, listLiteClassRecipientStates, classID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLiteClassRecipientStatesRow
	for rows.Next() {
		var i ListLiteClassRecipientStatesRow
		if err := rows.Scan(
			&i.UserID,
			&i.StartedAt,
			&i.DueAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiteClassRoster = `-- name: ListLiteClassRoster :many

SELECT u.id, u.display_name, u.avatar_color,
       COALESCE((SELECT max(a.last_activity_at) FROM atom a WHERE a.user_id = u.id), 'epoch'::timestamptz)::timestamptz AS last_active_at,
       COALESCE((SELECT sum(a.active_seconds) FROM atom a WHERE a.user_id = u.id), 0)::int AS seconds_total,
       COALESCE((SELECT sum(d.seconds) FROM atom_active_day d JOIN atom a ON a.id = d.atom_id
         WHERE a.user_id = u.id AND d.day >= $1::date AND d.day < $2::date), 0)::int AS seconds_this_week,
       (SELECT count(*) FROM atom_active_day d JOIN atom a ON a.id = d.atom_id WHERE a.user_id = u.id)::int AS bucket_count,
       (SELECT count(DISTINCT x.day) FROM (
          SELECT d.day FROM atom_active_day d JOIN atom a ON a.id = d.atom_id
           WHERE a.user_id = u.id AND d.seconds > 0 AND d.day >= $1::date AND d.day < $2::date
          UNION
          SELECT (m.created_at AT TIME ZONE 'Asia/Shanghai')::date FROM atom_message m JOIN atom a ON a.id = m.atom_id
           WHERE a.user_id = u.id AND m.role = 'student' AND m.created_at >= $3::timestamptz AND m.created_at < $4::timestamptz
        ) x)::int AS active_days_this_week,
       (SELECT count(*) FROM atom_message m JOIN atom a ON a.id = m.atom_id WHERE a.user_id = u.id AND m.role = 'student')::int AS turns,
       (SELECT count(*) FROM reading r JOIN atom a ON a.id = r.atom_id WHERE a.user_id = u.id AND r.status = 'finished')::int AS readings_done,
       (SELECT count(*) FROM atom a WHERE a.user_id = u.id AND a.kind = 'reading')::int AS readings_total,
       (SELECT count(*) FROM writing w JOIN atom a ON a.id = w.atom_id WHERE a.user_id = u.id AND w.status = 'finished')::int AS writings_done,
       (SELECT count(*) FROM atom a WHERE a.user_id = u.id AND a.kind = 'writing')::int AS writings_total,
       (SELECT count(*) FROM pbl_project p JOIN atom a ON a.id = p.atom_id WHERE a.user_id = u.id AND p.status IN ('review','keeping','archived'))::int AS projects_done,
       (SELECT count(*) FROM atom a WHERE a.user_id = u.id AND a.kind = 'project')::int AS projects_total
FROM enrollments e
JOIN users u ON u.id = e.user_id
WHERE e.class_id = $5 AND e.role_in_class = 'student'
ORDER BY u.display_name
`

type ListLiteClassRosterParams struct {
	WeekStartDay pgtype.Date `json:"week_start_day"`
	WeekEndDay   pgtype.Date `json:"week_end_day"`
	WeekStart    time.Time   `json:"week_start"`
	WeekEnd      time.Time   `json:"week_end"`
	ClassID      uuid.UUID   `json:"class_id"`
}

type ListLiteClassRosterRow struct {
	ID                 uuid.UUID `json:"id"`
	DisplayName        string    `json:"display_name"`
	AvatarColor        string    `json:"avatar_color"`
	LastActiveAt       time.Time `json:"last_active_at"`
	SecondsTotal       int32     `json:"seconds_total"`
	SecondsThisWeek    int32     `json:"seconds_this_week"`
	BucketCount        int32     `json:"bucket_count"`
	ActiveDaysThisWeek int32     `json:"active_days_this_week"`
	Turns              int32     `json:"turns"`
	ReadingsDone       int32     `json:"readings_done"`
	ReadingsTotal      int32     `json:"readings_total"`
	WritingsDone       int32     `json:"writings_done"`
	WritingsTotal      int32     `json:"writings_total"`
	ProjectsDone       int32     `json:"projects_done"`
	ProjectsTotal      int32     `json:"projects_total"`
}

// 教师端（lite）读学生数据。只读；只数、只取产出，不取对话正文。
// Every aggregate here is COALESCEd to a deterministic value: sqlc's static
// nullability inference (no live DB connection configured in sqlc.yaml)
// treats a bare aggregate-in-a-subquery as NOT NULL regardless of whether
// max()/sum() over zero rows can genuinely be NULL — an un-COALESCEd
// max(atom.last_activity_at) generated a non-pointer time.Time that panicked
// scanning a real NULL for a student with zero atoms. 'epoch'::timestamptz
// (1970-01-01) is the sentinel for "never active" — liteRosterRow (Go) checks
// against it rather than against a Go nil. seconds_this_week's 0 needs no
// sentinel: it is already an honest answer for "measured before, nothing
// this week".
func (q *Queries) ListLiteClassRoster(ctx context.Context, arg ListLiteClassRosterParams) ([]ListLiteClassRosterRow, error) {
	rows, err := q.db.Query(ctx, listLiteClassRoster,
		arg.WeekStartDay,
		arg.WeekEndDay,
		arg.WeekStart,
		arg.WeekEnd,
		arg.ClassID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLiteClassRosterRow
	for rows.Next() {
		var i ListLiteClassRosterRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.AvatarColor,
			&i.LastActiveAt,
			&i.SecondsTotal,
			&i.SecondsThisWeek,
			&i.BucketCount,
			&i.ActiveDaysThisWeek,
			&i.Turns,
			&i.ReadingsDone,
			&i.ReadingsTotal,
			&i.WritingsDone,
			&i.WritingsTotal,
			&i.ProjectsDone,
			&i.ProjectsTotal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiteStudentAssignments = `-- name: ListLiteStudentAssignments :many
SELECT a.id, a.kind, a.title, a.due_at, r.atom_id, r.started_at,
       COALESCE(rd.finished_at, w.finished_at, p.finished_at) AS finished_at
FROM lite_assignment_recipient r
JOIN lite_assignment a ON a.id = r.assignment_id
LEFT JOIN reading rd ON rd.atom_id = r.atom_id
LEFT JOIN writing w ON w.atom_id = r.atom_id
LEFT JOIN pbl_project p ON p.atom_id = r.atom_id
WHERE a.class_id = $1 AND r.user_id = $2 AND a.archived_at IS NULL
ORDER BY a.due_at DESC
`

type ListLiteStudentAssignmentsParams struct {
	ClassID uuid.UUID `json:"class_id"`
	UserID  uuid.UUID `json:"user_id"`
}

type ListLiteStudentAssignmentsRow struct {
	ID         uuid.UUID          `json:"id"`
	Kind       string             `json:"kind"`
	Title      string             `json:"title"`
	DueAt      time.Time          `json:"due_at"`
	AtomID     pgtype.UUID        `json:"atom_id"`
	StartedAt  pgtype.Timestamptz `json:"started_at"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
}

// One student's assignments within one class, for the teacher's student
// page. Same COALESCE finished_at as ListLiteClassRecipientStates; status is
// derived in Go from started_at/finished_at/due_at, never stored.
func (q *Queries) ListLiteStudentAssignments(ctx context.Context, arg ListLiteStudentAssignmentsParams) ([]ListLiteStudentAssignmentsRow, error) {
	rows, err := q.db.Query(ctx, listLiteStudentAssignments, arg.ClassID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLiteStudentAssignmentsRow
	for rows.Next() {
		var i ListLiteStudentAssignmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Title,
			&i.DueAt,
			&i.AtomID,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiteStudentItems = `-- name: ListLiteStudentItems :many
SELECT a.id AS atom_id, a.kind, a.created_at, a.last_activity_at, a.active_seconds,
       COALESCE(r.title, w.title, NULLIF(p.name, ''), p.idea, '')::text AS title,
       COALESCE(r.status, w.status, p.status, '')::text AS status,
       r.library_tier AS level,
       COALESCE(r.finished_at, w.finished_at) AS finished_at,
       (SELECT count(*) FROM atom_message m WHERE m.atom_id = a.id AND m.role = 'student')::int AS turns
FROM atom a
LEFT JOIN reading r ON r.atom_id = a.id
LEFT JOIN writing w ON w.atom_id = a.id
LEFT JOIN pbl_project p ON p.atom_id = a.id
WHERE a.user_id = $1 AND a.kind IN ('reading','writing','project')
ORDER BY a.last_activity_at DESC
`

type ListLiteStudentItemsRow struct {
	AtomID         uuid.UUID          `json:"atom_id"`
	Kind           string             `json:"kind"`
	CreatedAt      time.Time          `json:"created_at"`
	LastActivityAt time.Time          `json:"last_activity_at"`
	ActiveSeconds  int32              `json:"active_seconds"`
	Title          string             `json:"title"`
	Status         string             `json:"status"`
	Level          *int16             `json:"level"`
	FinishedAt     pgtype.Timestamptz `json:"finished_at"`
	Turns          int32              `json:"turns"`
}

// One row per reading/writing/project atom the student has, header + status +
// time + turns, for the teacher's student page. finished_at and level (reading's
// library_tier) are genuinely nullable here (project atoms have neither), so
// unlike the aggregates above they are left un-COALESCEd — sqlc's static
// inference already maps a bare LEFT JOINed column to a nullable Go type
// (level -> *int16, finished_at -> pgtype.Timestamptz) without help.
func (q *Queries) ListLiteStudentItems(ctx context.Context, userID uuid.UUID) ([]ListLiteStudentItemsRow, error) {
	rows, err := q.db.Query(ctx, listLiteStudentItems, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLiteStudentItemsRow
	for rows.Next() {
		var i ListLiteStudentItemsRow
		if err := rows.Scan(
			&i.AtomID,
			&i.Kind,
			&i.CreatedAt,
			&i.LastActivityAt,
			&i.ActiveSeconds,
			&i.Title,
			&i.Status,
			&i.Level,
			&i.FinishedAt,
			&i.Turns,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
