// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: lite_teacher.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const listLiteClassRoster = `-- name: ListLiteClassRoster :many

SELECT u.id, u.display_name, u.avatar_color,
       COALESCE((SELECT max(a.last_activity_at) FROM atom a WHERE a.user_id = u.id), 'epoch'::timestamptz)::timestamptz AS last_active_at,
       COALESCE((SELECT sum(a.active_seconds) FROM atom a WHERE a.user_id = u.id), 0)::int AS seconds_total,
       COALESCE((SELECT sum(d.seconds) FROM atom_active_day d JOIN atom a ON a.id = d.atom_id
         WHERE a.user_id = u.id AND d.day >= $1::date AND d.day < $2::date), 0)::int AS seconds_this_week,
       (SELECT count(*) FROM atom_active_day d JOIN atom a ON a.id = d.atom_id WHERE a.user_id = u.id)::int AS bucket_count,
       (SELECT count(DISTINCT x.day) FROM (
          SELECT d.day FROM atom_active_day d JOIN atom a ON a.id = d.atom_id
           WHERE a.user_id = u.id AND d.seconds > 0 AND d.day >= $1::date AND d.day < $2::date
          UNION
          SELECT (m.created_at AT TIME ZONE 'Asia/Shanghai')::date FROM atom_message m JOIN atom a ON a.id = m.atom_id
           WHERE a.user_id = u.id AND m.role = 'student' AND m.created_at >= $3::timestamptz AND m.created_at < $4::timestamptz
        ) x)::int AS active_days_this_week,
       (SELECT count(*) FROM atom_message m JOIN atom a ON a.id = m.atom_id WHERE a.user_id = u.id AND m.role = 'student')::int AS turns,
       (SELECT count(*) FROM reading r JOIN atom a ON a.id = r.atom_id WHERE a.user_id = u.id AND r.status = 'finished')::int AS readings_done,
       (SELECT count(*) FROM atom a WHERE a.user_id = u.id AND a.kind = 'reading')::int AS readings_total,
       (SELECT count(*) FROM writing w JOIN atom a ON a.id = w.atom_id WHERE a.user_id = u.id AND w.status = 'finished')::int AS writings_done,
       (SELECT count(*) FROM atom a WHERE a.user_id = u.id AND a.kind = 'writing')::int AS writings_total,
       (SELECT count(*) FROM pbl_project p JOIN atom a ON a.id = p.atom_id WHERE a.user_id = u.id AND p.status IN ('review','keeping','archived'))::int AS projects_done,
       (SELECT count(*) FROM atom a WHERE a.user_id = u.id AND a.kind = 'project')::int AS projects_total
FROM enrollments e
JOIN users u ON u.id = e.user_id
WHERE e.class_id = $5 AND e.role_in_class = 'student'
ORDER BY u.display_name
`

type ListLiteClassRosterParams struct {
	WeekStartDay pgtype.Date `json:"week_start_day"`
	WeekEndDay   pgtype.Date `json:"week_end_day"`
	WeekStart    time.Time   `json:"week_start"`
	WeekEnd      time.Time   `json:"week_end"`
	ClassID      uuid.UUID   `json:"class_id"`
}

type ListLiteClassRosterRow struct {
	ID                 uuid.UUID `json:"id"`
	DisplayName        string    `json:"display_name"`
	AvatarColor        string    `json:"avatar_color"`
	LastActiveAt       time.Time `json:"last_active_at"`
	SecondsTotal       int32     `json:"seconds_total"`
	SecondsThisWeek    int32     `json:"seconds_this_week"`
	BucketCount        int32     `json:"bucket_count"`
	ActiveDaysThisWeek int32     `json:"active_days_this_week"`
	Turns              int32     `json:"turns"`
	ReadingsDone       int32     `json:"readings_done"`
	ReadingsTotal      int32     `json:"readings_total"`
	WritingsDone       int32     `json:"writings_done"`
	WritingsTotal      int32     `json:"writings_total"`
	ProjectsDone       int32     `json:"projects_done"`
	ProjectsTotal      int32     `json:"projects_total"`
}

// 教师端（lite）读学生数据。只读；只数、只取产出，不取对话正文。
// Every aggregate here is COALESCEd to a deterministic value: sqlc's static
// nullability inference (no live DB connection configured in sqlc.yaml)
// treats a bare aggregate-in-a-subquery as NOT NULL regardless of whether
// max()/sum() over zero rows can genuinely be NULL — an un-COALESCEd
// max(atom.last_activity_at) generated a non-pointer time.Time that panicked
// scanning a real NULL for a student with zero atoms. 'epoch'::timestamptz
// (1970-01-01) is the sentinel for "never active" — liteRosterRow (Go) checks
// against it rather than against a Go nil. seconds_this_week's 0 needs no
// sentinel: it is already an honest answer for "measured before, nothing
// this week".
func (q *Queries) ListLiteClassRoster(ctx context.Context, arg ListLiteClassRosterParams) ([]ListLiteClassRosterRow, error) {
	rows, err := q.db.Query(ctx, listLiteClassRoster,
		arg.WeekStartDay,
		arg.WeekEndDay,
		arg.WeekStart,
		arg.WeekEnd,
		arg.ClassID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLiteClassRosterRow
	for rows.Next() {
		var i ListLiteClassRosterRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.AvatarColor,
			&i.LastActiveAt,
			&i.SecondsTotal,
			&i.SecondsThisWeek,
			&i.BucketCount,
			&i.ActiveDaysThisWeek,
			&i.Turns,
			&i.ReadingsDone,
			&i.ReadingsTotal,
			&i.WritingsDone,
			&i.WritingsTotal,
			&i.ProjectsDone,
			&i.ProjectsTotal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
