// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: lite_grading.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimLiteGrading = `-- name: ClaimLiteGrading :one
UPDATE lite_grading SET status = 'running', error = NULL, updated_at = now()
WHERE id = $1 AND status = 'queued'
RETURNING id, atom_id, version_id, user_id, class_id, assignment_id, rubric, status, ai, content, error, requested_by, reviewed_at, sent_at, student_seen_at, created_at, updated_at
`

// 只有排队中的行可以开始，同一行不会被两个任务同时批改。
func (q *Queries) ClaimLiteGrading(ctx context.Context, id uuid.UUID) (LiteGrading, error) {
	row := q.db.QueryRow(ctx, claimLiteGrading, id)
	var i LiteGrading
	err := row.Scan(
		&i.ID,
		&i.AtomID,
		&i.VersionID,
		&i.UserID,
		&i.ClassID,
		&i.AssignmentID,
		&i.Rubric,
		&i.Status,
		&i.Ai,
		&i.Content,
		&i.Error,
		&i.RequestedBy,
		&i.ReviewedAt,
		&i.SentAt,
		&i.StudentSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createLiteGrading = `-- name: CreateLiteGrading :one

INSERT INTO lite_grading (atom_id, version_id, user_id, class_id, assignment_id, rubric, requested_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (version_id) DO NOTHING
RETURNING id, atom_id, version_id, user_id, class_id, assignment_id, rubric, status, ai, content, error, requested_by, reviewed_at, sent_at, student_seen_at, created_at, updated_at
`

type CreateLiteGradingParams struct {
	AtomID       uuid.UUID   `json:"atom_id"`
	VersionID    uuid.UUID   `json:"version_id"`
	UserID       uuid.UUID   `json:"user_id"`
	ClassID      uuid.UUID   `json:"class_id"`
	AssignmentID pgtype.UUID `json:"assignment_id"`
	Rubric       []byte      `json:"rubric"`
	RequestedBy  uuid.UUID   `json:"requested_by"`
}

// Lite AI 批改（0154）。
// 一个版本只有一行：已有一行时不插入，返回 no rows。
func (q *Queries) CreateLiteGrading(ctx context.Context, arg CreateLiteGradingParams) (LiteGrading, error) {
	row := q.db.QueryRow(ctx, createLiteGrading,
		arg.AtomID,
		arg.VersionID,
		arg.UserID,
		arg.ClassID,
		arg.AssignmentID,
		arg.Rubric,
		arg.RequestedBy,
	)
	var i LiteGrading
	err := row.Scan(
		&i.ID,
		&i.AtomID,
		&i.VersionID,
		&i.UserID,
		&i.ClassID,
		&i.AssignmentID,
		&i.Rubric,
		&i.Status,
		&i.Ai,
		&i.Content,
		&i.Error,
		&i.RequestedBy,
		&i.ReviewedAt,
		&i.SentAt,
		&i.StudentSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createManualLiteGrading = `-- name: CreateManualLiteGrading :one
INSERT INTO lite_grading (atom_id, version_id, user_id, class_id, assignment_id, rubric, requested_by, status, content)
VALUES ($1, $2, $3, $4, $5, $6, $7, 'draft', $8::jsonb)
ON CONFLICT (version_id) DO NOTHING
RETURNING id, atom_id, version_id, user_id, class_id, assignment_id, rubric, status, ai, content, error, requested_by, reviewed_at, sent_at, student_seen_at, created_at, updated_at
`

type CreateManualLiteGradingParams struct {
	AtomID       uuid.UUID   `json:"atom_id"`
	VersionID    uuid.UUID   `json:"version_id"`
	UserID       uuid.UUID   `json:"user_id"`
	ClassID      uuid.UUID   `json:"class_id"`
	AssignmentID pgtype.UUID `json:"assignment_id"`
	Rubric       []byte      `json:"rubric"`
	RequestedBy  uuid.UUID   `json:"requested_by"`
	Content      []byte      `json:"content"`
}

// 人工批改：老师自己写，不调用模型，所以直接落成草稿。content 是按评分标准
// 生成的空白表（等级和评语都为空），不能为 NULL —— UpdateLiteGradingContent
// 要求 content IS NOT NULL，否则老师第一次保存就会被拒。ai 保持为 NULL，
// 学生那边据此显示这份批改不是 AI 起草的。
// 一个版本只有一行：已有一行时不插入，返回 no rows。
func (q *Queries) CreateManualLiteGrading(ctx context.Context, arg CreateManualLiteGradingParams) (LiteGrading, error) {
	row := q.db.QueryRow(ctx, createManualLiteGrading,
		arg.AtomID,
		arg.VersionID,
		arg.UserID,
		arg.ClassID,
		arg.AssignmentID,
		arg.Rubric,
		arg.RequestedBy,
		arg.Content,
	)
	var i LiteGrading
	err := row.Scan(
		&i.ID,
		&i.AtomID,
		&i.VersionID,
		&i.UserID,
		&i.ClassID,
		&i.AssignmentID,
		&i.Rubric,
		&i.Status,
		&i.Ai,
		&i.Content,
		&i.Error,
		&i.RequestedBy,
		&i.ReviewedAt,
		&i.SentAt,
		&i.StudentSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLiteGrading = `-- name: GetLiteGrading :one
SELECT id, atom_id, version_id, user_id, class_id, assignment_id, rubric, status, ai, content, error, requested_by, reviewed_at, sent_at, student_seen_at, created_at, updated_at FROM lite_grading WHERE id = $1
`

func (q *Queries) GetLiteGrading(ctx context.Context, id uuid.UUID) (LiteGrading, error) {
	row := q.db.QueryRow(ctx, getLiteGrading, id)
	var i LiteGrading
	err := row.Scan(
		&i.ID,
		&i.AtomID,
		&i.VersionID,
		&i.UserID,
		&i.ClassID,
		&i.AssignmentID,
		&i.Rubric,
		&i.Status,
		&i.Ai,
		&i.Content,
		&i.Error,
		&i.RequestedBy,
		&i.ReviewedAt,
		&i.SentAt,
		&i.StudentSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLiteGradingByVersion = `-- name: GetLiteGradingByVersion :one
SELECT id, atom_id, version_id, user_id, class_id, assignment_id, rubric, status, ai, content, error, requested_by, reviewed_at, sent_at, student_seen_at, created_at, updated_at FROM lite_grading WHERE version_id = $1
`

func (q *Queries) GetLiteGradingByVersion(ctx context.Context, versionID uuid.UUID) (LiteGrading, error) {
	row := q.db.QueryRow(ctx, getLiteGradingByVersion, versionID)
	var i LiteGrading
	err := row.Scan(
		&i.ID,
		&i.AtomID,
		&i.VersionID,
		&i.UserID,
		&i.ClassID,
		&i.AssignmentID,
		&i.Rubric,
		&i.Status,
		&i.Ai,
		&i.Content,
		&i.Error,
		&i.RequestedBy,
		&i.ReviewedAt,
		&i.SentAt,
		&i.StudentSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLiteGradingSource = `-- name: GetLiteGradingSource :one
SELECT v.id AS version_id, v.atom_id, v.number, v.title, v.body,
       w.lang, w.assigned_prompt, w.target_words
FROM writing_version v
JOIN writing w ON w.atom_id = v.atom_id
WHERE v.id = $1
`

type GetLiteGradingSourceRow struct {
	VersionID      uuid.UUID `json:"version_id"`
	AtomID         uuid.UUID `json:"atom_id"`
	Number         int32     `json:"number"`
	Title          string    `json:"title"`
	Body           string    `json:"body"`
	Lang           string    `json:"lang"`
	AssignedPrompt *string   `json:"assigned_prompt"`
	TargetWords    *int32    `json:"target_words"`
}

// 批改读的那一版正文，以及写作的语言、老师的题目和目标字数。
func (q *Queries) GetLiteGradingSource(ctx context.Context, id uuid.UUID) (GetLiteGradingSourceRow, error) {
	row := q.db.QueryRow(ctx, getLiteGradingSource, id)
	var i GetLiteGradingSourceRow
	err := row.Scan(
		&i.VersionID,
		&i.AtomID,
		&i.Number,
		&i.Title,
		&i.Body,
		&i.Lang,
		&i.AssignedPrompt,
		&i.TargetWords,
	)
	return i, err
}

const listLatestWritingVersionsForAtoms = `-- name: ListLatestWritingVersionsForAtoms :many
SELECT DISTINCT ON (atom_id) id, atom_id, number, submitted_at
FROM writing_version
WHERE atom_id = ANY($1::uuid[])
ORDER BY atom_id, number DESC
`

type ListLatestWritingVersionsForAtomsRow struct {
	ID          uuid.UUID `json:"id"`
	AtomID      uuid.UUID `json:"atom_id"`
	Number      int32     `json:"number"`
	SubmittedAt time.Time `json:"submitted_at"`
}

// 每篇写作的最新提交版本，不带正文。
func (q *Queries) ListLatestWritingVersionsForAtoms(ctx context.Context, atomIds []uuid.UUID) ([]ListLatestWritingVersionsForAtomsRow, error) {
	rows, err := q.db.Query(ctx, listLatestWritingVersionsForAtoms, atomIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLatestWritingVersionsForAtomsRow
	for rows.Next() {
		var i ListLatestWritingVersionsForAtomsRow
		if err := rows.Scan(
			&i.ID,
			&i.AtomID,
			&i.Number,
			&i.SubmittedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiteGradingsForVersions = `-- name: ListLiteGradingsForVersions :many
SELECT id, atom_id, version_id, user_id, class_id, assignment_id, rubric, status, ai, content, error, requested_by, reviewed_at, sent_at, student_seen_at, created_at, updated_at FROM lite_grading WHERE version_id = ANY($1::uuid[])
`

func (q *Queries) ListLiteGradingsForVersions(ctx context.Context, versionIds []uuid.UUID) ([]LiteGrading, error) {
	rows, err := q.db.Query(ctx, listLiteGradingsForVersions, versionIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LiteGrading
	for rows.Next() {
		var i LiteGrading
		if err := rows.Scan(
			&i.ID,
			&i.AtomID,
			&i.VersionID,
			&i.UserID,
			&i.ClassID,
			&i.AssignmentID,
			&i.Rubric,
			&i.Status,
			&i.Ai,
			&i.Content,
			&i.Error,
			&i.RequestedBy,
			&i.ReviewedAt,
			&i.SentAt,
			&i.StudentSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiteInboxGradings = `-- name: ListLiteInboxGradings :many
SELECT g.id, g.atom_id, g.sent_at, g.student_seen_at, w.title
FROM lite_grading g
JOIN writing w ON w.atom_id = g.atom_id
WHERE g.user_id = $1 AND g.status = 'sent'
ORDER BY g.sent_at DESC, g.id DESC
`

type ListLiteInboxGradingsRow struct {
	ID            uuid.UUID          `json:"id"`
	AtomID        uuid.UUID          `json:"atom_id"`
	SentAt        pgtype.Timestamptz `json:"sent_at"`
	StudentSeenAt pgtype.Timestamptz `json:"student_seen_at"`
	Title         string             `json:"title"`
}

// g.id 是 sent_at 相同时（发送全部已审阅一次发出多行）的次序打散。
func (q *Queries) ListLiteInboxGradings(ctx context.Context, userID uuid.UUID) ([]ListLiteInboxGradingsRow, error) {
	rows, err := q.db.Query(ctx, listLiteInboxGradings, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLiteInboxGradingsRow
	for rows.Next() {
		var i ListLiteInboxGradingsRow
		if err := rows.Scan(
			&i.ID,
			&i.AtomID,
			&i.SentAt,
			&i.StudentSeenAt,
			&i.Title,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSentLiteGradingsForAtom = `-- name: ListSentLiteGradingsForAtom :many
SELECT g.id, g.rubric, g.content, g.sent_at, g.student_seen_at, v.number AS version_number,
       (g.ai IS NOT NULL)::bool AS ai_drafted
FROM lite_grading g
JOIN writing_version v ON v.id = g.version_id
WHERE g.atom_id = $1 AND g.status = 'sent'
ORDER BY v.number DESC
`

type ListSentLiteGradingsForAtomRow struct {
	ID            uuid.UUID          `json:"id"`
	Rubric        []byte             `json:"rubric"`
	Content       []byte             `json:"content"`
	SentAt        pgtype.Timestamptz `json:"sent_at"`
	StudentSeenAt pgtype.Timestamptz `json:"student_seen_at"`
	VersionNumber int32              `json:"version_number"`
	AiDrafted     bool               `json:"ai_drafted"`
}

// 学生读的批改：只有已发送的行。
func (q *Queries) ListSentLiteGradingsForAtom(ctx context.Context, atomID uuid.UUID) ([]ListSentLiteGradingsForAtomRow, error) {
	rows, err := q.db.Query(ctx, listSentLiteGradingsForAtom, atomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSentLiteGradingsForAtomRow
	for rows.Next() {
		var i ListSentLiteGradingsForAtomRow
		if err := rows.Scan(
			&i.ID,
			&i.Rubric,
			&i.Content,
			&i.SentAt,
			&i.StudentSeenAt,
			&i.VersionNumber,
			&i.AiDrafted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const liteTeacherSeesStudent = `-- name: LiteTeacherSeesStudent :one
SELECT EXISTS (
  SELECT 1
  FROM enrollments s
  JOIN classes c ON c.id = s.class_id
  WHERE s.user_id = $1 AND s.role_in_class = 'student'
    AND (
      EXISTS (
        SELECT 1 FROM enrollments t
        WHERE t.class_id = s.class_id AND t.user_id = $2 AND t.role_in_class = 'teacher'
      )
      OR ($3::bool AND c.school_id = $4::uuid)
    )
)::bool
`

type LiteTeacherSeesStudentParams struct {
	StudentID      uuid.UUID `json:"student_id"`
	CallerID       uuid.UUID `json:"caller_id"`
	CallerIsAdmin  bool      `json:"caller_is_admin"`
	CallerSchoolID uuid.UUID `json:"caller_school_id"`
}

// 调用者是否教这名学生当前所在的某个班（学生身份）；学校管理员看本校班级里的学生。
// 用于不属于任何作业的批改的可见性。
func (q *Queries) LiteTeacherSeesStudent(ctx context.Context, arg LiteTeacherSeesStudentParams) (bool, error) {
	row := q.db.QueryRow(ctx, liteTeacherSeesStudent,
		arg.StudentID,
		arg.CallerID,
		arg.CallerIsAdmin,
		arg.CallerSchoolID,
	)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const markLiteGradingSeen = `-- name: MarkLiteGradingSeen :execrows
UPDATE lite_grading SET student_seen_at = COALESCE(student_seen_at, now())
WHERE id = $1 AND user_id = $2 AND status = 'sent'
`

type MarkLiteGradingSeenParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) MarkLiteGradingSeen(ctx context.Context, arg MarkLiteGradingSeenParams) (int64, error) {
	result, err := q.db.Exec(ctx, markLiteGradingSeen, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markStaleLiteGradingsFailed = `-- name: MarkStaleLiteGradingsFailed :exec
UPDATE lite_grading
SET status = CASE WHEN content IS NOT NULL THEN 'draft' ELSE 'failed' END,
    error = '批改超时：任务未完成', updated_at = now()
WHERE status = 'running' AND updated_at < now() - interval '15 minutes'
  AND id = ANY($1::uuid[])
`

// 任务只跑一次（MaxAttempts 1），超时 6 分钟。进程在批改中途退出时这一行会停在 running，
// 超过 15 分钟没有更新就判为失败；已有内容的行（重新批改途中卡住）退回 draft 并保留
// 内容，只标错误。排队中的行不动：队列可能还没轮到它。
func (q *Queries) MarkStaleLiteGradingsFailed(ctx context.Context, ids []uuid.UUID) error {
	_, err := q.db.Exec(ctx, markStaleLiteGradingsFailed, ids)
	return err
}

const requeueLiteGrading = `-- name: RequeueLiteGrading :one
UPDATE lite_grading
SET status = 'queued', error = NULL,
    rubric = CASE WHEN content IS NULL THEN $1::jsonb ELSE rubric END,
    requested_by = $2, updated_at = now()
WHERE id = $3 AND status IN ('draft', 'failed')
RETURNING id, atom_id, version_id, user_id, class_id, assignment_id, rubric, status, ai, content, error, requested_by, reviewed_at, sent_at, student_seen_at, created_at, updated_at
`

type RequeueLiteGradingParams struct {
	Rubric      []byte    `json:"rubric"`
	RequestedBy uuid.UUID `json:"requested_by"`
	ID          uuid.UUID `json:"id"`
}

// 重新批改：草稿或失败的行回到排队。已发送的行不重新批改。
// 已有内容的行不在这里改 rubric：批改失败时这一行退回 draft 并保留旧内容，
// rubric 必须仍是描述旧内容的那一份，否则老师保存时维度对不上。新的评分标准
// 随任务参数传给 worker，批改成功时由 SetLiteGradingDraft 与内容一起写入。
// 没有内容的行（第一次批改失败）直接换成新的评分标准。
func (q *Queries) RequeueLiteGrading(ctx context.Context, arg RequeueLiteGradingParams) (LiteGrading, error) {
	row := q.db.QueryRow(ctx, requeueLiteGrading, arg.Rubric, arg.RequestedBy, arg.ID)
	var i LiteGrading
	err := row.Scan(
		&i.ID,
		&i.AtomID,
		&i.VersionID,
		&i.UserID,
		&i.ClassID,
		&i.AssignmentID,
		&i.Rubric,
		&i.Status,
		&i.Ai,
		&i.Content,
		&i.Error,
		&i.RequestedBy,
		&i.ReviewedAt,
		&i.SentAt,
		&i.StudentSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const sendLiteGrading = `-- name: SendLiteGrading :one
UPDATE lite_grading
SET status = 'sent', sent_at = now(), student_seen_at = NULL,
    reviewed_at = COALESCE(reviewed_at, now()), updated_at = now()
WHERE id = $1 AND status IN ('draft', 'sent') AND content IS NOT NULL
RETURNING id, atom_id, version_id, user_id, class_id, assignment_id, rubric, status, ai, content, error, requested_by, reviewed_at, sent_at, student_seen_at, created_at, updated_at
`

func (q *Queries) SendLiteGrading(ctx context.Context, id uuid.UUID) (LiteGrading, error) {
	row := q.db.QueryRow(ctx, sendLiteGrading, id)
	var i LiteGrading
	err := row.Scan(
		&i.ID,
		&i.AtomID,
		&i.VersionID,
		&i.UserID,
		&i.ClassID,
		&i.AssignmentID,
		&i.Rubric,
		&i.Status,
		&i.Ai,
		&i.Content,
		&i.Error,
		&i.RequestedBy,
		&i.ReviewedAt,
		&i.SentAt,
		&i.StudentSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const sendReviewedLiteGradings = `-- name: SendReviewedLiteGradings :execrows
UPDATE lite_grading g
SET status = 'sent', sent_at = now(), student_seen_at = NULL, updated_at = now()
WHERE g.assignment_id = $1 AND g.id = ANY($2::uuid[])
  AND g.status = 'draft' AND g.reviewed_at IS NOT NULL AND g.content IS NOT NULL
  AND EXISTS (
    SELECT 1 FROM enrollments e
    WHERE e.class_id = g.class_id AND e.user_id = g.user_id AND e.role_in_class = 'student'
  )
`

type SendReviewedLiteGradingsParams struct {
	AssignmentID pgtype.UUID `json:"assignment_id"`
	Ids          []uuid.UUID `json:"ids"`
}

// 发送全部已审阅：只发这份作业里已审阅的草稿，且学生仍在班里
// （离班学生的草稿即便已审阅也不发送——她已经不是这个老师的学生了）。
func (q *Queries) SendReviewedLiteGradings(ctx context.Context, arg SendReviewedLiteGradingsParams) (int64, error) {
	result, err := q.db.Exec(ctx, sendReviewedLiteGradings, arg.AssignmentID, arg.Ids)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setLiteGradingDraft = `-- name: SetLiteGradingDraft :execrows
UPDATE lite_grading
SET status = 'draft', ai = $1, content = $1,
    rubric = COALESCE($2::jsonb, rubric),
    reviewed_at = NULL, error = NULL, updated_at = now()
WHERE id = $3 AND status = 'running'
`

type SetLiteGradingDraftParams struct {
	Result []byte    `json:"result"`
	Rubric []byte    `json:"rubric"`
	ID     uuid.UUID `json:"id"`
}

// 批改成功：ai 与 content 都是这次的结果；之前的审阅作废。rubric 写成这次批改
// 用的评分标准，与 content 一起更新（重新批改排队时不改 rubric，见 RequeueLiteGrading）。
// rubric 为 NULL 时保留原值。
func (q *Queries) SetLiteGradingDraft(ctx context.Context, arg SetLiteGradingDraftParams) (int64, error) {
	result, err := q.db.Exec(ctx, setLiteGradingDraft, arg.Result, arg.Rubric, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setLiteGradingFailed = `-- name: SetLiteGradingFailed :execrows
UPDATE lite_grading
SET status = CASE WHEN content IS NOT NULL THEN 'draft' ELSE 'failed' END,
    error = $1, updated_at = now()
WHERE id = $2 AND status IN ('queued', 'running')
`

type SetLiteGradingFailedParams struct {
	Error *string   `json:"error"`
	ID    uuid.UUID `json:"id"`
}

// 失败不丢掉已有草稿：这一行如果已经有内容（重新批改失败），退回 draft 并保留
// 旧的 ai/content/reviewed_at，只把这次的失败原因写进 error；第一次批改（还没有
// 内容）才真正落到 failed。
func (q *Queries) SetLiteGradingFailed(ctx context.Context, arg SetLiteGradingFailedParams) (int64, error) {
	result, err := q.db.Exec(ctx, setLiteGradingFailed, arg.Error, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const startManualOnFailedLiteGrading = `-- name: StartManualOnFailedLiteGrading :one
UPDATE lite_grading
SET status = 'draft', content = $1::jsonb, ai = NULL, error = NULL,
    requested_by = $2, updated_at = now()
WHERE id = $3 AND status = 'failed' AND content IS NULL
RETURNING id, atom_id, version_id, user_id, class_id, assignment_id, rubric, status, ai, content, error, requested_by, reviewed_at, sent_at, student_seen_at, created_at, updated_at
`

type StartManualOnFailedLiteGradingParams struct {
	Content     []byte    `json:"content"`
	RequestedBy uuid.UUID `json:"requested_by"`
	ID          uuid.UUID `json:"id"`
}

// AI 批改失败（没有内容）之后改为人工批改：同一行变成老师的空白草稿。
// 否则老师在 AI 连续失败时既不能人工批改（这一版已有一行），也改不了这一行。
func (q *Queries) StartManualOnFailedLiteGrading(ctx context.Context, arg StartManualOnFailedLiteGradingParams) (LiteGrading, error) {
	row := q.db.QueryRow(ctx, startManualOnFailedLiteGrading, arg.Content, arg.RequestedBy, arg.ID)
	var i LiteGrading
	err := row.Scan(
		&i.ID,
		&i.AtomID,
		&i.VersionID,
		&i.UserID,
		&i.ClassID,
		&i.AssignmentID,
		&i.Rubric,
		&i.Status,
		&i.Ai,
		&i.Content,
		&i.Error,
		&i.RequestedBy,
		&i.ReviewedAt,
		&i.SentAt,
		&i.StudentSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateLiteGradingContent = `-- name: UpdateLiteGradingContent :one
UPDATE lite_grading
SET content = COALESCE($1::jsonb, content),
    reviewed_at = now(),
    error = NULL,
    sent_at = CASE WHEN status = 'sent' THEN now() ELSE sent_at END,
    student_seen_at = CASE WHEN status = 'sent' THEN NULL ELSE student_seen_at END,
    updated_at = now()
WHERE id = $2 AND status IN ('draft', 'sent') AND content IS NOT NULL
RETURNING id, atom_id, version_id, user_id, class_id, assignment_id, rubric, status, ai, content, error, requested_by, reviewed_at, sent_at, student_seen_at, created_at, updated_at
`

type UpdateLiteGradingContentParams struct {
	Content []byte    `json:"content"`
	ID      uuid.UUID `json:"id"`
}

// 老师保存即算审阅，并清掉上一次的失败原因。已发送的行保存后重新发送：学生那边变为未读。
func (q *Queries) UpdateLiteGradingContent(ctx context.Context, arg UpdateLiteGradingContentParams) (LiteGrading, error) {
	row := q.db.QueryRow(ctx, updateLiteGradingContent, arg.Content, arg.ID)
	var i LiteGrading
	err := row.Scan(
		&i.ID,
		&i.AtomID,
		&i.VersionID,
		&i.UserID,
		&i.ClassID,
		&i.AssignmentID,
		&i.Rubric,
		&i.Status,
		&i.Ai,
		&i.Content,
		&i.Error,
		&i.RequestedBy,
		&i.ReviewedAt,
		&i.SentAt,
		&i.StudentSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
