// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: messages.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const appendMessage = `-- name: AppendMessage :one
INSERT INTO messages (
    task_id, role, content, tool_call,
    provider, model, tier, prompt_tokens, completion_tokens, cost_estimate, source
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
RETURNING id, task_id, role, content, tool_call, provider, model, tier, prompt_tokens, completion_tokens, cost_estimate, created_at, source
`

type AppendMessageParams struct {
	TaskID           uuid.UUID      `json:"task_id"`
	Role             string         `json:"role"`
	Content          string         `json:"content"`
	ToolCall         []byte         `json:"tool_call"`
	Provider         *string        `json:"provider"`
	Model            *string        `json:"model"`
	Tier             *string        `json:"tier"`
	PromptTokens     *int32         `json:"prompt_tokens"`
	CompletionTokens *int32         `json:"completion_tokens"`
	CostEstimate     pgtype.Numeric `json:"cost_estimate"`
	Source           *string        `json:"source"`
}

func (q *Queries) AppendMessage(ctx context.Context, arg AppendMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, appendMessage,
		arg.TaskID,
		arg.Role,
		arg.Content,
		arg.ToolCall,
		arg.Provider,
		arg.Model,
		arg.Tier,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.CostEstimate,
		arg.Source,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Role,
		&i.Content,
		&i.ToolCall,
		&i.Provider,
		&i.Model,
		&i.Tier,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.CostEstimate,
		&i.CreatedAt,
		&i.Source,
	)
	return i, err
}

const listMessagesByTask = `-- name: ListMessagesByTask :many
SELECT id, task_id, role, content, tool_call, provider, model, tier, prompt_tokens, completion_tokens, cost_estimate, created_at, source FROM messages
WHERE task_id = $1
ORDER BY created_at, id
`

func (q *Queries) ListMessagesByTask(ctx context.Context, taskID uuid.UUID) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessagesByTask, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Role,
			&i.Content,
			&i.ToolCall,
			&i.Provider,
			&i.Model,
			&i.Tier,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.CostEstimate,
			&i.CreatedAt,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
