// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ActivityLogEntry struct {
	ID        uuid.UUID   `json:"id"`
	ProjectID uuid.UUID   `json:"project_id"`
	EntryDate pgtype.Date `json:"entry_date"`
	Text      string      `json:"text"`
	Source    string      `json:"source"`
	CreatedAt time.Time   `json:"created_at"`
}

type Atom struct {
	ID             uuid.UUID `json:"id"`
	Kind           string    `json:"kind"`
	UserID         uuid.UUID `json:"user_id"`
	CreatedAt      time.Time `json:"created_at"`
	LastActivityAt time.Time `json:"last_activity_at"`
}

type AtomAnnotation struct {
	ID        uuid.UUID `json:"id"`
	AtomID    uuid.UUID `json:"atom_id"`
	BlockID   string    `json:"block_id"`
	Span      []byte    `json:"span"`
	Quote     string    `json:"quote"`
	Note      string    `json:"note"`
	CreatedAt time.Time `json:"created_at"`
}

type AtomCard struct {
	ID            uuid.UUID          `json:"id"`
	AtomID        uuid.UUID          `json:"atom_id"`
	CardID        string             `json:"card_id"`
	BlockID       *string            `json:"block_id"`
	Status        string             `json:"status"`
	FieldValues   []byte             `json:"field_values"`
	EventTrace    []byte             `json:"event_trace"`
	CreatedAt     time.Time          `json:"created_at"`
	SubmittedAt   pgtype.Timestamptz `json:"submitted_at"`
	Anchors       []byte             `json:"anchors"`
	FrameworkFill []byte             `json:"framework_fill"`
	Origin        string             `json:"origin"`
}

type AtomMessage struct {
	ID        uuid.UUID `json:"id"`
	AtomID    uuid.UUID `json:"atom_id"`
	Seq       int32     `json:"seq"`
	Role      string    `json:"role"`
	Content   string    `json:"content"`
	CreatedAt time.Time `json:"created_at"`
	BlockID   *string   `json:"block_id"`
}

type CardCompetence struct {
	ID              uuid.UUID `json:"id"`
	UserID          uuid.UUID `json:"user_id"`
	CardID          string    `json:"card_id"`
	ScaffoldState   string    `json:"scaffold_state"`
	UnpromptedCount int32     `json:"unprompted_count"`
	PromptedCount   int32     `json:"prompted_count"`
	UpdatedAt       time.Time `json:"updated_at"`
}

type CardInstance struct {
	ID            uuid.UUID          `json:"id"`
	CardID        string             `json:"card_id"`
	TaskID        pgtype.UUID        `json:"task_id"`
	ParentNodeID  pgtype.UUID        `json:"parent_node_id"`
	Status        string             `json:"status"`
	FieldValues   []byte             `json:"field_values"`
	EventTrace    []byte             `json:"event_trace"`
	RubricTags    []string           `json:"rubric_tags"`
	CreatedAt     time.Time          `json:"created_at"`
	CompletedAt   pgtype.Timestamptz `json:"completed_at"`
	Anchors       []byte             `json:"anchors"`
	ProjectID     pgtype.UUID        `json:"project_id"`
	ContractRef   *string            `json:"contract_ref"`
	FrameworkFill []byte             `json:"framework_fill"`
	ThreadID      pgtype.UUID        `json:"thread_id"`
	SessionID     pgtype.UUID        `json:"session_id"`
}

type ChatMessage struct {
	ID             uuid.UUID          `json:"id"`
	ThreadID       uuid.UUID          `json:"thread_id"`
	Role           string             `json:"role"`
	Content        string             `json:"content"`
	Modality       string             `json:"modality"`
	Attachments    []byte             `json:"attachments"`
	QuotedFragment *string            `json:"quoted_fragment"`
	CreatedAt      time.Time          `json:"created_at"`
	Surface        *string            `json:"surface"`
	FoldedAt       pgtype.Timestamptz `json:"folded_at"`
	Stage          *string            `json:"stage"`
}

type ChatThread struct {
	ID              uuid.UUID   `json:"id"`
	UserID          uuid.UUID   `json:"user_id"`
	Title           string      `json:"title"`
	SeededProjectID pgtype.UUID `json:"seeded_project_id"`
	CreatedAt       time.Time   `json:"created_at"`
}

type Citation struct {
	ID          uuid.UUID `json:"id"`
	ProjectID   uuid.UUID `json:"project_id"`
	ReferenceID uuid.UUID `json:"reference_id"`
	Section     string    `json:"section"`
	CreatedAt   time.Time `json:"created_at"`
}

type Class struct {
	ID        uuid.UUID   `json:"id"`
	SchoolID  uuid.UUID   `json:"school_id"`
	Name      string      `json:"name"`
	JoinCode  string      `json:"join_code"`
	CreatedAt time.Time   `json:"created_at"`
	CreatedBy pgtype.UUID `json:"created_by"`
}

type ClassWeeklyProse struct {
	ClassID      uuid.UUID   `json:"class_id"`
	WeekStart    pgtype.Date `json:"week_start"`
	Comment      string      `json:"comment"`
	DepthNote    string      `json:"depth_note"`
	AutonomyNote string      `json:"autonomy_note"`
	Cards        []byte      `json:"cards"`
	CreatedAt    time.Time   `json:"created_at"`
	UpdatedAt    time.Time   `json:"updated_at"`
}

type Collection struct {
	ID        uuid.UUID   `json:"id"`
	ProjectID uuid.UUID   `json:"project_id"`
	Name      string      `json:"name"`
	ParentID  pgtype.UUID `json:"parent_id"`
	Position  int32       `json:"position"`
	CreatedAt time.Time   `json:"created_at"`
}

type ConversationDigest struct {
	ProjectID   uuid.UUID `json:"project_id"`
	Prose       string    `json:"prose"`
	TurnsFolded int32     `json:"turns_folded"`
	Model       *string   `json:"model"`
	Tier        *string   `json:"tier"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type Course struct {
	ID               uuid.UUID `json:"id"`
	Branch           string    `json:"branch"`
	Title            string    `json:"title"`
	Blurb            string    `json:"blurb"`
	TimeLabel        string    `json:"time_label"`
	CreatedAt        time.Time `json:"created_at"`
	Slug             string    `json:"slug"`
	CardIds          []string  `json:"card_ids"`
	Structure        []byte    `json:"structure"`
	RenderCache      []byte    `json:"render_cache"`
	StepCount        int32     `json:"step_count"`
	UpdatedAt        time.Time `json:"updated_at"`
	AudioManifest    []byte    `json:"audio_manifest"`
	CourseDefinition []byte    `json:"course_definition"`
	Status           string    `json:"status"`
	Cover            string    `json:"cover"`
	Category         *string   `json:"category"`
	Introduction     []byte    `json:"introduction"`
	FeaturedRank     *int32    `json:"featured_rank"`
}

type CourseProgress struct {
	ID                uuid.UUID          `json:"id"`
	UserID            uuid.UUID          `json:"user_id"`
	CourseID          uuid.UUID          `json:"course_id"`
	CurrentOrdinal    int32              `json:"current_ordinal"`
	CompletedOrdinals []int32            `json:"completed_ordinals"`
	UpdatedAt         time.Time          `json:"updated_at"`
	StartedAt         pgtype.Timestamptz `json:"started_at"`
	CompletedAt       pgtype.Timestamptz `json:"completed_at"`
	ActiveSeconds     int32              `json:"active_seconds"`
}

type CourseSession struct {
	ID          uuid.UUID          `json:"id"`
	UserID      uuid.UUID          `json:"user_id"`
	CourseID    uuid.UUID          `json:"course_id"`
	Session     []byte             `json:"session"`
	Status      string             `json:"status"`
	CreatedAt   time.Time          `json:"created_at"`
	UpdatedAt   time.Time          `json:"updated_at"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
}

type Disposition struct {
	ID             uuid.UUID `json:"id"`
	InterventionID uuid.UUID `json:"intervention_id"`
	Action         string    `json:"action"`
	Reason         string    `json:"reason"`
	CreatedAt      time.Time `json:"created_at"`
}

type DraftSnapshot struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
	Seq       int32     `json:"seq"`
	Content   string    `json:"content"`
	SpanIndex []byte    `json:"span_index"`
	CreatedAt time.Time `json:"created_at"`
	DocKind   string    `json:"doc_kind"`
}

type EditBuffer struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
	Content   string    `json:"content"`
	UpdatedAt time.Time `json:"updated_at"`
	DocKind   string    `json:"doc_kind"`
}

type EmailVerificationToken struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	TokenHash  string             `json:"token_hash"`
	ExpiresAt  time.Time          `json:"expires_at"`
	ConsumedAt pgtype.Timestamptz `json:"consumed_at"`
	CreatedAt  time.Time          `json:"created_at"`
}

type Enrollment struct {
	ID          uuid.UUID `json:"id"`
	UserID      uuid.UUID `json:"user_id"`
	ClassID     uuid.UUID `json:"class_id"`
	RoleInClass string    `json:"role_in_class"`
	CreatedAt   time.Time `json:"created_at"`
}

type Evaluation struct {
	ID               uuid.UUID          `json:"id"`
	TaskID           pgtype.UUID        `json:"task_id"`
	Scores           []byte             `json:"scores"`
	Narrative        string             `json:"narrative"`
	Model            string             `json:"model"`
	Tier             string             `json:"tier"`
	PromptTokens     *int32             `json:"prompt_tokens"`
	CompletionTokens *int32             `json:"completion_tokens"`
	CostEstimate     pgtype.Numeric     `json:"cost_estimate"`
	Status           string             `json:"status"`
	Error            *string            `json:"error"`
	CreatedAt        time.Time          `json:"created_at"`
	CompletedAt      pgtype.Timestamptz `json:"completed_at"`
	Signals          []byte             `json:"signals"`
	RubricVersion    *string            `json:"rubric_version"`
	Trigger          string             `json:"trigger"`
	TriggerMilestone *int32             `json:"trigger_milestone"`
	ProjectID        pgtype.UUID        `json:"project_id"`
	Rubric           *string            `json:"rubric"`
	Leaps            []byte             `json:"leaps"`
	SessionID        pgtype.UUID        `json:"session_id"`
	ThreadID         pgtype.UUID        `json:"thread_id"`
}

type EvaluationReport struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
	Version   int32     `json:"version"`
	Report    []byte    `json:"report"`
	CreatedAt time.Time `json:"created_at"`
	Status    string    `json:"status"`
}

type Event struct {
	ID        uuid.UUID   `json:"id"`
	ProjectID pgtype.UUID `json:"project_id"`
	UserID    uuid.UUID   `json:"user_id"`
	Surface   string      `json:"surface"`
	Type      string      `json:"type"`
	Payload   []byte      `json:"payload"`
	CreatedAt time.Time   `json:"created_at"`
	SessionID pgtype.UUID `json:"session_id"`
	ThreadID  pgtype.UUID `json:"thread_id"`
	CourseID  pgtype.UUID `json:"course_id"`
}

type ExplorationLead struct {
	ID                   uuid.UUID   `json:"id"`
	ProjectID            uuid.UUID   `json:"project_id"`
	Text                 string      `json:"text"`
	Status               string      `json:"status"`
	Origin               string      `json:"origin"`
	SourceReferenceID    pgtype.UUID `json:"source_reference_id"`
	ConnectedReferenceID pgtype.UUID `json:"connected_reference_id"`
	Position             int32       `json:"position"`
	CreatedAt            time.Time   `json:"created_at"`
	UpdatedAt            time.Time   `json:"updated_at"`
	ParentLeadID         pgtype.UUID `json:"parent_lead_id"`
}

type Feedback struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	Text      string    `json:"text"`
	CreatedAt time.Time `json:"created_at"`
}

type GraphEdge struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
	Type      string    `json:"type"`
	FromKind  string    `json:"from_kind"`
	FromID    uuid.UUID `json:"from_id"`
	ToKind    string    `json:"to_kind"`
	ToID      uuid.UUID `json:"to_id"`
	CreatedAt time.Time `json:"created_at"`
}

type GraphNode struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
	Type      string    `json:"type"`
	Body      []byte    `json:"body"`
	Author    string    `json:"author"`
	SpanRef   []byte    `json:"span_ref"`
	CreatedAt time.Time `json:"created_at"`
}

type Intervention struct {
	ID                 uuid.UUID   `json:"id"`
	ProjectID          uuid.UUID   `json:"project_id"`
	CardInstanceID     pgtype.UUID `json:"card_instance_id"`
	Type               string      `json:"type"`
	Anchor             []byte      `json:"anchor"`
	Criterion          *string     `json:"criterion"`
	Body               string      `json:"body"`
	Level              *string     `json:"level"`
	OutputCheckVerdict *string     `json:"output_check_verdict"`
	CreatedAt          time.Time   `json:"created_at"`
}

type LlmCall struct {
	ID               uuid.UUID      `json:"id"`
	UserID           uuid.UUID      `json:"user_id"`
	ProjectID        pgtype.UUID    `json:"project_id"`
	Surface          string         `json:"surface"`
	Purpose          string         `json:"purpose"`
	Provider         string         `json:"provider"`
	Model            string         `json:"model"`
	Tier             string         `json:"tier"`
	PromptTokens     int32          `json:"prompt_tokens"`
	CompletionTokens int32          `json:"completion_tokens"`
	CostEstimate     pgtype.Numeric `json:"cost_estimate"`
	CreatedAt        time.Time      `json:"created_at"`
	AtomID           pgtype.UUID    `json:"atom_id"`
}

type LlmUsage struct {
	ID               uuid.UUID      `json:"id"`
	UserID           uuid.UUID      `json:"user_id"`
	SchoolID         uuid.UUID      `json:"school_id"`
	Kind             string         `json:"kind"`
	Provider         string         `json:"provider"`
	Model            string         `json:"model"`
	Tier             string         `json:"tier"`
	PromptTokens     int32          `json:"prompt_tokens"`
	CompletionTokens int32          `json:"completion_tokens"`
	CostEstimate     pgtype.Numeric `json:"cost_estimate"`
	CreatedAt        time.Time      `json:"created_at"`
}

type Material struct {
	ID        uuid.UUID   `json:"id"`
	TaskID    pgtype.UUID `json:"task_id"`
	Kind      string      `json:"kind"`
	Source    string      `json:"source"`
	Title     string      `json:"title"`
	SourceUrl *string     `json:"source_url"`
	Blocks    []byte      `json:"blocks"`
	Scratch   string      `json:"scratch"`
	CreatedAt time.Time   `json:"created_at"`
	ProjectID pgtype.UUID `json:"project_id"`
	ThreadID  pgtype.UUID `json:"thread_id"`
	SessionID pgtype.UUID `json:"session_id"`
}

type Message struct {
	ID               uuid.UUID      `json:"id"`
	TaskID           uuid.UUID      `json:"task_id"`
	Role             string         `json:"role"`
	Content          string         `json:"content"`
	ToolCall         []byte         `json:"tool_call"`
	Provider         *string        `json:"provider"`
	Model            *string        `json:"model"`
	Tier             *string        `json:"tier"`
	PromptTokens     *int32         `json:"prompt_tokens"`
	CompletionTokens *int32         `json:"completion_tokens"`
	CostEstimate     pgtype.Numeric `json:"cost_estimate"`
	CreatedAt        time.Time      `json:"created_at"`
	Source           *string        `json:"source"`
}

type OutlineNode struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
	Text      string    `json:"text"`
	Depth     int32     `json:"depth"`
	Position  int32     `json:"position"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type PlanItem struct {
	ID            uuid.UUID   `json:"id"`
	ProjectID     uuid.UUID   `json:"project_id"`
	Title         string      `json:"title"`
	Tag           string      `json:"tag"`
	Col           string      `json:"col"`
	Stage         string      `json:"stage"`
	RefMaterialID pgtype.UUID `json:"ref_material_id"`
	StartDay      int32       `json:"start_day"`
	Days          int32       `json:"days"`
	Position      int32       `json:"position"`
	CreatedAt     time.Time   `json:"created_at"`
	UpdatedAt     time.Time   `json:"updated_at"`
}

type Project struct {
	ID            uuid.UUID          `json:"id"`
	UserID        uuid.UUID          `json:"user_id"`
	Qualification string             `json:"qualification"`
	Title         string             `json:"title"`
	Deadline      pgtype.Timestamptz `json:"deadline"`
	BoardCfgVer   int32              `json:"board_cfg_ver"`
	Status        string             `json:"status"`
	CreatedAt     time.Time          `json:"created_at"`
	LastActiveAt  time.Time          `json:"last_active_at"`
	StudioState   []byte             `json:"studio_state"`
	Cover         *string            `json:"cover"`
	IsDemo        bool               `json:"is_demo"`
}

type ProjectAiUse struct {
	ProjectID  uuid.UUID `json:"project_id"`
	UsedFor    string    `json:"used_for"`
	NotUsedFor string    `json:"not_used_for"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type ProjectProposal struct {
	ProjectID     uuid.UUID `json:"project_id"`
	Objective     string    `json:"objective"`
	Reason        string    `json:"reason"`
	Activities    string    `json:"activities"`
	Resources     string    `json:"resources"`
	UpdatedAt     time.Time `json:"updated_at"`
	Counterpoints string    `json:"counterpoints"`
}

type ProjectReflection struct {
	ProjectID uuid.UUID `json:"project_id"`
	Answers   []byte    `json:"answers"`
	Done      bool      `json:"done"`
	UpdatedAt time.Time `json:"updated_at"`
}

type ProjectSummaryProse struct {
	ProjectID uuid.UUID `json:"project_id"`
	Prose     string    `json:"prose"`
	Model     string    `json:"model"`
	Tier      string    `json:"tier"`
	CreatedAt time.Time `json:"created_at"`
}

type QuestionEdge struct {
	ID         uuid.UUID `json:"id"`
	ProjectID  uuid.UUID `json:"project_id"`
	FromLeadID uuid.UUID `json:"from_lead_id"`
	ToLeadID   uuid.UUID `json:"to_lead_id"`
	Label      string    `json:"label"`
	Status     string    `json:"status"`
	CreatedAt  time.Time `json:"created_at"`
}

type Reading struct {
	AtomID     uuid.UUID          `json:"atom_id"`
	Title      string             `json:"title"`
	Lang       string             `json:"lang"`
	Status     string             `json:"status"`
	UpdatedAt  time.Time          `json:"updated_at"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
	RoutineKey string             `json:"routine_key"`
}

type ReadingBlockNote struct {
	ID        uuid.UUID `json:"id"`
	AtomID    uuid.UUID `json:"atom_id"`
	BlockID   string    `json:"block_id"`
	Tool      string    `json:"tool"`
	Body      string    `json:"body"`
	CreatedAt time.Time `json:"created_at"`
}

type ReadingBrief struct {
	AtomID        uuid.UUID `json:"atom_id"`
	PhaseTag      *string   `json:"phase_tag"`
	ReadingReason string    `json:"reading_reason"`
	ReadingFocus  string    `json:"reading_focus"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type ReadingSource struct {
	AtomID     uuid.UUID `json:"atom_id"`
	Title      string    `json:"title"`
	Body       string    `json:"body"`
	SourceUrl  *string   `json:"source_url"`
	Bib        []byte    `json:"bib"`
	IngestedAt time.Time `json:"ingested_at"`
}

type ReadingTakeaway struct {
	AtomID    uuid.UUID `json:"atom_id"`
	Text      string    `json:"text"`
	UpdatedAt time.Time `json:"updated_at"`
}

type ReadingTask struct {
	ID          uuid.UUID          `json:"id"`
	AtomID      uuid.UUID          `json:"atom_id"`
	Position    int32              `json:"position"`
	Kind        string             `json:"kind"`
	Label       string             `json:"label"`
	Detail      string             `json:"detail"`
	BlockID     string             `json:"block_id"`
	Status      string             `json:"status"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
}

type Reference struct {
	ID                  uuid.UUID          `json:"id"`
	ProjectID           uuid.UUID          `json:"project_id"`
	Title               string             `json:"title"`
	Classification      string             `json:"classification"`
	Author              string             `json:"author"`
	Credentials         string             `json:"credentials"`
	Year                string             `json:"year"`
	Url                 string             `json:"url"`
	Tags                []byte             `json:"tags"`
	CollectionID        pgtype.UUID        `json:"collection_id"`
	Credibility         *string            `json:"credibility"`
	Evaluation          string             `json:"evaluation"`
	Decision            *string            `json:"decision"`
	Pending             bool               `json:"pending"`
	SearchHints         []byte             `json:"search_hints"`
	MaterialID          pgtype.UUID        `json:"material_id"`
	Position            int32              `json:"position"`
	CreatedAt           time.Time          `json:"created_at"`
	UpdatedAt           time.Time          `json:"updated_at"`
	ReadingReason       *string            `json:"reading_reason"`
	ReadingFocus        *string            `json:"reading_focus"`
	PhaseTag            *string            `json:"phase_tag"`
	Takeaway            []byte             `json:"takeaway"`
	TakeawayFinalizedAt pgtype.Timestamptz `json:"takeaway_finalized_at"`
	ReadingNote         string             `json:"reading_note"`
	Abstract            string             `json:"abstract"`
	Journal             string             `json:"journal"`
	ReadingStatus       string             `json:"reading_status"`
	Triage              string             `json:"triage"`
	EvidenceNature      string             `json:"evidence_nature"`
	EvidenceArgument    string             `json:"evidence_argument"`
	EvidenceFinding     string             `json:"evidence_finding"`
	EvidencePlacement   string             `json:"evidence_placement"`
	Archived            bool               `json:"archived"`
}

type RevisionCheckpoint struct {
	ID           uuid.UUID   `json:"id"`
	ProjectID    uuid.UUID   `json:"project_id"`
	ArtifactType string      `json:"artifact_type"`
	Trigger      string      `json:"trigger"`
	Content      []byte      `json:"content"`
	ContentHash  string      `json:"content_hash"`
	FeedbackRef  pgtype.UUID `json:"feedback_ref"`
	CreatedAt    time.Time   `json:"created_at"`
}

type School struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	Edition   string    `json:"edition"`
}

type Session struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	TokenHash string    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
	UserAgent *string   `json:"user_agent"`
	Ip        *string   `json:"ip"`
	CreatedAt time.Time `json:"created_at"`
}

type Snippet struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
	Text      string    `json:"text"`
	Position  int32     `json:"position"`
	CreatedAt time.Time `json:"created_at"`
	Section   *string   `json:"section"`
}

type SourceLogEntry struct {
	ID          uuid.UUID   `json:"id"`
	ProjectID   uuid.UUID   `json:"project_id"`
	Url         string      `json:"url"`
	Title       string      `json:"title"`
	TimeSpentS  int32       `json:"time_spent_s"`
	Takeaway    string      `json:"takeaway"`
	Tier        *string     `json:"tier"`
	LateralRead bool        `json:"lateral_read"`
	OpenedAt    time.Time   `json:"opened_at"`
	MaterialID  pgtype.UUID `json:"material_id"`
}

type StudentEvaluation struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	Scores    []byte    `json:"scores"`
	CreatedAt time.Time `json:"created_at"`
	Surface   string    `json:"surface"`
	ScopeID   uuid.UUID `json:"scope_id"`
}

type Task struct {
	ID           uuid.UUID `json:"id"`
	UserID       uuid.UUID `json:"user_id"`
	Title        string    `json:"title"`
	Seed         *string   `json:"seed"`
	Status       string    `json:"status"`
	CreatedAt    time.Time `json:"created_at"`
	LastActiveAt time.Time `json:"last_active_at"`
}

type TeacherInvite struct {
	ID         uuid.UUID          `json:"id"`
	SchoolID   uuid.UUID          `json:"school_id"`
	Code       string             `json:"code"`
	Email      *string            `json:"email"`
	CreatedBy  uuid.UUID          `json:"created_by"`
	ExpiresAt  time.Time          `json:"expires_at"`
	ConsumedAt pgtype.Timestamptz `json:"consumed_at"`
	ConsumedBy pgtype.UUID        `json:"consumed_by"`
	CreatedAt  time.Time          `json:"created_at"`
}

type User struct {
	ID              uuid.UUID          `json:"id"`
	Email           string             `json:"email"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
	PasswordHash    string             `json:"password_hash"`
	Role            string             `json:"role"`
	SchoolID        uuid.UUID          `json:"school_id"`
	DisplayName     string             `json:"display_name"`
	AvatarColor     string             `json:"avatar_color"`
	CreatedAt       time.Time          `json:"created_at"`
	CardTheme       string             `json:"card_theme"`
	PageBackground  string             `json:"page_background"`
	OnboardedAt     pgtype.Timestamptz `json:"onboarded_at"`
}

type VoiceTtsCache struct {
	Key       string    `json:"key"`
	Audio     []byte    `json:"audio"`
	Voice     string    `json:"voice"`
	CreatedAt time.Time `json:"created_at"`
}

type Writing struct {
	AtomID       uuid.UUID          `json:"atom_id"`
	Title        string             `json:"title"`
	Lang         string             `json:"lang"`
	Stage        string             `json:"stage"`
	TargetWords  *int32             `json:"target_words"`
	Status       string             `json:"status"`
	UpdatedAt    time.Time          `json:"updated_at"`
	FinishedAt   pgtype.Timestamptz `json:"finished_at"`
	StructureKey string             `json:"structure_key"`
	SetupAt      pgtype.Timestamptz `json:"setup_at"`
}

type WritingComment struct {
	ID        uuid.UUID   `json:"id"`
	AtomID    uuid.UUID   `json:"atom_id"`
	SnippetID pgtype.UUID `json:"snippet_id"`
	Scope     string      `json:"scope"`
	Summary   string      `json:"summary"`
	Points    []byte      `json:"points"`
	CreatedAt time.Time   `json:"created_at"`
}

type WritingDraft struct {
	AtomID    uuid.UUID `json:"atom_id"`
	Body      string    `json:"body"`
	UpdatedAt time.Time `json:"updated_at"`
}

type WritingFinish struct {
	ID         uuid.UUID `json:"id"`
	ProjectID  uuid.UUID `json:"project_id"`
	DocKind    string    `json:"doc_kind"`
	FinishedAt time.Time `json:"finished_at"`
}

type WritingOutline struct {
	ID       uuid.UUID `json:"id"`
	AtomID   uuid.UUID `json:"atom_id"`
	Text     string    `json:"text"`
	Depth    int32     `json:"depth"`
	Position int32     `json:"position"`
	Role     string    `json:"role"`
	Guide    []byte    `json:"guide"`
}

type WritingSnippet struct {
	ID        uuid.UUID   `json:"id"`
	AtomID    uuid.UUID   `json:"atom_id"`
	OutlineID pgtype.UUID `json:"outline_id"`
	Position  int32       `json:"position"`
	Text      string      `json:"text"`
	UpdatedAt time.Time   `json:"updated_at"`
}
