// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type CardInstance struct {
	ID           uuid.UUID          `json:"id"`
	CardID       string             `json:"card_id"`
	TaskID       uuid.UUID          `json:"task_id"`
	ParentNodeID pgtype.UUID        `json:"parent_node_id"`
	Status       string             `json:"status"`
	FieldValues  []byte             `json:"field_values"`
	EventTrace   []byte             `json:"event_trace"`
	RubricTags   []string           `json:"rubric_tags"`
	CreatedAt    time.Time          `json:"created_at"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
	Anchors      []byte             `json:"anchors"`
}

type Class struct {
	ID        uuid.UUID   `json:"id"`
	SchoolID  uuid.UUID   `json:"school_id"`
	Name      string      `json:"name"`
	JoinCode  string      `json:"join_code"`
	CreatedAt time.Time   `json:"created_at"`
	CreatedBy pgtype.UUID `json:"created_by"`
}

type Course struct {
	ID         uuid.UUID `json:"id"`
	Branch     string    `json:"branch"`
	Title      string    `json:"title"`
	Blurb      string    `json:"blurb"`
	TasksCount int32     `json:"tasks_count"`
	ToolsCount int32     `json:"tools_count"`
	TimeLabel  string    `json:"time_label"`
	CreatedAt  time.Time `json:"created_at"`
}

type CourseProgress struct {
	ID                uuid.UUID `json:"id"`
	UserID            uuid.UUID `json:"user_id"`
	CourseID          uuid.UUID `json:"course_id"`
	CurrentOrdinal    int32     `json:"current_ordinal"`
	CompletedOrdinals []int32   `json:"completed_ordinals"`
	UpdatedAt         time.Time `json:"updated_at"`
}

type CourseStep struct {
	ID              uuid.UUID `json:"id"`
	CourseID        uuid.UUID `json:"course_id"`
	Ordinal         int32     `json:"ordinal"`
	Kind            string    `json:"kind"`
	Purpose         string    `json:"purpose"`
	Assets          []byte    `json:"assets"`
	ChallengeType   *string   `json:"challenge_type"`
	AuthoredContent []byte    `json:"authored_content"`
}

type CourseStepRender struct {
	CourseStepID uuid.UUID `json:"course_step_id"`
	Content      []byte    `json:"content"`
	Source       string    `json:"source"`
	CreatedAt    time.Time `json:"created_at"`
}

type EmailVerificationToken struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	TokenHash  string             `json:"token_hash"`
	ExpiresAt  time.Time          `json:"expires_at"`
	ConsumedAt pgtype.Timestamptz `json:"consumed_at"`
	CreatedAt  time.Time          `json:"created_at"`
}

type Enrollment struct {
	ID          uuid.UUID `json:"id"`
	UserID      uuid.UUID `json:"user_id"`
	ClassID     uuid.UUID `json:"class_id"`
	RoleInClass string    `json:"role_in_class"`
	CreatedAt   time.Time `json:"created_at"`
}

type Evaluation struct {
	ID               uuid.UUID          `json:"id"`
	TaskID           uuid.UUID          `json:"task_id"`
	Scores           []byte             `json:"scores"`
	Narrative        string             `json:"narrative"`
	Model            string             `json:"model"`
	Tier             string             `json:"tier"`
	PromptTokens     *int32             `json:"prompt_tokens"`
	CompletionTokens *int32             `json:"completion_tokens"`
	CostEstimate     pgtype.Numeric     `json:"cost_estimate"`
	Status           string             `json:"status"`
	Error            *string            `json:"error"`
	CreatedAt        time.Time          `json:"created_at"`
	CompletedAt      pgtype.Timestamptz `json:"completed_at"`
	Signals          []byte             `json:"signals"`
	RubricVersion    *string            `json:"rubric_version"`
	Trigger          string             `json:"trigger"`
	TriggerMilestone *int32             `json:"trigger_milestone"`
}

type LlmUsage struct {
	ID               uuid.UUID      `json:"id"`
	UserID           uuid.UUID      `json:"user_id"`
	SchoolID         uuid.UUID      `json:"school_id"`
	Kind             string         `json:"kind"`
	Provider         *string        `json:"provider"`
	Model            *string        `json:"model"`
	Tier             *string        `json:"tier"`
	PromptTokens     *int32         `json:"prompt_tokens"`
	CompletionTokens *int32         `json:"completion_tokens"`
	CostEstimate     pgtype.Numeric `json:"cost_estimate"`
	CreatedAt        time.Time      `json:"created_at"`
}

type Material struct {
	ID        uuid.UUID `json:"id"`
	TaskID    uuid.UUID `json:"task_id"`
	Kind      string    `json:"kind"`
	Source    string    `json:"source"`
	Title     string    `json:"title"`
	SourceUrl *string   `json:"source_url"`
	Blocks    []byte    `json:"blocks"`
	Scratch   string    `json:"scratch"`
	CreatedAt time.Time `json:"created_at"`
}

type Message struct {
	ID               uuid.UUID      `json:"id"`
	TaskID           uuid.UUID      `json:"task_id"`
	Role             string         `json:"role"`
	Content          string         `json:"content"`
	ToolCall         []byte         `json:"tool_call"`
	Provider         *string        `json:"provider"`
	Model            *string        `json:"model"`
	Tier             *string        `json:"tier"`
	PromptTokens     *int32         `json:"prompt_tokens"`
	CompletionTokens *int32         `json:"completion_tokens"`
	CostEstimate     pgtype.Numeric `json:"cost_estimate"`
	CreatedAt        time.Time      `json:"created_at"`
}

type School struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

type Session struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	TokenHash string    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
	UserAgent *string   `json:"user_agent"`
	Ip        *string   `json:"ip"`
	CreatedAt time.Time `json:"created_at"`
}

type Task struct {
	ID           uuid.UUID `json:"id"`
	UserID       uuid.UUID `json:"user_id"`
	Title        string    `json:"title"`
	Seed         *string   `json:"seed"`
	Status       string    `json:"status"`
	CreatedAt    time.Time `json:"created_at"`
	LastActiveAt time.Time `json:"last_active_at"`
}

type TeacherInvite struct {
	ID         uuid.UUID          `json:"id"`
	SchoolID   uuid.UUID          `json:"school_id"`
	Code       string             `json:"code"`
	Email      *string            `json:"email"`
	CreatedBy  uuid.UUID          `json:"created_by"`
	ExpiresAt  time.Time          `json:"expires_at"`
	ConsumedAt pgtype.Timestamptz `json:"consumed_at"`
	ConsumedBy pgtype.UUID        `json:"consumed_by"`
	CreatedAt  time.Time          `json:"created_at"`
}

type User struct {
	ID              uuid.UUID          `json:"id"`
	Email           string             `json:"email"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
	PasswordHash    string             `json:"password_hash"`
	Role            string             `json:"role"`
	SchoolID        uuid.UUID          `json:"school_id"`
	DisplayName     string             `json:"display_name"`
	AvatarColor     string             `json:"avatar_color"`
	CreatedAt       time.Time          `json:"created_at"`
}
