// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: news.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const finishNewsDay = `-- name: FinishNewsDay :exec
UPDATE news_day SET planet_count = $2, note = $3 WHERE day = $1
`

type FinishNewsDayParams struct {
	Day         pgtype.Date `json:"day"`
	PlanetCount int32       `json:"planet_count"`
	Note        string      `json:"note"`
}

func (q *Queries) FinishNewsDay(ctx context.Context, arg FinishNewsDayParams) error {
	_, err := q.db.Exec(ctx, finishNewsDay, arg.Day, arg.PlanetCount, arg.Note)
	return err
}

const getNewsDay = `-- name: GetNewsDay :one

SELECT day, attempted_at, planet_count, note FROM news_day WHERE day = $1
`

// news.sql —— 今日新闻星图。
//
// 生成是**惰性**的，和兴趣采集同一个理由：这个 repo 里没有 river worker，
// 而一个每天定时跑的任务需要一个跑它的东西。第一个打开星图的学生触发生成，
// 拿 advisory lock，其余人直接读。见 internal/api/explore.go。
func (q *Queries) GetNewsDay(ctx context.Context, day pgtype.Date) (NewsDay, error) {
	row := q.db.QueryRow(ctx, getNewsDay, day)
	var i NewsDay
	err := row.Scan(
		&i.Day,
		&i.AttemptedAt,
		&i.PlanetCount,
		&i.Note,
	)
	return i, err
}

const getNewsPlanet = `-- name: GetNewsPlanet :one
SELECT id, day, rank, title_zh, title_en, summary, hook, url, source_name, field, discipline_id, keyword, published_at, created_at FROM news_planet WHERE id = $1
`

func (q *Queries) GetNewsPlanet(ctx context.Context, id uuid.UUID) (NewsPlanet, error) {
	row := q.db.QueryRow(ctx, getNewsPlanet, id)
	var i NewsPlanet
	err := row.Scan(
		&i.ID,
		&i.Day,
		&i.Rank,
		&i.TitleZh,
		&i.TitleEn,
		&i.Summary,
		&i.Hook,
		&i.Url,
		&i.SourceName,
		&i.Field,
		&i.DisciplineID,
		&i.Keyword,
		&i.PublishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const hasSavedPlanet = `-- name: HasSavedPlanet :one
SELECT EXISTS (SELECT 1 FROM news_saved WHERE user_id = $1 AND planet_id = $2)
`

type HasSavedPlanetParams struct {
	UserID   uuid.UUID `json:"user_id"`
	PlanetID uuid.UUID `json:"planet_id"`
}

func (q *Queries) HasSavedPlanet(ctx context.Context, arg HasSavedPlanetParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasSavedPlanet, arg.UserID, arg.PlanetID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertNewsPlanet = `-- name: InsertNewsPlanet :one
INSERT INTO news_planet (
  day, rank, title_zh, title_en, summary, hook, url, source_name,
  field, discipline_id, keyword, published_at
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)
ON CONFLICT (day, rank) DO NOTHING
RETURNING id, day, rank, title_zh, title_en, summary, hook, url, source_name, field, discipline_id, keyword, published_at, created_at
`

type InsertNewsPlanetParams struct {
	Day          pgtype.Date        `json:"day"`
	Rank         int32              `json:"rank"`
	TitleZh      string             `json:"title_zh"`
	TitleEn      string             `json:"title_en"`
	Summary      string             `json:"summary"`
	Hook         string             `json:"hook"`
	Url          string             `json:"url"`
	SourceName   string             `json:"source_name"`
	Field        string             `json:"field"`
	DisciplineID string             `json:"discipline_id"`
	Keyword      string             `json:"keyword"`
	PublishedAt  pgtype.Timestamptz `json:"published_at"`
}

func (q *Queries) InsertNewsPlanet(ctx context.Context, arg InsertNewsPlanetParams) (NewsPlanet, error) {
	row := q.db.QueryRow(ctx, insertNewsPlanet,
		arg.Day,
		arg.Rank,
		arg.TitleZh,
		arg.TitleEn,
		arg.Summary,
		arg.Hook,
		arg.Url,
		arg.SourceName,
		arg.Field,
		arg.DisciplineID,
		arg.Keyword,
		arg.PublishedAt,
	)
	var i NewsPlanet
	err := row.Scan(
		&i.ID,
		&i.Day,
		&i.Rank,
		&i.TitleZh,
		&i.TitleEn,
		&i.Summary,
		&i.Hook,
		&i.Url,
		&i.SourceName,
		&i.Field,
		&i.DisciplineID,
		&i.Keyword,
		&i.PublishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listNewsPlanets = `-- name: ListNewsPlanets :many
SELECT id, day, rank, title_zh, title_en, summary, hook, url, source_name, field, discipline_id, keyword, published_at, created_at FROM news_planet WHERE day = $1 ORDER BY rank
`

func (q *Queries) ListNewsPlanets(ctx context.Context, day pgtype.Date) ([]NewsPlanet, error) {
	rows, err := q.db.Query(ctx, listNewsPlanets, day)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NewsPlanet
	for rows.Next() {
		var i NewsPlanet
		if err := rows.Scan(
			&i.ID,
			&i.Day,
			&i.Rank,
			&i.TitleZh,
			&i.TitleEn,
			&i.Summary,
			&i.Hook,
			&i.Url,
			&i.SourceName,
			&i.Field,
			&i.DisciplineID,
			&i.Keyword,
			&i.PublishedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentNewsDays = `-- name: ListRecentNewsDays :many
SELECT DISTINCT day FROM news_planet ORDER BY day DESC LIMIT $1
`

// 她最近几天见过的星图。星图是**每天一屏**，往回翻是看昨天，不是一个信息流，
// 所以调用方给一个很小的 limit。
func (q *Queries) ListRecentNewsDays(ctx context.Context, limit int32) ([]pgtype.Date, error) {
	rows, err := q.db.Query(ctx, listRecentNewsDays, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.Date
	for rows.Next() {
		var day pgtype.Date
		if err := rows.Scan(&day); err != nil {
			return nil, err
		}
		items = append(items, day)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSavedPlanetIDs = `-- name: ListSavedPlanetIDs :many
SELECT planet_id FROM news_saved WHERE user_id = $1
`

func (q *Queries) ListSavedPlanetIDs(ctx context.Context, userID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listSavedPlanetIDs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var planet_id uuid.UUID
		if err := rows.Scan(&planet_id); err != nil {
			return nil, err
		}
		items = append(items, planet_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNewsDayAttempted = `-- name: MarkNewsDayAttempted :exec
INSERT INTO news_day (day) VALUES ($1)
ON CONFLICT (day) DO NOTHING
`

// 盖章。**在生成之前调**：语义是「今天试过一次」，不是「今天出过星图」。
// 所有源都挂掉的那天，如果按产出判断，每个打开星图的学生都会再触发一次全量
// 抓取 + 一次旗舰调用。
func (q *Queries) MarkNewsDayAttempted(ctx context.Context, day pgtype.Date) error {
	_, err := q.db.Exec(ctx, markNewsDayAttempted, day)
	return err
}

const savePlanet = `-- name: SavePlanet :exec
INSERT INTO news_saved (user_id, planet_id) VALUES ($1, $2)
ON CONFLICT (user_id, planet_id) DO NOTHING
`

type SavePlanetParams struct {
	UserID   uuid.UUID `json:"user_id"`
	PlanetID uuid.UUID `json:"planet_id"`
}

// 收藏是一次动作，不是开关；重复收藏什么也不做（她的树上那个词也因此只会
// 有一条来自这颗星的来源）。
func (q *Queries) SavePlanet(ctx context.Context, arg SavePlanetParams) error {
	_, err := q.db.Exec(ctx, savePlanet, arg.UserID, arg.PlanetID)
	return err
}
