// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: parent.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getParentReportProse = `-- name: GetParentReportProse :one
SELECT prose FROM parent_report_prose
WHERE student_user_id = $1 AND surface = $2 AND scope_id = $3
`

type GetParentReportProseParams struct {
	StudentUserID uuid.UUID `json:"student_user_id"`
	Surface       string    `json:"surface"`
	ScopeID       string    `json:"scope_id"`
}

func (q *Queries) GetParentReportProse(ctx context.Context, arg GetParentReportProseParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getParentReportProse, arg.StudentUserID, arg.Surface, arg.ScopeID)
	var prose []byte
	err := row.Scan(&prose)
	return prose, err
}

const insertParentReportProse = `-- name: InsertParentReportProse :exec
INSERT INTO parent_report_prose (student_user_id, surface, scope_id, prose)
VALUES ($1, $2, $3, $4)
ON CONFLICT (student_user_id, surface, scope_id) DO NOTHING
`

type InsertParentReportProseParams struct {
	StudentUserID uuid.UUID `json:"student_user_id"`
	Surface       string    `json:"surface"`
	ScopeID       string    `json:"scope_id"`
	Prose         []byte    `json:"prose"`
}

func (q *Queries) InsertParentReportProse(ctx context.Context, arg InsertParentReportProseParams) error {
	_, err := q.db.Exec(ctx, insertParentReportProse,
		arg.StudentUserID,
		arg.Surface,
		arg.ScopeID,
		arg.Prose,
	)
	return err
}
