// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: pbl_note_link.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createPblNoteLink = `-- name: CreatePblNoteLink :one

INSERT INTO pbl_note_link (atom_id, from_id, to_id, relation)
VALUES ($1, $2, $3, $4)
ON CONFLICT (from_id, to_id, relation) DO UPDATE SET relation = EXCLUDED.relation
RETURNING id, atom_id, from_id, to_id, relation, created_at
`

type CreatePblNoteLinkParams struct {
	AtomID   uuid.UUID `json:"atom_id"`
	FromID   uuid.UUID `json:"from_id"`
	ToID     uuid.UUID `json:"to_id"`
	Relation string    `json:"relation"`
}

// 两张便签之间的关系。见 migration 0126。
// 同一对纸之间同一种关系连一次就够：她再连一次是想改关系，不是想要两条线。
func (q *Queries) CreatePblNoteLink(ctx context.Context, arg CreatePblNoteLinkParams) (PblNoteLink, error) {
	row := q.db.QueryRow(ctx, createPblNoteLink,
		arg.AtomID,
		arg.FromID,
		arg.ToID,
		arg.Relation,
	)
	var i PblNoteLink
	err := row.Scan(
		&i.ID,
		&i.AtomID,
		&i.FromID,
		&i.ToID,
		&i.Relation,
		&i.CreatedAt,
	)
	return i, err
}

const deletePblNoteLink = `-- name: DeletePblNoteLink :exec
DELETE FROM pbl_note_link WHERE id = $1 AND atom_id = $2
`

type DeletePblNoteLinkParams struct {
	ID     uuid.UUID `json:"id"`
	AtomID uuid.UUID `json:"atom_id"`
}

func (q *Queries) DeletePblNoteLink(ctx context.Context, arg DeletePblNoteLinkParams) error {
	_, err := q.db.Exec(ctx, deletePblNoteLink, arg.ID, arg.AtomID)
	return err
}

const listPblNoteLinks = `-- name: ListPblNoteLinks :many
SELECT id, atom_id, from_id, to_id, relation, created_at FROM pbl_note_link WHERE atom_id = $1 ORDER BY created_at
`

func (q *Queries) ListPblNoteLinks(ctx context.Context, atomID uuid.UUID) ([]PblNoteLink, error) {
	rows, err := q.db.Query(ctx, listPblNoteLinks, atomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PblNoteLink
	for rows.Next() {
		var i PblNoteLink
		if err := rows.Scan(
			&i.ID,
			&i.AtomID,
			&i.FromID,
			&i.ToID,
			&i.Relation,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPblNoteLinksWithBodies = `-- name: ListPblNoteLinksWithBodies :many
SELECT l.relation, f.body AS from_body, t.body AS to_body
FROM pbl_note_link l
JOIN pbl_note f ON f.id = l.from_id
JOIN pbl_note t ON t.id = l.to_id
WHERE l.atom_id = $1
ORDER BY l.created_at
`

type ListPblNoteLinksWithBodiesRow struct {
	Relation string `json:"relation"`
	FromBody string `json:"from_body"`
	ToBody   string `json:"to_body"`
}

// 回灌用：印记要读到「『走廊站着 14 个人』和『教室里坐不住』互相矛盾」，
// 不是两个 uuid。
func (q *Queries) ListPblNoteLinksWithBodies(ctx context.Context, atomID uuid.UUID) ([]ListPblNoteLinksWithBodiesRow, error) {
	rows, err := q.db.Query(ctx, listPblNoteLinksWithBodies, atomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPblNoteLinksWithBodiesRow
	for rows.Next() {
		var i ListPblNoteLinksWithBodiesRow
		if err := rows.Scan(&i.Relation, &i.FromBody, &i.ToBody); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
