// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: pbl_session.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const appendPblSessionMessage = `-- name: AppendPblSessionMessage :one
INSERT INTO atom_message (atom_id, seq, role, content, payload, session_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, atom_id, seq, role, content, created_at, block_id, payload, session_id
`

type AppendPblSessionMessageParams struct {
	AtomID    uuid.UUID   `json:"atom_id"`
	Seq       int32       `json:"seq"`
	Role      string      `json:"role"`
	Content   string      `json:"content"`
	Payload   []byte      `json:"payload"`
	SessionID pgtype.UUID `json:"session_id"`
}

func (q *Queries) AppendPblSessionMessage(ctx context.Context, arg AppendPblSessionMessageParams) (AtomMessage, error) {
	row := q.db.QueryRow(ctx, appendPblSessionMessage,
		arg.AtomID,
		arg.Seq,
		arg.Role,
		arg.Content,
		arg.Payload,
		arg.SessionID,
	)
	var i AtomMessage
	err := row.Scan(
		&i.ID,
		&i.AtomID,
		&i.Seq,
		&i.Role,
		&i.Content,
		&i.CreatedAt,
		&i.BlockID,
		&i.Payload,
		&i.SessionID,
	)
	return i, err
}

const closePblSession = `-- name: ClosePblSession :one
UPDATE pbl_session
SET takeaway = $2, writeback = $3, closed_at = now()
WHERE id = $1 AND closed_at IS NULL
RETURNING id, atom_id, kind, parent_id, depth, anchor_kind, anchor_ref, question, takeaway, writeback, closed_at, created_at
`

type ClosePblSessionParams struct {
	ID        uuid.UUID `json:"id"`
	Takeaway  string    `json:"takeaway"`
	Writeback []byte    `json:"writeback"`
}

// 写回内容够不够，由 Go 按 kind 判断（pbl.ValidateClose）——SQL 表达不了
// 「这个 kind 至少要产出什么」。这里只负责落库。
func (q *Queries) ClosePblSession(ctx context.Context, arg ClosePblSessionParams) (PblSession, error) {
	row := q.db.QueryRow(ctx, closePblSession, arg.ID, arg.Takeaway, arg.Writeback)
	var i PblSession
	err := row.Scan(
		&i.ID,
		&i.AtomID,
		&i.Kind,
		&i.ParentID,
		&i.Depth,
		&i.AnchorKind,
		&i.AnchorRef,
		&i.Question,
		&i.Takeaway,
		&i.Writeback,
		&i.ClosedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createPblSession = `-- name: CreatePblSession :one

INSERT INTO pbl_session (atom_id, kind, parent_id, depth, anchor_kind, anchor_ref, question)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, atom_id, kind, parent_id, depth, anchor_kind, anchor_ref, question, takeaway, writeback, closed_at, created_at
`

type CreatePblSessionParams struct {
	AtomID     uuid.UUID   `json:"atom_id"`
	Kind       string      `json:"kind"`
	ParentID   pgtype.UUID `json:"parent_id"`
	Depth      int16       `json:"depth"`
	AnchorKind string      `json:"anchor_kind"`
	AnchorRef  string      `json:"anchor_ref"`
	Question   string      `json:"question"`
}

// PBL session：自由深挖和四种思考模式共用的那张表。
// 名字全部带 Pbl 前缀——和 pro 共用一个 sqlc 包，重名会直接覆盖掉对方的方法。
func (q *Queries) CreatePblSession(ctx context.Context, arg CreatePblSessionParams) (PblSession, error) {
	row := q.db.QueryRow(ctx, createPblSession,
		arg.AtomID,
		arg.Kind,
		arg.ParentID,
		arg.Depth,
		arg.AnchorKind,
		arg.AnchorRef,
		arg.Question,
	)
	var i PblSession
	err := row.Scan(
		&i.ID,
		&i.AtomID,
		&i.Kind,
		&i.ParentID,
		&i.Depth,
		&i.AnchorKind,
		&i.AnchorRef,
		&i.Question,
		&i.Takeaway,
		&i.Writeback,
		&i.ClosedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPblSession = `-- name: GetPblSession :one
SELECT s.id, s.atom_id, s.kind, s.parent_id, s.depth, s.anchor_kind, s.anchor_ref, s.question, s.takeaway, s.writeback, s.closed_at, s.created_at, a.user_id
FROM pbl_session s JOIN atom a ON a.id = s.atom_id
WHERE s.id = $1
`

type GetPblSessionRow struct {
	ID         uuid.UUID          `json:"id"`
	AtomID     uuid.UUID          `json:"atom_id"`
	Kind       string             `json:"kind"`
	ParentID   pgtype.UUID        `json:"parent_id"`
	Depth      int16              `json:"depth"`
	AnchorKind string             `json:"anchor_kind"`
	AnchorRef  string             `json:"anchor_ref"`
	Question   string             `json:"question"`
	Takeaway   string             `json:"takeaway"`
	Writeback  []byte             `json:"writeback"`
	ClosedAt   pgtype.Timestamptz `json:"closed_at"`
	CreatedAt  time.Time          `json:"created_at"`
	UserID     uuid.UUID          `json:"user_id"`
}

func (q *Queries) GetPblSession(ctx context.Context, id uuid.UUID) (GetPblSessionRow, error) {
	row := q.db.QueryRow(ctx, getPblSession, id)
	var i GetPblSessionRow
	err := row.Scan(
		&i.ID,
		&i.AtomID,
		&i.Kind,
		&i.ParentID,
		&i.Depth,
		&i.AnchorKind,
		&i.AnchorRef,
		&i.Question,
		&i.Takeaway,
		&i.Writeback,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UserID,
	)
	return i, err
}

const listPblMainThread = `-- name: ListPblMainThread :many
SELECT id, atom_id, seq, role, content, created_at, block_id, payload, session_id FROM atom_message
WHERE atom_id = $1 AND session_id IS NULL AND block_id IS NULL
ORDER BY seq
`

// 项目主线。session_id IS NULL 是它的全部定义——和 0102 的 block_id 同构。
func (q *Queries) ListPblMainThread(ctx context.Context, atomID uuid.UUID) ([]AtomMessage, error) {
	rows, err := q.db.Query(ctx, listPblMainThread, atomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AtomMessage
	for rows.Next() {
		var i AtomMessage
		if err := rows.Scan(
			&i.ID,
			&i.AtomID,
			&i.Seq,
			&i.Role,
			&i.Content,
			&i.CreatedAt,
			&i.BlockID,
			&i.Payload,
			&i.SessionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPblSessionMessages = `-- name: ListPblSessionMessages :many
SELECT id, atom_id, seq, role, content, created_at, block_id, payload, session_id FROM atom_message
WHERE atom_id = $1 AND session_id = $2
ORDER BY seq
`

type ListPblSessionMessagesParams struct {
	AtomID    uuid.UUID   `json:"atom_id"`
	SessionID pgtype.UUID `json:"session_id"`
}

// 一个 session 自己的对话。seq 仍在原子的同一个空间里，所以过滤之后仍然有序
// （中间的空档是别处的消息）。
func (q *Queries) ListPblSessionMessages(ctx context.Context, arg ListPblSessionMessagesParams) ([]AtomMessage, error) {
	rows, err := q.db.Query(ctx, listPblSessionMessages, arg.AtomID, arg.SessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AtomMessage
	for rows.Next() {
		var i AtomMessage
		if err := rows.Scan(
			&i.ID,
			&i.AtomID,
			&i.Seq,
			&i.Role,
			&i.Content,
			&i.CreatedAt,
			&i.BlockID,
			&i.Payload,
			&i.SessionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPblSessionWriteBacks = `-- name: ListPblSessionWriteBacks :many
SELECT id, atom_id, kind, parent_id, depth, anchor_kind, anchor_ref, question, takeaway, writeback, closed_at, created_at FROM pbl_session
WHERE atom_id = $1
  AND parent_id IS NOT DISTINCT FROM $2::uuid
  AND closed_at IS NOT NULL
ORDER BY closed_at
`

type ListPblSessionWriteBacksParams struct {
	AtomID   uuid.UUID   `json:"atom_id"`
	ParentID pgtype.UUID `json:"parent_id"`
}

// 主线（或某个父 session）能看到的：已关闭子 session 的写回，而不是它们的
// 每一轮对话。这就是 spec §10.3 的上下文规则落到查询上的样子。
func (q *Queries) ListPblSessionWriteBacks(ctx context.Context, arg ListPblSessionWriteBacksParams) ([]PblSession, error) {
	rows, err := q.db.Query(ctx, listPblSessionWriteBacks, arg.AtomID, arg.ParentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PblSession
	for rows.Next() {
		var i PblSession
		if err := rows.Scan(
			&i.ID,
			&i.AtomID,
			&i.Kind,
			&i.ParentID,
			&i.Depth,
			&i.AnchorKind,
			&i.AnchorRef,
			&i.Question,
			&i.Takeaway,
			&i.Writeback,
			&i.ClosedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPblSessions = `-- name: ListPblSessions :many
SELECT id, atom_id, kind, parent_id, depth, anchor_kind, anchor_ref, question, takeaway, writeback, closed_at, created_at FROM pbl_session WHERE atom_id = $1 ORDER BY created_at
`

// 一个项目的全部 session，含未关闭的。前端按 parent_id 还原成树。
func (q *Queries) ListPblSessions(ctx context.Context, atomID uuid.UUID) ([]PblSession, error) {
	rows, err := q.db.Query(ctx, listPblSessions, atomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PblSession
	for rows.Next() {
		var i PblSession
		if err := rows.Scan(
			&i.ID,
			&i.AtomID,
			&i.Kind,
			&i.ParentID,
			&i.Depth,
			&i.AnchorKind,
			&i.AnchorRef,
			&i.Question,
			&i.Takeaway,
			&i.Writeback,
			&i.ClosedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
