// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: pbl_course.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const assignPblCourse = `-- name: AssignPblCourse :one

INSERT INTO pbl_course_assignment (atom_id, session_id, course_slug, why)
VALUES ($1, $2, $3, $4)
ON CONFLICT (atom_id, course_slug) DO UPDATE SET why = EXCLUDED.why
RETURNING id, atom_id, session_id, course_slug, why, takeaway, finished_at, created_at
`

type AssignPblCourseParams struct {
	AtomID     uuid.UUID   `json:"atom_id"`
	SessionID  pgtype.UUID `json:"session_id"`
	CourseSlug string      `json:"course_slug"`
	Why        string      `json:"why"`
}

// 项目里的课程指派（migration 0133）。
//
// 印记在项目里递出一门课，她去上，上完回来写一句「这一课对我这个项目有什么
// 用」。那一句是闭环的内容本身，回灌读的就是它。
// 同一个项目里同一门课只指派一次（唯一索引）。重复递就更新理由——印记第二次
// 递它，说明这一刻的理由和上一次不一样，而她屏幕上仍然只该有一张卡。
func (q *Queries) AssignPblCourse(ctx context.Context, arg AssignPblCourseParams) (PblCourseAssignment, error) {
	row := q.db.QueryRow(ctx, assignPblCourse,
		arg.AtomID,
		arg.SessionID,
		arg.CourseSlug,
		arg.Why,
	)
	var i PblCourseAssignment
	err := row.Scan(
		&i.ID,
		&i.AtomID,
		&i.SessionID,
		&i.CourseSlug,
		&i.Why,
		&i.Takeaway,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const finishPblCourseAssignment = `-- name: FinishPblCourseAssignment :one
UPDATE pbl_course_assignment
SET takeaway = $2, finished_at = COALESCE(finished_at, now())
WHERE id = $1
RETURNING id, atom_id, session_id, course_slug, why, takeaway, finished_at, created_at
`

type FinishPblCourseAssignmentParams struct {
	ID       uuid.UUID `json:"id"`
	Takeaway string    `json:"takeaway"`
}

// 她上完回来了。takeaway 由 Go 校验（trim 之后非空）——一次没留下任何一句话
// 的上课，对这个项目来说等于没发生，而闭环要回灌的正是那句话。
// finished_at 用 COALESCE 保持首次完成的时间：她后来改了那句话，"什么时候上完
// 的"不该跟着变。
func (q *Queries) FinishPblCourseAssignment(ctx context.Context, arg FinishPblCourseAssignmentParams) (PblCourseAssignment, error) {
	row := q.db.QueryRow(ctx, finishPblCourseAssignment, arg.ID, arg.Takeaway)
	var i PblCourseAssignment
	err := row.Scan(
		&i.ID,
		&i.AtomID,
		&i.SessionID,
		&i.CourseSlug,
		&i.Why,
		&i.Takeaway,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPblCourseAssignment = `-- name: GetPblCourseAssignment :one
SELECT c.id, c.atom_id, c.session_id, c.course_slug, c.why, c.takeaway, c.finished_at, c.created_at, a.user_id
FROM pbl_course_assignment c JOIN atom a ON a.id = c.atom_id
WHERE c.id = $1
`

type GetPblCourseAssignmentRow struct {
	ID         uuid.UUID          `json:"id"`
	AtomID     uuid.UUID          `json:"atom_id"`
	SessionID  pgtype.UUID        `json:"session_id"`
	CourseSlug string             `json:"course_slug"`
	Why        string             `json:"why"`
	Takeaway   string             `json:"takeaway"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
	CreatedAt  time.Time          `json:"created_at"`
	UserID     uuid.UUID          `json:"user_id"`
}

// 带上 user_id，调用方一次查询就能判归属，不用先取 atom 再比一次。
func (q *Queries) GetPblCourseAssignment(ctx context.Context, id uuid.UUID) (GetPblCourseAssignmentRow, error) {
	row := q.db.QueryRow(ctx, getPblCourseAssignment, id)
	var i GetPblCourseAssignmentRow
	err := row.Scan(
		&i.ID,
		&i.AtomID,
		&i.SessionID,
		&i.CourseSlug,
		&i.Why,
		&i.Takeaway,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UserID,
	)
	return i, err
}

const listPblCourseAssignments = `-- name: ListPblCourseAssignments :many
SELECT id, atom_id, session_id, course_slug, why, takeaway, finished_at, created_at FROM pbl_course_assignment WHERE atom_id = $1 ORDER BY created_at
`

func (q *Queries) ListPblCourseAssignments(ctx context.Context, atomID uuid.UUID) ([]PblCourseAssignment, error) {
	rows, err := q.db.Query(ctx, listPblCourseAssignments, atomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PblCourseAssignment
	for rows.Next() {
		var i PblCourseAssignment
		if err := rows.Scan(
			&i.ID,
			&i.AtomID,
			&i.SessionID,
			&i.CourseSlug,
			&i.Why,
			&i.Takeaway,
			&i.FinishedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
