// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: pbl_artifact_trial.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const ensurePblArtifactTrialDraft = `-- name: EnsurePblArtifactTrialDraft :exec
INSERT INTO pbl_artifact_trial_draft (artifact_id) VALUES ($1) ON CONFLICT DO NOTHING
`

func (q *Queries) EnsurePblArtifactTrialDraft(ctx context.Context, artifactID uuid.UUID) error {
	_, err := q.db.Exec(ctx, ensurePblArtifactTrialDraft, artifactID)
	return err
}

const getPblArtifactTrialDraft = `-- name: GetPblArtifactTrialDraft :one
SELECT artifact_id, document, revision, submitted_revision, submitted_entry_id, updated_at FROM pbl_artifact_trial_draft WHERE artifact_id = $1
`

func (q *Queries) GetPblArtifactTrialDraft(ctx context.Context, artifactID uuid.UUID) (PblArtifactTrialDraft, error) {
	row := q.db.QueryRow(ctx, getPblArtifactTrialDraft, artifactID)
	var i PblArtifactTrialDraft
	err := row.Scan(
		&i.ArtifactID,
		&i.Document,
		&i.Revision,
		&i.SubmittedRevision,
		&i.SubmittedEntryID,
		&i.UpdatedAt,
	)
	return i, err
}

const getPblTrialSubmittedEntry = `-- name: GetPblTrialSubmittedEntry :one
SELECT id, atom_id, kind, body, stage, session_id, created_at, metric, value, prev, unit, expect, verdict FROM pbl_keep_entry WHERE id = $1 AND atom_id = $2
`

type GetPblTrialSubmittedEntryParams struct {
	ID     uuid.UUID `json:"id"`
	AtomID uuid.UUID `json:"atom_id"`
}

func (q *Queries) GetPblTrialSubmittedEntry(ctx context.Context, arg GetPblTrialSubmittedEntryParams) (PblKeepEntry, error) {
	row := q.db.QueryRow(ctx, getPblTrialSubmittedEntry, arg.ID, arg.AtomID)
	var i PblKeepEntry
	err := row.Scan(
		&i.ID,
		&i.AtomID,
		&i.Kind,
		&i.Body,
		&i.Stage,
		&i.SessionID,
		&i.CreatedAt,
		&i.Metric,
		&i.Value,
		&i.Prev,
		&i.Unit,
		&i.Expect,
		&i.Verdict,
	)
	return i, err
}

const savePblArtifactTrialDraft = `-- name: SavePblArtifactTrialDraft :one
UPDATE pbl_artifact_trial_draft SET document = $2, revision = revision + 1, updated_at = now()
WHERE artifact_id = $1 AND revision = $3 RETURNING artifact_id, document, revision, submitted_revision, submitted_entry_id, updated_at
`

type SavePblArtifactTrialDraftParams struct {
	ArtifactID uuid.UUID `json:"artifact_id"`
	Document   []byte    `json:"document"`
	Revision   int32     `json:"revision"`
}

func (q *Queries) SavePblArtifactTrialDraft(ctx context.Context, arg SavePblArtifactTrialDraftParams) (PblArtifactTrialDraft, error) {
	row := q.db.QueryRow(ctx, savePblArtifactTrialDraft, arg.ArtifactID, arg.Document, arg.Revision)
	var i PblArtifactTrialDraft
	err := row.Scan(
		&i.ArtifactID,
		&i.Document,
		&i.Revision,
		&i.SubmittedRevision,
		&i.SubmittedEntryID,
		&i.UpdatedAt,
	)
	return i, err
}

const submitPblArtifactTrialDraft = `-- name: SubmitPblArtifactTrialDraft :one
UPDATE pbl_artifact_trial_draft
SET document = $2, submitted_revision = revision, submitted_entry_id = $3, revision = revision + 1, updated_at = now()
WHERE artifact_id = $1 AND revision = $4 RETURNING artifact_id, document, revision, submitted_revision, submitted_entry_id, updated_at
`

type SubmitPblArtifactTrialDraftParams struct {
	ArtifactID       uuid.UUID   `json:"artifact_id"`
	Document         []byte      `json:"document"`
	SubmittedEntryID pgtype.UUID `json:"submitted_entry_id"`
	Revision         int32       `json:"revision"`
}

func (q *Queries) SubmitPblArtifactTrialDraft(ctx context.Context, arg SubmitPblArtifactTrialDraftParams) (PblArtifactTrialDraft, error) {
	row := q.db.QueryRow(ctx, submitPblArtifactTrialDraft,
		arg.ArtifactID,
		arg.Document,
		arg.SubmittedEntryID,
		arg.Revision,
	)
	var i PblArtifactTrialDraft
	err := row.Scan(
		&i.ArtifactID,
		&i.Document,
		&i.Revision,
		&i.SubmittedRevision,
		&i.SubmittedEntryID,
		&i.UpdatedAt,
	)
	return i, err
}
