// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: pbl_persona.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const choosePblPersona = `-- name: ChoosePblPersona :one
UPDATE pbl_persona SET chosen = true WHERE id = $2 AND atom_id = $1 RETURNING id, atom_id, label, why_knows, wants, feeling, keywords, portrait_key, chosen, created_at
`

type ChoosePblPersonaParams struct {
	AtomID uuid.UUID `json:"atom_id"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) ChoosePblPersona(ctx context.Context, arg ChoosePblPersonaParams) (PblPersona, error) {
	row := q.db.QueryRow(ctx, choosePblPersona, arg.AtomID, arg.ID)
	var i PblPersona
	err := row.Scan(
		&i.ID,
		&i.AtomID,
		&i.Label,
		&i.WhyKnows,
		&i.Wants,
		&i.Feeling,
		&i.Keywords,
		&i.PortraitKey,
		&i.Chosen,
		&i.CreatedAt,
	)
	return i, err
}

const clearPblPersonaChosen = `-- name: ClearPblPersonaChosen :exec
UPDATE pbl_persona SET chosen = false WHERE atom_id = $1 AND chosen
`

// 先清空再置一个：唯一索引 pbl_persona_one_chosen 不允许两个同时为真，所以这
// 两步必须在同一个事务里。
func (q *Queries) ClearPblPersonaChosen(ctx context.Context, atomID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearPblPersonaChosen, atomID)
	return err
}

const createPblPersona = `-- name: CreatePblPersona :one
INSERT INTO pbl_persona (atom_id, label, why_knows, wants, feeling, keywords)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, atom_id, label, why_knows, wants, feeling, keywords, portrait_key, chosen, created_at
`

type CreatePblPersonaParams struct {
	AtomID   uuid.UUID `json:"atom_id"`
	Label    string    `json:"label"`
	WhyKnows string    `json:"why_knows"`
	Wants    string    `json:"wants"`
	Feeling  string    `json:"feeling"`
	Keywords []byte    `json:"keywords"`
}

func (q *Queries) CreatePblPersona(ctx context.Context, arg CreatePblPersonaParams) (PblPersona, error) {
	row := q.db.QueryRow(ctx, createPblPersona,
		arg.AtomID,
		arg.Label,
		arg.WhyKnows,
		arg.Wants,
		arg.Feeling,
		arg.Keywords,
	)
	var i PblPersona
	err := row.Scan(
		&i.ID,
		&i.AtomID,
		&i.Label,
		&i.WhyKnows,
		&i.Wants,
		&i.Feeling,
		&i.Keywords,
		&i.PortraitKey,
		&i.Chosen,
		&i.CreatedAt,
	)
	return i, err
}

const deletePblPersonasByAtom = `-- name: DeletePblPersonasByAtom :exec
DELETE FROM pbl_persona WHERE atom_id = $1
`

// 「都不像」——整批重来。
func (q *Queries) DeletePblPersonasByAtom(ctx context.Context, atomID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePblPersonasByAtom, atomID)
	return err
}

const getPblPersona = `-- name: GetPblPersona :one
SELECT id, atom_id, label, why_knows, wants, feeling, keywords, portrait_key, chosen, created_at FROM pbl_persona WHERE id = $2 AND atom_id = $1
`

type GetPblPersonaParams struct {
	AtomID uuid.UUID `json:"atom_id"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) GetPblPersona(ctx context.Context, arg GetPblPersonaParams) (PblPersona, error) {
	row := q.db.QueryRow(ctx, getPblPersona, arg.AtomID, arg.ID)
	var i PblPersona
	err := row.Scan(
		&i.ID,
		&i.AtomID,
		&i.Label,
		&i.WhyKnows,
		&i.Wants,
		&i.Feeling,
		&i.Keywords,
		&i.PortraitKey,
		&i.Chosen,
		&i.CreatedAt,
	)
	return i, err
}

const listPblPersonas = `-- name: ListPblPersonas :many
SELECT id, atom_id, label, why_knows, wants, feeling, keywords, portrait_key, chosen, created_at FROM pbl_persona WHERE atom_id = $1 ORDER BY created_at
`

func (q *Queries) ListPblPersonas(ctx context.Context, atomID uuid.UUID) ([]PblPersona, error) {
	rows, err := q.db.Query(ctx, listPblPersonas, atomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PblPersona
	for rows.Next() {
		var i PblPersona
		if err := rows.Scan(
			&i.ID,
			&i.AtomID,
			&i.Label,
			&i.WhyKnows,
			&i.Wants,
			&i.Feeling,
			&i.Keywords,
			&i.PortraitKey,
			&i.Chosen,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPblPersonaKeywords = `-- name: SetPblPersonaKeywords :one
UPDATE pbl_persona SET keywords = $3 WHERE id = $2 AND atom_id = $1 RETURNING id, atom_id, label, why_knows, wants, feeling, keywords, portrait_key, chosen, created_at
`

type SetPblPersonaKeywordsParams struct {
	AtomID   uuid.UUID `json:"atom_id"`
	ID       uuid.UUID `json:"id"`
	Keywords []byte    `json:"keywords"`
}

func (q *Queries) SetPblPersonaKeywords(ctx context.Context, arg SetPblPersonaKeywordsParams) (PblPersona, error) {
	row := q.db.QueryRow(ctx, setPblPersonaKeywords, arg.AtomID, arg.ID, arg.Keywords)
	var i PblPersona
	err := row.Scan(
		&i.ID,
		&i.AtomID,
		&i.Label,
		&i.WhyKnows,
		&i.Wants,
		&i.Feeling,
		&i.Keywords,
		&i.PortraitKey,
		&i.Chosen,
		&i.CreatedAt,
	)
	return i, err
}

const setPblPersonaPortrait = `-- name: SetPblPersonaPortrait :one
UPDATE pbl_persona SET portrait_key = $3 WHERE id = $2 AND atom_id = $1 RETURNING id, atom_id, label, why_knows, wants, feeling, keywords, portrait_key, chosen, created_at
`

type SetPblPersonaPortraitParams struct {
	AtomID      uuid.UUID `json:"atom_id"`
	ID          uuid.UUID `json:"id"`
	PortraitKey string    `json:"portrait_key"`
}

func (q *Queries) SetPblPersonaPortrait(ctx context.Context, arg SetPblPersonaPortraitParams) (PblPersona, error) {
	row := q.db.QueryRow(ctx, setPblPersonaPortrait, arg.AtomID, arg.ID, arg.PortraitKey)
	var i PblPersona
	err := row.Scan(
		&i.ID,
		&i.AtomID,
		&i.Label,
		&i.WhyKnows,
		&i.Wants,
		&i.Feeling,
		&i.Keywords,
		&i.PortraitKey,
		&i.Chosen,
		&i.CreatedAt,
	)
	return i, err
}
