// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: pbl_review.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const answerPblReviewDimension = `-- name: AnswerPblReviewDimension :one
UPDATE pbl_review_dimension SET answer = $2 WHERE id = $1 RETURNING id, artifact_id, prompt, why, answer, ordinal, created_at
`

type AnswerPblReviewDimensionParams struct {
	ID     uuid.UUID `json:"id"`
	Answer string    `json:"answer"`
}

func (q *Queries) AnswerPblReviewDimension(ctx context.Context, arg AnswerPblReviewDimensionParams) (PblReviewDimension, error) {
	row := q.db.QueryRow(ctx, answerPblReviewDimension, arg.ID, arg.Answer)
	var i PblReviewDimension
	err := row.Scan(
		&i.ID,
		&i.ArtifactID,
		&i.Prompt,
		&i.Why,
		&i.Answer,
		&i.Ordinal,
		&i.CreatedAt,
	)
	return i, err
}

const answerPblReviewMark = `-- name: AnswerPblReviewMark :one
UPDATE pbl_review_mark SET answer = $2 WHERE id = $1 RETURNING id, artifact_id, part, part_note, quote, question, answer, session_id, ordinal, created_at
`

type AnswerPblReviewMarkParams struct {
	ID     uuid.UUID `json:"id"`
	Answer string    `json:"answer"`
}

func (q *Queries) AnswerPblReviewMark(ctx context.Context, arg AnswerPblReviewMarkParams) (PblReviewMark, error) {
	row := q.db.QueryRow(ctx, answerPblReviewMark, arg.ID, arg.Answer)
	var i PblReviewMark
	err := row.Scan(
		&i.ID,
		&i.ArtifactID,
		&i.Part,
		&i.PartNote,
		&i.Quote,
		&i.Question,
		&i.Answer,
		&i.SessionID,
		&i.Ordinal,
		&i.CreatedAt,
	)
	return i, err
}

const answerPblReviewPrompt = `-- name: AnswerPblReviewPrompt :one
UPDATE pbl_review SET answer = $2, stance = $3 WHERE id = $1 RETURNING id, atom_id, prompt, anchor_kind, anchor_ref, answer, ordinal, created_at, section, stance
`

type AnswerPblReviewPromptParams struct {
	ID     uuid.UUID `json:"id"`
	Answer string    `json:"answer"`
	Stance string    `json:"stance"`
}

// stance 是「现在还这么想吗」。空白框里承认「当时没想清楚」要写一段话，
// 成本太高她于是写「挺好的」；一个可点的态度只要一下。
func (q *Queries) AnswerPblReviewPrompt(ctx context.Context, arg AnswerPblReviewPromptParams) (PblReview, error) {
	row := q.db.QueryRow(ctx, answerPblReviewPrompt, arg.ID, arg.Answer, arg.Stance)
	var i PblReview
	err := row.Scan(
		&i.ID,
		&i.AtomID,
		&i.Prompt,
		&i.AnchorKind,
		&i.AnchorRef,
		&i.Answer,
		&i.Ordinal,
		&i.CreatedAt,
		&i.Section,
		&i.Stance,
	)
	return i, err
}

const createPblReviewDimension = `-- name: CreatePblReviewDimension :one

INSERT INTO pbl_review_dimension (artifact_id, prompt, why, ordinal)
VALUES ($1, $2, $3, $4)
RETURNING id, artifact_id, prompt, why, answer, ordinal, created_at
`

type CreatePblReviewDimensionParams struct {
	ArtifactID uuid.UUID `json:"artifact_id"`
	Prompt     string    `json:"prompt"`
	Why        string    `json:"why"`
	Ordinal    int32     `json:"ordinal"`
}

// ── 阶段二：每种材料该看的几个方面 ─────────────────────────────────────
func (q *Queries) CreatePblReviewDimension(ctx context.Context, arg CreatePblReviewDimensionParams) (PblReviewDimension, error) {
	row := q.db.QueryRow(ctx, createPblReviewDimension,
		arg.ArtifactID,
		arg.Prompt,
		arg.Why,
		arg.Ordinal,
	)
	var i PblReviewDimension
	err := row.Scan(
		&i.ID,
		&i.ArtifactID,
		&i.Prompt,
		&i.Why,
		&i.Answer,
		&i.Ordinal,
		&i.CreatedAt,
	)
	return i, err
}

const createPblReviewMark = `-- name: CreatePblReviewMark :one


INSERT INTO pbl_review_mark (artifact_id, part, part_note, quote, question, ordinal, answer)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, artifact_id, part, part_note, quote, question, answer, session_id, ordinal, created_at
`

type CreatePblReviewMarkParams struct {
	ArtifactID uuid.UUID `json:"artifact_id"`
	Part       string    `json:"part"`
	PartNote   string    `json:"part_note"`
	Quote      string    `json:"quote"`
	Question   string    `json:"question"`
	Ordinal    int32     `json:"ordinal"`
	Answer     string    `json:"answer"`
}

// 审阅印记交出来的东西（阶段二），以及项目结束时的复盘（阶段六）。
// ── 阶段二：划出来的句子 ───────────────────────────────────────────────
func (q *Queries) CreatePblReviewMark(ctx context.Context, arg CreatePblReviewMarkParams) (PblReviewMark, error) {
	row := q.db.QueryRow(ctx, createPblReviewMark,
		arg.ArtifactID,
		arg.Part,
		arg.PartNote,
		arg.Quote,
		arg.Question,
		arg.Ordinal,
		arg.Answer,
	)
	var i PblReviewMark
	err := row.Scan(
		&i.ID,
		&i.ArtifactID,
		&i.Part,
		&i.PartNote,
		&i.Quote,
		&i.Question,
		&i.Answer,
		&i.SessionID,
		&i.Ordinal,
		&i.CreatedAt,
	)
	return i, err
}

const createPblReviewPrompt = `-- name: CreatePblReviewPrompt :one

INSERT INTO pbl_review (atom_id, prompt, section, anchor_kind, anchor_ref, ordinal)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, atom_id, prompt, anchor_kind, anchor_ref, answer, ordinal, created_at, section, stance
`

type CreatePblReviewPromptParams struct {
	AtomID     uuid.UUID `json:"atom_id"`
	Prompt     string    `json:"prompt"`
	Section    string    `json:"section"`
	AnchorKind string    `json:"anchor_kind"`
	AnchorRef  string    `json:"anchor_ref"`
	Ordinal    int32     `json:"ordinal"`
}

// ── 阶段六：复盘 ───────────────────────────────────────────────────────
func (q *Queries) CreatePblReviewPrompt(ctx context.Context, arg CreatePblReviewPromptParams) (PblReview, error) {
	row := q.db.QueryRow(ctx, createPblReviewPrompt,
		arg.AtomID,
		arg.Prompt,
		arg.Section,
		arg.AnchorKind,
		arg.AnchorRef,
		arg.Ordinal,
	)
	var i PblReview
	err := row.Scan(
		&i.ID,
		&i.AtomID,
		&i.Prompt,
		&i.AnchorKind,
		&i.AnchorRef,
		&i.Answer,
		&i.Ordinal,
		&i.CreatedAt,
		&i.Section,
		&i.Stance,
	)
	return i, err
}

const getPblReviewDimension = `-- name: GetPblReviewDimension :one
SELECT d.id, d.artifact_id, d.prompt, d.why, d.answer, d.ordinal, d.created_at, at.user_id, at.id AS atom_id
FROM pbl_review_dimension d
JOIN pbl_artifact ar ON ar.id = d.artifact_id
JOIN atom at ON at.id = ar.atom_id
WHERE d.id = $1
`

type GetPblReviewDimensionRow struct {
	ID         uuid.UUID `json:"id"`
	ArtifactID uuid.UUID `json:"artifact_id"`
	Prompt     string    `json:"prompt"`
	Why        string    `json:"why"`
	Answer     string    `json:"answer"`
	Ordinal    int32     `json:"ordinal"`
	CreatedAt  time.Time `json:"created_at"`
	UserID     uuid.UUID `json:"user_id"`
	AtomID     uuid.UUID `json:"atom_id"`
}

func (q *Queries) GetPblReviewDimension(ctx context.Context, id uuid.UUID) (GetPblReviewDimensionRow, error) {
	row := q.db.QueryRow(ctx, getPblReviewDimension, id)
	var i GetPblReviewDimensionRow
	err := row.Scan(
		&i.ID,
		&i.ArtifactID,
		&i.Prompt,
		&i.Why,
		&i.Answer,
		&i.Ordinal,
		&i.CreatedAt,
		&i.UserID,
		&i.AtomID,
	)
	return i, err
}

const getPblReviewMark = `-- name: GetPblReviewMark :one
SELECT m.id, m.artifact_id, m.part, m.part_note, m.quote, m.question, m.answer, m.session_id, m.ordinal, m.created_at, at.user_id, at.id AS atom_id
FROM pbl_review_mark m
JOIN pbl_artifact ar ON ar.id = m.artifact_id
JOIN atom at ON at.id = ar.atom_id
WHERE m.id = $1
`

type GetPblReviewMarkRow struct {
	ID         uuid.UUID   `json:"id"`
	ArtifactID uuid.UUID   `json:"artifact_id"`
	Part       string      `json:"part"`
	PartNote   string      `json:"part_note"`
	Quote      string      `json:"quote"`
	Question   string      `json:"question"`
	Answer     string      `json:"answer"`
	SessionID  pgtype.UUID `json:"session_id"`
	Ordinal    int32       `json:"ordinal"`
	CreatedAt  time.Time   `json:"created_at"`
	UserID     uuid.UUID   `json:"user_id"`
	AtomID     uuid.UUID   `json:"atom_id"`
}

// 归属要一路查到 atom：成果挂在项目上，项目挂在人身上。
func (q *Queries) GetPblReviewMark(ctx context.Context, id uuid.UUID) (GetPblReviewMarkRow, error) {
	row := q.db.QueryRow(ctx, getPblReviewMark, id)
	var i GetPblReviewMarkRow
	err := row.Scan(
		&i.ID,
		&i.ArtifactID,
		&i.Part,
		&i.PartNote,
		&i.Quote,
		&i.Question,
		&i.Answer,
		&i.SessionID,
		&i.Ordinal,
		&i.CreatedAt,
		&i.UserID,
		&i.AtomID,
	)
	return i, err
}

const getPblReviewPrompt = `-- name: GetPblReviewPrompt :one
SELECT p.id, p.atom_id, p.prompt, p.anchor_kind, p.anchor_ref, p.answer, p.ordinal, p.created_at, p.section, p.stance, a.user_id
FROM pbl_review p JOIN atom a ON a.id = p.atom_id
WHERE p.id = $1
`

type GetPblReviewPromptRow struct {
	ID         uuid.UUID `json:"id"`
	AtomID     uuid.UUID `json:"atom_id"`
	Prompt     string    `json:"prompt"`
	AnchorKind string    `json:"anchor_kind"`
	AnchorRef  string    `json:"anchor_ref"`
	Answer     string    `json:"answer"`
	Ordinal    int32     `json:"ordinal"`
	CreatedAt  time.Time `json:"created_at"`
	Section    string    `json:"section"`
	Stance     string    `json:"stance"`
	UserID     uuid.UUID `json:"user_id"`
}

func (q *Queries) GetPblReviewPrompt(ctx context.Context, id uuid.UUID) (GetPblReviewPromptRow, error) {
	row := q.db.QueryRow(ctx, getPblReviewPrompt, id)
	var i GetPblReviewPromptRow
	err := row.Scan(
		&i.ID,
		&i.AtomID,
		&i.Prompt,
		&i.AnchorKind,
		&i.AnchorRef,
		&i.Answer,
		&i.Ordinal,
		&i.CreatedAt,
		&i.Section,
		&i.Stance,
		&i.UserID,
	)
	return i, err
}

const linkPblReviewMarkSession = `-- name: LinkPblReviewMarkSession :one
UPDATE pbl_review_mark SET session_id = $2 WHERE id = $1 RETURNING id, artifact_id, part, part_note, quote, question, answer, session_id, ordinal, created_at
`

type LinkPblReviewMarkSessionParams struct {
	ID        uuid.UUID   `json:"id"`
	SessionID pgtype.UUID `json:"session_id"`
}

// 她点开一句话，就地开一条会话线聊它。
func (q *Queries) LinkPblReviewMarkSession(ctx context.Context, arg LinkPblReviewMarkSessionParams) (PblReviewMark, error) {
	row := q.db.QueryRow(ctx, linkPblReviewMarkSession, arg.ID, arg.SessionID)
	var i PblReviewMark
	err := row.Scan(
		&i.ID,
		&i.ArtifactID,
		&i.Part,
		&i.PartNote,
		&i.Quote,
		&i.Question,
		&i.Answer,
		&i.SessionID,
		&i.Ordinal,
		&i.CreatedAt,
	)
	return i, err
}

const listPblReviewDimensions = `-- name: ListPblReviewDimensions :many
SELECT id, artifact_id, prompt, why, answer, ordinal, created_at FROM pbl_review_dimension WHERE artifact_id = $1 ORDER BY ordinal, created_at
`

func (q *Queries) ListPblReviewDimensions(ctx context.Context, artifactID uuid.UUID) ([]PblReviewDimension, error) {
	rows, err := q.db.Query(ctx, listPblReviewDimensions, artifactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PblReviewDimension
	for rows.Next() {
		var i PblReviewDimension
		if err := rows.Scan(
			&i.ID,
			&i.ArtifactID,
			&i.Prompt,
			&i.Why,
			&i.Answer,
			&i.Ordinal,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPblReviewMarks = `-- name: ListPblReviewMarks :many
SELECT id, artifact_id, part, part_note, quote, question, answer, session_id, ordinal, created_at FROM pbl_review_mark WHERE artifact_id = $1 ORDER BY ordinal, created_at
`

func (q *Queries) ListPblReviewMarks(ctx context.Context, artifactID uuid.UUID) ([]PblReviewMark, error) {
	rows, err := q.db.Query(ctx, listPblReviewMarks, artifactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PblReviewMark
	for rows.Next() {
		var i PblReviewMark
		if err := rows.Scan(
			&i.ID,
			&i.ArtifactID,
			&i.Part,
			&i.PartNote,
			&i.Quote,
			&i.Question,
			&i.Answer,
			&i.SessionID,
			&i.Ordinal,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPblReviewPrompts = `-- name: ListPblReviewPrompts :many
SELECT id, atom_id, prompt, anchor_kind, anchor_ref, answer, ordinal, created_at, section, stance FROM pbl_review WHERE atom_id = $1 ORDER BY ordinal, created_at
`

func (q *Queries) ListPblReviewPrompts(ctx context.Context, atomID uuid.UUID) ([]PblReview, error) {
	rows, err := q.db.Query(ctx, listPblReviewPrompts, atomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PblReview
	for rows.Next() {
		var i PblReview
		if err := rows.Scan(
			&i.ID,
			&i.AtomID,
			&i.Prompt,
			&i.AnchorKind,
			&i.AnchorRef,
			&i.Answer,
			&i.Ordinal,
			&i.CreatedAt,
			&i.Section,
			&i.Stance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
