// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: pbl_site_ref.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const countPblSiteRefs = `-- name: CountPblSiteRefs :one
SELECT count(*) FROM pbl_site_ref WHERE atom_id = $1
`

func (q *Queries) CountPblSiteRefs(ctx context.Context, atomID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPblSiteRefs, atomID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPblSiteRef = `-- name: CreatePblSiteRef :one
INSERT INTO pbl_site_ref (atom_id, url, title, what, structure, best)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (atom_id, url) DO UPDATE
SET title = EXCLUDED.title,
    what = EXCLUDED.what,
    structure = EXCLUDED.structure,
    best = EXCLUDED.best
RETURNING id, atom_id, url, title, what, structure, best, she_said, created_at
`

type CreatePblSiteRefParams struct {
	AtomID    uuid.UUID `json:"atom_id"`
	Url       string    `json:"url"`
	Title     string    `json:"title"`
	What      string    `json:"what"`
	Structure string    `json:"structure"`
	Best      string    `json:"best"`
}

// 同一个项目里同一个网址只留一条。她贴第二遍是手滑，不是第二个例子——所以
// 冲突时更新印记那三句（重贴多半意味着上一次读失败了），保留她自己补的那句。
func (q *Queries) CreatePblSiteRef(ctx context.Context, arg CreatePblSiteRefParams) (PblSiteRef, error) {
	row := q.db.QueryRow(ctx, createPblSiteRef,
		arg.AtomID,
		arg.Url,
		arg.Title,
		arg.What,
		arg.Structure,
		arg.Best,
	)
	var i PblSiteRef
	err := row.Scan(
		&i.ID,
		&i.AtomID,
		&i.Url,
		&i.Title,
		&i.What,
		&i.Structure,
		&i.Best,
		&i.SheSaid,
		&i.CreatedAt,
	)
	return i, err
}

const deletePblSiteRef = `-- name: DeletePblSiteRef :exec
DELETE FROM pbl_site_ref WHERE id = $2 AND atom_id = $1
`

type DeletePblSiteRefParams struct {
	AtomID uuid.UUID `json:"atom_id"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) DeletePblSiteRef(ctx context.Context, arg DeletePblSiteRefParams) error {
	_, err := q.db.Exec(ctx, deletePblSiteRef, arg.AtomID, arg.ID)
	return err
}

const listPblSiteRefs = `-- name: ListPblSiteRefs :many
SELECT id, atom_id, url, title, what, structure, best, she_said, created_at FROM pbl_site_ref WHERE atom_id = $1 ORDER BY created_at
`

func (q *Queries) ListPblSiteRefs(ctx context.Context, atomID uuid.UUID) ([]PblSiteRef, error) {
	rows, err := q.db.Query(ctx, listPblSiteRefs, atomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PblSiteRef
	for rows.Next() {
		var i PblSiteRef
		if err := rows.Scan(
			&i.ID,
			&i.AtomID,
			&i.Url,
			&i.Title,
			&i.What,
			&i.Structure,
			&i.Best,
			&i.SheSaid,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPblSiteRefSaid = `-- name: SetPblSiteRefSaid :one
UPDATE pbl_site_ref SET she_said = $3 WHERE id = $2 AND atom_id = $1 RETURNING id, atom_id, url, title, what, structure, best, she_said, created_at
`

type SetPblSiteRefSaidParams struct {
	AtomID  uuid.UUID `json:"atom_id"`
	ID      uuid.UUID `json:"id"`
	SheSaid string    `json:"she_said"`
}

// 她在这一站上补的那一句。
func (q *Queries) SetPblSiteRefSaid(ctx context.Context, arg SetPblSiteRefSaidParams) (PblSiteRef, error) {
	row := q.db.QueryRow(ctx, setPblSiteRefSaid, arg.AtomID, arg.ID, arg.SheSaid)
	var i PblSiteRef
	err := row.Scan(
		&i.ID,
		&i.AtomID,
		&i.Url,
		&i.Title,
		&i.What,
		&i.Structure,
		&i.Best,
		&i.SheSaid,
		&i.CreatedAt,
	)
	return i, err
}
