// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: pbl_site.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const ensurePblSite = `-- name: EnsurePblSite :one
INSERT INTO pbl_site (user_id, atom_id) VALUES ($1, $2)
ON CONFLICT (user_id) DO UPDATE SET atom_id = EXCLUDED.atom_id, updated_at = now()
RETURNING user_id, atom_id, layout, layout_why, content, share_token, published_at, created_at, updated_at, palette, hero_key
`

type EnsurePblSiteParams struct {
	UserID uuid.UUID   `json:"user_id"`
	AtomID pgtype.UUID `json:"atom_id"`
}

// 第一次进主页项目时把行建出来。ON CONFLICT DO UPDATE 而不是 DO NOTHING：
// DO NOTHING 时 RETURNING 一行都不返回，调用方就得再查一次，于是「建好并读出来」
// 这件本该原子的事变成两次往返、中间有缝。这里 SET atom_id 顺带把主页认到当前
// 这个项目名下——她重建主页时是新项目、同一个页面。
func (q *Queries) EnsurePblSite(ctx context.Context, arg EnsurePblSiteParams) (PblSite, error) {
	row := q.db.QueryRow(ctx, ensurePblSite, arg.UserID, arg.AtomID)
	var i PblSite
	err := row.Scan(
		&i.UserID,
		&i.AtomID,
		&i.Layout,
		&i.LayoutWhy,
		&i.Content,
		&i.ShareToken,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Palette,
		&i.HeroKey,
	)
	return i, err
}

const getPblSite = `-- name: GetPblSite :one

SELECT user_id, atom_id, layout, layout_why, content, share_token, published_at, created_at, updated_at, palette, hero_key FROM pbl_site WHERE user_id = $1
`

// 她的主页（迁移 0117）。一个学生一行。
//
// 🚨 每个查询名都带 Pbl 前缀，理由同 pbl_project.sql：pro 与 lite 共用一个 sqlc
// 包，重名会直接盖掉 pro 的方法。
func (q *Queries) GetPblSite(ctx context.Context, userID uuid.UUID) (PblSite, error) {
	row := q.db.QueryRow(ctx, getPblSite, userID)
	var i PblSite
	err := row.Scan(
		&i.UserID,
		&i.AtomID,
		&i.Layout,
		&i.LayoutWhy,
		&i.Content,
		&i.ShareToken,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Palette,
		&i.HeroKey,
	)
	return i, err
}

const getPblSiteByShareToken = `-- name: GetPblSiteByShareToken :one
SELECT s.user_id, s.atom_id, s.layout, s.layout_why, s.content, s.share_token, s.published_at, s.created_at, s.updated_at, s.palette, s.hero_key, u.display_name
FROM pbl_site s JOIN users u ON u.id = s.user_id
WHERE s.share_token = $1 AND s.share_token IS NOT NULL
`

type GetPblSiteByShareTokenRow struct {
	UserID      uuid.UUID          `json:"user_id"`
	AtomID      pgtype.UUID        `json:"atom_id"`
	Layout      string             `json:"layout"`
	LayoutWhy   string             `json:"layout_why"`
	Content     []byte             `json:"content"`
	ShareToken  *string            `json:"share_token"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
	CreatedAt   time.Time          `json:"created_at"`
	UpdatedAt   time.Time          `json:"updated_at"`
	Palette     []byte             `json:"palette"`
	HeroKey     string             `json:"hero_key"`
	DisplayName string             `json:"display_name"`
}

// 公开路由唯一读的那一条。share_token IS NOT NULL 是多余的（NULL = NULL 永远不
// 成立），但写出来是为了让人一眼看见撤销之后这里必然落空。
func (q *Queries) GetPblSiteByShareToken(ctx context.Context, shareToken *string) (GetPblSiteByShareTokenRow, error) {
	row := q.db.QueryRow(ctx, getPblSiteByShareToken, shareToken)
	var i GetPblSiteByShareTokenRow
	err := row.Scan(
		&i.UserID,
		&i.AtomID,
		&i.Layout,
		&i.LayoutWhy,
		&i.Content,
		&i.ShareToken,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Palette,
		&i.HeroKey,
		&i.DisplayName,
	)
	return i, err
}

const getPblWebsiteProjectByUser = `-- name: GetPblWebsiteProjectByUser :one
SELECT p.atom_id, p.idea, p.kind, p.name, p.cover_ground, p.cover_glyph, p.status, p.updated_at, p.board_axes, p.finished_at, p.assigned, p.assigned_brief, a.created_at AS atom_created_at, a.last_activity_at
FROM pbl_project p JOIN atom a ON a.id = p.atom_id
WHERE a.user_id = $1 AND a.kind = 'project' AND p.kind = 'website'
ORDER BY EXISTS (SELECT 1 FROM pbl_site s WHERE s.user_id = a.user_id AND s.atom_id = p.atom_id) DESC, a.created_at ASC, a.id ASC LIMIT 1
`

type GetPblWebsiteProjectByUserRow struct {
	AtomID         uuid.UUID          `json:"atom_id"`
	Idea           string             `json:"idea"`
	Kind           string             `json:"kind"`
	Name           string             `json:"name"`
	CoverGround    string             `json:"cover_ground"`
	CoverGlyph     string             `json:"cover_glyph"`
	Status         string             `json:"status"`
	UpdatedAt      time.Time          `json:"updated_at"`
	BoardAxes      bool               `json:"board_axes"`
	FinishedAt     pgtype.Timestamptz `json:"finished_at"`
	Assigned       bool               `json:"assigned"`
	AssignedBrief  *string            `json:"assigned_brief"`
	AtomCreatedAt  time.Time          `json:"atom_created_at"`
	LastActivityAt time.Time          `json:"last_activity_at"`
}

// 她的主页项目。spec §4 的门槛靠它回答「她是不是已经有一个了」——建第二个主页
// 项目没有意义，页面是单数的。
func (q *Queries) GetPblWebsiteProjectByUser(ctx context.Context, userID uuid.UUID) (GetPblWebsiteProjectByUserRow, error) {
	row := q.db.QueryRow(ctx, getPblWebsiteProjectByUser, userID)
	var i GetPblWebsiteProjectByUserRow
	err := row.Scan(
		&i.AtomID,
		&i.Idea,
		&i.Kind,
		&i.Name,
		&i.CoverGround,
		&i.CoverGlyph,
		&i.Status,
		&i.UpdatedAt,
		&i.BoardAxes,
		&i.FinishedAt,
		&i.Assigned,
		&i.AssignedBrief,
		&i.AtomCreatedAt,
		&i.LastActivityAt,
	)
	return i, err
}

const listSiteProjectsByUser = `-- name: ListSiteProjectsByUser :many
SELECT a.id AS atom_id, p.name, p.idea, p.kind, p.status, p.assigned,
       a.created_at AS atom_created_at, a.last_activity_at
FROM pbl_project p
JOIN atom a ON a.id = p.atom_id
WHERE a.user_id = $1 AND a.kind = 'project'
  AND p.status IN ('keeping', 'review')
  AND p.kind <> 'website'
ORDER BY a.last_activity_at DESC
LIMIT 12
`

type ListSiteProjectsByUserRow struct {
	AtomID         uuid.UUID `json:"atom_id"`
	Name           string    `json:"name"`
	Idea           string    `json:"idea"`
	Kind           string    `json:"kind"`
	Status         string    `json:"status"`
	Assigned       bool      `json:"assigned"`
	AtomCreatedAt  time.Time `json:"atom_created_at"`
	LastActivityAt time.Time `json:"last_activity_at"`
}

// 🚨 主页不列自己。主页项目交付的就是这一页，给它一张卡片等于把访客指回他正在
// 读的这一页。所以 kind <> 'website' —— 这一条在 site.go 里还有一道，因为
// kind 是 0112 之后由她自己填的，可能是空串。
//
// 只取做完的（keeping）和在复盘的（review）。talking / running 是还没定型的
// 想法，把它们摆到主页上，等于替她对外宣布一件她自己都还没想清楚的事。
func (q *Queries) ListSiteProjectsByUser(ctx context.Context, userID uuid.UUID) ([]ListSiteProjectsByUserRow, error) {
	rows, err := q.db.Query(ctx, listSiteProjectsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSiteProjectsByUserRow
	for rows.Next() {
		var i ListSiteProjectsByUserRow
		if err := rows.Scan(
			&i.AtomID,
			&i.Name,
			&i.Idea,
			&i.Kind,
			&i.Status,
			&i.Assigned,
			&i.AtomCreatedAt,
			&i.LastActivityAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSiteReadingsByUser = `-- name: ListSiteReadingsByUser :many
SELECT a.id AS atom_id, r.title, r.finished_at,
       COALESCE(s.source_url, '')::text AS source_url,
       COALESCE(rep.share_token, '')::text AS share_token
FROM reading r
JOIN atom a ON a.id = r.atom_id
LEFT JOIN reading_source s ON s.atom_id = r.atom_id
LEFT JOIN atom_report rep ON rep.atom_id = a.id
WHERE a.user_id = $1 AND a.kind = 'reading' AND r.status = 'finished'
ORDER BY r.finished_at DESC NULLS LAST
LIMIT 12
`

type ListSiteReadingsByUserRow struct {
	AtomID     uuid.UUID          `json:"atom_id"`
	Title      string             `json:"title"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
	SourceUrl  string             `json:"source_url"`
	ShareToken string             `json:"share_token"`
}

// 她读完的东西。source_url 可能没有（她直接粘的正文），所以是 LEFT JOIN + 空串。
// share_token 同 ListSiteWritingsByUser：有就是已发布。
func (q *Queries) ListSiteReadingsByUser(ctx context.Context, userID uuid.UUID) ([]ListSiteReadingsByUserRow, error) {
	rows, err := q.db.Query(ctx, listSiteReadingsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSiteReadingsByUserRow
	for rows.Next() {
		var i ListSiteReadingsByUserRow
		if err := rows.Scan(
			&i.AtomID,
			&i.Title,
			&i.FinishedAt,
			&i.SourceUrl,
			&i.ShareToken,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSiteWritingsByUser = `-- name: ListSiteWritingsByUser :many
/* ── 页面上那三张列表的真实来源 ────────────────────────────────────────────
   这三个查询是这一版和原型最根本的差别：原型里 READINGS / WRITINGS / STUDENT
   是三个写死的常量，于是每个学生建出来的都是同一个人的主页。            */

SELECT a.id AS atom_id, w.title, w.finished_at,
       COALESCE(char_length(d.body), 0)::int AS words,
       COALESCE(rep.share_token, '')::text AS share_token
FROM writing w
JOIN atom a ON a.id = w.atom_id
LEFT JOIN writing_draft d ON d.atom_id = w.atom_id
LEFT JOIN atom_report rep ON rep.atom_id = a.id
WHERE a.user_id = $1 AND a.kind = 'writing' AND w.status = 'finished'
ORDER BY w.finished_at DESC NULLS LAST
LIMIT 12
`

type ListSiteWritingsByUserRow struct {
	AtomID     uuid.UUID          `json:"atom_id"`
	Title      string             `json:"title"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
	Words      int32              `json:"words"`
	ShareToken string             `json:"share_token"`
}

// 她真正写完的文章。字数取草稿正文的字符数——中文里字符数就是字数，而且它是
// 真的，不是估的。没写完的不上主页：主页是给陌生人看的，不是她的工作台。
// 2026-09-16：多带一个 share_token。**有 token 就是已发布** —— 发布这件事不
// 需要自己的一张表，一篇成稿有没有公开链接，就是它公不公开。LEFT JOIN：没生成
// 过报告的那些行照常出现在列表里，只是没有链接。
func (q *Queries) ListSiteWritingsByUser(ctx context.Context, userID uuid.UUID) ([]ListSiteWritingsByUserRow, error) {
	rows, err := q.db.Query(ctx, listSiteWritingsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSiteWritingsByUserRow
	for rows.Next() {
		var i ListSiteWritingsByUserRow
		if err := rows.Scan(
			&i.AtomID,
			&i.Title,
			&i.FinishedAt,
			&i.Words,
			&i.ShareToken,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockPblSiteOwner = `-- name: LockPblSiteOwner :one
SELECT id FROM users WHERE id = $1 FOR UPDATE
`

// Serialize starts even before the site exists. Use inside a transaction.
func (q *Queries) LockPblSiteOwner(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lockPblSiteOwner, id)
	err := row.Scan(&id)
	return id, err
}

const setPblSiteContent = `-- name: SetPblSiteContent :one
UPDATE pbl_site SET content = $2, updated_at = now()
WHERE user_id = $1 RETURNING user_id, atom_id, layout, layout_why, content, share_token, published_at, created_at, updated_at, palette, hero_key
`

type SetPblSiteContentParams struct {
	UserID  uuid.UUID `json:"user_id"`
	Content []byte    `json:"content"`
}

func (q *Queries) SetPblSiteContent(ctx context.Context, arg SetPblSiteContentParams) (PblSite, error) {
	row := q.db.QueryRow(ctx, setPblSiteContent, arg.UserID, arg.Content)
	var i PblSite
	err := row.Scan(
		&i.UserID,
		&i.AtomID,
		&i.Layout,
		&i.LayoutWhy,
		&i.Content,
		&i.ShareToken,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Palette,
		&i.HeroKey,
	)
	return i, err
}

const setPblSiteHero = `-- name: SetPblSiteHero :one
UPDATE pbl_site SET hero_key = $2, updated_at = now()
WHERE user_id = $1 RETURNING user_id, atom_id, layout, layout_why, content, share_token, published_at, created_at, updated_at, palette, hero_key
`

type SetPblSiteHeroParams struct {
	UserID  uuid.UUID `json:"user_id"`
	HeroKey string    `json:"hero_key"`
}

func (q *Queries) SetPblSiteHero(ctx context.Context, arg SetPblSiteHeroParams) (PblSite, error) {
	row := q.db.QueryRow(ctx, setPblSiteHero, arg.UserID, arg.HeroKey)
	var i PblSite
	err := row.Scan(
		&i.UserID,
		&i.AtomID,
		&i.Layout,
		&i.LayoutWhy,
		&i.Content,
		&i.ShareToken,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Palette,
		&i.HeroKey,
	)
	return i, err
}

const setPblSiteLook = `-- name: SetPblSiteLook :one
UPDATE pbl_site SET layout = $2, palette = $3, updated_at = now()
WHERE user_id = $1 RETURNING user_id, atom_id, layout, layout_why, content, share_token, published_at, created_at, updated_at, palette, hero_key
`

type SetPblSiteLookParams struct {
	UserID  uuid.UUID `json:"user_id"`
	Layout  string    `json:"layout"`
	Palette []byte    `json:"palette"`
}

// 第三关：版式（她管它叫「风格」）+ 配色。
//
// 🚨 取代了 SetPblSiteLayout。旧的那条要她为版式**写一句理由**才落定，那是
// SiteStudio 那个表单里的一格。第三关她挑的是一组从自己关键词派生出来的配色，
// 理由已经在那些关键词里了；再要一段话，就是把这一关重新变回一个输入框。
func (q *Queries) SetPblSiteLook(ctx context.Context, arg SetPblSiteLookParams) (PblSite, error) {
	row := q.db.QueryRow(ctx, setPblSiteLook, arg.UserID, arg.Layout, arg.Palette)
	var i PblSite
	err := row.Scan(
		&i.UserID,
		&i.AtomID,
		&i.Layout,
		&i.LayoutWhy,
		&i.Content,
		&i.ShareToken,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Palette,
		&i.HeroKey,
	)
	return i, err
}

const setPblSiteShare = `-- name: SetPblSiteShare :one
UPDATE pbl_site SET share_token = $2, published_at = $3, updated_at = now()
WHERE user_id = $1 RETURNING user_id, atom_id, layout, layout_why, content, share_token, published_at, created_at, updated_at, palette, hero_key
`

type SetPblSiteShareParams struct {
	UserID      uuid.UUID          `json:"user_id"`
	ShareToken  *string            `json:"share_token"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
}

// 发布与撤销走同一条语句。撤销 = 两个字段一起置 NULL，下一个请求就查不到了。
func (q *Queries) SetPblSiteShare(ctx context.Context, arg SetPblSiteShareParams) (PblSite, error) {
	row := q.db.QueryRow(ctx, setPblSiteShare, arg.UserID, arg.ShareToken, arg.PublishedAt)
	var i PblSite
	err := row.Scan(
		&i.UserID,
		&i.AtomID,
		&i.Layout,
		&i.LayoutWhy,
		&i.Content,
		&i.ShareToken,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Palette,
		&i.HeroKey,
	)
	return i, err
}
