// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: pbl_code_version.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPblCodeVersion = `-- name: CreatePblCodeVersion :one
INSERT INTO pbl_code_version(atom_id,brief_revision,brief,html,parent_version_id,feedback) VALUES($1,$2,$3,$4,$5,$6) RETURNING id, atom_id, brief_revision, brief, html, created_at, parent_version_id, feedback
`

type CreatePblCodeVersionParams struct {
	AtomID          uuid.UUID   `json:"atom_id"`
	BriefRevision   int32       `json:"brief_revision"`
	Brief           []byte      `json:"brief"`
	Html            string      `json:"html"`
	ParentVersionID pgtype.UUID `json:"parent_version_id"`
	Feedback        string      `json:"feedback"`
}

func (q *Queries) CreatePblCodeVersion(ctx context.Context, arg CreatePblCodeVersionParams) (PblCodeVersion, error) {
	row := q.db.QueryRow(ctx, createPblCodeVersion,
		arg.AtomID,
		arg.BriefRevision,
		arg.Brief,
		arg.Html,
		arg.ParentVersionID,
		arg.Feedback,
	)
	var i PblCodeVersion
	err := row.Scan(
		&i.ID,
		&i.AtomID,
		&i.BriefRevision,
		&i.Brief,
		&i.Html,
		&i.CreatedAt,
		&i.ParentVersionID,
		&i.Feedback,
	)
	return i, err
}

const getPblCodeVersion = `-- name: GetPblCodeVersion :one
SELECT id, atom_id, brief_revision, brief, html, created_at, parent_version_id, feedback FROM pbl_code_version WHERE atom_id=$1 AND id=$2
`

type GetPblCodeVersionParams struct {
	AtomID uuid.UUID `json:"atom_id"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) GetPblCodeVersion(ctx context.Context, arg GetPblCodeVersionParams) (PblCodeVersion, error) {
	row := q.db.QueryRow(ctx, getPblCodeVersion, arg.AtomID, arg.ID)
	var i PblCodeVersion
	err := row.Scan(
		&i.ID,
		&i.AtomID,
		&i.BriefRevision,
		&i.Brief,
		&i.Html,
		&i.CreatedAt,
		&i.ParentVersionID,
		&i.Feedback,
	)
	return i, err
}

const listPblCodeVersions = `-- name: ListPblCodeVersions :many
SELECT id,atom_id,brief_revision,brief,created_at,parent_version_id,feedback FROM pbl_code_version WHERE atom_id=$1 ORDER BY created_at DESC,id DESC LIMIT 50
`

type ListPblCodeVersionsRow struct {
	ID              uuid.UUID   `json:"id"`
	AtomID          uuid.UUID   `json:"atom_id"`
	BriefRevision   int32       `json:"brief_revision"`
	Brief           []byte      `json:"brief"`
	CreatedAt       time.Time   `json:"created_at"`
	ParentVersionID pgtype.UUID `json:"parent_version_id"`
	Feedback        string      `json:"feedback"`
}

func (q *Queries) ListPblCodeVersions(ctx context.Context, atomID uuid.UUID) ([]ListPblCodeVersionsRow, error) {
	rows, err := q.db.Query(ctx, listPblCodeVersions, atomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPblCodeVersionsRow
	for rows.Next() {
		var i ListPblCodeVersionsRow
		if err := rows.Scan(
			&i.ID,
			&i.AtomID,
			&i.BriefRevision,
			&i.Brief,
			&i.CreatedAt,
			&i.ParentVersionID,
			&i.Feedback,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
