// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: pbl_mission.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPblMissionItem = `-- name: CreatePblMissionItem :one

INSERT INTO pbl_mission_item (tool_id, prompt, want_kind, ordinal)
VALUES ($1, $2, $3, $4)
RETURNING id, tool_id, prompt, want_kind, ordinal, done_at, created_at, superseded_at, edited_by_student
`

type CreatePblMissionItemParams struct {
	ToolID   uuid.UUID `json:"tool_id"`
	Prompt   string    `json:"prompt"`
	WantKind string    `json:"want_kind"`
	Ordinal  int32     `json:"ordinal"`
}

// 出门前的观察清单。见 migration 0124。
func (q *Queries) CreatePblMissionItem(ctx context.Context, arg CreatePblMissionItemParams) (PblMissionItem, error) {
	row := q.db.QueryRow(ctx, createPblMissionItem,
		arg.ToolID,
		arg.Prompt,
		arg.WantKind,
		arg.Ordinal,
	)
	var i PblMissionItem
	err := row.Scan(
		&i.ID,
		&i.ToolID,
		&i.Prompt,
		&i.WantKind,
		&i.Ordinal,
		&i.DoneAt,
		&i.CreatedAt,
		&i.SupersededAt,
		&i.EditedByStudent,
	)
	return i, err
}

const createStudentPblMissionItem = `-- name: CreateStudentPblMissionItem :one
INSERT INTO pbl_mission_item (tool_id, prompt, want_kind, ordinal, edited_by_student)
VALUES ($1, $2, $3, $4, true)
RETURNING id, tool_id, prompt, want_kind, ordinal, done_at, created_at, superseded_at, edited_by_student
`

type CreateStudentPblMissionItemParams struct {
	ToolID   uuid.UUID `json:"tool_id"`
	Prompt   string    `json:"prompt"`
	WantKind string    `json:"want_kind"`
	Ordinal  int32     `json:"ordinal"`
}

func (q *Queries) CreateStudentPblMissionItem(ctx context.Context, arg CreateStudentPblMissionItemParams) (PblMissionItem, error) {
	row := q.db.QueryRow(ctx, createStudentPblMissionItem,
		arg.ToolID,
		arg.Prompt,
		arg.WantKind,
		arg.Ordinal,
	)
	var i PblMissionItem
	err := row.Scan(
		&i.ID,
		&i.ToolID,
		&i.Prompt,
		&i.WantKind,
		&i.Ordinal,
		&i.DoneAt,
		&i.CreatedAt,
		&i.SupersededAt,
		&i.EditedByStudent,
	)
	return i, err
}

const getPblMissionItem = `-- name: GetPblMissionItem :one
SELECT m.id, m.tool_id, m.prompt, m.want_kind, m.ordinal, m.done_at, m.created_at, m.superseded_at, m.edited_by_student, a.user_id
FROM pbl_mission_item m
JOIN pbl_tool_instance t ON t.id = m.tool_id
JOIN atom a ON a.id = t.atom_id
WHERE m.id = $1
`

type GetPblMissionItemRow struct {
	ID              uuid.UUID          `json:"id"`
	ToolID          uuid.UUID          `json:"tool_id"`
	Prompt          string             `json:"prompt"`
	WantKind        string             `json:"want_kind"`
	Ordinal         int32              `json:"ordinal"`
	DoneAt          pgtype.Timestamptz `json:"done_at"`
	CreatedAt       time.Time          `json:"created_at"`
	SupersededAt    pgtype.Timestamptz `json:"superseded_at"`
	EditedByStudent bool               `json:"edited_by_student"`
	UserID          uuid.UUID          `json:"user_id"`
}

// 归属一路查到人：清单挂在工具上，工具挂在项目上，项目挂在她身上。
func (q *Queries) GetPblMissionItem(ctx context.Context, id uuid.UUID) (GetPblMissionItemRow, error) {
	row := q.db.QueryRow(ctx, getPblMissionItem, id)
	var i GetPblMissionItemRow
	err := row.Scan(
		&i.ID,
		&i.ToolID,
		&i.Prompt,
		&i.WantKind,
		&i.Ordinal,
		&i.DoneAt,
		&i.CreatedAt,
		&i.SupersededAt,
		&i.EditedByStudent,
		&i.UserID,
	)
	return i, err
}

const listPblMissionItems = `-- name: ListPblMissionItems :many
SELECT id, tool_id, prompt, want_kind, ordinal, done_at, created_at, superseded_at, edited_by_student FROM pbl_mission_item WHERE tool_id = $1 ORDER BY ordinal, created_at
`

func (q *Queries) ListPblMissionItems(ctx context.Context, toolID uuid.UUID) ([]PblMissionItem, error) {
	rows, err := q.db.Query(ctx, listPblMissionItems, toolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PblMissionItem
	for rows.Next() {
		var i PblMissionItem
		if err := rows.Scan(
			&i.ID,
			&i.ToolID,
			&i.Prompt,
			&i.WantKind,
			&i.Ordinal,
			&i.DoneAt,
			&i.CreatedAt,
			&i.SupersededAt,
			&i.EditedByStudent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPblMissionItemsByAtom = `-- name: ListPblMissionItemsByAtom :many
SELECT m.id, m.tool_id, m.prompt, m.want_kind, m.ordinal, m.done_at, m.created_at, m.superseded_at, m.edited_by_student
FROM pbl_mission_item m
JOIN pbl_tool_instance t ON t.id = m.tool_id
WHERE t.atom_id = $1
ORDER BY m.created_at, m.ordinal
`

// 这个项目所有出门趟次的清单，回灌用：没做到的那几条要说给印记听。
func (q *Queries) ListPblMissionItemsByAtom(ctx context.Context, atomID uuid.UUID) ([]PblMissionItem, error) {
	rows, err := q.db.Query(ctx, listPblMissionItemsByAtom, atomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PblMissionItem
	for rows.Next() {
		var i PblMissionItem
		if err := rows.Scan(
			&i.ID,
			&i.ToolID,
			&i.Prompt,
			&i.WantKind,
			&i.Ordinal,
			&i.DoneAt,
			&i.CreatedAt,
			&i.SupersededAt,
			&i.EditedByStudent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockPblMissionTool = `-- name: LockPblMissionTool :one
SELECT id, atom_id, session_id, tool, reason, result, status, created_at, kind, accepted_at, resolved_at, student_note FROM pbl_tool_instance WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockPblMissionTool(ctx context.Context, id uuid.UUID) (PblToolInstance, error) {
	row := q.db.QueryRow(ctx, lockPblMissionTool, id)
	var i PblToolInstance
	err := row.Scan(
		&i.ID,
		&i.AtomID,
		&i.SessionID,
		&i.Tool,
		&i.Reason,
		&i.Result,
		&i.Status,
		&i.CreatedAt,
		&i.Kind,
		&i.AcceptedAt,
		&i.ResolvedAt,
		&i.StudentNote,
	)
	return i, err
}

const supersedePblMissionItem = `-- name: SupersedePblMissionItem :exec
UPDATE pbl_mission_item SET superseded_at = now() WHERE id = $1 AND superseded_at IS NULL
`

func (q *Queries) SupersedePblMissionItem(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, supersedePblMissionItem, id)
	return err
}

const supersedePblMissionItems = `-- name: SupersedePblMissionItems :exec
UPDATE pbl_mission_item SET superseded_at = now() WHERE tool_id = $1 AND superseded_at IS NULL
`

func (q *Queries) SupersedePblMissionItems(ctx context.Context, toolID uuid.UUID) error {
	_, err := q.db.Exec(ctx, supersedePblMissionItems, toolID)
	return err
}

const tickPblMissionItem = `-- name: TickPblMissionItem :one
UPDATE pbl_mission_item SET done_at = $2 WHERE id = $1 AND superseded_at IS NULL RETURNING id, tool_id, prompt, want_kind, ordinal, done_at, created_at, superseded_at, edited_by_student
`

type TickPblMissionItemParams struct {
	ID     uuid.UUID          `json:"id"`
	DoneAt pgtype.Timestamptz `json:"done_at"`
}

// 她在现场点掉一条。再点一下是取消——现场点错了不该没法反悔。
func (q *Queries) TickPblMissionItem(ctx context.Context, arg TickPblMissionItemParams) (PblMissionItem, error) {
	row := q.db.QueryRow(ctx, tickPblMissionItem, arg.ID, arg.DoneAt)
	var i PblMissionItem
	err := row.Scan(
		&i.ID,
		&i.ToolID,
		&i.Prompt,
		&i.WantKind,
		&i.Ordinal,
		&i.DoneAt,
		&i.CreatedAt,
		&i.SupersededAt,
		&i.EditedByStudent,
	)
	return i, err
}
