// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: pbl_artifact.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const acceptPblTool = `-- name: AcceptPblTool :one
UPDATE pbl_tool_instance
SET status = 'accepted', accepted_at = now()
WHERE id = $1 AND status = 'summoned'
RETURNING id, atom_id, session_id, tool, reason, result, status, created_at, kind, accepted_at, resolved_at, student_note
`

// 她答应了。对于 thinking 工具这几乎是一瞬间的事；对于 world 工具，她可能
// 就此离开几天——所以这个中间状态必须存得下来，否则「在做」和「放弃了」
// 只能靠猜。
func (q *Queries) AcceptPblTool(ctx context.Context, id uuid.UUID) (PblToolInstance, error) {
	row := q.db.QueryRow(ctx, acceptPblTool, id)
	var i PblToolInstance
	err := row.Scan(
		&i.ID,
		&i.AtomID,
		&i.SessionID,
		&i.Tool,
		&i.Reason,
		&i.Result,
		&i.Status,
		&i.CreatedAt,
		&i.Kind,
		&i.AcceptedAt,
		&i.ResolvedAt,
		&i.StudentNote,
	)
	return i, err
}

const createPblArtifact = `-- name: CreatePblArtifact :one

INSERT INTO pbl_artifact (atom_id, session_id, kind, title, payload, guessed, admits)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, atom_id, session_id, kind, title, payload, guessed, admits, verdict, why, settled_at, created_at
`

type CreatePblArtifactParams struct {
	AtomID    uuid.UUID   `json:"atom_id"`
	SessionID pgtype.UUID `json:"session_id"`
	Kind      string      `json:"kind"`
	Title     string      `json:"title"`
	Payload   []byte      `json:"payload"`
	Guessed   []byte      `json:"guessed"`
	Admits    []byte      `json:"admits"`
}

// 成果与工具。名字仍然全部带 Pbl 前缀。
func (q *Queries) CreatePblArtifact(ctx context.Context, arg CreatePblArtifactParams) (PblArtifact, error) {
	row := q.db.QueryRow(ctx, createPblArtifact,
		arg.AtomID,
		arg.SessionID,
		arg.Kind,
		arg.Title,
		arg.Payload,
		arg.Guessed,
		arg.Admits,
	)
	var i PblArtifact
	err := row.Scan(
		&i.ID,
		&i.AtomID,
		&i.SessionID,
		&i.Kind,
		&i.Title,
		&i.Payload,
		&i.Guessed,
		&i.Admits,
		&i.Verdict,
		&i.Why,
		&i.SettledAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPblArtifact = `-- name: GetPblArtifact :one
SELECT a.id, a.atom_id, a.session_id, a.kind, a.title, a.payload, a.guessed, a.admits, a.verdict, a.why, a.settled_at, a.created_at, at.user_id
FROM pbl_artifact a JOIN atom at ON at.id = a.atom_id
WHERE a.id = $1
`

type GetPblArtifactRow struct {
	ID        uuid.UUID          `json:"id"`
	AtomID    uuid.UUID          `json:"atom_id"`
	SessionID pgtype.UUID        `json:"session_id"`
	Kind      string             `json:"kind"`
	Title     string             `json:"title"`
	Payload   []byte             `json:"payload"`
	Guessed   []byte             `json:"guessed"`
	Admits    []byte             `json:"admits"`
	Verdict   *string            `json:"verdict"`
	Why       string             `json:"why"`
	SettledAt pgtype.Timestamptz `json:"settled_at"`
	CreatedAt time.Time          `json:"created_at"`
	UserID    uuid.UUID          `json:"user_id"`
}

func (q *Queries) GetPblArtifact(ctx context.Context, id uuid.UUID) (GetPblArtifactRow, error) {
	row := q.db.QueryRow(ctx, getPblArtifact, id)
	var i GetPblArtifactRow
	err := row.Scan(
		&i.ID,
		&i.AtomID,
		&i.SessionID,
		&i.Kind,
		&i.Title,
		&i.Payload,
		&i.Guessed,
		&i.Admits,
		&i.Verdict,
		&i.Why,
		&i.SettledAt,
		&i.CreatedAt,
		&i.UserID,
	)
	return i, err
}

const getPblTool = `-- name: GetPblTool :one
SELECT t.id, t.atom_id, t.session_id, t.tool, t.reason, t.result, t.status, t.created_at, t.kind, t.accepted_at, t.resolved_at, t.student_note, a.user_id
FROM pbl_tool_instance t JOIN atom a ON a.id = t.atom_id
WHERE t.id = $1
`

type GetPblToolRow struct {
	ID          uuid.UUID          `json:"id"`
	AtomID      uuid.UUID          `json:"atom_id"`
	SessionID   pgtype.UUID        `json:"session_id"`
	Tool        string             `json:"tool"`
	Reason      string             `json:"reason"`
	Result      []byte             `json:"result"`
	Status      string             `json:"status"`
	CreatedAt   time.Time          `json:"created_at"`
	Kind        string             `json:"kind"`
	AcceptedAt  pgtype.Timestamptz `json:"accepted_at"`
	ResolvedAt  pgtype.Timestamptz `json:"resolved_at"`
	StudentNote string             `json:"student_note"`
	UserID      uuid.UUID          `json:"user_id"`
}

func (q *Queries) GetPblTool(ctx context.Context, id uuid.UUID) (GetPblToolRow, error) {
	row := q.db.QueryRow(ctx, getPblTool, id)
	var i GetPblToolRow
	err := row.Scan(
		&i.ID,
		&i.AtomID,
		&i.SessionID,
		&i.Tool,
		&i.Reason,
		&i.Result,
		&i.Status,
		&i.CreatedAt,
		&i.Kind,
		&i.AcceptedAt,
		&i.ResolvedAt,
		&i.StudentNote,
		&i.UserID,
	)
	return i, err
}

const latestPblToolDrop = `-- name: LatestPblToolDrop :one
SELECT id, atom_id, tool, needs, created_at FROM pbl_tool_drop WHERE atom_id = $1 ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) LatestPblToolDrop(ctx context.Context, atomID uuid.UUID) (PblToolDrop, error) {
	row := q.db.QueryRow(ctx, latestPblToolDrop, atomID)
	var i PblToolDrop
	err := row.Scan(
		&i.ID,
		&i.AtomID,
		&i.Tool,
		&i.Needs,
		&i.CreatedAt,
	)
	return i, err
}

const listOpenPblTools = `-- name: ListOpenPblTools :many
SELECT id, atom_id, session_id, tool, reason, result, status, created_at, kind, accepted_at, resolved_at, student_note FROM pbl_tool_instance
WHERE atom_id = $1 AND status IN ('summoned', 'accepted')
ORDER BY created_at
`

// 还没了结的：刚递出的，和她答应了正在做的。
func (q *Queries) ListOpenPblTools(ctx context.Context, atomID uuid.UUID) ([]PblToolInstance, error) {
	rows, err := q.db.Query(ctx, listOpenPblTools, atomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PblToolInstance
	for rows.Next() {
		var i PblToolInstance
		if err := rows.Scan(
			&i.ID,
			&i.AtomID,
			&i.SessionID,
			&i.Tool,
			&i.Reason,
			&i.Result,
			&i.Status,
			&i.CreatedAt,
			&i.Kind,
			&i.AcceptedAt,
			&i.ResolvedAt,
			&i.StudentNote,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPblArtifacts = `-- name: ListPblArtifacts :many
SELECT id, atom_id, session_id, kind, title, payload, guessed, admits, verdict, why, settled_at, created_at FROM pbl_artifact WHERE atom_id = $1 ORDER BY created_at
`

func (q *Queries) ListPblArtifacts(ctx context.Context, atomID uuid.UUID) ([]PblArtifact, error) {
	rows, err := q.db.Query(ctx, listPblArtifacts, atomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PblArtifact
	for rows.Next() {
		var i PblArtifact
		if err := rows.Scan(
			&i.ID,
			&i.AtomID,
			&i.SessionID,
			&i.Kind,
			&i.Title,
			&i.Payload,
			&i.Guessed,
			&i.Admits,
			&i.Verdict,
			&i.Why,
			&i.SettledAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPblTools = `-- name: ListPblTools :many
SELECT id, atom_id, session_id, tool, reason, result, status, created_at, kind, accepted_at, resolved_at, student_note FROM pbl_tool_instance WHERE atom_id = $1 ORDER BY created_at
`

func (q *Queries) ListPblTools(ctx context.Context, atomID uuid.UUID) ([]PblToolInstance, error) {
	rows, err := q.db.Query(ctx, listPblTools, atomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PblToolInstance
	for rows.Next() {
		var i PblToolInstance
		if err := rows.Scan(
			&i.ID,
			&i.AtomID,
			&i.SessionID,
			&i.Tool,
			&i.Reason,
			&i.Result,
			&i.Status,
			&i.CreatedAt,
			&i.Kind,
			&i.AcceptedAt,
			&i.ResolvedAt,
			&i.StudentNote,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordPblToolDrop = `-- name: RecordPblToolDrop :exec
INSERT INTO pbl_tool_drop (atom_id, tool, needs) VALUES ($1, $2, $3)
`

type RecordPblToolDropParams struct {
	AtomID uuid.UUID `json:"atom_id"`
	Tool   string    `json:"tool"`
	Needs  string    `json:"needs"`
}

// 服务端撤掉的那件工具（migration 0134）。
//
// 闸撤掉一件工具之后，学生和印记都得知道。这两条查询是那条回路的两端：
// 撤的时候记一行，下一轮建上下文的时候读最近那一行。
func (q *Queries) RecordPblToolDrop(ctx context.Context, arg RecordPblToolDropParams) error {
	_, err := q.db.Exec(ctx, recordPblToolDrop, arg.AtomID, arg.Tool, arg.Needs)
	return err
}

const resolvePblTool = `-- name: ResolvePblTool :one
UPDATE pbl_tool_instance
SET status = $2, result = $3, student_note = $4, resolved_at = now()
WHERE id = $1 AND status IN ('summoned', 'accepted')
RETURNING id, atom_id, session_id, tool, reason, result, status, created_at, kind, accepted_at, resolved_at, student_note
`

type ResolvePblToolParams struct {
	ID          uuid.UUID `json:"id"`
	Status      string    `json:"status"`
	Result      []byte    `json:"result"`
	StudentNote string    `json:"student_note"`
}

// declined 也是一个结果：她可以不打开（铁律②），而这件事本身要留痕。
func (q *Queries) ResolvePblTool(ctx context.Context, arg ResolvePblToolParams) (PblToolInstance, error) {
	row := q.db.QueryRow(ctx, resolvePblTool,
		arg.ID,
		arg.Status,
		arg.Result,
		arg.StudentNote,
	)
	var i PblToolInstance
	err := row.Scan(
		&i.ID,
		&i.AtomID,
		&i.SessionID,
		&i.Tool,
		&i.Reason,
		&i.Result,
		&i.Status,
		&i.CreatedAt,
		&i.Kind,
		&i.AcceptedAt,
		&i.ResolvedAt,
		&i.StudentNote,
	)
	return i, err
}

const settlePblArtifact = `-- name: SettlePblArtifact :one
UPDATE pbl_artifact
SET verdict = $2, why = $3, settled_at = now()
WHERE id = $1 AND settled_at IS NULL
RETURNING id, atom_id, session_id, kind, title, payload, guessed, admits, verdict, why, settled_at, created_at
`

type SettlePblArtifactParams struct {
	ID      uuid.UUID `json:"id"`
	Verdict *string   `json:"verdict"`
	Why     string    `json:"why"`
}

// 没有理由就不落地。why 由 Go 校验（trim 之后非空），这里只落库。
func (q *Queries) SettlePblArtifact(ctx context.Context, arg SettlePblArtifactParams) (PblArtifact, error) {
	row := q.db.QueryRow(ctx, settlePblArtifact, arg.ID, arg.Verdict, arg.Why)
	var i PblArtifact
	err := row.Scan(
		&i.ID,
		&i.AtomID,
		&i.SessionID,
		&i.Kind,
		&i.Title,
		&i.Payload,
		&i.Guessed,
		&i.Admits,
		&i.Verdict,
		&i.Why,
		&i.SettledAt,
		&i.CreatedAt,
	)
	return i, err
}

const summonPblTool = `-- name: SummonPblTool :one
INSERT INTO pbl_tool_instance (atom_id, session_id, tool, reason, kind)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, atom_id, session_id, tool, reason, result, status, created_at, kind, accepted_at, resolved_at, student_note
`

type SummonPblToolParams struct {
	AtomID    uuid.UUID   `json:"atom_id"`
	SessionID pgtype.UUID `json:"session_id"`
	Tool      string      `json:"tool"`
	Reason    string      `json:"reason"`
	Kind      string      `json:"kind"`
}

func (q *Queries) SummonPblTool(ctx context.Context, arg SummonPblToolParams) (PblToolInstance, error) {
	row := q.db.QueryRow(ctx, summonPblTool,
		arg.AtomID,
		arg.SessionID,
		arg.Tool,
		arg.Reason,
		arg.Kind,
	)
	var i PblToolInstance
	err := row.Scan(
		&i.ID,
		&i.AtomID,
		&i.SessionID,
		&i.Tool,
		&i.Reason,
		&i.Result,
		&i.Status,
		&i.CreatedAt,
		&i.Kind,
		&i.AcceptedAt,
		&i.ResolvedAt,
		&i.StudentNote,
	)
	return i, err
}
