// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: project.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countActivityLogByUserProject = `-- name: CountActivityLogByUserProject :many
SELECT a.project_id, COUNT(*)::int AS n
FROM activity_log_entry a
JOIN project p ON p.id = a.project_id
WHERE p.user_id = $1
GROUP BY a.project_id
`

type CountActivityLogByUserProjectRow struct {
	ProjectID uuid.UUID `json:"project_id"`
	N         int32     `json:"n"`
}

// Per-project activity-log totals for the caller's whole project list, in ONE
// grouped pass. activity_log_entry has no user_id, so join project to scope to
// the caller; activity_log_entry is indexed on project_id.
func (q *Queries) CountActivityLogByUserProject(ctx context.Context, userID uuid.UUID) ([]CountActivityLogByUserProjectRow, error) {
	rows, err := q.db.Query(ctx, countActivityLogByUserProject, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountActivityLogByUserProjectRow
	for rows.Next() {
		var i CountActivityLogByUserProjectRow
		if err := rows.Scan(&i.ProjectID, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countLLMCallsByUserProject = `-- name: CountLLMCallsByUserProject :many
SELECT project_id, COUNT(*)::int AS n
FROM llm_call
WHERE user_id = $1 AND project_id IS NOT NULL
GROUP BY project_id
`

type CountLLMCallsByUserProjectRow struct {
	ProjectID pgtype.UUID `json:"project_id"`
	N         int32       `json:"n"`
}

// Per-project AI-call totals for the caller's whole project list, in ONE grouped
// pass (not N per-project reads). llm_call carries user_id + project_id directly
// (project_id NULL for course/chat calls, excluded here); indexed on both.
func (q *Queries) CountLLMCallsByUserProject(ctx context.Context, userID uuid.UUID) ([]CountLLMCallsByUserProjectRow, error) {
	rows, err := q.db.Query(ctx, countLLMCallsByUserProject, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountLLMCallsByUserProjectRow
	for rows.Next() {
		var i CountLLMCallsByUserProjectRow
		if err := rows.Scan(&i.ProjectID, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createProject = `-- name: CreateProject :one
INSERT INTO project (user_id, qualification, title, deadline, board_cfg_ver, cover)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, qualification, title, deadline, board_cfg_ver, status, created_at, last_active_at, studio_state, cover
`

type CreateProjectParams struct {
	UserID        uuid.UUID          `json:"user_id"`
	Qualification string             `json:"qualification"`
	Title         string             `json:"title"`
	Deadline      pgtype.Timestamptz `json:"deadline"`
	BoardCfgVer   int32              `json:"board_cfg_ver"`
	Cover         *string            `json:"cover"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.UserID,
		arg.Qualification,
		arg.Title,
		arg.Deadline,
		arg.BoardCfgVer,
		arg.Cover,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Qualification,
		&i.Title,
		&i.Deadline,
		&i.BoardCfgVer,
		&i.Status,
		&i.CreatedAt,
		&i.LastActiveAt,
		&i.StudioState,
		&i.Cover,
	)
	return i, err
}

const getProject = `-- name: GetProject :one
SELECT id, user_id, qualification, title, deadline, board_cfg_ver, status, created_at, last_active_at, studio_state, cover FROM project WHERE id = $1
`

func (q *Queries) GetProject(ctx context.Context, id uuid.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Qualification,
		&i.Title,
		&i.Deadline,
		&i.BoardCfgVer,
		&i.Status,
		&i.CreatedAt,
		&i.LastActiveAt,
		&i.StudioState,
		&i.Cover,
	)
	return i, err
}

const getStudioState = `-- name: GetStudioState :one
SELECT studio_state FROM project WHERE id = $1
`

func (q *Queries) GetStudioState(ctx context.Context, id uuid.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, getStudioState, id)
	var studio_state []byte
	err := row.Scan(&studio_state)
	return studio_state, err
}

const listProjectsByUser = `-- name: ListProjectsByUser :many
SELECT id, user_id, qualification, title, deadline, board_cfg_ver, status, created_at, last_active_at, studio_state, cover FROM project
WHERE user_id = $1
ORDER BY last_active_at DESC
`

func (q *Queries) ListProjectsByUser(ctx context.Context, userID uuid.UUID) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjectsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Qualification,
			&i.Title,
			&i.Deadline,
			&i.BoardCfgVer,
			&i.Status,
			&i.CreatedAt,
			&i.LastActiveAt,
			&i.StudioState,
			&i.Cover,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setProjectActive = `-- name: SetProjectActive :exec
UPDATE project SET status = 'active', last_active_at = now() WHERE id = $1
`

// BE5: the finish goroutine rolls status back to 'active' when report
// generation fails or is rejected, so the terminal stays retryable.
func (q *Queries) SetProjectActive(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, setProjectActive, id)
	return err
}

const setProjectEvaluating = `-- name: SetProjectEvaluating :exec
UPDATE project SET status = 'evaluating', last_active_at = now() WHERE id = $1
`

// BE5: the non-blocking finish flips status to 'evaluating' before spawning the
// detached report goroutine; a second finish while 'evaluating' is refused.
func (q *Queries) SetProjectEvaluating(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, setProjectEvaluating, id)
	return err
}

const setProjectFinished = `-- name: SetProjectFinished :exec
UPDATE project SET status = 'finished', last_active_at = now() WHERE id = $1
`

// A3 terminal: the first and only writer of project.status='finished'.
func (q *Queries) SetProjectFinished(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, setProjectFinished, id)
	return err
}

const setProjectTitle = `-- name: SetProjectTitle :exec

UPDATE project SET title = $2, last_active_at = now() WHERE id = $1
`

type SetProjectTitleParams struct {
	ID    uuid.UUID `json:"id"`
	Title string    `json:"title"`
}

// The 完成写作 milestone moved to the per-document writing_finish table
// (Phase B, writing_finish.sql); project.writing_finished_at is dropped in
// migration 0061.
// Student renames their own project (ownership is enforced in the handler).
func (q *Queries) SetProjectTitle(ctx context.Context, arg SetProjectTitleParams) error {
	_, err := q.db.Exec(ctx, setProjectTitle, arg.ID, arg.Title)
	return err
}

const setStudioState = `-- name: SetStudioState :exec
UPDATE project SET studio_state = $2, last_active_at = now() WHERE id = $1
`

type SetStudioStateParams struct {
	ID          uuid.UUID `json:"id"`
	StudioState []byte    `json:"studio_state"`
}

func (q *Queries) SetStudioState(ctx context.Context, arg SetStudioStateParams) error {
	_, err := q.db.Exec(ctx, setStudioState, arg.ID, arg.StudioState)
	return err
}

const touchProject = `-- name: TouchProject :exec
UPDATE project SET last_active_at = now() WHERE id = $1
`

func (q *Queries) TouchProject(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchProject, id)
	return err
}
