// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: reading.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createReading = `-- name: CreateReading :one
INSERT INTO reading (atom_id, title, lang) VALUES ($1, $2, $3) RETURNING atom_id, title, lang, status, updated_at, finished_at
`

type CreateReadingParams struct {
	AtomID uuid.UUID `json:"atom_id"`
	Title  string    `json:"title"`
	Lang   string    `json:"lang"`
}

func (q *Queries) CreateReading(ctx context.Context, arg CreateReadingParams) (Reading, error) {
	row := q.db.QueryRow(ctx, createReading, arg.AtomID, arg.Title, arg.Lang)
	var i Reading
	err := row.Scan(
		&i.AtomID,
		&i.Title,
		&i.Lang,
		&i.Status,
		&i.UpdatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getReading = `-- name: GetReading :one
SELECT atom_id, title, lang, status, updated_at, finished_at FROM reading WHERE atom_id = $1
`

func (q *Queries) GetReading(ctx context.Context, atomID uuid.UUID) (Reading, error) {
	row := q.db.QueryRow(ctx, getReading, atomID)
	var i Reading
	err := row.Scan(
		&i.AtomID,
		&i.Title,
		&i.Lang,
		&i.Status,
		&i.UpdatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getReadingBrief = `-- name: GetReadingBrief :one
SELECT atom_id, phase_tag, reading_reason, reading_focus, updated_at FROM reading_brief WHERE atom_id = $1
`

func (q *Queries) GetReadingBrief(ctx context.Context, atomID uuid.UUID) (ReadingBrief, error) {
	row := q.db.QueryRow(ctx, getReadingBrief, atomID)
	var i ReadingBrief
	err := row.Scan(
		&i.AtomID,
		&i.PhaseTag,
		&i.ReadingReason,
		&i.ReadingFocus,
		&i.UpdatedAt,
	)
	return i, err
}

const getReadingSource = `-- name: GetReadingSource :one
SELECT atom_id, title, body, source_url, bib, ingested_at FROM reading_source WHERE atom_id = $1
`

func (q *Queries) GetReadingSource(ctx context.Context, atomID uuid.UUID) (ReadingSource, error) {
	row := q.db.QueryRow(ctx, getReadingSource, atomID)
	var i ReadingSource
	err := row.Scan(
		&i.AtomID,
		&i.Title,
		&i.Body,
		&i.SourceUrl,
		&i.Bib,
		&i.IngestedAt,
	)
	return i, err
}

const getReadingTakeaway = `-- name: GetReadingTakeaway :one
SELECT atom_id, text, updated_at FROM reading_takeaway WHERE atom_id = $1
`

func (q *Queries) GetReadingTakeaway(ctx context.Context, atomID uuid.UUID) (ReadingTakeaway, error) {
	row := q.db.QueryRow(ctx, getReadingTakeaway, atomID)
	var i ReadingTakeaway
	err := row.Scan(&i.AtomID, &i.Text, &i.UpdatedAt)
	return i, err
}

const listReadingsByUser = `-- name: ListReadingsByUser :many
SELECT r.atom_id, r.title, r.lang, r.status, r.updated_at, r.finished_at, a.created_at AS atom_created_at
FROM reading r
JOIN atom a ON a.id = r.atom_id
WHERE a.user_id = $1 AND a.kind = 'reading'
ORDER BY a.created_at DESC
`

type ListReadingsByUserRow struct {
	AtomID        uuid.UUID          `json:"atom_id"`
	Title         string             `json:"title"`
	Lang          string             `json:"lang"`
	Status        string             `json:"status"`
	UpdatedAt     time.Time          `json:"updated_at"`
	FinishedAt    pgtype.Timestamptz `json:"finished_at"`
	AtomCreatedAt time.Time          `json:"atom_created_at"`
}

// The list the 阅读 tab shows. Joins atom for ownership + creation order.
func (q *Queries) ListReadingsByUser(ctx context.Context, userID uuid.UUID) ([]ListReadingsByUserRow, error) {
	rows, err := q.db.Query(ctx, listReadingsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReadingsByUserRow
	for rows.Next() {
		var i ListReadingsByUserRow
		if err := rows.Scan(
			&i.AtomID,
			&i.Title,
			&i.Lang,
			&i.Status,
			&i.UpdatedAt,
			&i.FinishedAt,
			&i.AtomCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameReading = `-- name: RenameReading :exec
UPDATE reading SET title = $2, updated_at = now() WHERE atom_id = $1
`

type RenameReadingParams struct {
	AtomID uuid.UUID `json:"atom_id"`
	Title  string    `json:"title"`
}

func (q *Queries) RenameReading(ctx context.Context, arg RenameReadingParams) error {
	_, err := q.db.Exec(ctx, renameReading, arg.AtomID, arg.Title)
	return err
}

const setReadingFinished = `-- name: SetReadingFinished :exec
UPDATE reading SET status = 'finished', finished_at = now(), updated_at = now()
WHERE atom_id = $1
`

func (q *Queries) SetReadingFinished(ctx context.Context, atomID uuid.UUID) error {
	_, err := q.db.Exec(ctx, setReadingFinished, atomID)
	return err
}

const upsertReadingBrief = `-- name: UpsertReadingBrief :one
INSERT INTO reading_brief (atom_id, phase_tag, reading_reason, reading_focus)
VALUES ($1, $2, $3, $4)
ON CONFLICT (atom_id) DO UPDATE
  SET phase_tag = EXCLUDED.phase_tag,
      reading_reason = EXCLUDED.reading_reason,
      reading_focus = EXCLUDED.reading_focus,
      updated_at = now()
RETURNING atom_id, phase_tag, reading_reason, reading_focus, updated_at
`

type UpsertReadingBriefParams struct {
	AtomID        uuid.UUID `json:"atom_id"`
	PhaseTag      *string   `json:"phase_tag"`
	ReadingReason string    `json:"reading_reason"`
	ReadingFocus  string    `json:"reading_focus"`
}

func (q *Queries) UpsertReadingBrief(ctx context.Context, arg UpsertReadingBriefParams) (ReadingBrief, error) {
	row := q.db.QueryRow(ctx, upsertReadingBrief,
		arg.AtomID,
		arg.PhaseTag,
		arg.ReadingReason,
		arg.ReadingFocus,
	)
	var i ReadingBrief
	err := row.Scan(
		&i.AtomID,
		&i.PhaseTag,
		&i.ReadingReason,
		&i.ReadingFocus,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertReadingSource = `-- name: UpsertReadingSource :one
INSERT INTO reading_source (atom_id, title, body, source_url)
VALUES ($1, $2, $3, $4)
ON CONFLICT (atom_id) DO UPDATE
  SET title = EXCLUDED.title, body = EXCLUDED.body,
      source_url = EXCLUDED.source_url, ingested_at = now()
RETURNING atom_id, title, body, source_url, bib, ingested_at
`

type UpsertReadingSourceParams struct {
	AtomID    uuid.UUID `json:"atom_id"`
	Title     string    `json:"title"`
	Body      string    `json:"body"`
	SourceUrl *string   `json:"source_url"`
}

func (q *Queries) UpsertReadingSource(ctx context.Context, arg UpsertReadingSourceParams) (ReadingSource, error) {
	row := q.db.QueryRow(ctx, upsertReadingSource,
		arg.AtomID,
		arg.Title,
		arg.Body,
		arg.SourceUrl,
	)
	var i ReadingSource
	err := row.Scan(
		&i.AtomID,
		&i.Title,
		&i.Body,
		&i.SourceUrl,
		&i.Bib,
		&i.IngestedAt,
	)
	return i, err
}

const upsertReadingTakeaway = `-- name: UpsertReadingTakeaway :one
INSERT INTO reading_takeaway (atom_id, text)
VALUES ($1, $2)
ON CONFLICT (atom_id) DO UPDATE SET text = EXCLUDED.text, updated_at = now()
RETURNING atom_id, text, updated_at
`

type UpsertReadingTakeawayParams struct {
	AtomID uuid.UUID `json:"atom_id"`
	Text   string    `json:"text"`
}

func (q *Queries) UpsertReadingTakeaway(ctx context.Context, arg UpsertReadingTakeawayParams) (ReadingTakeaway, error) {
	row := q.db.QueryRow(ctx, upsertReadingTakeaway, arg.AtomID, arg.Text)
	var i ReadingTakeaway
	err := row.Scan(&i.AtomID, &i.Text, &i.UpdatedAt)
	return i, err
}
