// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: revision_checkpoint.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const insertRevisionCheckpoint = `-- name: InsertRevisionCheckpoint :one
INSERT INTO revision_checkpoint (project_id, artifact_type, trigger, content, content_hash, feedback_ref)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, project_id, artifact_type, trigger, content, content_hash, feedback_ref, created_at
`

type InsertRevisionCheckpointParams struct {
	ProjectID    uuid.UUID   `json:"project_id"`
	ArtifactType string      `json:"artifact_type"`
	Trigger      string      `json:"trigger"`
	Content      []byte      `json:"content"`
	ContentHash  string      `json:"content_hash"`
	FeedbackRef  pgtype.UUID `json:"feedback_ref"`
}

func (q *Queries) InsertRevisionCheckpoint(ctx context.Context, arg InsertRevisionCheckpointParams) (RevisionCheckpoint, error) {
	row := q.db.QueryRow(ctx, insertRevisionCheckpoint,
		arg.ProjectID,
		arg.ArtifactType,
		arg.Trigger,
		arg.Content,
		arg.ContentHash,
		arg.FeedbackRef,
	)
	var i RevisionCheckpoint
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ArtifactType,
		&i.Trigger,
		&i.Content,
		&i.ContentHash,
		&i.FeedbackRef,
		&i.CreatedAt,
	)
	return i, err
}

const listRevisionCheckpoints = `-- name: ListRevisionCheckpoints :many
SELECT id, project_id, artifact_type, trigger, content, content_hash, feedback_ref, created_at FROM revision_checkpoint
WHERE project_id = $1
ORDER BY created_at, artifact_type
`

func (q *Queries) ListRevisionCheckpoints(ctx context.Context, projectID uuid.UUID) ([]RevisionCheckpoint, error) {
	rows, err := q.db.Query(ctx, listRevisionCheckpoints, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RevisionCheckpoint
	for rows.Next() {
		var i RevisionCheckpoint
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ArtifactType,
			&i.Trigger,
			&i.Content,
			&i.ContentHash,
			&i.FeedbackRef,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
