// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: tasks.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (user_id, title, seed)
VALUES ($1, $2, $3)
RETURNING id, user_id, title, seed, status, created_at, last_active_at
`

type CreateTaskParams struct {
	UserID uuid.UUID `json:"user_id"`
	Title  string    `json:"title"`
	Seed   *string   `json:"seed"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask, arg.UserID, arg.Title, arg.Seed)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Seed,
		&i.Status,
		&i.CreatedAt,
		&i.LastActiveAt,
	)
	return i, err
}

const getTask = `-- name: GetTask :one
SELECT id, user_id, title, seed, status, created_at, last_active_at FROM tasks WHERE id = $1
`

// Still used by loadOwnedTask (api/tasks.go) for the surviving
// /api/v1/tasks/{id}/evaluate + /evaluation routes, and directly by fixtures.
func (q *Queries) GetTask(ctx context.Context, id uuid.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Seed,
		&i.Status,
		&i.CreatedAt,
		&i.LastActiveAt,
	)
	return i, err
}

const markTaskEvaluated = `-- name: MarkTaskEvaluated :exec
UPDATE tasks SET status = 'evaluated' WHERE id = $1
`

func (q *Queries) MarkTaskEvaluated(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markTaskEvaluated, id)
	return err
}
