// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: teacher_weekly.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const appendClassWeeklyProseCards = `-- name: AppendClassWeeklyProseCards :exec
UPDATE class_weekly_prose
SET cards = cards || $1::jsonb, updated_at = now()
WHERE class_id = $2 AND week_start = $3
`

type AppendClassWeeklyProseCardsParams struct {
	Cards     []byte      `json:"cards"`
	ClassID   uuid.UUID   `json:"class_id"`
	WeekStart pgtype.Date `json:"week_start"`
}

// The top-up (DEC-6): appends newly-composed card prose to an existing row.
// comment/depth_note/autonomy_note are never touched — nothing already written
// is ever rewritten.
func (q *Queries) AppendClassWeeklyProseCards(ctx context.Context, arg AppendClassWeeklyProseCardsParams) error {
	_, err := q.db.Exec(ctx, appendClassWeeklyProseCards, arg.Cards, arg.ClassID, arg.WeekStart)
	return err
}

const getClassWeekStats = `-- name: GetClassWeekStats :one
WITH members AS (
  SELECT u.id
  FROM enrollments e JOIN users u ON u.id = e.user_id
  WHERE e.class_id = $3 AND e.role_in_class = 'student'
)
SELECT
  (SELECT count(*) FROM members)::int AS class_size,
  (SELECT count(DISTINCT ev.user_id) FROM event ev JOIN members m ON m.id = ev.user_id
     WHERE ev.created_at >= $1 AND ev.created_at < $2)::int AS active_students,
  (SELECT count(*) FROM event ev JOIN members m ON m.id = ev.user_id
     WHERE ev.created_at >= $1 AND ev.created_at < $2
       AND ev.type IN ('prompt_sent','course_message'))::int AS turns,
  (SELECT count(DISTINCT (ev.user_id, ev.course_id, ev.payload->>'ordinal'))
     FROM event ev JOIN members m ON m.id = ev.user_id
     WHERE ev.created_at >= $1 AND ev.created_at < $2
       AND ev.type = 'step_viewed')::int AS course_steps,
  (SELECT count(*) FROM evaluation_report er JOIN project p ON p.id = er.project_id
     JOIN members m ON m.id = p.user_id
     WHERE er.status = 'ready' AND er.created_at >= $1 AND er.created_at < $2)::int AS reports
`

type GetClassWeekStatsParams struct {
	WeekStart time.Time `json:"week_start"`
	WeekEnd   time.Time `json:"week_end"`
	ClassID   uuid.UUID `json:"class_id"`
}

type GetClassWeekStatsRow struct {
	ClassSize      int32 `json:"class_size"`
	ActiveStudents int32 `json:"active_students"`
	Turns          int32 `json:"turns"`
	CourseSteps    int32 `json:"course_steps"`
	Reports        int32 `json:"reports"`
}

// The four stat cards for one half-open window. 对话轮次 口径 is D1's, verbatim:
// prompt_sent (studio AND chat) + course_message. Course steps count DISTINCT
// (student, course, ordinal) so a re-render cannot inflate the number.
func (q *Queries) GetClassWeekStats(ctx context.Context, arg GetClassWeekStatsParams) (GetClassWeekStatsRow, error) {
	row := q.db.QueryRow(ctx, getClassWeekStats, arg.WeekStart, arg.WeekEnd, arg.ClassID)
	var i GetClassWeekStatsRow
	err := row.Scan(
		&i.ClassSize,
		&i.ActiveStudents,
		&i.Turns,
		&i.CourseSteps,
		&i.Reports,
	)
	return i, err
}

const getClassWeeklyProse = `-- name: GetClassWeeklyProse :one

SELECT comment, depth_note, autonomy_note, cards, created_at
FROM class_weekly_prose
WHERE class_id = $1 AND week_start = $2
`

type GetClassWeeklyProseParams struct {
	ClassID   uuid.UUID   `json:"class_id"`
	WeekStart pgtype.Date `json:"week_start"`
}

type GetClassWeeklyProseRow struct {
	Comment      string    `json:"comment"`
	DepthNote    string    `json:"depth_note"`
	AutonomyNote string    `json:"autonomy_note"`
	Cards        []byte    `json:"cards"`
	CreatedAt    time.Time `json:"created_at"`
}

// D2 weekly-report reads. Class-scoped like teacher.sql: the handler has
// already authorised the class via assertTeacherOwnsClass, and every student
// query JOINs enrollments with role_in_class='student'. No writes except the
// prose row, which holds no student data beyond names already on screen.
func (q *Queries) GetClassWeeklyProse(ctx context.Context, arg GetClassWeeklyProseParams) (GetClassWeeklyProseRow, error) {
	row := q.db.QueryRow(ctx, getClassWeeklyProse, arg.ClassID, arg.WeekStart)
	var i GetClassWeeklyProseRow
	err := row.Scan(
		&i.Comment,
		&i.DepthNote,
		&i.AutonomyNote,
		&i.Cards,
		&i.CreatedAt,
	)
	return i, err
}

const insertClassWeeklyProse = `-- name: InsertClassWeeklyProse :exec
INSERT INTO class_weekly_prose (class_id, week_start, comment, depth_note, autonomy_note, cards)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (class_id, week_start) DO NOTHING
`

type InsertClassWeeklyProseParams struct {
	ClassID      uuid.UUID   `json:"class_id"`
	WeekStart    pgtype.Date `json:"week_start"`
	Comment      string      `json:"comment"`
	DepthNote    string      `json:"depth_note"`
	AutonomyNote string      `json:"autonomy_note"`
	Cards        []byte      `json:"cards"`
}

// First-open-wins (DEC-2): a concurrent second generation is discarded, and
// the caller re-reads to return the winner's row.
func (q *Queries) InsertClassWeeklyProse(ctx context.Context, arg InsertClassWeeklyProseParams) error {
	_, err := q.db.Exec(ctx, insertClassWeeklyProse,
		arg.ClassID,
		arg.WeekStart,
		arg.Comment,
		arg.DepthNote,
		arg.AutonomyNote,
		arg.Cards,
	)
	return err
}

const listClassStudentWeekActivity = `-- name: ListClassStudentWeekActivity :many
WITH latest_reports AS (
  SELECT DISTINCT ON (p.user_id) p.user_id, er.project_id,
         er.report->'abstract'->>'overview' AS overview
  FROM evaluation_report er JOIN project p ON p.id = er.project_id
  WHERE er.status = 'ready'
  ORDER BY p.user_id, er.created_at DESC
)
SELECT
  u.id AS user_id, u.display_name, u.avatar_color,
  COALESCE(cur.active_days, 0)::int AS active_days,
  COALESCE(cur.turns, 0)::int       AS turns,
  COALESCE(prv.active_days, 0)::int AS prev_active_days,
  COALESCE(rep.n, 0)::int           AS reports_this_week,
  COALESCE(prior.n, 0)::int         AS prior_reports,
  lr.project_id                     AS latest_report_project_id,
  lr.overview                       AS latest_report_overview
FROM enrollments e
JOIN users u ON u.id = e.user_id
LEFT JOIN LATERAL (
  SELECT COUNT(DISTINCT (ev.created_at AT TIME ZONE 'UTC')::date) AS active_days,
         COUNT(*) FILTER (WHERE ev.type IN ('prompt_sent','course_message')) AS turns
  FROM event ev
  WHERE ev.user_id = u.id AND ev.created_at >= $1 AND ev.created_at < $2
) cur ON true
LEFT JOIN LATERAL (
  SELECT COUNT(DISTINCT (ev.created_at AT TIME ZONE 'UTC')::date) AS active_days
  FROM event ev
  WHERE ev.user_id = u.id AND ev.created_at >= $3 AND ev.created_at < $4
) prv ON true
LEFT JOIN LATERAL (
  SELECT count(*) AS n FROM evaluation_report er JOIN project p ON p.id = er.project_id
  WHERE p.user_id = u.id AND er.status = 'ready' AND er.created_at >= $1 AND er.created_at < $2
) rep ON true
LEFT JOIN LATERAL (
  SELECT count(*) AS n FROM evaluation_report er JOIN project p ON p.id = er.project_id
  WHERE p.user_id = u.id AND er.status = 'ready' AND er.created_at < $1
) prior ON true
LEFT JOIN latest_reports lr ON lr.user_id = u.id
WHERE e.class_id = $5 AND e.role_in_class = 'student'
ORDER BY u.display_name
`

type ListClassStudentWeekActivityParams struct {
	WeekStart time.Time `json:"week_start"`
	WeekEnd   time.Time `json:"week_end"`
	PrevStart time.Time `json:"prev_start"`
	PrevEnd   time.Time `json:"prev_end"`
	ClassID   uuid.UUID `json:"class_id"`
}

type ListClassStudentWeekActivityRow struct {
	UserID                uuid.UUID   `json:"user_id"`
	DisplayName           string      `json:"display_name"`
	AvatarColor           string      `json:"avatar_color"`
	ActiveDays            int32       `json:"active_days"`
	Turns                 int32       `json:"turns"`
	PrevActiveDays        int32       `json:"prev_active_days"`
	ReportsThisWeek       int32       `json:"reports_this_week"`
	PriorReports          int32       `json:"prior_reports"`
	LatestReportProjectID pgtype.UUID `json:"latest_report_project_id"`
	LatestReportOverview  interface{} `json:"latest_report_overview"`
}

// Per-student activity for a COMPLETED week + the full prior week, plus report
// counts (this week / before this week) and the latest ready report's project id
// for the card link. All no-LLM; no student_evaluation.
//
// latest_report_project_id is joined via a plain (non-LATERAL) LEFT JOIN to a
// CTE, not a LATERAL "ON true" subselect or a scalar subquery in the SELECT
// list: sqlc's nullability inference does not propagate "this join might not
// match" through those two shapes (it kept typing the column as the
// underlying NOT NULL evaluation_report.project_id, which pgx then fails to
// scan when a student has no ready report). A CTE joined by an ordinary
// LEFT JOIN ... ON condition is the shape sqlc reliably marks nullable
// (-> pgtype.UUID).
func (q *Queries) ListClassStudentWeekActivity(ctx context.Context, arg ListClassStudentWeekActivityParams) ([]ListClassStudentWeekActivityRow, error) {
	rows, err := q.db.Query(ctx, listClassStudentWeekActivity,
		arg.WeekStart,
		arg.WeekEnd,
		arg.PrevStart,
		arg.PrevEnd,
		arg.ClassID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListClassStudentWeekActivityRow
	for rows.Next() {
		var i ListClassStudentWeekActivityRow
		if err := rows.Scan(
			&i.UserID,
			&i.DisplayName,
			&i.AvatarColor,
			&i.ActiveDays,
			&i.Turns,
			&i.PrevActiveDays,
			&i.ReportsThisWeek,
			&i.PriorReports,
			&i.LatestReportProjectID,
			&i.LatestReportOverview,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
