// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: teacher.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getClassLiveHeader = `-- name: GetClassLiveHeader :one
WITH members AS (
  SELECT u.id FROM enrollments e JOIN users u ON u.id = e.user_id
  WHERE e.class_id = $3 AND e.role_in_class = 'student'
)
SELECT
  (SELECT count(*) FROM members)::int AS class_size,
  (SELECT count(DISTINCT ev.user_id) FROM event ev JOIN members m ON m.id = ev.user_id
     WHERE ev.created_at >= $1 AND ev.created_at < $2)::int AS active_students,
  (SELECT count(*) FROM event ev JOIN members m ON m.id = ev.user_id
     WHERE ev.created_at >= $1 AND ev.created_at < $2
       AND ev.type IN ('prompt_sent','course_message'))::int AS turns,
  (SELECT count(*) FROM project p JOIN members m ON m.id = p.user_id
     WHERE p.status = 'active')::int AS active_projects,
  (SELECT count(*) FROM evaluation_report er JOIN project p ON p.id = er.project_id
     JOIN members m ON m.id = p.user_id
     WHERE er.status = 'ready' AND er.created_at >= $1 AND er.created_at < $2)::int AS reports
`

type GetClassLiveHeaderParams struct {
	WeekStart time.Time `json:"week_start"`
	WeekEnd   time.Time `json:"week_end"`
	ClassID   uuid.UUID `json:"class_id"`
}

type GetClassLiveHeaderRow struct {
	ClassSize      int32 `json:"class_size"`
	ActiveStudents int32 `json:"active_students"`
	Turns          int32 `json:"turns"`
	ActiveProjects int32 `json:"active_projects"`
	Reports        int32 `json:"reports"`
}

// Live class-level snapshot for View B's header. active_students/turns/reports
// are windowed (the current in-progress week); active_projects is current state.
func (q *Queries) GetClassLiveHeader(ctx context.Context, arg GetClassLiveHeaderParams) (GetClassLiveHeaderRow, error) {
	row := q.db.QueryRow(ctx, getClassLiveHeader, arg.WeekStart, arg.WeekEnd, arg.ClassID)
	var i GetClassLiveHeaderRow
	err := row.Scan(
		&i.ClassSize,
		&i.ActiveStudents,
		&i.Turns,
		&i.ActiveProjects,
		&i.Reports,
	)
	return i, err
}

const getLatestReportScoresForStudent = `-- name: GetLatestReportScoresForStudent :one
SELECT se.scores
FROM student_evaluation se
WHERE se.user_id = $1
ORDER BY se.created_at DESC
LIMIT 1
`

// Latest report scores for one student across ALL scopes (project/course/chat),
// for D/A head-badge derivation on the student-detail page. (The roster view
// no longer derives a D/A badge — see ListClassRosterCounts — but the
// student-detail head still does, until Task 4.)
func (q *Queries) GetLatestReportScoresForStudent(ctx context.Context, userID uuid.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, getLatestReportScoresForStudent, userID)
	var scores []byte
	err := row.Scan(&scores)
	return scores, err
}

const getStudentUsageForTeacher = `-- name: GetStudentUsageForTeacher :one
SELECT
  COUNT(DISTINCT (ev.created_at AT TIME ZONE 'UTC')::date) AS active_days,
  COUNT(*) FILTER (WHERE ev.type IN ('prompt_sent','course_message')) AS turns
FROM event ev
WHERE ev.user_id = $1
  AND ev.created_at >= $2 AND ev.created_at < $3
`

type GetStudentUsageForTeacherParams struct {
	UserID    uuid.UUID `json:"user_id"`
	WeekStart time.Time `json:"week_start"`
	WeekEnd   time.Time `json:"week_end"`
}

type GetStudentUsageForTeacherRow struct {
	ActiveDays int64 `json:"active_days"`
	Turns      int64 `json:"turns"`
}

// This-week active days + turns for one student (used by the student detail head).
// Bucketed via `AT TIME ZONE 'UTC'` (not the DB session's TimeZone GUC, which
// may differ from the app's) so a 7x24h window (weekWindow, UTC-pinned) can
// never span more than 7 distinct dates.
func (q *Queries) GetStudentUsageForTeacher(ctx context.Context, arg GetStudentUsageForTeacherParams) (GetStudentUsageForTeacherRow, error) {
	row := q.db.QueryRow(ctx, getStudentUsageForTeacher, arg.UserID, arg.WeekStart, arg.WeekEnd)
	var i GetStudentUsageForTeacherRow
	err := row.Scan(&i.ActiveDays, &i.Turns)
	return i, err
}

const getStudentWeekStats = `-- name: GetStudentWeekStats :one
SELECT
  COUNT(DISTINCT (ev.created_at AT TIME ZONE 'UTC')::date)::int AS active_days,
  COUNT(*) FILTER (WHERE ev.type IN ('prompt_sent','course_message'))::int AS turns,
  (SELECT count(*) FROM student_evaluation se
     WHERE se.user_id = $1
       AND se.created_at >= $2 AND se.created_at < $3)::int AS reports,
  COUNT(DISTINCT (ev.course_id, ev.payload->>'ordinal'))
    FILTER (WHERE ev.type = 'step_viewed')::int AS course_steps
FROM event ev
WHERE ev.user_id = $1
  AND ev.created_at >= $2 AND ev.created_at < $3
`

type GetStudentWeekStatsParams struct {
	UserID    uuid.UUID `json:"user_id"`
	WeekStart time.Time `json:"week_start"`
	WeekEnd   time.Time `json:"week_end"`
}

type GetStudentWeekStatsRow struct {
	ActiveDays  int32 `json:"active_days"`
	Turns       int32 `json:"turns"`
	Reports     int32 `json:"reports"`
	CourseSteps int32 `json:"course_steps"`
}

// One student's four stage-card counts for a half-open window. Same口径 as
// GetClassWeekStats: active days bucketed via AT TIME ZONE 'UTC'; turns =
// prompt_sent + course_message; reports = student_evaluation rows; course_steps
// = DISTINCT (course, ordinal) step_viewed. Tenancy is the handler's
// (authTeacherStudent has proven this student is in the teacher's class).
func (q *Queries) GetStudentWeekStats(ctx context.Context, arg GetStudentWeekStatsParams) (GetStudentWeekStatsRow, error) {
	row := q.db.QueryRow(ctx, getStudentWeekStats, arg.UserID, arg.WeekStart, arg.WeekEnd)
	var i GetStudentWeekStatsRow
	err := row.Scan(
		&i.ActiveDays,
		&i.Turns,
		&i.Reports,
		&i.CourseSteps,
	)
	return i, err
}

const listClassRosterCounts = `-- name: ListClassRosterCounts :many

SELECT
  u.id, u.display_name, u.avatar_color,
  COALESCE(ap.n, 0)::int AS active_projects,
  COALESCE(rc.n, 0)::int AS report_count,
  COALESCE(cf.n, 0)::int AS courses_finished
FROM enrollments e
JOIN users u ON u.id = e.user_id
LEFT JOIN LATERAL (
  SELECT count(*) AS n FROM project p WHERE p.user_id = u.id AND p.status = 'active'
) ap ON true
LEFT JOIN LATERAL (
  SELECT count(*) AS n FROM evaluation_report er JOIN project p ON p.id = er.project_id
  WHERE p.user_id = u.id AND er.status = 'ready'
) rc ON true
LEFT JOIN LATERAL (
  SELECT count(*) AS n FROM course_progress cp WHERE cp.user_id = u.id AND cp.completed_at IS NOT NULL
) cf ON true
WHERE e.class_id = $1 AND e.role_in_class = 'student'
ORDER BY u.display_name
`

type ListClassRosterCountsRow struct {
	ID              uuid.UUID `json:"id"`
	DisplayName     string    `json:"display_name"`
	AvatarColor     string    `json:"avatar_color"`
	ActiveProjects  int32     `json:"active_projects"`
	ReportCount     int32     `json:"report_count"`
	CoursesFinished int32     `json:"courses_finished"`
}

// Teacher read-path (Spec D1). Every query is class-scoped: it JOINs enrollments
// with role_in_class='student' so a teacher can only read members of the class
// the handler already authorised via assertTeacherOwnsClass. No writes.
// One row per student: current-state activity counts, all no-LLM. active
// projects = status='active'; report count = ready evaluation_report on the
// student's projects; courses finished = course_progress.completed_at set.
// Class-scoped like every teacher query (enrollments + role_in_class='student').
func (q *Queries) ListClassRosterCounts(ctx context.Context, classID uuid.UUID) ([]ListClassRosterCountsRow, error) {
	rows, err := q.db.Query(ctx, listClassRosterCounts, classID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListClassRosterCountsRow
	for rows.Next() {
		var i ListClassRosterCountsRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.AvatarColor,
			&i.ActiveProjects,
			&i.ReportCount,
			&i.CoursesFinished,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudentProjectsForTeacher = `-- name: ListStudentProjectsForTeacher :many
SELECT p.id, p.title, p.last_active_at,
       EXISTS (SELECT 1 FROM evaluations ev WHERE ev.project_id = p.id) AS has_report
FROM project p
WHERE p.user_id = $1
ORDER BY p.last_active_at DESC NULLS LAST
`

type ListStudentProjectsForTeacherRow struct {
	ID           uuid.UUID `json:"id"`
	Title        string    `json:"title"`
	LastActiveAt time.Time `json:"last_active_at"`
	HasReport    bool      `json:"has_report"`
}

// All of a student's projects (title/date + whether a report exists), so
// in-progress projects without a report still appear in the records list.
func (q *Queries) ListStudentProjectsForTeacher(ctx context.Context, userID uuid.UUID) ([]ListStudentProjectsForTeacherRow, error) {
	rows, err := q.db.Query(ctx, listStudentProjectsForTeacher, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStudentProjectsForTeacherRow
	for rows.Next() {
		var i ListStudentProjectsForTeacherRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.LastActiveAt,
			&i.HasReport,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudentReportsForTeacher = `-- name: ListStudentReportsForTeacher :many
SELECT surface, scope_id, label, sublabel, created_at
FROM (
  (SELECT DISTINCT ON (e.project_id)
     'project'::text AS surface, e.project_id AS scope_id,
     p.title AS label, NULL::text AS sublabel, e.created_at AS created_at
   FROM evaluations e JOIN project p ON p.id = e.project_id
   WHERE e.project_id IS NOT NULL AND p.user_id = $1
   ORDER BY e.project_id, e.created_at DESC)
  UNION ALL
  (SELECT DISTINCT ON (e.thread_id)
     'chat'::text, e.thread_id, t.title, NULL::text, e.created_at
   FROM evaluations e JOIN chat_thread t ON t.id = e.thread_id
   WHERE e.thread_id IS NOT NULL AND t.user_id = $1
   ORDER BY e.thread_id, e.created_at DESC)
) rows
ORDER BY created_at DESC
`

type ListStudentReportsForTeacherRow struct {
	Surface   string      `json:"surface"`
	ScopeID   pgtype.UUID `json:"scope_id"`
	Label     string      `json:"label"`
	Sublabel  *string     `json:"sublabel"`
	CreatedAt time.Time   `json:"created_at"`
}

// Every report one class member owns, across both remaining scopes,
// newest-first, one row per scope. A teacher-scoped read of the student's
// stored evaluations, filtered by "this user AND a student member
// of this class". The course-session arm is retired along with course_session
// itself (migration 0050, course v2, no back-compat).
func (q *Queries) ListStudentReportsForTeacher(ctx context.Context, userID uuid.UUID) ([]ListStudentReportsForTeacherRow, error) {
	rows, err := q.db.Query(ctx, listStudentReportsForTeacher, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStudentReportsForTeacherRow
	for rows.Next() {
		var i ListStudentReportsForTeacherRow
		if err := rows.Scan(
			&i.Surface,
			&i.ScopeID,
			&i.Label,
			&i.Sublabel,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
