// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: teacher.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getLatestReportScoresForStudent = `-- name: GetLatestReportScoresForStudent :one
SELECT se.scores
FROM student_evaluation se
WHERE se.user_id = $1
ORDER BY se.created_at DESC
LIMIT 1
`

// Latest report scores for one student across ALL scopes (project/course/chat),
// for D/A head-badge derivation on the student-detail page. Mirrors the lateral
// inside ListClassRosterReport so the roster badge and the head badge can never
// disagree.
func (q *Queries) GetLatestReportScoresForStudent(ctx context.Context, userID uuid.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, getLatestReportScoresForStudent, userID)
	var scores []byte
	err := row.Scan(&scores)
	return scores, err
}

const getStudentUsageForTeacher = `-- name: GetStudentUsageForTeacher :one
SELECT
  COUNT(DISTINCT (ev.created_at AT TIME ZONE 'UTC')::date) AS active_days,
  COUNT(*) FILTER (WHERE ev.type IN ('prompt_sent','course_message')) AS turns
FROM event ev
WHERE ev.user_id = $1
  AND ev.created_at >= $2 AND ev.created_at < $3
`

type GetStudentUsageForTeacherParams struct {
	UserID    uuid.UUID `json:"user_id"`
	WeekStart time.Time `json:"week_start"`
	WeekEnd   time.Time `json:"week_end"`
}

type GetStudentUsageForTeacherRow struct {
	ActiveDays int64 `json:"active_days"`
	Turns      int64 `json:"turns"`
}

// This-week active days + turns for one student (used by the student detail head).
// Bucketed via `AT TIME ZONE 'UTC'` (not the DB session's TimeZone GUC, which
// may differ from the app's) so a 7x24h window (weekWindow, UTC-pinned) can
// never span more than 7 distinct dates.
func (q *Queries) GetStudentUsageForTeacher(ctx context.Context, arg GetStudentUsageForTeacherParams) (GetStudentUsageForTeacherRow, error) {
	row := q.db.QueryRow(ctx, getStudentUsageForTeacher, arg.UserID, arg.WeekStart, arg.WeekEnd)
	var i GetStudentUsageForTeacherRow
	err := row.Scan(&i.ActiveDays, &i.Turns)
	return i, err
}

const getStudentWeekStats = `-- name: GetStudentWeekStats :one
SELECT
  COUNT(DISTINCT (ev.created_at AT TIME ZONE 'UTC')::date)::int AS active_days,
  COUNT(*) FILTER (WHERE ev.type IN ('prompt_sent','course_message'))::int AS turns,
  (SELECT count(*) FROM student_evaluation se
     WHERE se.user_id = $1
       AND se.created_at >= $2 AND se.created_at < $3)::int AS reports,
  COUNT(DISTINCT (ev.course_id, ev.payload->>'ordinal'))
    FILTER (WHERE ev.type = 'step_viewed')::int AS course_steps
FROM event ev
WHERE ev.user_id = $1
  AND ev.created_at >= $2 AND ev.created_at < $3
`

type GetStudentWeekStatsParams struct {
	UserID    uuid.UUID `json:"user_id"`
	WeekStart time.Time `json:"week_start"`
	WeekEnd   time.Time `json:"week_end"`
}

type GetStudentWeekStatsRow struct {
	ActiveDays  int32 `json:"active_days"`
	Turns       int32 `json:"turns"`
	Reports     int32 `json:"reports"`
	CourseSteps int32 `json:"course_steps"`
}

// One student's four stage-card counts for a half-open window. Same口径 as
// GetClassWeekStats: active days bucketed via AT TIME ZONE 'UTC'; turns =
// prompt_sent + course_message; reports = student_evaluation rows; course_steps
// = DISTINCT (course, ordinal) step_viewed. Tenancy is the handler's
// (authTeacherStudent has proven this student is in the teacher's class).
func (q *Queries) GetStudentWeekStats(ctx context.Context, arg GetStudentWeekStatsParams) (GetStudentWeekStatsRow, error) {
	row := q.db.QueryRow(ctx, getStudentWeekStats, arg.UserID, arg.WeekStart, arg.WeekEnd)
	var i GetStudentWeekStatsRow
	err := row.Scan(
		&i.ActiveDays,
		&i.Turns,
		&i.Reports,
		&i.CourseSteps,
	)
	return i, err
}

const listClassRosterReport = `-- name: ListClassRosterReport :many

SELECT
  u.id, u.display_name, u.avatar_color,
  ev.scores AS latest_project_scores,
  COALESCE(act.active_days, 0)::int AS active_days,
  COALESCE(act.turns, 0)::int       AS turns,
  (ev.scores IS NOT NULL)           AS has_report
FROM enrollments e
JOIN users u ON u.id = e.user_id
LEFT JOIN LATERAL (
  SELECT se.scores
  FROM student_evaluation se
  WHERE se.user_id = u.id
  ORDER BY se.created_at DESC
  LIMIT 1
) ev ON true
LEFT JOIN LATERAL (
  SELECT
    COUNT(DISTINCT (ev4.created_at AT TIME ZONE 'UTC')::date) AS active_days,
    COUNT(*) FILTER (WHERE ev4.type IN ('prompt_sent','course_message')) AS turns
  FROM event ev4
  WHERE ev4.user_id = u.id
    AND ev4.created_at >= $1 AND ev4.created_at < $2
) act ON true
WHERE e.class_id = $3 AND e.role_in_class = 'student'
ORDER BY u.display_name
`

type ListClassRosterReportParams struct {
	WeekStart time.Time `json:"week_start"`
	WeekEnd   time.Time `json:"week_end"`
	ClassID   uuid.UUID `json:"class_id"`
}

type ListClassRosterReportRow struct {
	ID                  uuid.UUID   `json:"id"`
	DisplayName         string      `json:"display_name"`
	AvatarColor         string      `json:"avatar_color"`
	LatestProjectScores []byte      `json:"latest_project_scores"`
	ActiveDays          int32       `json:"active_days"`
	Turns               int32       `json:"turns"`
	HasReport           interface{} `json:"has_report"`
}

// Teacher read-path (Spec D1). Every query is class-scoped: it JOINs enrollments
// with role_in_class='student' so a teacher can only read members of the class
// the handler already authorised via assertTeacherOwnsClass. No writes.
// One row per student: latest report scores across all scopes (for D/A badge
// derivation, NULL when unrated) + this-week activity. Mirrors GetClassRoster's
// enrollment scoping (org.sql).
func (q *Queries) ListClassRosterReport(ctx context.Context, arg ListClassRosterReportParams) ([]ListClassRosterReportRow, error) {
	rows, err := q.db.Query(ctx, listClassRosterReport, arg.WeekStart, arg.WeekEnd, arg.ClassID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListClassRosterReportRow
	for rows.Next() {
		var i ListClassRosterReportRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.AvatarColor,
			&i.LatestProjectScores,
			&i.ActiveDays,
			&i.Turns,
			&i.HasReport,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudentProjectsForTeacher = `-- name: ListStudentProjectsForTeacher :many
SELECT p.id, p.title, p.last_active_at,
       EXISTS (SELECT 1 FROM evaluations ev WHERE ev.project_id = p.id) AS has_report
FROM project p
WHERE p.user_id = $1
ORDER BY p.last_active_at DESC NULLS LAST
`

type ListStudentProjectsForTeacherRow struct {
	ID           uuid.UUID `json:"id"`
	Title        string    `json:"title"`
	LastActiveAt time.Time `json:"last_active_at"`
	HasReport    bool      `json:"has_report"`
}

// All of a student's projects (title/date + whether a report exists), so
// in-progress projects without a report still appear in the records list.
func (q *Queries) ListStudentProjectsForTeacher(ctx context.Context, userID uuid.UUID) ([]ListStudentProjectsForTeacherRow, error) {
	rows, err := q.db.Query(ctx, listStudentProjectsForTeacher, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStudentProjectsForTeacherRow
	for rows.Next() {
		var i ListStudentProjectsForTeacherRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.LastActiveAt,
			&i.HasReport,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudentReportsForTeacher = `-- name: ListStudentReportsForTeacher :many
SELECT surface, scope_id, label, sublabel, created_at
FROM (
  (SELECT DISTINCT ON (e.project_id)
     'project'::text AS surface, e.project_id AS scope_id,
     p.title AS label, NULL::text AS sublabel, e.created_at AS created_at
   FROM evaluations e JOIN project p ON p.id = e.project_id
   WHERE e.project_id IS NOT NULL AND p.user_id = $1
   ORDER BY e.project_id, e.created_at DESC)
  UNION ALL
  (SELECT DISTINCT ON (e.thread_id)
     'chat'::text, e.thread_id, t.title, NULL::text, e.created_at
   FROM evaluations e JOIN chat_thread t ON t.id = e.thread_id
   WHERE e.thread_id IS NOT NULL AND t.user_id = $1
   ORDER BY e.thread_id, e.created_at DESC)
) rows
ORDER BY created_at DESC
`

type ListStudentReportsForTeacherRow struct {
	Surface   string      `json:"surface"`
	ScopeID   pgtype.UUID `json:"scope_id"`
	Label     string      `json:"label"`
	Sublabel  *string     `json:"sublabel"`
	CreatedAt time.Time   `json:"created_at"`
}

// Every report one class member owns, across both remaining scopes,
// newest-first, one row per scope. Teacher variant of ListGrowthHistory: same
// shape, but the owner filter is replaced by "this user AND a student member
// of this class". The course-session arm is retired along with course_session
// itself (migration 0050, course v2, no back-compat).
func (q *Queries) ListStudentReportsForTeacher(ctx context.Context, userID uuid.UUID) ([]ListStudentReportsForTeacherRow, error) {
	rows, err := q.db.Query(ctx, listStudentReportsForTeacher, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStudentReportsForTeacherRow
	for rows.Next() {
		var i ListStudentReportsForTeacherRow
		if err := rows.Scan(
			&i.Surface,
			&i.ScopeID,
			&i.Label,
			&i.Sublabel,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
