// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: teacher_weekly.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const appendClassWeeklyProseCards = `-- name: AppendClassWeeklyProseCards :exec
UPDATE class_weekly_prose
SET cards = cards || $1::jsonb, updated_at = now()
WHERE class_id = $2 AND week_start = $3
`

type AppendClassWeeklyProseCardsParams struct {
	Cards     []byte      `json:"cards"`
	ClassID   uuid.UUID   `json:"class_id"`
	WeekStart pgtype.Date `json:"week_start"`
}

// The top-up (DEC-6): appends newly-composed card prose to an existing row.
// comment/depth_note/autonomy_note are never touched — nothing already written
// is ever rewritten.
func (q *Queries) AppendClassWeeklyProseCards(ctx context.Context, arg AppendClassWeeklyProseCardsParams) error {
	_, err := q.db.Exec(ctx, appendClassWeeklyProseCards, arg.Cards, arg.ClassID, arg.WeekStart)
	return err
}

const getClassWeeklyProse = `-- name: GetClassWeeklyProse :one

SELECT comment, depth_note, autonomy_note, cards, created_at
FROM class_weekly_prose
WHERE class_id = $1 AND week_start = $2
`

type GetClassWeeklyProseParams struct {
	ClassID   uuid.UUID   `json:"class_id"`
	WeekStart pgtype.Date `json:"week_start"`
}

type GetClassWeeklyProseRow struct {
	Comment      string    `json:"comment"`
	DepthNote    string    `json:"depth_note"`
	AutonomyNote string    `json:"autonomy_note"`
	Cards        []byte    `json:"cards"`
	CreatedAt    time.Time `json:"created_at"`
}

// D2 weekly-report reads. Class-scoped like teacher.sql: the handler has
// already authorised the class via assertTeacherOwnsClass, and every student
// query JOINs enrollments with role_in_class='student'. No writes except the
// prose row, which holds no student data beyond names already on screen.
func (q *Queries) GetClassWeeklyProse(ctx context.Context, arg GetClassWeeklyProseParams) (GetClassWeeklyProseRow, error) {
	row := q.db.QueryRow(ctx, getClassWeeklyProse, arg.ClassID, arg.WeekStart)
	var i GetClassWeeklyProseRow
	err := row.Scan(
		&i.Comment,
		&i.DepthNote,
		&i.AutonomyNote,
		&i.Cards,
		&i.CreatedAt,
	)
	return i, err
}

const insertClassWeeklyProse = `-- name: InsertClassWeeklyProse :exec
INSERT INTO class_weekly_prose (class_id, week_start, comment, depth_note, autonomy_note, cards)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (class_id, week_start) DO NOTHING
`

type InsertClassWeeklyProseParams struct {
	ClassID      uuid.UUID   `json:"class_id"`
	WeekStart    pgtype.Date `json:"week_start"`
	Comment      string      `json:"comment"`
	DepthNote    string      `json:"depth_note"`
	AutonomyNote string      `json:"autonomy_note"`
	Cards        []byte      `json:"cards"`
}

// First-open-wins (DEC-2): a concurrent second generation is discarded, and
// the caller re-reads to return the winner's row.
func (q *Queries) InsertClassWeeklyProse(ctx context.Context, arg InsertClassWeeklyProseParams) error {
	_, err := q.db.Exec(ctx, insertClassWeeklyProse,
		arg.ClassID,
		arg.WeekStart,
		arg.Comment,
		arg.DepthNote,
		arg.AutonomyNote,
		arg.Cards,
	)
	return err
}
