// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, email_verified_at, password_hash, role, school_id, display_name, avatar_color, created_at, card_theme, page_background, onboarded_at, gender FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.PasswordHash,
		&i.Role,
		&i.SchoolID,
		&i.DisplayName,
		&i.AvatarColor,
		&i.CreatedAt,
		&i.CardTheme,
		&i.PageBackground,
		&i.OnboardedAt,
		&i.Gender,
	)
	return i, err
}

const getUserCardTheme = `-- name: GetUserCardTheme :one
SELECT card_theme FROM users WHERE id = $1
`

// The student's chosen 工具卡图鉴 cover colorway (see migration 0047). Narrow
// read, does not touch the full User row.
func (q *Queries) GetUserCardTheme(ctx context.Context, userID uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getUserCardTheme, userID)
	var card_theme string
	err := row.Scan(&card_theme)
	return card_theme, err
}

const getUserPageBackground = `-- name: GetUserPageBackground :one
SELECT page_background FROM users WHERE id = $1
`

// The student's chosen page background colorway (see migration 0074). Narrow
// read, does not touch the full User row.
func (q *Queries) GetUserPageBackground(ctx context.Context, userID uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getUserPageBackground, userID)
	var page_background string
	err := row.Scan(&page_background)
	return page_background, err
}

const setUserAvatarColor = `-- name: SetUserAvatarColor :exec
UPDATE users SET avatar_color = $1 WHERE id = $2
`

type SetUserAvatarColorParams struct {
	AvatarColor string    `json:"avatar_color"`
	UserID      uuid.UUID `json:"user_id"`
}

// Persists the student's chosen accent preset id into the existing
// avatar_color column. The handler validates against the 8-preset allowlist
// before calling; no CHECK constraint on this column.
func (q *Queries) SetUserAvatarColor(ctx context.Context, arg SetUserAvatarColorParams) error {
	_, err := q.db.Exec(ctx, setUserAvatarColor, arg.AvatarColor, arg.UserID)
	return err
}

const setUserCardTheme = `-- name: SetUserCardTheme :exec
UPDATE users SET card_theme = $1 WHERE id = $2
`

type SetUserCardThemeParams struct {
	CardTheme string    `json:"card_theme"`
	UserID    uuid.UUID `json:"user_id"`
}

// Set the student's cover colorway. The 4-value CHECK is enforced by the column;
// the handler validates against cards.ValidTheme before calling.
func (q *Queries) SetUserCardTheme(ctx context.Context, arg SetUserCardThemeParams) error {
	_, err := q.db.Exec(ctx, setUserCardTheme, arg.CardTheme, arg.UserID)
	return err
}

const setUserOnboardedAt = `-- name: SetUserOnboardedAt :exec
UPDATE users SET onboarded_at = now() WHERE id = $1
`

// Stamps the moment the student completed/dismissed onboarding. Idempotent enough for
// our use (re-running just refreshes the timestamp).
func (q *Queries) SetUserOnboardedAt(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, setUserOnboardedAt, userID)
	return err
}

const setUserPageBackground = `-- name: SetUserPageBackground :exec
UPDATE users SET page_background = $1 WHERE id = $2
`

type SetUserPageBackgroundParams struct {
	PageBackground string    `json:"page_background"`
	UserID         uuid.UUID `json:"user_id"`
}

// Set the student's page background. The 6-value CHECK is enforced by the column;
// the handler validates against the preset allowlist before calling.
func (q *Queries) SetUserPageBackground(ctx context.Context, arg SetUserPageBackgroundParams) error {
	_, err := q.db.Exec(ctx, setUserPageBackground, arg.PageBackground, arg.UserID)
	return err
}
