// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: workspace.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createActivityLogEntry = `-- name: CreateActivityLogEntry :one
INSERT INTO activity_log_entry (project_id, entry_date, text, source)
VALUES ($1, $2, $3, $4)
RETURNING id, project_id, entry_date, text, source, created_at
`

type CreateActivityLogEntryParams struct {
	ProjectID uuid.UUID   `json:"project_id"`
	EntryDate pgtype.Date `json:"entry_date"`
	Text      string      `json:"text"`
	Source    string      `json:"source"`
}

func (q *Queries) CreateActivityLogEntry(ctx context.Context, arg CreateActivityLogEntryParams) (ActivityLogEntry, error) {
	row := q.db.QueryRow(ctx, createActivityLogEntry,
		arg.ProjectID,
		arg.EntryDate,
		arg.Text,
		arg.Source,
	)
	var i ActivityLogEntry
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EntryDate,
		&i.Text,
		&i.Source,
		&i.CreatedAt,
	)
	return i, err
}

const createCollection = `-- name: CreateCollection :one
INSERT INTO collection (project_id, name, parent_id, position)
VALUES ($1, $2, $3, $4)
RETURNING id, project_id, name, parent_id, position, created_at
`

type CreateCollectionParams struct {
	ProjectID uuid.UUID   `json:"project_id"`
	Name      string      `json:"name"`
	ParentID  pgtype.UUID `json:"parent_id"`
	Position  int32       `json:"position"`
}

func (q *Queries) CreateCollection(ctx context.Context, arg CreateCollectionParams) (Collection, error) {
	row := q.db.QueryRow(ctx, createCollection,
		arg.ProjectID,
		arg.Name,
		arg.ParentID,
		arg.Position,
	)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.ParentID,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const createOutlineNode = `-- name: CreateOutlineNode :one
INSERT INTO outline_node (project_id, text, depth, position)
VALUES ($1, $2, $3, $4)
RETURNING id, project_id, text, depth, position, created_at, updated_at
`

type CreateOutlineNodeParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Text      string    `json:"text"`
	Depth     int32     `json:"depth"`
	Position  int32     `json:"position"`
}

func (q *Queries) CreateOutlineNode(ctx context.Context, arg CreateOutlineNodeParams) (OutlineNode, error) {
	row := q.db.QueryRow(ctx, createOutlineNode,
		arg.ProjectID,
		arg.Text,
		arg.Depth,
		arg.Position,
	)
	var i OutlineNode
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Text,
		&i.Depth,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPlanItem = `-- name: CreatePlanItem :one
INSERT INTO plan_item (project_id, title, tag, col, stage, ref_material_id, start_day, days, position)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, project_id, title, tag, col, stage, ref_material_id, start_day, days, position, created_at, updated_at
`

type CreatePlanItemParams struct {
	ProjectID     uuid.UUID   `json:"project_id"`
	Title         string      `json:"title"`
	Tag           string      `json:"tag"`
	Col           string      `json:"col"`
	Stage         string      `json:"stage"`
	RefMaterialID pgtype.UUID `json:"ref_material_id"`
	StartDay      int32       `json:"start_day"`
	Days          int32       `json:"days"`
	Position      int32       `json:"position"`
}

func (q *Queries) CreatePlanItem(ctx context.Context, arg CreatePlanItemParams) (PlanItem, error) {
	row := q.db.QueryRow(ctx, createPlanItem,
		arg.ProjectID,
		arg.Title,
		arg.Tag,
		arg.Col,
		arg.Stage,
		arg.RefMaterialID,
		arg.StartDay,
		arg.Days,
		arg.Position,
	)
	var i PlanItem
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Tag,
		&i.Col,
		&i.Stage,
		&i.RefMaterialID,
		&i.StartDay,
		&i.Days,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createReference = `-- name: CreateReference :one
INSERT INTO reference (
    project_id, title, classification, author, credentials, year, url,
    tags, collection_id, credibility, evaluation, decision, pending, search_hints
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING id, project_id, title, classification, author, credentials, year, url, tags, collection_id, credibility, evaluation, decision, pending, search_hints, material_id, position, created_at, updated_at
`

type CreateReferenceParams struct {
	ProjectID      uuid.UUID   `json:"project_id"`
	Title          string      `json:"title"`
	Classification string      `json:"classification"`
	Author         string      `json:"author"`
	Credentials    string      `json:"credentials"`
	Year           string      `json:"year"`
	Url            string      `json:"url"`
	Tags           []byte      `json:"tags"`
	CollectionID   pgtype.UUID `json:"collection_id"`
	Credibility    *string     `json:"credibility"`
	Evaluation     string      `json:"evaluation"`
	Decision       *string     `json:"decision"`
	Pending        bool        `json:"pending"`
	SearchHints    []byte      `json:"search_hints"`
}

func (q *Queries) CreateReference(ctx context.Context, arg CreateReferenceParams) (Reference, error) {
	row := q.db.QueryRow(ctx, createReference,
		arg.ProjectID,
		arg.Title,
		arg.Classification,
		arg.Author,
		arg.Credentials,
		arg.Year,
		arg.Url,
		arg.Tags,
		arg.CollectionID,
		arg.Credibility,
		arg.Evaluation,
		arg.Decision,
		arg.Pending,
		arg.SearchHints,
	)
	var i Reference
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Classification,
		&i.Author,
		&i.Credentials,
		&i.Year,
		&i.Url,
		&i.Tags,
		&i.CollectionID,
		&i.Credibility,
		&i.Evaluation,
		&i.Decision,
		&i.Pending,
		&i.SearchHints,
		&i.MaterialID,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAllOutlineNodes = `-- name: DeleteAllOutlineNodes :exec
DELETE FROM outline_node WHERE project_id = $1
`

// Clears the whole outline for a project; PUT /outline replaces the set by
// deleting then re-inserting the posted array in one transaction.
func (q *Queries) DeleteAllOutlineNodes(ctx context.Context, projectID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAllOutlineNodes, projectID)
	return err
}

const deleteCollection = `-- name: DeleteCollection :exec
DELETE FROM collection WHERE id = $1 AND project_id = $2
`

type DeleteCollectionParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
}

// Children cascade (parent_id FK ON DELETE CASCADE); a deleted collection's
// references have their collection_id nulled (reference.collection_id FK ON
// DELETE SET NULL).
func (q *Queries) DeleteCollection(ctx context.Context, arg DeleteCollectionParams) error {
	_, err := q.db.Exec(ctx, deleteCollection, arg.ID, arg.ProjectID)
	return err
}

const deletePlanItem = `-- name: DeletePlanItem :exec
DELETE FROM plan_item WHERE id = $1 AND project_id = $2
`

type DeletePlanItemParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
}

func (q *Queries) DeletePlanItem(ctx context.Context, arg DeletePlanItemParams) error {
	_, err := q.db.Exec(ctx, deletePlanItem, arg.ID, arg.ProjectID)
	return err
}

const deleteReference = `-- name: DeleteReference :exec
DELETE FROM reference WHERE id = $1 AND project_id = $2
`

type DeleteReferenceParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
}

func (q *Queries) DeleteReference(ctx context.Context, arg DeleteReferenceParams) error {
	_, err := q.db.Exec(ctx, deleteReference, arg.ID, arg.ProjectID)
	return err
}

const getCollection = `-- name: GetCollection :one
SELECT id, project_id, name, parent_id, position, created_at FROM collection WHERE id = $1 AND project_id = $2
`

type GetCollectionParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
}

func (q *Queries) GetCollection(ctx context.Context, arg GetCollectionParams) (Collection, error) {
	row := q.db.QueryRow(ctx, getCollection, arg.ID, arg.ProjectID)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.ParentID,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const getPlanItem = `-- name: GetPlanItem :one
SELECT id, project_id, title, tag, col, stage, ref_material_id, start_day, days, position, created_at, updated_at FROM plan_item WHERE id = $1 AND project_id = $2
`

type GetPlanItemParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
}

func (q *Queries) GetPlanItem(ctx context.Context, arg GetPlanItemParams) (PlanItem, error) {
	row := q.db.QueryRow(ctx, getPlanItem, arg.ID, arg.ProjectID)
	var i PlanItem
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Tag,
		&i.Col,
		&i.Stage,
		&i.RefMaterialID,
		&i.StartDay,
		&i.Days,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectProposal = `-- name: GetProjectProposal :one
SELECT project_id, objective, reason, activities, resources, updated_at FROM project_proposal WHERE project_id = $1
`

func (q *Queries) GetProjectProposal(ctx context.Context, projectID uuid.UUID) (ProjectProposal, error) {
	row := q.db.QueryRow(ctx, getProjectProposal, projectID)
	var i ProjectProposal
	err := row.Scan(
		&i.ProjectID,
		&i.Objective,
		&i.Reason,
		&i.Activities,
		&i.Resources,
		&i.UpdatedAt,
	)
	return i, err
}

const getReference = `-- name: GetReference :one
SELECT id, project_id, title, classification, author, credentials, year, url, tags, collection_id, credibility, evaluation, decision, pending, search_hints, material_id, position, created_at, updated_at FROM reference WHERE id = $1 AND project_id = $2
`

type GetReferenceParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
}

func (q *Queries) GetReference(ctx context.Context, arg GetReferenceParams) (Reference, error) {
	row := q.db.QueryRow(ctx, getReference, arg.ID, arg.ProjectID)
	var i Reference
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Classification,
		&i.Author,
		&i.Credentials,
		&i.Year,
		&i.Url,
		&i.Tags,
		&i.CollectionID,
		&i.Credibility,
		&i.Evaluation,
		&i.Decision,
		&i.Pending,
		&i.SearchHints,
		&i.MaterialID,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActivityLog = `-- name: ListActivityLog :many
SELECT id, project_id, entry_date, text, source, created_at FROM activity_log_entry
WHERE project_id = $1
ORDER BY entry_date, created_at
`

func (q *Queries) ListActivityLog(ctx context.Context, projectID uuid.UUID) ([]ActivityLogEntry, error) {
	rows, err := q.db.Query(ctx, listActivityLog, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActivityLogEntry
	for rows.Next() {
		var i ActivityLogEntry
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.EntryDate,
			&i.Text,
			&i.Source,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCollections = `-- name: ListCollections :many

SELECT id, project_id, name, parent_id, position, created_at FROM collection
WHERE project_id = $1
ORDER BY position, created_at
`

// Read library · collections (self-referential tree). ---------------------
func (q *Queries) ListCollections(ctx context.Context, projectID uuid.UUID) ([]Collection, error) {
	rows, err := q.db.Query(ctx, listCollections, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Collection
	for rows.Next() {
		var i Collection
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.ParentID,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOutlineNodes = `-- name: ListOutlineNodes :many

SELECT id, project_id, text, depth, position, created_at, updated_at FROM outline_node
WHERE project_id = $1
ORDER BY position, created_at
`

// Write · outline nodes (depth-indexed flat list, projected to a tree). ------
func (q *Queries) ListOutlineNodes(ctx context.Context, projectID uuid.UUID) ([]OutlineNode, error) {
	rows, err := q.db.Query(ctx, listOutlineNodes, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutlineNode
	for rows.Next() {
		var i OutlineNode
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Text,
			&i.Depth,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlanItems = `-- name: ListPlanItems :many
SELECT id, project_id, title, tag, col, stage, ref_material_id, start_day, days, position, created_at, updated_at FROM plan_item
WHERE project_id = $1
ORDER BY stage, position, start_day, created_at
`

func (q *Queries) ListPlanItems(ctx context.Context, projectID uuid.UUID) ([]PlanItem, error) {
	rows, err := q.db.Query(ctx, listPlanItems, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlanItem
	for rows.Next() {
		var i PlanItem
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Tag,
			&i.Col,
			&i.Stage,
			&i.RefMaterialID,
			&i.StartDay,
			&i.Days,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReferences = `-- name: ListReferences :many

SELECT id, project_id, title, classification, author, credentials, year, url, tags, collection_id, credibility, evaluation, decision, pending, search_hints, material_id, position, created_at, updated_at FROM reference
WHERE project_id = $1
ORDER BY position, created_at
`

// Read library · references. -----------------------------------------------
func (q *Queries) ListReferences(ctx context.Context, projectID uuid.UUID) ([]Reference, error) {
	rows, err := q.db.Query(ctx, listReferences, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reference
	for rows.Next() {
		var i Reference
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Classification,
			&i.Author,
			&i.Credentials,
			&i.Year,
			&i.Url,
			&i.Tags,
			&i.CollectionID,
			&i.Credibility,
			&i.Evaluation,
			&i.Decision,
			&i.Pending,
			&i.SearchHints,
			&i.MaterialID,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setReferenceMaterial = `-- name: SetReferenceMaterial :one
UPDATE reference SET
    material_id = $3,
    updated_at  = now()
WHERE id = $1 AND project_id = $2
RETURNING id, project_id, title, classification, author, credentials, year, url, tags, collection_id, credibility, evaluation, decision, pending, search_hints, material_id, position, created_at, updated_at
`

type SetReferenceMaterialParams struct {
	ID         uuid.UUID   `json:"id"`
	ProjectID  uuid.UUID   `json:"project_id"`
	MaterialID pgtype.UUID `json:"material_id"`
}

// Binds a reference to the material fetched/created for it on enter-reading.
func (q *Queries) SetReferenceMaterial(ctx context.Context, arg SetReferenceMaterialParams) (Reference, error) {
	row := q.db.QueryRow(ctx, setReferenceMaterial, arg.ID, arg.ProjectID, arg.MaterialID)
	var i Reference
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Classification,
		&i.Author,
		&i.Credentials,
		&i.Year,
		&i.Url,
		&i.Tags,
		&i.CollectionID,
		&i.Credibility,
		&i.Evaluation,
		&i.Decision,
		&i.Pending,
		&i.SearchHints,
		&i.MaterialID,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCollection = `-- name: UpdateCollection :one
UPDATE collection SET
    name      = $3,
    parent_id = $4,
    position  = $5
WHERE id = $1 AND project_id = $2
RETURNING id, project_id, name, parent_id, position, created_at
`

type UpdateCollectionParams struct {
	ID        uuid.UUID   `json:"id"`
	ProjectID uuid.UUID   `json:"project_id"`
	Name      string      `json:"name"`
	ParentID  pgtype.UUID `json:"parent_id"`
	Position  int32       `json:"position"`
}

// Sets ALL columns by id + project_id; the handler merges partial patches over
// the current row before calling this (UpdatePlanItem's pattern).
func (q *Queries) UpdateCollection(ctx context.Context, arg UpdateCollectionParams) (Collection, error) {
	row := q.db.QueryRow(ctx, updateCollection,
		arg.ID,
		arg.ProjectID,
		arg.Name,
		arg.ParentID,
		arg.Position,
	)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.ParentID,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const updatePlanItem = `-- name: UpdatePlanItem :one
UPDATE plan_item SET
    title           = $3,
    tag             = $4,
    col             = $5,
    stage           = $6,
    ref_material_id = $7,
    start_day       = $8,
    days            = $9,
    position        = $10,
    updated_at      = now()
WHERE id = $1 AND project_id = $2
RETURNING id, project_id, title, tag, col, stage, ref_material_id, start_day, days, position, created_at, updated_at
`

type UpdatePlanItemParams struct {
	ID            uuid.UUID   `json:"id"`
	ProjectID     uuid.UUID   `json:"project_id"`
	Title         string      `json:"title"`
	Tag           string      `json:"tag"`
	Col           string      `json:"col"`
	Stage         string      `json:"stage"`
	RefMaterialID pgtype.UUID `json:"ref_material_id"`
	StartDay      int32       `json:"start_day"`
	Days          int32       `json:"days"`
	Position      int32       `json:"position"`
}

// Sets ALL columns by id + project_id; the handler merges partial patches over
// the current row before calling this, so every field is always supplied.
func (q *Queries) UpdatePlanItem(ctx context.Context, arg UpdatePlanItemParams) (PlanItem, error) {
	row := q.db.QueryRow(ctx, updatePlanItem,
		arg.ID,
		arg.ProjectID,
		arg.Title,
		arg.Tag,
		arg.Col,
		arg.Stage,
		arg.RefMaterialID,
		arg.StartDay,
		arg.Days,
		arg.Position,
	)
	var i PlanItem
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Tag,
		&i.Col,
		&i.Stage,
		&i.RefMaterialID,
		&i.StartDay,
		&i.Days,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateReference = `-- name: UpdateReference :one
UPDATE reference SET
    title          = $3,
    classification = $4,
    author         = $5,
    credentials    = $6,
    year           = $7,
    url            = $8,
    tags           = $9,
    collection_id  = $10,
    credibility    = $11,
    evaluation     = $12,
    decision       = $13,
    pending        = $14,
    search_hints   = $15,
    updated_at     = now()
WHERE id = $1 AND project_id = $2
RETURNING id, project_id, title, classification, author, credentials, year, url, tags, collection_id, credibility, evaluation, decision, pending, search_hints, material_id, position, created_at, updated_at
`

type UpdateReferenceParams struct {
	ID             uuid.UUID   `json:"id"`
	ProjectID      uuid.UUID   `json:"project_id"`
	Title          string      `json:"title"`
	Classification string      `json:"classification"`
	Author         string      `json:"author"`
	Credentials    string      `json:"credentials"`
	Year           string      `json:"year"`
	Url            string      `json:"url"`
	Tags           []byte      `json:"tags"`
	CollectionID   pgtype.UUID `json:"collection_id"`
	Credibility    *string     `json:"credibility"`
	Evaluation     string      `json:"evaluation"`
	Decision       *string     `json:"decision"`
	Pending        bool        `json:"pending"`
	SearchHints    []byte      `json:"search_hints"`
}

// Sets ALL editable columns by id + project_id; the handler merges partial
// patches over the current row first (UpdatePlanItem's pattern). material_id is
// NOT set here — SetReferenceMaterial owns that link (enter-reading only).
func (q *Queries) UpdateReference(ctx context.Context, arg UpdateReferenceParams) (Reference, error) {
	row := q.db.QueryRow(ctx, updateReference,
		arg.ID,
		arg.ProjectID,
		arg.Title,
		arg.Classification,
		arg.Author,
		arg.Credentials,
		arg.Year,
		arg.Url,
		arg.Tags,
		arg.CollectionID,
		arg.Credibility,
		arg.Evaluation,
		arg.Decision,
		arg.Pending,
		arg.SearchHints,
	)
	var i Reference
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Classification,
		&i.Author,
		&i.Credentials,
		&i.Year,
		&i.Url,
		&i.Tags,
		&i.CollectionID,
		&i.Credibility,
		&i.Evaluation,
		&i.Decision,
		&i.Pending,
		&i.SearchHints,
		&i.MaterialID,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertProjectProposal = `-- name: UpsertProjectProposal :one
INSERT INTO project_proposal (project_id, objective, reason, activities, resources, updated_at)
VALUES ($1, $2, $3, $4, $5, now())
ON CONFLICT (project_id) DO UPDATE SET
    objective  = EXCLUDED.objective,
    reason     = EXCLUDED.reason,
    activities = EXCLUDED.activities,
    resources  = EXCLUDED.resources,
    updated_at = now()
RETURNING project_id, objective, reason, activities, resources, updated_at
`

type UpsertProjectProposalParams struct {
	ProjectID  uuid.UUID `json:"project_id"`
	Objective  string    `json:"objective"`
	Reason     string    `json:"reason"`
	Activities string    `json:"activities"`
	Resources  string    `json:"resources"`
}

func (q *Queries) UpsertProjectProposal(ctx context.Context, arg UpsertProjectProposalParams) (ProjectProposal, error) {
	row := q.db.QueryRow(ctx, upsertProjectProposal,
		arg.ProjectID,
		arg.Objective,
		arg.Reason,
		arg.Activities,
		arg.Resources,
	)
	var i ProjectProposal
	err := row.Scan(
		&i.ProjectID,
		&i.Objective,
		&i.Reason,
		&i.Activities,
		&i.Resources,
		&i.UpdatedAt,
	)
	return i, err
}
