// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: workspace.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countExplorationLeadForSource = `-- name: CountExplorationLeadForSource :one
SELECT count(*) FROM exploration_lead
WHERE project_id = $1 AND source_reference_id = $2 AND text = $3
`

type CountExplorationLeadForSourceParams struct {
	ProjectID         uuid.UUID   `json:"project_id"`
	SourceReferenceID pgtype.UUID `json:"source_reference_id"`
	Text              string      `json:"text"`
}

// The idempotent-materialize dedupe check for postFinalizeReading (D-S3-2):
// re-finalizing a source must not duplicate a lead whose text already exists
// for that (project, source).
func (q *Queries) CountExplorationLeadForSource(ctx context.Context, arg CountExplorationLeadForSourceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countExplorationLeadForSource, arg.ProjectID, arg.SourceReferenceID, arg.Text)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createActivityLogEntry = `-- name: CreateActivityLogEntry :one
INSERT INTO activity_log_entry (project_id, entry_date, text, source)
VALUES ($1, $2, $3, $4)
RETURNING id, project_id, entry_date, text, source, created_at
`

type CreateActivityLogEntryParams struct {
	ProjectID uuid.UUID   `json:"project_id"`
	EntryDate pgtype.Date `json:"entry_date"`
	Text      string      `json:"text"`
	Source    string      `json:"source"`
}

func (q *Queries) CreateActivityLogEntry(ctx context.Context, arg CreateActivityLogEntryParams) (ActivityLogEntry, error) {
	row := q.db.QueryRow(ctx, createActivityLogEntry,
		arg.ProjectID,
		arg.EntryDate,
		arg.Text,
		arg.Source,
	)
	var i ActivityLogEntry
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EntryDate,
		&i.Text,
		&i.Source,
		&i.CreatedAt,
	)
	return i, err
}

const createCollection = `-- name: CreateCollection :one
INSERT INTO collection (project_id, name, parent_id, position)
VALUES ($1, $2, $3, $4)
RETURNING id, project_id, name, parent_id, position, created_at
`

type CreateCollectionParams struct {
	ProjectID uuid.UUID   `json:"project_id"`
	Name      string      `json:"name"`
	ParentID  pgtype.UUID `json:"parent_id"`
	Position  int32       `json:"position"`
}

func (q *Queries) CreateCollection(ctx context.Context, arg CreateCollectionParams) (Collection, error) {
	row := q.db.QueryRow(ctx, createCollection,
		arg.ProjectID,
		arg.Name,
		arg.ParentID,
		arg.Position,
	)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.ParentID,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const createExplorationLead = `-- name: CreateExplorationLead :one
INSERT INTO exploration_lead (
    project_id, text, status, origin, source_reference_id, connected_reference_id, position, parent_lead_id
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, project_id, text, status, origin, source_reference_id, connected_reference_id, position, created_at, updated_at, parent_lead_id
`

type CreateExplorationLeadParams struct {
	ProjectID            uuid.UUID   `json:"project_id"`
	Text                 string      `json:"text"`
	Status               string      `json:"status"`
	Origin               string      `json:"origin"`
	SourceReferenceID    pgtype.UUID `json:"source_reference_id"`
	ConnectedReferenceID pgtype.UUID `json:"connected_reference_id"`
	Position             int32       `json:"position"`
	ParentLeadID         pgtype.UUID `json:"parent_lead_id"`
}

func (q *Queries) CreateExplorationLead(ctx context.Context, arg CreateExplorationLeadParams) (ExplorationLead, error) {
	row := q.db.QueryRow(ctx, createExplorationLead,
		arg.ProjectID,
		arg.Text,
		arg.Status,
		arg.Origin,
		arg.SourceReferenceID,
		arg.ConnectedReferenceID,
		arg.Position,
		arg.ParentLeadID,
	)
	var i ExplorationLead
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Text,
		&i.Status,
		&i.Origin,
		&i.SourceReferenceID,
		&i.ConnectedReferenceID,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ParentLeadID,
	)
	return i, err
}

const createOutlineNode = `-- name: CreateOutlineNode :one
INSERT INTO outline_node (project_id, text, depth, position)
VALUES ($1, $2, $3, $4)
RETURNING id, project_id, text, depth, position, created_at, updated_at
`

type CreateOutlineNodeParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Text      string    `json:"text"`
	Depth     int32     `json:"depth"`
	Position  int32     `json:"position"`
}

func (q *Queries) CreateOutlineNode(ctx context.Context, arg CreateOutlineNodeParams) (OutlineNode, error) {
	row := q.db.QueryRow(ctx, createOutlineNode,
		arg.ProjectID,
		arg.Text,
		arg.Depth,
		arg.Position,
	)
	var i OutlineNode
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Text,
		&i.Depth,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPlanItem = `-- name: CreatePlanItem :one
INSERT INTO plan_item (project_id, title, tag, col, stage, ref_material_id, start_day, days, position)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, project_id, title, tag, col, stage, ref_material_id, start_day, days, position, created_at, updated_at
`

type CreatePlanItemParams struct {
	ProjectID     uuid.UUID   `json:"project_id"`
	Title         string      `json:"title"`
	Tag           string      `json:"tag"`
	Col           string      `json:"col"`
	Stage         string      `json:"stage"`
	RefMaterialID pgtype.UUID `json:"ref_material_id"`
	StartDay      int32       `json:"start_day"`
	Days          int32       `json:"days"`
	Position      int32       `json:"position"`
}

func (q *Queries) CreatePlanItem(ctx context.Context, arg CreatePlanItemParams) (PlanItem, error) {
	row := q.db.QueryRow(ctx, createPlanItem,
		arg.ProjectID,
		arg.Title,
		arg.Tag,
		arg.Col,
		arg.Stage,
		arg.RefMaterialID,
		arg.StartDay,
		arg.Days,
		arg.Position,
	)
	var i PlanItem
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Tag,
		&i.Col,
		&i.Stage,
		&i.RefMaterialID,
		&i.StartDay,
		&i.Days,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createReference = `-- name: CreateReference :one
INSERT INTO reference (
    project_id, title, classification, author, credentials, year, url,
    tags, collection_id, credibility, evaluation, decision, pending, search_hints,
    abstract, journal
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
RETURNING id, project_id, title, classification, author, credentials, year, url, tags, collection_id, credibility, evaluation, decision, pending, search_hints, material_id, position, created_at, updated_at, reading_reason, reading_focus, phase_tag, takeaway, takeaway_finalized_at, reading_note, abstract, journal
`

type CreateReferenceParams struct {
	ProjectID      uuid.UUID   `json:"project_id"`
	Title          string      `json:"title"`
	Classification string      `json:"classification"`
	Author         string      `json:"author"`
	Credentials    string      `json:"credentials"`
	Year           string      `json:"year"`
	Url            string      `json:"url"`
	Tags           []byte      `json:"tags"`
	CollectionID   pgtype.UUID `json:"collection_id"`
	Credibility    *string     `json:"credibility"`
	Evaluation     string      `json:"evaluation"`
	Decision       *string     `json:"decision"`
	Pending        bool        `json:"pending"`
	SearchHints    []byte      `json:"search_hints"`
	Abstract       string      `json:"abstract"`
	Journal        string      `json:"journal"`
}

func (q *Queries) CreateReference(ctx context.Context, arg CreateReferenceParams) (Reference, error) {
	row := q.db.QueryRow(ctx, createReference,
		arg.ProjectID,
		arg.Title,
		arg.Classification,
		arg.Author,
		arg.Credentials,
		arg.Year,
		arg.Url,
		arg.Tags,
		arg.CollectionID,
		arg.Credibility,
		arg.Evaluation,
		arg.Decision,
		arg.Pending,
		arg.SearchHints,
		arg.Abstract,
		arg.Journal,
	)
	var i Reference
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Classification,
		&i.Author,
		&i.Credentials,
		&i.Year,
		&i.Url,
		&i.Tags,
		&i.CollectionID,
		&i.Credibility,
		&i.Evaluation,
		&i.Decision,
		&i.Pending,
		&i.SearchHints,
		&i.MaterialID,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReadingReason,
		&i.ReadingFocus,
		&i.PhaseTag,
		&i.Takeaway,
		&i.TakeawayFinalizedAt,
		&i.ReadingNote,
		&i.Abstract,
		&i.Journal,
	)
	return i, err
}

const createSnippet = `-- name: CreateSnippet :one
INSERT INTO snippet (project_id, text, position, section)
VALUES ($1, $2, $3, $4)
RETURNING id, project_id, text, position, created_at, section
`

type CreateSnippetParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Text      string    `json:"text"`
	Position  int32     `json:"position"`
	Section   *string   `json:"section"`
}

func (q *Queries) CreateSnippet(ctx context.Context, arg CreateSnippetParams) (Snippet, error) {
	row := q.db.QueryRow(ctx, createSnippet,
		arg.ProjectID,
		arg.Text,
		arg.Position,
		arg.Section,
	)
	var i Snippet
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Text,
		&i.Position,
		&i.CreatedAt,
		&i.Section,
	)
	return i, err
}

const deleteAllOutlineNodes = `-- name: DeleteAllOutlineNodes :exec
DELETE FROM outline_node WHERE project_id = $1
`

// Clears the whole outline for a project; PUT /outline replaces the set by
// deleting then re-inserting the posted array in one transaction.
func (q *Queries) DeleteAllOutlineNodes(ctx context.Context, projectID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAllOutlineNodes, projectID)
	return err
}

const deleteAllSnippets = `-- name: DeleteAllSnippets :exec
DELETE FROM snippet WHERE project_id = $1
`

// PUT /snippets replaces the whole set (delete + re-insert the posted array).
func (q *Queries) DeleteAllSnippets(ctx context.Context, projectID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAllSnippets, projectID)
	return err
}

const deleteCollection = `-- name: DeleteCollection :exec
DELETE FROM collection WHERE id = $1 AND project_id = $2
`

type DeleteCollectionParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
}

// Children cascade (parent_id FK ON DELETE CASCADE); a deleted collection's
// references have their collection_id nulled (reference.collection_id FK ON
// DELETE SET NULL).
func (q *Queries) DeleteCollection(ctx context.Context, arg DeleteCollectionParams) error {
	_, err := q.db.Exec(ctx, deleteCollection, arg.ID, arg.ProjectID)
	return err
}

const deleteExplorationLead = `-- name: DeleteExplorationLead :exec
DELETE FROM exploration_lead WHERE id = $1 AND project_id = $2
`

type DeleteExplorationLeadParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
}

func (q *Queries) DeleteExplorationLead(ctx context.Context, arg DeleteExplorationLeadParams) error {
	_, err := q.db.Exec(ctx, deleteExplorationLead, arg.ID, arg.ProjectID)
	return err
}

const deletePlanItem = `-- name: DeletePlanItem :exec
DELETE FROM plan_item WHERE id = $1 AND project_id = $2
`

type DeletePlanItemParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
}

func (q *Queries) DeletePlanItem(ctx context.Context, arg DeletePlanItemParams) error {
	_, err := q.db.Exec(ctx, deletePlanItem, arg.ID, arg.ProjectID)
	return err
}

const deletePlanItemsByProject = `-- name: DeletePlanItemsByProject :exec
DELETE FROM plan_item WHERE project_id = $1
`

// Regenerating the plan replaces it wholesale (#15): clear the whole board
// before inserting the freshly generated tasks, in one transaction.
func (q *Queries) DeletePlanItemsByProject(ctx context.Context, projectID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePlanItemsByProject, projectID)
	return err
}

const deleteReference = `-- name: DeleteReference :exec
DELETE FROM reference WHERE id = $1 AND project_id = $2
`

type DeleteReferenceParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
}

func (q *Queries) DeleteReference(ctx context.Context, arg DeleteReferenceParams) error {
	_, err := q.db.Exec(ctx, deleteReference, arg.ID, arg.ProjectID)
	return err
}

const finalizeReadingTakeaway = `-- name: FinalizeReadingTakeaway :one
UPDATE reference
SET takeaway = $3, takeaway_finalized_at = now(), updated_at = now()
WHERE id = $1 AND project_id = $2
RETURNING id, project_id, title, classification, author, credentials, year, url, tags, collection_id, credibility, evaluation, decision, pending, search_hints, material_id, position, created_at, updated_at, reading_reason, reading_focus, phase_tag, takeaway, takeaway_finalized_at, reading_note, abstract, journal
`

type FinalizeReadingTakeawayParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
	Takeaway  []byte    `json:"takeaway"`
}

// Takeaways-out: land the compact 5-field object and stamp finalized_at.
// UPDATE (not insert) — re-finalize on a re-read SUPERSEDES (§1, deliberately
// unlike S1's first-open-wins proposal prose; reading is iterative).
func (q *Queries) FinalizeReadingTakeaway(ctx context.Context, arg FinalizeReadingTakeawayParams) (Reference, error) {
	row := q.db.QueryRow(ctx, finalizeReadingTakeaway, arg.ID, arg.ProjectID, arg.Takeaway)
	var i Reference
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Classification,
		&i.Author,
		&i.Credentials,
		&i.Year,
		&i.Url,
		&i.Tags,
		&i.CollectionID,
		&i.Credibility,
		&i.Evaluation,
		&i.Decision,
		&i.Pending,
		&i.SearchHints,
		&i.MaterialID,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReadingReason,
		&i.ReadingFocus,
		&i.PhaseTag,
		&i.Takeaway,
		&i.TakeawayFinalizedAt,
		&i.ReadingNote,
		&i.Abstract,
		&i.Journal,
	)
	return i, err
}

const getCollection = `-- name: GetCollection :one
SELECT id, project_id, name, parent_id, position, created_at FROM collection WHERE id = $1 AND project_id = $2
`

type GetCollectionParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
}

func (q *Queries) GetCollection(ctx context.Context, arg GetCollectionParams) (Collection, error) {
	row := q.db.QueryRow(ctx, getCollection, arg.ID, arg.ProjectID)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.ParentID,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const getExplorationLeadForProject = `-- name: GetExplorationLeadForProject :one
SELECT id, project_id, text, status, origin, source_reference_id, connected_reference_id, position, created_at, updated_at, parent_lead_id FROM exploration_lead WHERE id = $1 AND project_id = $2
`

type GetExplorationLeadForProjectParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
}

// IDOR guard, mirrors GetReferenceForProject.
func (q *Queries) GetExplorationLeadForProject(ctx context.Context, arg GetExplorationLeadForProjectParams) (ExplorationLead, error) {
	row := q.db.QueryRow(ctx, getExplorationLeadForProject, arg.ID, arg.ProjectID)
	var i ExplorationLead
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Text,
		&i.Status,
		&i.Origin,
		&i.SourceReferenceID,
		&i.ConnectedReferenceID,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ParentLeadID,
	)
	return i, err
}

const getPlanItem = `-- name: GetPlanItem :one
SELECT id, project_id, title, tag, col, stage, ref_material_id, start_day, days, position, created_at, updated_at FROM plan_item WHERE id = $1 AND project_id = $2
`

type GetPlanItemParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
}

func (q *Queries) GetPlanItem(ctx context.Context, arg GetPlanItemParams) (PlanItem, error) {
	row := q.db.QueryRow(ctx, getPlanItem, arg.ID, arg.ProjectID)
	var i PlanItem
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Tag,
		&i.Col,
		&i.Stage,
		&i.RefMaterialID,
		&i.StartDay,
		&i.Days,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectAIUse = `-- name: GetProjectAIUse :one

SELECT project_id, used_for, not_used_for, updated_at FROM project_ai_use WHERE project_id = $1
`

// Review · the five-dimension reflection doc (answers jsonb string array). ----
// S5 · the student's AI-use statement (回顾 · 复盘我与 AI 的互动).
func (q *Queries) GetProjectAIUse(ctx context.Context, projectID uuid.UUID) (ProjectAiUse, error) {
	row := q.db.QueryRow(ctx, getProjectAIUse, projectID)
	var i ProjectAiUse
	err := row.Scan(
		&i.ProjectID,
		&i.UsedFor,
		&i.NotUsedFor,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectMirror = `-- name: GetProjectMirror :one

SELECT project_id, sections, carry_forwards, model, tier, created_at FROM project_mirror_prose WHERE project_id = $1
`

// Review · the 你的思维印记 mirror prose (first-open-wins). -------------------
func (q *Queries) GetProjectMirror(ctx context.Context, projectID uuid.UUID) (ProjectMirrorProse, error) {
	row := q.db.QueryRow(ctx, getProjectMirror, projectID)
	var i ProjectMirrorProse
	err := row.Scan(
		&i.ProjectID,
		&i.Sections,
		&i.CarryForwards,
		&i.Model,
		&i.Tier,
		&i.CreatedAt,
	)
	return i, err
}

const getProjectProposal = `-- name: GetProjectProposal :one
SELECT project_id, objective, reason, activities, resources, updated_at FROM project_proposal WHERE project_id = $1
`

func (q *Queries) GetProjectProposal(ctx context.Context, projectID uuid.UUID) (ProjectProposal, error) {
	row := q.db.QueryRow(ctx, getProjectProposal, projectID)
	var i ProjectProposal
	err := row.Scan(
		&i.ProjectID,
		&i.Objective,
		&i.Reason,
		&i.Activities,
		&i.Resources,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectReflection = `-- name: GetProjectReflection :one
SELECT project_id, answers, done, updated_at FROM project_reflection WHERE project_id = $1
`

func (q *Queries) GetProjectReflection(ctx context.Context, projectID uuid.UUID) (ProjectReflection, error) {
	row := q.db.QueryRow(ctx, getProjectReflection, projectID)
	var i ProjectReflection
	err := row.Scan(
		&i.ProjectID,
		&i.Answers,
		&i.Done,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectSummaryProse = `-- name: GetProjectSummaryProse :one

SELECT project_id, prose, model, tier, created_at FROM project_summary_prose WHERE project_id = $1
`

// S1 · summary-on-return prose (first-open-wins, same pattern as the mirror). --
func (q *Queries) GetProjectSummaryProse(ctx context.Context, projectID uuid.UUID) (ProjectSummaryProse, error) {
	row := q.db.QueryRow(ctx, getProjectSummaryProse, projectID)
	var i ProjectSummaryProse
	err := row.Scan(
		&i.ProjectID,
		&i.Prose,
		&i.Model,
		&i.Tier,
		&i.CreatedAt,
	)
	return i, err
}

const getReference = `-- name: GetReference :one
SELECT id, project_id, title, classification, author, credentials, year, url, tags, collection_id, credibility, evaluation, decision, pending, search_hints, material_id, position, created_at, updated_at, reading_reason, reading_focus, phase_tag, takeaway, takeaway_finalized_at, reading_note, abstract, journal FROM reference WHERE id = $1 AND project_id = $2
`

type GetReferenceParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
}

func (q *Queries) GetReference(ctx context.Context, arg GetReferenceParams) (Reference, error) {
	row := q.db.QueryRow(ctx, getReference, arg.ID, arg.ProjectID)
	var i Reference
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Classification,
		&i.Author,
		&i.Credentials,
		&i.Year,
		&i.Url,
		&i.Tags,
		&i.CollectionID,
		&i.Credibility,
		&i.Evaluation,
		&i.Decision,
		&i.Pending,
		&i.SearchHints,
		&i.MaterialID,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReadingReason,
		&i.ReadingFocus,
		&i.PhaseTag,
		&i.Takeaway,
		&i.TakeawayFinalizedAt,
		&i.ReadingNote,
		&i.Abstract,
		&i.Journal,
	)
	return i, err
}

const getReferenceForProject = `-- name: GetReferenceForProject :one
SELECT id, project_id, title, classification, author, credentials, year, url, tags, collection_id, credibility, evaluation, decision, pending, search_hints, material_id, position, created_at, updated_at, reading_reason, reading_focus, phase_tag, takeaway, takeaway_finalized_at, reading_note, abstract, journal FROM reference WHERE id = $1 AND project_id = $2
`

type GetReferenceForProjectParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
}

// Scope a reference id to its project (the IDOR guard for the reading-brief /
// takeaway endpoints, mirroring patchReference's ownership scoping).
func (q *Queries) GetReferenceForProject(ctx context.Context, arg GetReferenceForProjectParams) (Reference, error) {
	row := q.db.QueryRow(ctx, getReferenceForProject, arg.ID, arg.ProjectID)
	var i Reference
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Classification,
		&i.Author,
		&i.Credentials,
		&i.Year,
		&i.Url,
		&i.Tags,
		&i.CollectionID,
		&i.Credibility,
		&i.Evaluation,
		&i.Decision,
		&i.Pending,
		&i.SearchHints,
		&i.MaterialID,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReadingReason,
		&i.ReadingFocus,
		&i.PhaseTag,
		&i.Takeaway,
		&i.TakeawayFinalizedAt,
		&i.ReadingNote,
		&i.Abstract,
		&i.Journal,
	)
	return i, err
}

const insertProjectMirror = `-- name: InsertProjectMirror :exec
INSERT INTO project_mirror_prose (project_id, sections, carry_forwards, model, tier)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (project_id) DO NOTHING
`

type InsertProjectMirrorParams struct {
	ProjectID     uuid.UUID `json:"project_id"`
	Sections      []byte    `json:"sections"`
	CarryForwards []byte    `json:"carry_forwards"`
	Model         string    `json:"model"`
	Tier          string    `json:"tier"`
}

// First-open-wins: the first composer to insert a row wins; a concurrent loser's
// INSERT is a no-op (ON CONFLICT DO NOTHING) and it re-reads the winner's row.
func (q *Queries) InsertProjectMirror(ctx context.Context, arg InsertProjectMirrorParams) error {
	_, err := q.db.Exec(ctx, insertProjectMirror,
		arg.ProjectID,
		arg.Sections,
		arg.CarryForwards,
		arg.Model,
		arg.Tier,
	)
	return err
}

const insertProjectSummaryProse = `-- name: InsertProjectSummaryProse :exec
INSERT INTO project_summary_prose (project_id, prose, model, tier)
VALUES ($1, $2, $3, $4)
ON CONFLICT (project_id) DO NOTHING
`

type InsertProjectSummaryProseParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Prose     string    `json:"prose"`
	Model     string    `json:"model"`
	Tier      string    `json:"tier"`
}

// First composer wins; a concurrent loser's INSERT is a no-op and it re-reads
// the winner's row. A failed compose is never inserted (retries next open).
func (q *Queries) InsertProjectSummaryProse(ctx context.Context, arg InsertProjectSummaryProseParams) error {
	_, err := q.db.Exec(ctx, insertProjectSummaryProse,
		arg.ProjectID,
		arg.Prose,
		arg.Model,
		arg.Tier,
	)
	return err
}

const listActivityLog = `-- name: ListActivityLog :many
SELECT id, project_id, entry_date, text, source, created_at FROM activity_log_entry
WHERE project_id = $1
ORDER BY entry_date, created_at
`

func (q *Queries) ListActivityLog(ctx context.Context, projectID uuid.UUID) ([]ActivityLogEntry, error) {
	rows, err := q.db.Query(ctx, listActivityLog, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActivityLogEntry
	for rows.Next() {
		var i ActivityLogEntry
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.EntryDate,
			&i.Text,
			&i.Source,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCollections = `-- name: ListCollections :many

SELECT id, project_id, name, parent_id, position, created_at FROM collection
WHERE project_id = $1
ORDER BY position, created_at
`

// Read library · collections (self-referential tree). ---------------------
func (q *Queries) ListCollections(ctx context.Context, projectID uuid.UUID) ([]Collection, error) {
	rows, err := q.db.Query(ctx, listCollections, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Collection
	for rows.Next() {
		var i Collection
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.ParentID,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExplorationLeads = `-- name: ListExplorationLeads :many

SELECT id, project_id, text, status, origin, source_reference_id, connected_reference_id, position, created_at, updated_at, parent_lead_id FROM exploration_lead
WHERE project_id = $1
ORDER BY position, created_at
`

// S3 · rabbit-hole exploration leads (branch off reading takeaways). ---------
func (q *Queries) ListExplorationLeads(ctx context.Context, projectID uuid.UUID) ([]ExplorationLead, error) {
	rows, err := q.db.Query(ctx, listExplorationLeads, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExplorationLead
	for rows.Next() {
		var i ExplorationLead
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Text,
			&i.Status,
			&i.Origin,
			&i.SourceReferenceID,
			&i.ConnectedReferenceID,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ParentLeadID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOutlineNodes = `-- name: ListOutlineNodes :many

SELECT id, project_id, text, depth, position, created_at, updated_at FROM outline_node
WHERE project_id = $1
ORDER BY position, created_at
`

// Write · outline nodes (depth-indexed flat list, projected to a tree). ------
func (q *Queries) ListOutlineNodes(ctx context.Context, projectID uuid.UUID) ([]OutlineNode, error) {
	rows, err := q.db.Query(ctx, listOutlineNodes, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutlineNode
	for rows.Next() {
		var i OutlineNode
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Text,
			&i.Depth,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlanItems = `-- name: ListPlanItems :many
SELECT id, project_id, title, tag, col, stage, ref_material_id, start_day, days, position, created_at, updated_at FROM plan_item
WHERE project_id = $1
ORDER BY stage, position, start_day, created_at
`

func (q *Queries) ListPlanItems(ctx context.Context, projectID uuid.UUID) ([]PlanItem, error) {
	rows, err := q.db.Query(ctx, listPlanItems, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlanItem
	for rows.Next() {
		var i PlanItem
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Tag,
			&i.Col,
			&i.Stage,
			&i.RefMaterialID,
			&i.StartDay,
			&i.Days,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReferences = `-- name: ListReferences :many

SELECT id, project_id, title, classification, author, credentials, year, url, tags, collection_id, credibility, evaluation, decision, pending, search_hints, material_id, position, created_at, updated_at, reading_reason, reading_focus, phase_tag, takeaway, takeaway_finalized_at, reading_note, abstract, journal FROM reference
WHERE project_id = $1
ORDER BY position, created_at
`

// Read library · references. -----------------------------------------------
func (q *Queries) ListReferences(ctx context.Context, projectID uuid.UUID) ([]Reference, error) {
	rows, err := q.db.Query(ctx, listReferences, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reference
	for rows.Next() {
		var i Reference
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Classification,
			&i.Author,
			&i.Credentials,
			&i.Year,
			&i.Url,
			&i.Tags,
			&i.CollectionID,
			&i.Credibility,
			&i.Evaluation,
			&i.Decision,
			&i.Pending,
			&i.SearchHints,
			&i.MaterialID,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReadingReason,
			&i.ReadingFocus,
			&i.PhaseTag,
			&i.Takeaway,
			&i.TakeawayFinalizedAt,
			&i.ReadingNote,
			&i.Abstract,
			&i.Journal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSnippets = `-- name: ListSnippets :many

SELECT id, project_id, text, position, created_at, section FROM snippet
WHERE project_id = $1
ORDER BY position, created_at
`

// Write · snippets (片段: flat, ordered text fragments). -----------------------
func (q *Queries) ListSnippets(ctx context.Context, projectID uuid.UUID) ([]Snippet, error) {
	rows, err := q.db.Query(ctx, listSnippets, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Snippet
	for rows.Next() {
		var i Snippet
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Text,
			&i.Position,
			&i.CreatedAt,
			&i.Section,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setReferenceMaterial = `-- name: SetReferenceMaterial :one
UPDATE reference SET
    material_id = $3,
    updated_at  = now()
WHERE id = $1 AND project_id = $2
RETURNING id, project_id, title, classification, author, credentials, year, url, tags, collection_id, credibility, evaluation, decision, pending, search_hints, material_id, position, created_at, updated_at, reading_reason, reading_focus, phase_tag, takeaway, takeaway_finalized_at, reading_note, abstract, journal
`

type SetReferenceMaterialParams struct {
	ID         uuid.UUID   `json:"id"`
	ProjectID  uuid.UUID   `json:"project_id"`
	MaterialID pgtype.UUID `json:"material_id"`
}

// Binds a reference to the material fetched/created for it on enter-reading.
func (q *Queries) SetReferenceMaterial(ctx context.Context, arg SetReferenceMaterialParams) (Reference, error) {
	row := q.db.QueryRow(ctx, setReferenceMaterial, arg.ID, arg.ProjectID, arg.MaterialID)
	var i Reference
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Classification,
		&i.Author,
		&i.Credentials,
		&i.Year,
		&i.Url,
		&i.Tags,
		&i.CollectionID,
		&i.Credibility,
		&i.Evaluation,
		&i.Decision,
		&i.Pending,
		&i.SearchHints,
		&i.MaterialID,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReadingReason,
		&i.ReadingFocus,
		&i.PhaseTag,
		&i.Takeaway,
		&i.TakeawayFinalizedAt,
		&i.ReadingNote,
		&i.Abstract,
		&i.Journal,
	)
	return i, err
}

const updateCollection = `-- name: UpdateCollection :one
UPDATE collection SET
    name      = $3,
    parent_id = $4,
    position  = $5
WHERE id = $1 AND project_id = $2
RETURNING id, project_id, name, parent_id, position, created_at
`

type UpdateCollectionParams struct {
	ID        uuid.UUID   `json:"id"`
	ProjectID uuid.UUID   `json:"project_id"`
	Name      string      `json:"name"`
	ParentID  pgtype.UUID `json:"parent_id"`
	Position  int32       `json:"position"`
}

// Sets ALL columns by id + project_id; the handler merges partial patches over
// the current row before calling this (UpdatePlanItem's pattern).
func (q *Queries) UpdateCollection(ctx context.Context, arg UpdateCollectionParams) (Collection, error) {
	row := q.db.QueryRow(ctx, updateCollection,
		arg.ID,
		arg.ProjectID,
		arg.Name,
		arg.ParentID,
		arg.Position,
	)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.ParentID,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const updateExplorationLead = `-- name: UpdateExplorationLead :one
UPDATE exploration_lead SET
    text                   = $3,
    status                 = $4,
    connected_reference_id = $5,
    position               = $6,
    updated_at             = now()
WHERE id = $1 AND project_id = $2
RETURNING id, project_id, text, status, origin, source_reference_id, connected_reference_id, position, created_at, updated_at, parent_lead_id
`

type UpdateExplorationLeadParams struct {
	ID                   uuid.UUID   `json:"id"`
	ProjectID            uuid.UUID   `json:"project_id"`
	Text                 string      `json:"text"`
	Status               string      `json:"status"`
	ConnectedReferenceID pgtype.UUID `json:"connected_reference_id"`
	Position             int32       `json:"position"`
}

// Sets text, status, connected_reference_id, position by id + project_id; the
// handler merges partial patches over the current row first (UpdatePlanItem's
// pattern).
func (q *Queries) UpdateExplorationLead(ctx context.Context, arg UpdateExplorationLeadParams) (ExplorationLead, error) {
	row := q.db.QueryRow(ctx, updateExplorationLead,
		arg.ID,
		arg.ProjectID,
		arg.Text,
		arg.Status,
		arg.ConnectedReferenceID,
		arg.Position,
	)
	var i ExplorationLead
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Text,
		&i.Status,
		&i.Origin,
		&i.SourceReferenceID,
		&i.ConnectedReferenceID,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ParentLeadID,
	)
	return i, err
}

const updatePlanItem = `-- name: UpdatePlanItem :one
UPDATE plan_item SET
    title           = $3,
    tag             = $4,
    col             = $5,
    stage           = $6,
    ref_material_id = $7,
    start_day       = $8,
    days            = $9,
    position        = $10,
    updated_at      = now()
WHERE id = $1 AND project_id = $2
RETURNING id, project_id, title, tag, col, stage, ref_material_id, start_day, days, position, created_at, updated_at
`

type UpdatePlanItemParams struct {
	ID            uuid.UUID   `json:"id"`
	ProjectID     uuid.UUID   `json:"project_id"`
	Title         string      `json:"title"`
	Tag           string      `json:"tag"`
	Col           string      `json:"col"`
	Stage         string      `json:"stage"`
	RefMaterialID pgtype.UUID `json:"ref_material_id"`
	StartDay      int32       `json:"start_day"`
	Days          int32       `json:"days"`
	Position      int32       `json:"position"`
}

// Sets ALL columns by id + project_id; the handler merges partial patches over
// the current row before calling this, so every field is always supplied.
func (q *Queries) UpdatePlanItem(ctx context.Context, arg UpdatePlanItemParams) (PlanItem, error) {
	row := q.db.QueryRow(ctx, updatePlanItem,
		arg.ID,
		arg.ProjectID,
		arg.Title,
		arg.Tag,
		arg.Col,
		arg.Stage,
		arg.RefMaterialID,
		arg.StartDay,
		arg.Days,
		arg.Position,
	)
	var i PlanItem
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Tag,
		&i.Col,
		&i.Stage,
		&i.RefMaterialID,
		&i.StartDay,
		&i.Days,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateReadingBrief = `-- name: UpdateReadingBrief :one
UPDATE reference
SET reading_reason = $3, reading_focus = $4, phase_tag = $5, updated_at = now()
WHERE id = $1 AND project_id = $2
RETURNING id, project_id, title, classification, author, credentials, year, url, tags, collection_id, credibility, evaluation, decision, pending, search_hints, material_id, position, created_at, updated_at, reading_reason, reading_focus, phase_tag, takeaway, takeaway_finalized_at, reading_note, abstract, journal
`

type UpdateReadingBriefParams struct {
	ID            uuid.UUID `json:"id"`
	ProjectID     uuid.UUID `json:"project_id"`
	ReadingReason *string   `json:"reading_reason"`
	ReadingFocus  *string   `json:"reading_focus"`
	PhaseTag      *string   `json:"phase_tag"`
}

// Brief-in: persist why-read-this + optional focus + phase_tag on the source.
// Editable any time; does not touch the takeaway.
func (q *Queries) UpdateReadingBrief(ctx context.Context, arg UpdateReadingBriefParams) (Reference, error) {
	row := q.db.QueryRow(ctx, updateReadingBrief,
		arg.ID,
		arg.ProjectID,
		arg.ReadingReason,
		arg.ReadingFocus,
		arg.PhaseTag,
	)
	var i Reference
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Classification,
		&i.Author,
		&i.Credentials,
		&i.Year,
		&i.Url,
		&i.Tags,
		&i.CollectionID,
		&i.Credibility,
		&i.Evaluation,
		&i.Decision,
		&i.Pending,
		&i.SearchHints,
		&i.MaterialID,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReadingReason,
		&i.ReadingFocus,
		&i.PhaseTag,
		&i.Takeaway,
		&i.TakeawayFinalizedAt,
		&i.ReadingNote,
		&i.Abstract,
		&i.Journal,
	)
	return i, err
}

const updateReference = `-- name: UpdateReference :one
UPDATE reference SET
    title          = $3,
    classification = $4,
    author         = $5,
    credentials    = $6,
    year           = $7,
    url            = $8,
    tags           = $9,
    collection_id  = $10,
    credibility    = $11,
    evaluation     = $12,
    decision       = $13,
    pending        = $14,
    search_hints   = $15,
    reading_note   = $16,
    abstract       = $17,
    journal        = $18,
    updated_at     = now()
WHERE id = $1 AND project_id = $2
RETURNING id, project_id, title, classification, author, credentials, year, url, tags, collection_id, credibility, evaluation, decision, pending, search_hints, material_id, position, created_at, updated_at, reading_reason, reading_focus, phase_tag, takeaway, takeaway_finalized_at, reading_note, abstract, journal
`

type UpdateReferenceParams struct {
	ID             uuid.UUID   `json:"id"`
	ProjectID      uuid.UUID   `json:"project_id"`
	Title          string      `json:"title"`
	Classification string      `json:"classification"`
	Author         string      `json:"author"`
	Credentials    string      `json:"credentials"`
	Year           string      `json:"year"`
	Url            string      `json:"url"`
	Tags           []byte      `json:"tags"`
	CollectionID   pgtype.UUID `json:"collection_id"`
	Credibility    *string     `json:"credibility"`
	Evaluation     string      `json:"evaluation"`
	Decision       *string     `json:"decision"`
	Pending        bool        `json:"pending"`
	SearchHints    []byte      `json:"search_hints"`
	ReadingNote    string      `json:"reading_note"`
	Abstract       string      `json:"abstract"`
	Journal        string      `json:"journal"`
}

// Sets ALL editable columns by id + project_id; the handler merges partial
// patches over the current row first (UpdatePlanItem's pattern). material_id is
// NOT set here — SetReferenceMaterial owns that link (enter-reading only).
func (q *Queries) UpdateReference(ctx context.Context, arg UpdateReferenceParams) (Reference, error) {
	row := q.db.QueryRow(ctx, updateReference,
		arg.ID,
		arg.ProjectID,
		arg.Title,
		arg.Classification,
		arg.Author,
		arg.Credentials,
		arg.Year,
		arg.Url,
		arg.Tags,
		arg.CollectionID,
		arg.Credibility,
		arg.Evaluation,
		arg.Decision,
		arg.Pending,
		arg.SearchHints,
		arg.ReadingNote,
		arg.Abstract,
		arg.Journal,
	)
	var i Reference
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Classification,
		&i.Author,
		&i.Credentials,
		&i.Year,
		&i.Url,
		&i.Tags,
		&i.CollectionID,
		&i.Credibility,
		&i.Evaluation,
		&i.Decision,
		&i.Pending,
		&i.SearchHints,
		&i.MaterialID,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReadingReason,
		&i.ReadingFocus,
		&i.PhaseTag,
		&i.Takeaway,
		&i.TakeawayFinalizedAt,
		&i.ReadingNote,
		&i.Abstract,
		&i.Journal,
	)
	return i, err
}

const upsertProjectAIUse = `-- name: UpsertProjectAIUse :exec
INSERT INTO project_ai_use (project_id, used_for, not_used_for, updated_at)
VALUES ($1, $2, $3, now())
ON CONFLICT (project_id) DO UPDATE SET
    used_for     = EXCLUDED.used_for,
    not_used_for = EXCLUDED.not_used_for,
    updated_at   = now()
`

type UpsertProjectAIUseParams struct {
	ProjectID  uuid.UUID `json:"project_id"`
	UsedFor    string    `json:"used_for"`
	NotUsedFor string    `json:"not_used_for"`
}

func (q *Queries) UpsertProjectAIUse(ctx context.Context, arg UpsertProjectAIUseParams) error {
	_, err := q.db.Exec(ctx, upsertProjectAIUse, arg.ProjectID, arg.UsedFor, arg.NotUsedFor)
	return err
}

const upsertProjectProposal = `-- name: UpsertProjectProposal :one
INSERT INTO project_proposal (project_id, objective, reason, activities, resources, updated_at)
VALUES ($1, $2, $3, $4, $5, now())
ON CONFLICT (project_id) DO UPDATE SET
    objective  = EXCLUDED.objective,
    reason     = EXCLUDED.reason,
    activities = EXCLUDED.activities,
    resources  = EXCLUDED.resources,
    updated_at = now()
RETURNING project_id, objective, reason, activities, resources, updated_at
`

type UpsertProjectProposalParams struct {
	ProjectID  uuid.UUID `json:"project_id"`
	Objective  string    `json:"objective"`
	Reason     string    `json:"reason"`
	Activities string    `json:"activities"`
	Resources  string    `json:"resources"`
}

func (q *Queries) UpsertProjectProposal(ctx context.Context, arg UpsertProjectProposalParams) (ProjectProposal, error) {
	row := q.db.QueryRow(ctx, upsertProjectProposal,
		arg.ProjectID,
		arg.Objective,
		arg.Reason,
		arg.Activities,
		arg.Resources,
	)
	var i ProjectProposal
	err := row.Scan(
		&i.ProjectID,
		&i.Objective,
		&i.Reason,
		&i.Activities,
		&i.Resources,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertProjectReflection = `-- name: UpsertProjectReflection :one
INSERT INTO project_reflection (project_id, answers, done, updated_at)
VALUES ($1, $2, $3, now())
ON CONFLICT (project_id) DO UPDATE SET
    answers    = EXCLUDED.answers,
    done       = EXCLUDED.done,
    updated_at = now()
RETURNING project_id, answers, done, updated_at
`

type UpsertProjectReflectionParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Answers   []byte    `json:"answers"`
	Done      bool      `json:"done"`
}

func (q *Queries) UpsertProjectReflection(ctx context.Context, arg UpsertProjectReflectionParams) (ProjectReflection, error) {
	row := q.db.QueryRow(ctx, upsertProjectReflection, arg.ProjectID, arg.Answers, arg.Done)
	var i ProjectReflection
	err := row.Scan(
		&i.ProjectID,
		&i.Answers,
		&i.Done,
		&i.UpdatedAt,
	)
	return i, err
}
