// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: writing_atom.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createWriting = `-- name: CreateWriting :one

INSERT INTO writing (atom_id, title, lang) VALUES ($1, $2, $3) RETURNING atom_id, title, lang, stage, target_words, status, updated_at, finished_at
`

type CreateWritingParams struct {
	AtomID uuid.UUID `json:"atom_id"`
	Title  string    `json:"title"`
	Lang   string    `json:"lang"`
}

// Writing's own atom-kind tables (0099): writing / writing_outline /
// writing_snippet / writing_draft. Named writing_atom.sql, not writing.sql —
// queries/writing.sql already exists for the unrelated pro-product edit
// buffer + draft snapshot feature (project_id-scoped, Slice 8/S5). The two
// "writing"s share a word, not a table or a domain.
func (q *Queries) CreateWriting(ctx context.Context, arg CreateWritingParams) (Writing, error) {
	row := q.db.QueryRow(ctx, createWriting, arg.AtomID, arg.Title, arg.Lang)
	var i Writing
	err := row.Scan(
		&i.AtomID,
		&i.Title,
		&i.Lang,
		&i.Stage,
		&i.TargetWords,
		&i.Status,
		&i.UpdatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getWriting = `-- name: GetWriting :one
SELECT atom_id, title, lang, stage, target_words, status, updated_at, finished_at FROM writing WHERE atom_id = $1
`

func (q *Queries) GetWriting(ctx context.Context, atomID uuid.UUID) (Writing, error) {
	row := q.db.QueryRow(ctx, getWriting, atomID)
	var i Writing
	err := row.Scan(
		&i.AtomID,
		&i.Title,
		&i.Lang,
		&i.Stage,
		&i.TargetWords,
		&i.Status,
		&i.UpdatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getWritingDraft = `-- name: GetWritingDraft :one
SELECT atom_id, body, updated_at FROM writing_draft WHERE atom_id = $1
`

func (q *Queries) GetWritingDraft(ctx context.Context, atomID uuid.UUID) (WritingDraft, error) {
	row := q.db.QueryRow(ctx, getWritingDraft, atomID)
	var i WritingDraft
	err := row.Scan(&i.AtomID, &i.Body, &i.UpdatedAt)
	return i, err
}

const listWritingOutline = `-- name: ListWritingOutline :many
SELECT id, atom_id, text, depth, position FROM writing_outline WHERE atom_id = $1 ORDER BY position
`

func (q *Queries) ListWritingOutline(ctx context.Context, atomID uuid.UUID) ([]WritingOutline, error) {
	rows, err := q.db.Query(ctx, listWritingOutline, atomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WritingOutline
	for rows.Next() {
		var i WritingOutline
		if err := rows.Scan(
			&i.ID,
			&i.AtomID,
			&i.Text,
			&i.Depth,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWritingSnippets = `-- name: ListWritingSnippets :many
SELECT id, atom_id, outline_id, position, text, updated_at FROM writing_snippet WHERE atom_id = $1 ORDER BY position
`

func (q *Queries) ListWritingSnippets(ctx context.Context, atomID uuid.UUID) ([]WritingSnippet, error) {
	rows, err := q.db.Query(ctx, listWritingSnippets, atomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WritingSnippet
	for rows.Next() {
		var i WritingSnippet
		if err := rows.Scan(
			&i.ID,
			&i.AtomID,
			&i.OutlineID,
			&i.Position,
			&i.Text,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWritingsByUser = `-- name: ListWritingsByUser :many
SELECT w.atom_id, w.title, w.lang, w.stage, w.target_words, w.status, w.updated_at, w.finished_at
FROM writing w
JOIN atom a ON a.id = w.atom_id
WHERE a.user_id = $1 AND a.kind = 'writing'
ORDER BY a.created_at DESC
`

// The list the 写作 tab shows. Joins atom for ownership + creation order,
// same shape as ListReadingsByUser.
func (q *Queries) ListWritingsByUser(ctx context.Context, userID uuid.UUID) ([]Writing, error) {
	rows, err := q.db.Query(ctx, listWritingsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Writing
	for rows.Next() {
		var i Writing
		if err := rows.Scan(
			&i.AtomID,
			&i.Title,
			&i.Lang,
			&i.Stage,
			&i.TargetWords,
			&i.Status,
			&i.UpdatedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameWriting = `-- name: RenameWriting :exec
UPDATE writing SET title = $2, updated_at = now() WHERE atom_id = $1
`

type RenameWritingParams struct {
	AtomID uuid.UUID `json:"atom_id"`
	Title  string    `json:"title"`
}

func (q *Queries) RenameWriting(ctx context.Context, arg RenameWritingParams) error {
	_, err := q.db.Exec(ctx, renameWriting, arg.AtomID, arg.Title)
	return err
}

const replaceWritingOutline = `-- name: ReplaceWritingOutline :many
WITH deleted AS (
  DELETE FROM writing_outline WHERE atom_id = $1
)
INSERT INTO writing_outline (atom_id, text, depth, position)
SELECT $1,
       unnest($2::text[]),
       unnest($3::int[]),
       unnest($4::int[])
RETURNING id, atom_id, text, depth, position
`

type ReplaceWritingOutlineParams struct {
	AtomID    uuid.UUID `json:"atom_id"`
	Texts     []string  `json:"texts"`
	Depths    []int32   `json:"depths"`
	Positions []int32   `json:"positions"`
}

// Full replace, not a diff: the whole outline is written as one shape each
// PUT (学生可改 the derived outline wholesale), so delete-then-insert keeps
// position contiguous and never leaves a stale tail row behind. The DELETE
// and INSERT run as ONE statement (a data-modifying CTE), so a concurrent
// reader never observes a momentarily-empty outline between the two.
func (q *Queries) ReplaceWritingOutline(ctx context.Context, arg ReplaceWritingOutlineParams) ([]WritingOutline, error) {
	rows, err := q.db.Query(ctx, replaceWritingOutline,
		arg.AtomID,
		arg.Texts,
		arg.Depths,
		arg.Positions,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WritingOutline
	for rows.Next() {
		var i WritingOutline
		if err := rows.Scan(
			&i.ID,
			&i.AtomID,
			&i.Text,
			&i.Depth,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setWritingFinished = `-- name: SetWritingFinished :exec
UPDATE writing SET status = 'finished', finished_at = now(), updated_at = now()
WHERE atom_id = $1 AND status <> 'finished'
`

// Guarded on status, like SetReadingFinished: a second /finish is a genuine
// no-op so finished_at never drifts after the fact (铁律④ makes it evidence).
// Deliberately does NOT force stage to 'finished' — a student who skipped
// straight to a finished draft without ever touching 提纲/片段 keeps that
// fact recorded in stage for the report, rather than having it silently
// overwritten at finish time.
func (q *Queries) SetWritingFinished(ctx context.Context, atomID uuid.UUID) error {
	_, err := q.db.Exec(ctx, setWritingFinished, atomID)
	return err
}

const setWritingStage = `-- name: SetWritingStage :one
UPDATE writing SET stage = $2, updated_at = now() WHERE atom_id = $1 RETURNING atom_id, title, lang, stage, target_words, status, updated_at, finished_at
`

type SetWritingStageParams struct {
	AtomID uuid.UUID `json:"atom_id"`
	Stage  string    `json:"stage"`
}

// No gate here on purpose (§6.2.3): stages are a map shown to the student,
// not a checkpoint the server enforces, so any legal value is accepted in any
// order. The CHECK constraint is the only guard.
func (q *Queries) SetWritingStage(ctx context.Context, arg SetWritingStageParams) (Writing, error) {
	row := q.db.QueryRow(ctx, setWritingStage, arg.AtomID, arg.Stage)
	var i Writing
	err := row.Scan(
		&i.AtomID,
		&i.Title,
		&i.Lang,
		&i.Stage,
		&i.TargetWords,
		&i.Status,
		&i.UpdatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const setWritingTargetWords = `-- name: SetWritingTargetWords :exec
UPDATE writing SET target_words = $2, updated_at = now() WHERE atom_id = $1
`

type SetWritingTargetWordsParams struct {
	AtomID      uuid.UUID `json:"atom_id"`
	TargetWords *int32    `json:"target_words"`
}

func (q *Queries) SetWritingTargetWords(ctx context.Context, arg SetWritingTargetWordsParams) error {
	_, err := q.db.Exec(ctx, setWritingTargetWords, arg.AtomID, arg.TargetWords)
	return err
}

const upsertWritingDraft = `-- name: UpsertWritingDraft :one
INSERT INTO writing_draft (atom_id, body)
VALUES ($1, $2)
ON CONFLICT (atom_id) DO UPDATE SET body = EXCLUDED.body, updated_at = now()
RETURNING atom_id, body, updated_at
`

type UpsertWritingDraftParams struct {
	AtomID uuid.UUID `json:"atom_id"`
	Body   string    `json:"body"`
}

func (q *Queries) UpsertWritingDraft(ctx context.Context, arg UpsertWritingDraftParams) (WritingDraft, error) {
	row := q.db.QueryRow(ctx, upsertWritingDraft, arg.AtomID, arg.Body)
	var i WritingDraft
	err := row.Scan(&i.AtomID, &i.Body, &i.UpdatedAt)
	return i, err
}

const upsertWritingSnippet = `-- name: UpsertWritingSnippet :one
INSERT INTO writing_snippet (atom_id, outline_id, position, text)
VALUES ($1, $2, $3, $4)
ON CONFLICT (atom_id, position) DO UPDATE
  SET outline_id = EXCLUDED.outline_id, text = EXCLUDED.text, updated_at = now()
RETURNING id, atom_id, outline_id, position, text, updated_at
`

type UpsertWritingSnippetParams struct {
	AtomID    uuid.UUID   `json:"atom_id"`
	OutlineID pgtype.UUID `json:"outline_id"`
	Position  int32       `json:"position"`
	Text      string      `json:"text"`
}

// Keyed by (atom_id, position) — writing the same slot again edits it in
// place, it never duplicates a row (writing_snippet_atom_position_idx, 0099).
func (q *Queries) UpsertWritingSnippet(ctx context.Context, arg UpsertWritingSnippetParams) (WritingSnippet, error) {
	row := q.db.QueryRow(ctx, upsertWritingSnippet,
		arg.AtomID,
		arg.OutlineID,
		arg.Position,
		arg.Text,
	)
	var i WritingSnippet
	err := row.Scan(
		&i.ID,
		&i.AtomID,
		&i.OutlineID,
		&i.Position,
		&i.Text,
		&i.UpdatedAt,
	)
	return i, err
}
