// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: writing_version.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countWritingVersions = `-- name: CountWritingVersions :one
SELECT count(*)::int FROM writing_version WHERE atom_id = $1
`

func (q *Queries) CountWritingVersions(ctx context.Context, atomID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countWritingVersions, atomID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createWritingVersion = `-- name: CreateWritingVersion :one
INSERT INTO writing_version (atom_id, number, title, body, word_count)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, atom_id, number, title, body, word_count, submitted_at
`

type CreateWritingVersionParams struct {
	AtomID    uuid.UUID `json:"atom_id"`
	Number    int32     `json:"number"`
	Title     string    `json:"title"`
	Body      string    `json:"body"`
	WordCount int32     `json:"word_count"`
}

func (q *Queries) CreateWritingVersion(ctx context.Context, arg CreateWritingVersionParams) (WritingVersion, error) {
	row := q.db.QueryRow(ctx, createWritingVersion,
		arg.AtomID,
		arg.Number,
		arg.Title,
		arg.Body,
		arg.WordCount,
	)
	var i WritingVersion
	err := row.Scan(
		&i.ID,
		&i.AtomID,
		&i.Number,
		&i.Title,
		&i.Body,
		&i.WordCount,
		&i.SubmittedAt,
	)
	return i, err
}

const getLatestWritingVersion = `-- name: GetLatestWritingVersion :one
SELECT id, atom_id, number, title, body, word_count, submitted_at FROM writing_version WHERE atom_id = $1 ORDER BY number DESC LIMIT 1
`

func (q *Queries) GetLatestWritingVersion(ctx context.Context, atomID uuid.UUID) (WritingVersion, error) {
	row := q.db.QueryRow(ctx, getLatestWritingVersion, atomID)
	var i WritingVersion
	err := row.Scan(
		&i.ID,
		&i.AtomID,
		&i.Number,
		&i.Title,
		&i.Body,
		&i.WordCount,
		&i.SubmittedAt,
	)
	return i, err
}

const getWritingVersion = `-- name: GetWritingVersion :one
SELECT id, atom_id, number, title, body, word_count, submitted_at FROM writing_version WHERE atom_id = $1 AND number = $2
`

type GetWritingVersionParams struct {
	AtomID uuid.UUID `json:"atom_id"`
	Number int32     `json:"number"`
}

func (q *Queries) GetWritingVersion(ctx context.Context, arg GetWritingVersionParams) (WritingVersion, error) {
	row := q.db.QueryRow(ctx, getWritingVersion, arg.AtomID, arg.Number)
	var i WritingVersion
	err := row.Scan(
		&i.ID,
		&i.AtomID,
		&i.Number,
		&i.Title,
		&i.Body,
		&i.WordCount,
		&i.SubmittedAt,
	)
	return i, err
}

const listWritingVersions = `-- name: ListWritingVersions :many
SELECT id, atom_id, number, title, word_count, submitted_at
FROM writing_version
WHERE atom_id = $1
ORDER BY number DESC
`

type ListWritingVersionsRow struct {
	ID          uuid.UUID `json:"id"`
	AtomID      uuid.UUID `json:"atom_id"`
	Number      int32     `json:"number"`
	Title       string    `json:"title"`
	WordCount   int32     `json:"word_count"`
	SubmittedAt time.Time `json:"submitted_at"`
}

// 版本列表不带正文，新的在前。
func (q *Queries) ListWritingVersions(ctx context.Context, atomID uuid.UUID) ([]ListWritingVersionsRow, error) {
	rows, err := q.db.Query(ctx, listWritingVersions, atomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWritingVersionsRow
	for rows.Next() {
		var i ListWritingVersionsRow
		if err := rows.Scan(
			&i.ID,
			&i.AtomID,
			&i.Number,
			&i.Title,
			&i.WordCount,
			&i.SubmittedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextWritingVersionNumber = `-- name: NextWritingVersionNumber :one

SELECT (COALESCE(max(number), 0) + 1)::int FROM writing_version WHERE atom_id = $1
`

// Lite 写作的提交版本（0153）。只插入、只读，没有 UPDATE 或 DELETE。
// 与 CreateWritingVersion 放在同一个事务里，并先锁住 writing 行（GetWritingForUpdate）。
func (q *Queries) NextWritingVersionNumber(ctx context.Context, atomID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextWritingVersionNumber, atomID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}
