import {FinishedReadingPanel} from "../../src/readings/ReadingRoomHost";
import {studentArtwork} from "../../src/learning/StudentArtwork";
import {createRoot} from "react-dom/client";
import {GuestTheme} from "../../src/learning/GuestTheme";
import {TreeView} from "../../src/tree/TreeView";
import {HubScene} from "../../src/awakening/scenes/Hub";
import {EnergyScene} from "../../src/awakening/scenes/Cards";
import {ReportView} from "../../src/awakening/ReportView";
import {RoomShell} from "../../src/awakening/RoomShell";
import {TALENT_CARDS} from "../../src/awakening/content";
import "../../src/index.css";
import "../../src/awakening/awakening.css";
const action=(s:string)=>()=>{document.body.dataset.lastAction=s};
const readingReport={version:1,kind:"reading",title:"城市为什么越来越热？",studentName:"小林",finishedAt:"2026-09-22T09:30:00Z",ordinal:8,stats:[{key:"focusMinutes",label:"阅读时长",value:21,unit:"分钟"}],moments:[],keep:{label:"我的收获",text:"我想比较树荫和建筑阴影对街道温度的影响。",source:"student"},gains:[],lensNotes:[],notes:[],excerpts:["Trees cool the air through shade and evaporation."],turningPoints:[],article:null,piece:"",prosePending:false};
const originalFetch=window.fetch.bind(window);
const requests: {url:string,method:string}[]=[];
(window as any).__requests=requests;
window.fetch=(async(url:any,init?:RequestInit)=>{if (!String(url).includes("/api/")) return originalFetch(url,init); requests.push({url:String(url),method:init?.method??"GET"}); const u=String(url); const body=u.endsWith("/report")?{report:readingReport}:u.endsWith("/source")?{title:readingReport.title,sourceUrl:"https://example.org/article",byline:"阅读预览 · 示例文章",blocks:[{id:"h1",text:"Understanding urban heat"},{id:"b1",text:"Cities can be warmer than the surrounding countryside. Roads and buildings absorb heat during the day and release it at night."},{id:"b2",text:"Trees cool the air through shade and evaporation. A shaded street can feel very different from an open square."},{id:"b3",text:"To understand the difference, researchers measure temperatures at different times and compare streets with different amounts of tree cover."}],headings:["h1"],figures:[{after:"",url:studentArtwork.discovery,width:600,height:400,caption:"城市环境与气候 · 预览插图",credit:""}]}:u.endsWith("/messages")?{messages:[{seq:1,role:"ai",content:"这篇文章提出了哪些降温方法？请从原文中找出依据。"},{seq:2,role:"student",content:"树荫和蒸发可以降温，但还需要比较不同街道的数据。"},{seq:3,role:"ai",content:"你区分了文章的解释和需要验证的证据。\n\n如果要比较两条街道，你会控制哪些条件？"}]}:u.endsWith("/questions")?{questions:[]}:{taken:true,open:true,latestReportRunId:"fixture-report"};return new Response(JSON.stringify(body),{headers:{"content-type":"application/json"}})}) as typeof fetch;
const words=[{id:"k1",interestId:"climate",text:"气候变化",en:"Climate",field:"science",strength:3,bornAt:0,firstSeenAt:"2026-09-20",note:"关注气候数据与人类活动的关系。",sources:[{kind:"reading",id:"r1",label:"城市的夏天",evidence:"我想知道树木能否降低街道的温度。",date:"2026-09-20"}],disciplineIds:[],at:{t:.7,spread:0}},{id:"k2",interestId:"city",text:"城市设计",en:"Urban design",field:"making",strength:2,bornAt:0,firstSeenAt:"2026-09-20",note:"关注城市空间。",sources:[],disciplineIds:[],at:{t:.55,spread:0}}];
const report={version:1,attemptNo:2,navigator:"",pursuing:words.map((w,i)=>({interestId:w.id,zh:w.text,en:w.en,field:w.field,note:w.note,evidence:i?"我想设计一条走起来更凉快的街道。":"我想知道树木能否降低街道的温度。",verdict:i?"grow":"confirm",strength:w.strength})),drivers:[{label:"理解现象背后的原因",evidence:"我会继续查找影响温度的因素。",confidence:.76}],question:"树木和建筑的排列，会怎样影响街道的温度？",workConcept:"我想记录学校周围几条街道的温度，并画出不同时间的变化。",talent:[{key:"love",label:"喜欢且擅长",cards:TALENT_CARDS.slice(0,2).map(c=>c.id)},{key:"learn",label:"喜欢，想练习",cards:TALENT_CARDS.slice(2,5).map(c=>c.id)},{key:"other",label:"暂不优先",cards:[]}],readings:[{slug:"fixture-city",title:"Cities and heat",zhTitle:"城市为什么越来越热？",field:"science",tier:2,why:["与你提出的街道温度问题相关"]}],openFields:[],selectionFailed:false,summary:"这次探索集中在城市环境与气候变化。你希望通过观察、测量和设计来验证自己的想法。",diff:null,answers:[],createdAt:"2026-09-22"};
const params=new URLSearchParams(location.search);
const view=params.get("view")??"tree";
if(params.get("theme")==="dark") document.documentElement.dataset.theme="dark";
const empty=params.has("empty");
if(empty) Object.assign(report,{pursuing:[],drivers:[],question:"",workConcept:"",talent:[],readings:[],summary:"",openFields:[],diff:null});
const body=view==="reading"?<FinishedReadingPanel reading={{id:"fixture-reading",title:readingReport.title} as any} takeaway="" onBack={action("back")} onReopen={async()=>{document.body.dataset.lastAction="reopen"}}/>:view==="tree"?<TreeView readOnly={params.has("teacher")} user={{display_name:"小林",classes:[]} as any} live={{status:empty?"empty":"ready",keywords:empty?[]:words,fields:[],error:"",reload:()=>{}} as any}/>:view==="report"?<ReportView report={report as any} onBackToTree={action("tree")} onOpenReading={action("reading")}/>:<div className="awk"><RoomShell stage={view==="energy"?"energy":"hub"} attemptNo={2} muted onToggleVoice={action("voice")} onLeave={action("leave")}>{view==="energy"?<EnergyScene onDone={action("energy-done")}/>:<HubScene returning turnsDone={3} threadCount={2} resume="terminal" navigator="" hasEnergy onContinue={action("continue")} onLibrary={action("library")} onEnergy={action("energy")} onStory={action("story")} onNavigator={action("navigator")}/>}</RoomShell></div>;
const style=document.createElement("style");style.textContent=".student-guest{height:auto!important;min-height:100vh}";document.head.appendChild(style);
createRoot(document.getElementById("root")!).render(<GuestTheme>{body}</GuestTheme>);
