# -*- coding: utf-8 -*-
"""生成 interests.json —— 领域词表的真相源。

条目写成元组是为了让整张表在一个屏幕的密度里可读，改一条词不用在 JSON 的
花括号里找。跑 `python3 build.py` 重新生成 interests.json 与 Go 侧副本。

入表标准（四条都要满足）：
  能填进「我对 ___ 感兴趣」· 陌生人一眼认得 · 2-4 字为主 · 是人类活动的一个领域
"""
import io, json, os

# (id, zh, en, "discipline-id discipline-id ...")
TABLE = {
"formal": [
 ("cryptography", "密码", "Cryptography", "logic-proof discrete-networks algorithms"),
 ("cryptocurrency", "加密货币", "Cryptocurrency", "economics discrete-networks political-economy"),
 ("gambling", "赌博", "Gambling", "probability cognitive-psychology economics"),
 ("puzzles", "谜题", "Puzzles", "logic-proof discrete-networks cognitive-psychology"),
 ("board-games", "棋", "Board games", "logic-proof probability algorithms"),
 ("polling", "民调", "Polling", "statistical-inference sociology media-literacy"),
 ("insurance", "保险", "Insurance", "probability economics statistical-inference"),
 ("navigation", "导航", "Navigation", "calculus astronomy geography-urban"),
 ("rankings", "排行榜", "Rankings", "statistical-inference sociology media-literacy"),
 ("symmetry", "对称", "Symmetry", "logic-proof visual-design matter-energy"),
 ("measurement", "计量", "Measurement", "statistical-inference matter-energy engineering-design"),
 ("data-visualisation", "数据可视化", "Data visualisation", "statistical-inference visual-design media-literacy"),
 ("optimisation", "优化", "Optimisation", "modelling algorithms economics"),
 ("game-theory", "博弈", "Game theory", "probability economics political-economy"),
 ("fractals", "分形", "Fractals", "calculus visual-design ecology"),
 ("calendars", "历法", "Calendars", "astronomy history anthropology"),
 ("gacha", "抽卡", "Gacha", "probability interaction-design cognitive-psychology"),
 ("forecasting", "预测", "Forecasting", "probability modelling statistical-inference"),
],
"science": [
 ("climate", "气候", "Climate", "climate-ocean energy-systems political-economy"),
 ("ocean", "海洋", "Ocean", "climate-ocean ecology geography-urban"),
 ("deep-sea", "深海", "Deep sea", "climate-ocean ecology engineering-design"),
 ("polar", "极地", "Polar regions", "climate-ocean ecology geography-urban"),
 ("glaciers", "冰川", "Glaciers", "climate-ocean geography-urban ecology"),
 ("deserts", "沙漠", "Deserts", "climate-ocean ecology geography-urban"),
 ("forests", "森林", "Forests", "ecology climate-ocean political-economy"),
 ("wetlands", "湿地", "Wetlands", "ecology climate-ocean geography-urban"),
 ("caves", "洞穴", "Caves", "geography-urban ecology history"),
 ("earthquakes", "地震", "Earthquakes", "matter-energy geography-urban engineering-design"),
 ("volcanoes", "火山", "Volcanoes", "matter-energy geography-urban ecology"),
 ("weather", "天气", "Weather", "climate-ocean probability modelling"),
 ("astronomy", "天文", "Astronomy", "astronomy matter-energy calculus"),
 ("spaceflight", "太空探索", "Spaceflight", "astronomy engineering-design political-economy"),
 ("dinosaurs", "恐龙", "Dinosaurs", "genetics ecology history"),
 ("fossils", "化石", "Fossils", "genetics history geography-urban"),
 ("insects", "昆虫", "Insects", "ecology genetics materials"),
 ("birds", "鸟类", "Birds", "ecology genetics geography-urban"),
 ("plants", "植物", "Plants", "ecology genetics materials"),
 ("fungi", "真菌", "Fungi", "ecology genetics public-health"),
 ("microbes", "微生物", "Microbes", "genetics public-health ecology"),
 ("viruses", "病毒", "Viruses", "genetics public-health ecology"),
 ("vaccines", "疫苗", "Vaccines", "public-health genetics political-economy"),
 ("immunity", "免疫", "Immunity", "public-health genetics wellbeing"),
 ("medicine", "药", "Medicine", "public-health genetics economics"),
 ("poisons", "毒物", "Poisons", "materials public-health ecology"),
 ("human-body", "人体", "Human body", "public-health neuroscience wellbeing"),
 ("brain", "大脑", "Brain", "neuroscience cognitive-psychology ai-ml"),
 ("heredity", "遗传", "Heredity", "genetics ethics public-health"),
 ("evolution", "进化", "Evolution", "genetics ecology philosophy"),
 ("animal-behaviour", "动物行为", "Animal behaviour", "ecology neuroscience cognitive-psychology"),
 ("pets", "宠物", "Pets", "ecology developmental-psychology wellbeing"),
 ("breeding", "育种", "Breeding", "genetics ecology economics"),
 ("crops", "作物", "Crops", "genetics ecology economics"),
 ("conservation", "生态保护", "Conservation", "ecology political-economy climate-ocean"),
 ("light", "光", "Light", "matter-energy visual-design astronomy"),
 ("sound", "声音", "Sound", "matter-energy music-theory neuroscience"),
 ("quantum", "量子", "Quantum", "matter-energy probability philosophy"),
 ("relativity", "相对论", "Relativity", "matter-energy astronomy calculus"),
 ("chemistry", "化学", "Chemistry", "matter-energy materials public-health"),
],
"making": [
 ("games", "游戏", "Games", "interaction-design probability visual-design"),
 ("programming", "编程", "Programming", "algorithms engineering-design logic-proof"),
 ("artificial-intelligence", "人工智能", "Artificial intelligence", "ai-ml algorithms ethics"),
 ("robots", "机器人", "Robots", "engineering-design ai-ml algorithms"),
 ("drones", "无人机", "Drones", "engineering-design ai-ml political-economy"),
 ("chips", "芯片", "Chips", "materials engineering-design economics"),
 ("phones", "手机", "Phones", "interaction-design materials economics"),
 ("cars", "汽车", "Cars", "engineering-design energy-systems materials"),
 ("electric-vehicles", "电动车", "Electric vehicles", "energy-systems materials economics"),
 ("aircraft", "飞机", "Aircraft", "engineering-design matter-energy materials"),
 ("rockets", "火箭", "Rockets", "engineering-design astronomy matter-energy"),
 ("ships", "船", "Ships", "engineering-design geography-urban history"),
 ("railways", "铁路", "Railways", "engineering-design geography-urban economics"),
 ("bridges", "桥梁", "Bridges", "engineering-design materials visual-design"),
 ("architecture", "建筑", "Architecture", "engineering-design art-history geography-urban"),
 ("woodworking", "木工", "Woodworking", "materials engineering-design visual-design"),
 ("tailoring", "裁缝", "Tailoring", "materials visual-design anthropology"),
 ("knitting", "编织", "Knitting", "materials visual-design anthropology"),
 ("ceramics", "陶艺", "Ceramics", "materials art-history visual-design"),
 ("metalwork", "金工", "Metalwork", "materials engineering-design art-history"),
 ("leatherwork", "皮革", "Leatherwork", "materials visual-design anthropology"),
 ("glass", "玻璃", "Glass", "materials art-history matter-energy"),
 ("baking", "烘焙", "Baking", "materials public-health anthropology"),
 ("cooking", "烹饪", "Cooking", "anthropology public-health materials"),
 ("coffee", "咖啡", "Coffee", "materials economics anthropology"),
 ("brewing", "酿造", "Brewing", "genetics materials anthropology"),
 ("perfume", "香水", "Perfume", "materials neuroscience art-history"),
 ("cosmetics", "化妆品", "Cosmetics", "materials public-health media-literacy"),
 ("3d-printing", "3D 打印", "3D printing", "materials engineering-design visual-design"),
 ("electronics", "电子制作", "Electronics", "engineering-design matter-energy algorithms"),
 ("repair", "修理", "Repair", "engineering-design materials economics"),
 ("model-making", "模型制作", "Model making", "materials visual-design art-history"),
 ("solar-power", "太阳能", "Solar power", "energy-systems materials economics"),
 ("wind-power", "风能", "Wind power", "energy-systems engineering-design geography-urban"),
 ("nuclear-power", "核能", "Nuclear power", "energy-systems matter-energy political-economy"),
 ("batteries", "电池", "Batteries", "materials energy-systems economics"),
 ("recycling", "回收", "Recycling", "materials energy-systems political-economy"),
 ("water-treatment", "净水", "Water treatment", "public-health materials geography-urban"),
 ("agricultural-technology", "农业技术", "Agricultural technology", "genetics engineering-design economics"),
 ("assistive-technology", "辅具", "Assistive technology", "engineering-design public-health interaction-design"),
 ("web", "网页", "The web", "interaction-design visual-design algorithms"),
 ("app-design", "应用设计", "App design", "interaction-design visual-design cognitive-psychology"),
 ("open-source", "开源", "Open source", "algorithms sociology economics"),
 ("cybersecurity", "网络安全", "Cybersecurity", "algorithms logic-proof political-economy"),
 ("automation", "自动化", "Automation", "ai-ml economics career-futures"),
],
"society": [
 ("finance", "金融", "Finance", "economics probability statistical-inference"),
 ("entrepreneurship", "创业", "Entrepreneurship", "economics career-futures sociology"),
 ("advertising", "广告", "Advertising", "media-literacy cognitive-psychology visual-design"),
 ("brands", "品牌", "Brands", "media-literacy economics visual-design"),
 ("retail", "零售", "Retail", "economics interaction-design sociology"),
 ("logistics", "物流", "Logistics", "economics discrete-networks geography-urban"),
 ("supply-chains", "供应链", "Supply chains", "economics political-economy geography-urban"),
 ("trade", "贸易", "Trade", "economics political-economy geography-urban"),
 ("cities", "城市", "Cities", "geography-urban sociology engineering-design"),
 ("transport", "交通", "Transport", "geography-urban engineering-design economics"),
 ("housing", "住房", "Housing", "geography-urban economics political-economy"),
 ("public-space", "公共空间", "Public space", "geography-urban visual-design sociology"),
 ("migration", "移民", "Migration", "anthropology geography-urban political-economy"),
 ("population", "人口", "Population", "statistical-inference sociology public-health"),
 ("law", "法律", "Law", "political-economy rhetoric-argument ethics"),
 ("forensics", "刑侦", "Forensics", "statistical-inference public-health logic-proof"),
 ("punishment", "惩罚与监狱", "Punishment", "political-economy sociology ethics"),
 ("elections", "选举", "Elections", "political-economy statistical-inference media-literacy"),
 ("diplomacy", "外交", "Diplomacy", "political-economy history rhetoric-argument"),
 ("war-history", "战争史", "History of war", "history political-economy geography-urban"),
 ("refugees", "难民", "Refugees", "political-economy anthropology public-health"),
 ("inequality", "不平等", "Inequality", "economics sociology political-economy"),
 ("poverty", "贫困", "Poverty", "economics public-health sociology"),
 ("philanthropy", "慈善", "Philanthropy", "economics ethics sociology"),
 ("education-systems", "教育制度", "Education systems", "education-learning political-economy sociology"),
 ("healthcare-systems", "医疗制度", "Healthcare systems", "public-health economics political-economy"),
 ("ageing", "养老", "Ageing", "public-health sociology economics"),
 ("parenting", "育儿", "Parenting", "developmental-psychology sociology anthropology"),
 ("family", "家庭", "Family", "sociology anthropology developmental-psychology"),
 ("gender", "性别", "Gender", "sociology anthropology ethics"),
 ("race", "族群", "Race and ethnicity", "sociology anthropology history"),
 ("religion", "宗教", "Religion", "anthropology philosophy history"),
 ("festivals", "节日", "Festivals", "anthropology history performance"),
 ("food-culture", "饮食文化", "Food culture", "anthropology public-health history"),
 ("dress-history", "服饰史", "History of dress", "anthropology art-history history"),
 ("social-media", "社交媒体", "Social media", "media-literacy sociology interaction-design"),
 ("public-opinion", "舆论", "Public opinion", "media-literacy statistical-inference sociology"),
 ("misinformation", "假消息", "Misinformation", "media-literacy rhetoric-argument statistical-inference"),
 ("privacy", "隐私", "Privacy", "political-economy ethics algorithms"),
 ("labour", "劳动", "Labour", "economics sociology career-futures"),
 ("rural-life", "乡村", "Rural life", "geography-urban economics anthropology"),
 ("tourism", "旅游", "Tourism", "geography-urban economics anthropology"),
 ("sports-industry", "体育产业", "Sports industry", "economics statistical-inference sociology"),
 ("volunteering", "志愿服务", "Volunteering", "sociology ethics career-futures"),
 ("disaster-response", "灾害应对", "Disaster response", "public-health geography-urban political-economy"),
 ("climate-policy", "气候政策", "Climate policy", "political-economy economics climate-ocean"),
],
"humanities": [
 ("science-fiction", "科幻", "Science fiction", "literary-criticism astronomy ethics"),
 ("fantasy", "奇幻", "Fantasy", "literary-criticism anthropology creative-writing"),
 ("mystery-fiction", "推理小说", "Mystery fiction", "literary-criticism logic-proof creative-writing"),
 ("poetry", "诗", "Poetry", "literary-criticism linguistics creative-writing"),
 ("mythology", "神话", "Mythology", "anthropology literary-criticism history"),
 ("folklore", "民间故事", "Folklore", "anthropology literary-criticism history"),
 ("archaeology", "考古", "Archaeology", "history anthropology materials"),
 ("ancient-scripts", "古文字", "Ancient scripts", "linguistics history anthropology"),
 ("dialects", "方言", "Dialects", "linguistics anthropology sociology"),
 ("translation", "翻译", "Translation", "linguistics literary-criticism philosophy"),
 ("foreign-languages", "外语", "Foreign languages", "linguistics anthropology education-learning"),
 ("etymology", "词源", "Etymology", "linguistics history literary-criticism"),
 ("sign-language", "手语", "Sign language", "linguistics neuroscience sociology"),
 ("rhetoric", "修辞", "Rhetoric", "rhetoric-argument philosophy media-literacy"),
 ("debate", "辩论", "Debate", "rhetoric-argument logic-proof political-economy"),
 ("fallacies", "逻辑谬误", "Fallacies", "rhetoric-argument logic-proof media-literacy"),
 ("journalism", "新闻", "Journalism", "media-literacy rhetoric-argument political-economy"),
 ("documentary", "纪录片", "Documentary", "media-literacy film-narrative history"),
 ("biography", "传记", "Biography", "history literary-criticism creative-writing"),
 ("nonfiction", "非虚构写作", "Nonfiction writing", "creative-writing literary-criticism history"),
 ("philosophy", "哲学", "Philosophy", "philosophy ethics logic-proof"),
 ("history-of-ideas", "思想史", "History of ideas", "history philosophy literary-criticism"),
 ("empires", "帝国", "Empires", "history political-economy geography-urban"),
 ("revolutions", "革命", "Revolutions", "history political-economy sociology"),
 ("silk-road", "丝绸之路", "The Silk Road", "history geography-urban anthropology"),
 ("pirates", "海盗", "Pirates", "history political-economy geography-urban"),
 ("map-history", "地图史", "History of maps", "geography-urban history visual-design"),
 ("museums", "博物馆", "Museums", "art-history history anthropology"),
 ("archives", "档案", "Archives", "history media-literacy philosophy"),
 ("family-history", "家族史", "Family history", "history anthropology genetics"),
 ("oral-history", "口述史", "Oral history", "history anthropology linguistics"),
 ("publishing", "出版", "Publishing", "literary-criticism economics media-literacy"),
 ("censorship", "审查", "Censorship", "political-economy media-literacy history"),
 ("traditional-medicine", "传统医学", "Traditional medicine", "anthropology public-health history"),
],
"arts": [
 ("film", "电影", "Film", "film-narrative art-history creative-writing"),
 ("animation", "动画", "Animation", "film-narrative visual-design art-history"),
 ("comics", "漫画", "Comics", "visual-design literary-criticism creative-writing"),
 ("illustration", "插画", "Illustration", "visual-design art-history materials"),
 ("photography", "摄影", "Photography", "visual-design art-history media-literacy"),
 ("graphic-design", "平面设计", "Graphic design", "visual-design art-history media-literacy"),
 ("typography", "字体", "Typography", "visual-design linguistics art-history"),
 ("painting", "绘画", "Painting", "art-history visual-design materials"),
 ("sculpture", "雕塑", "Sculpture", "art-history materials visual-design"),
 ("printmaking", "版画", "Printmaking", "art-history materials visual-design"),
 ("calligraphy", "书法", "Calligraphy", "art-history linguistics visual-design"),
 ("street-art", "街头艺术", "Street art", "art-history sociology visual-design"),
 ("installation-art", "装置艺术", "Installation art", "art-history engineering-design performance"),
 ("curation", "策展", "Curation", "art-history media-literacy visual-design"),
 ("fashion", "时装", "Fashion", "visual-design materials anthropology"),
 ("jewellery", "珠宝", "Jewellery", "materials art-history visual-design"),
 ("interior-design", "室内设计", "Interior design", "visual-design engineering-design art-history"),
 ("landscape-design", "景观设计", "Landscape design", "visual-design ecology geography-urban"),
 ("stage-design", "舞台设计", "Stage design", "performance visual-design engineering-design"),
 ("lighting", "灯光", "Lighting", "performance matter-energy visual-design"),
 ("theatre", "戏剧", "Theatre", "performance literary-criticism creative-writing"),
 ("musical-theatre", "音乐剧", "Musical theatre", "performance music-theory creative-writing"),
 ("dance", "舞蹈", "Dance", "performance music-theory wellbeing"),
 ("circus", "杂技", "Circus arts", "performance wellbeing art-history"),
 ("magic", "魔术", "Magic", "performance cognitive-psychology visual-design"),
 ("voice-acting", "配音", "Voice acting", "performance linguistics music-theory"),
 ("classical-music", "古典音乐", "Classical music", "music-theory art-history history"),
 ("rock-music", "摇滚", "Rock music", "music-theory sociology art-history"),
 ("hip-hop", "说唱", "Hip hop", "music-theory linguistics sociology"),
 ("folk-music", "民乐", "Folk music", "music-theory anthropology history"),
 ("electronic-music", "电子音乐", "Electronic music", "music-theory algorithms matter-energy"),
 ("composing", "作曲", "Composing", "music-theory creative-writing art-history"),
 ("instruments", "乐器", "Instruments", "music-theory materials matter-energy"),
 ("sound-design", "声音设计", "Sound design", "music-theory film-narrative matter-energy"),
 ("podcasting", "播客", "Podcasting", "media-literacy performance creative-writing"),
 ("short-video", "短视频", "Short video", "film-narrative media-literacy interaction-design"),
 ("game-art", "游戏美术", "Game art", "visual-design film-narrative art-history"),
 ("film-editing", "剪辑", "Film editing", "film-narrative media-literacy visual-design"),
 ("collage", "拼贴", "Collage", "visual-design creative-writing art-history"),
],
"self": [
 ("sleep", "睡眠", "Sleep", "neuroscience wellbeing cognitive-psychology"),
 ("memory", "记忆", "Memory", "cognitive-psychology neuroscience education-learning"),
 ("focus", "专注", "Focus", "cognitive-psychology education-learning wellbeing"),
 ("procrastination", "拖延", "Procrastination", "cognitive-psychology education-learning wellbeing"),
 ("habits", "习惯", "Habits", "cognitive-psychology wellbeing education-learning"),
 ("emotions", "情绪", "Emotions", "developmental-psychology neuroscience wellbeing"),
 ("anxiety", "焦虑", "Anxiety", "wellbeing developmental-psychology public-health"),
 ("friendship", "友谊", "Friendship", "developmental-psychology sociology ethics"),
 ("romance", "恋爱", "Romance", "developmental-psychology sociology literary-criticism"),
 ("loneliness", "孤独", "Loneliness", "developmental-psychology sociology wellbeing"),
 ("confidence", "自信", "Confidence", "developmental-psychology education-learning wellbeing"),
 ("persuasion", "说服", "Persuasion", "rhetoric-argument cognitive-psychology sociology"),
 ("leadership", "领导", "Leadership", "sociology career-futures ethics"),
 ("teamwork", "团队合作", "Teamwork", "sociology career-futures education-learning"),
 ("conflict", "冲突与调解", "Conflict and mediation", "ethics sociology rhetoric-argument"),
 ("study-methods", "学习方法", "Study methods", "education-learning cognitive-psychology career-futures"),
 ("exams", "考试", "Exams", "education-learning statistical-inference wellbeing"),
 ("time-management", "时间管理", "Time management", "education-learning career-futures wellbeing"),
 ("personal-finance", "理财", "Personal finance", "economics ethics career-futures"),
 ("choosing-a-major", "选专业", "Choosing a major", "career-futures education-learning economics"),
 ("careers", "职业", "Careers", "career-futures economics sociology"),
 ("training", "运动训练", "Athletic training", "wellbeing public-health statistical-inference"),
 ("nutrition", "营养", "Nutrition", "public-health wellbeing genetics"),
 ("meditation", "冥想", "Meditation", "wellbeing neuroscience philosophy"),
 ("purpose", "志向", "Purpose", "ethics career-futures philosophy"),
 ("decision-making", "决策", "Decision making", "probability cognitive-psychology ethics"),
 ("bias", "偏见", "Bias", "cognitive-psychology statistical-inference sociology"),
],
}

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", "..", ".."))

out = []
for field, rows in TABLE.items():
    for iid, zh, en, discs in rows:
        out.append({
            "id": iid,
            "field": field,
            "zh": zh,
            "en": en,
            "disciplines": discs.split(),
        })

text = json.dumps(out, ensure_ascii=False, indent=2) + "\n"
for path in (
    os.path.join(HERE, "interests.json"),
    os.path.join(ROOT, "apps", "api", "internal", "interests", "interests.json"),
):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    io.open(path, "w", encoding="utf-8").write(text)

print("%d entries" % len(out))
for field, rows in TABLE.items():
    print("  %-11s %d" % (field, len(rows)))
