package cards

import (
	_ "embed"
	"encoding/json"
)

// covers-manifest.json maps a card's asset_id (T-number) to its cover object key
// per colorway theme, e.g. {"T01": {"light": "web/....webp", "cyber-sage": ...}}.
// Generated by the OSS upload script (see docs/2026-08-01-card-gallery-...); the
// object keys are non-secret and resolved to short-lived signed URLs at request
// time by the catalog endpoint.
//
//go:embed covers-manifest.json
var coversRaw []byte

// Themes is the closed set of cover colorways a student may choose. "light" is
// the default (matches users.card_theme default).
var Themes = []string{"light", "cyber-sage", "cyber-slate", "cyber-warm"}

// DefaultTheme is used when a caller supplies no theme or an unknown one.
const DefaultTheme = "light"

var coversManifest = func() map[string]map[string]string {
	m := map[string]map[string]string{}
	if err := json.Unmarshal(coversRaw, &m); err != nil {
		panic("cards: bad covers-manifest.json: " + err.Error())
	}
	return m
}()

// ValidTheme reports whether theme is one of the known colorways.
func ValidTheme(theme string) bool {
	for _, t := range Themes {
		if t == theme {
			return true
		}
	}
	return false
}

// CoverKey returns the OSS object key for a card's cover in the given theme, and
// whether one exists. An unknown theme falls back to DefaultTheme so a bad query
// param never blanks every cover.
func CoverKey(assetID, theme string) (string, bool) {
	if assetID == "" {
		return "", false
	}
	if !ValidTheme(theme) {
		theme = DefaultTheme
	}
	byTheme, ok := coversManifest[assetID]
	if !ok {
		return "", false
	}
	key, ok := byTheme[theme]
	return key, ok && key != ""
}
